// VALTREN ACCOUNTING BROWSER
function crmAccountingService(){
  if(typeof ValtrenAccountingCore==='undefined')throw new Error('ValtrenAccountingCore indisponível');
  if(typeof crmFinanceService!=='function')throw new Error('Financeiro → Transações canônico indisponível');
  state.crmAccounting=ValtrenAccountingCore.ensureState(state.crmAccounting);
  if(!state.__crmAccountingService||state.__crmAccountingService.data!==state.crmAccounting){
    state.__crmAccountingService=ValtrenAccountingCore.createService(state.crmAccounting,{financeService:()=>crmFinanceService(),actorProvider:()=>state.crmUserId||state.crmUserName||null});
  }
  return state.__crmAccountingService;
}
function crmAccountingMoney(value){return crmFinanceMoney(Number(value||0),'BRL');}
function crmAccountingMargin(value){return value==null||!Number.isFinite(Number(value))?'—':`${Number(value).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;}
function crmAccountingProducts(){return typeof crmFinanceProducts==='function'?crmFinanceProducts():[];}
function crmAccountingServices(){const rows=[state.businessServices,state.crmBusinessServices,state.negociosServices].find(Array.isArray)||[];return rows.filter((x)=>x&&x.id&&x.name).map((x)=>({id:String(x.id),name:String(x.name),status:x.status||'active'}));}
function crmAccountingUnits(){const rows=[state.businessUnits,state.crmBusinessUnits,state.negociosBusinessUnits].find(Array.isArray)||[];return rows.filter((x)=>x&&x.id&&x.name).map((x)=>({id:String(x.id),name:String(x.name),status:x.status||'active'}));}
function crmAccountingPeriodRange(period,query){
  const today=new Date(),pad=(v)=>String(v).padStart(2,'0'),fmt=(d)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,year=today.getFullYear(),month=today.getMonth();
  if(period==='month')return [fmt(new Date(year,month,1)),fmt(today)];
  if(period==='quarter'){const q=Math.floor(month/3)*3;return [fmt(new Date(year,q,1)),fmt(today)];}
  if(period==='year')return [fmt(new Date(year,0,1)),fmt(today)];
  if(period==='custom')return [query.get('from')||'',query.get('to')||''];
  return ['',''];
}
function crmAccountingCurrentFilters(){
  const q=routeInfo().query,view=['dre','entries','classifications'].includes(q.get('view'))?q.get('view'):'dre',basis=['cash','accrual'].includes(q.get('basis'))?q.get('basis'):'accrual',period=q.get('period')||'month',[from,to]=crmAccountingPeriodRange(period,q),dimension=q.get('dimension')||'',productId=dimension.startsWith('product:')?dimension.slice(8):'',corporate=dimension==='corporate';
  return {view,basis,period,from,to,dimension:corporate?'corporate':'',productId,serviceId:q.get('service')||'',businessUnitId:q.get('unit')||'',categoryId:q.get('category')||'',classificationId:q.get('classification')||'',compare:q.get('compare')==='1',onlyPending:q.get('only')==='pending'};
}
function crmAccountingSetQuery(changes){
  const q=new URLSearchParams(routeInfo().query||new URLSearchParams());
  Object.entries(changes).forEach(([key,value])=>{if(value==null||value===''||value===false||value==='all')q.delete(key);else q.set(key,value===true?'1':String(value));});
  const suffix=q.toString()?`?${q.toString()}`:'';location.hash=`#/crm/financeiro/accounting${suffix}`;
}
function crmAccountingClassificationOptions(selected='',includeEmpty=true){const service=crmAccountingService(),rows=service.data.classifications.filter((x)=>x.status==='active').sort((a,b)=>a.order-b.order);return `${includeEmpty?'<option value="">Não classificada</option>':''}${rows.map((x)=>`<option value="${esc(x.id)}" ${selected===x.id?'selected':''}>${esc(x.code?`${x.code} · ${x.name}`:x.name)}</option>`).join('')}`;}
function crmAccountingServiceOptions(selected=''){const rows=crmAccountingServices();if(!rows.length)return '<option value="">Nenhum serviço cadastrado</option>';return `<option value="">Sem serviço</option>${rows.map((x)=>`<option value="${esc(x.id)}" ${selected===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}`;}
function crmAccountingUnitOptions(selected=''){const rows=crmAccountingUnits();if(!rows.length)return '<option value="">Nenhuma unidade cadastrada</option>';return `<option value="">Sem unidade</option>${rows.map((x)=>`<option value="${esc(x.id)}" ${selected===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}`;}
function crmAccountingGroupLabel(section){return ValtrenAccountingCore.SECTION_LABELS[section]||section||'—';}
function crmAccountingResult(){const service=crmAccountingService(),f=crmAccountingCurrentFilters(),dre=service.buildDre(f),previous=f.compare&&f.from&&f.to?service.buildDre({...f,...ValtrenAccountingCore.previousPeriod(f.from,f.to),compare:false}):null,pendencies=service.pendencies(f);return {service,f,dre,previous,pendencies};}
function crmAccountingCompareText(current,previous){if(!previous||previous===0)return '';const pct=((current-previous)/Math.abs(previous))*100;if(!Number.isFinite(pct))return '';return `${pct>=0?'+':''}${pct.toLocaleString('pt-BR',{maximumFractionDigits:1})}% vs. período anterior`;}
function crmAccountingSummaryCards(dre,previous){
  const s=dre.summary,p=previous?.summary,has=dre.rowCount>0,value=(v)=>has?crmAccountingMoney(v):'—',margin=(v)=>has?crmAccountingMargin(v):'—';
  const card=(label,val,desc='')=>`<article class="crm-acct-kpi"><span>${esc(label)}</span><strong>${esc(val)}</strong>${desc?`<small>${esc(desc)}</small>`:''}</article>`;
  return `<section class="crm-acct-summary">${card('Receita Bruta',value(s.grossRevenue),has&&p?crmAccountingCompareText(s.grossRevenue,p.grossRevenue):'')}${card('Receita Líquida',value(s.netRevenue),has&&p?crmAccountingCompareText(s.netRevenue,p.netRevenue):'')}${card('Custos',value(s.costs))}${card('Despesas Operacionais',value(s.operatingExpenses))}${card('Resultado Operacional',value(s.operatingResult),has&&p?crmAccountingCompareText(s.operatingResult,p.operatingResult):'')}${card('Resultado Final',value(s.finalResult),has&&p?crmAccountingCompareText(s.finalResult,p.finalResult):'')}${card('Margem Operacional',margin(s.operatingMargin))}</section>`;
}
function crmAccountingPendingBanner(p){if(!p.counts.total)return '';return `<section class="crm-acct-pending"><div><strong>${p.counts.total} movimentaç${p.counts.total===1?'ão':'ões'} com pendência contábil</strong><span>${p.counts.unclassified||0} sem classificação · ${p.counts.missing_competence||0} sem competência${p.counts.invalid_allocation_reference?` · ${p.counts.invalid_allocation_reference} rateio(s) inválido(s)`:''}</span></div><button type="button" data-action="crm-acct-review-pending">Revisar lançamentos</button></section>`;}
function crmAccountingTabs(f){return `<nav class="crm-acct-tabs" aria-label="Visões de Contabilidade">${[['dre','DRE'],['entries','Lançamentos'],['classifications','Classificações']].map(([id,label])=>`<button type="button" class="${f.view===id?'active':''}" data-action="crm-acct-view" data-view="${id}">${label}</button>`).join('')}</nav>`;}
function crmAccountingFilters(f){
  const service=crmAccountingService(),finance=crmFinanceService(),products=crmAccountingProducts(),services=crmAccountingServices(),units=crmAccountingUnits();
  return `<section class="crm-acct-filters"><select id="crm-acct-period"><option value="month" ${f.period==='month'?'selected':''}>Este mês</option><option value="quarter" ${f.period==='quarter'?'selected':''}>Este trimestre</option><option value="year" ${f.period==='year'?'selected':''}>Este ano</option><option value="custom" ${f.period==='custom'?'selected':''}>Personalizado</option></select>${f.period==='custom'?`<input id="crm-acct-from" type="date" value="${esc(f.from)}"><input id="crm-acct-to" type="date" value="${esc(f.to)}">`:''}<select id="crm-acct-basis" title="Regime contábil"><option value="accrual" ${f.basis==='accrual'?'selected':''}>Competência</option><option value="cash" ${f.basis==='cash'?'selected':''}>Caixa</option></select><select id="crm-acct-dimension"><option value="">Todos os Produtos/Sistemas</option><option value="corporate" ${f.dimension==='corporate'?'selected':''}>Corporativo</option>${products.map((p)=>`<option value="product:${esc(p.id)}" ${f.productId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><select id="crm-acct-service" ${services.length?'':'disabled'}><option value="">${services.length?'Todos os Serviços':'Sem serviços cadastrados'}</option>${services.map((x)=>`<option value="${esc(x.id)}" ${f.serviceId===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><select id="crm-acct-unit" ${units.length?'':'disabled'}><option value="">${units.length?'Todas as Unidades':'Sem unidades cadastradas'}</option>${units.map((x)=>`<option value="${esc(x.id)}" ${f.businessUnitId===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><details class="crm-acct-more"><summary>Mais filtros</summary><div><select id="crm-acct-category"><option value="">Todas as categorias financeiras</option>${finance.data.categories.filter((x)=>x.status==='active').map((x)=>`<option value="${esc(x.id)}" ${f.categoryId===x.id?'selected':''}>${esc(typeof crmFinanceCategoryLabel==='function'?crmFinanceCategoryLabel(x.id):x.name)}</option>`).join('')}</select><select id="crm-acct-classification"><option value="">Todas as classificações</option>${crmAccountingClassificationOptions(f.classificationId,false)}</select><label><input id="crm-acct-compare" type="checkbox" ${f.compare?'checked':''}> Comparar período anterior</label></div></details></section>`;
}
function crmAccountingBreakdown(section,dre){const rows=dre.breakdown[section]||[];if(!rows.length)return '';return `<div class="crm-acct-breakdown">${rows.map((item)=>`<button type="button" data-action="crm-acct-drill" data-target="${esc(item.classification.id)}"><span>${esc(item.classification.name)}</span><small>${item.count} movimento${item.count===1?'':'s'}</small><strong>${crmAccountingMoney(item.displayAmount)}</strong></button>`).join('')}</div>`;}
function crmAccountingDreRow(label,target,amount,previousAmount=null,options={}){const hasBreakdown=!!options.breakdown;return `<tr class="${options.result?'result':''} ${options.final?'final':''}"><td>${hasBreakdown?`<details ${options.open?'open':''}><summary><button type="button" data-action="crm-acct-drill" data-target="${esc(target)}">${esc(label)}</button></summary>${options.breakdown}</details>`:`<button type="button" data-action="crm-acct-drill" data-target="${esc(target)}">${esc(label)}</button>`}</td><td class="money">${crmAccountingMoney(amount)}</td>${previousAmount==null?'':`<td class="money previous">${crmAccountingMoney(previousAmount)}</td>`}</tr>`;}
function crmAccountingDreView(result){
  const {dre,previous,f}=result;if(!dre.rowCount)return `<section class="crm-acct-empty"><strong>Nenhum dado contábil para este período.</strong><span>As movimentações lançadas, classificadas e com competência definida em Transações aparecerão aqui.</span></section>`;
  const s=dre.summary,p=previous?.summary,withPrevious=!!previous,previousCell=(key)=>withPrevious?p[key]:null,rows=[];
  if(dre.breakdown.gross_revenue.length)rows.push(crmAccountingDreRow('Receita Bruta','gross_revenue',s.grossRevenue,previousCell('grossRevenue'),{breakdown:crmAccountingBreakdown('gross_revenue',dre),open:true}));
  if(dre.breakdown.deductions.length)rows.push(crmAccountingDreRow('(-) Deduções da Receita','deductions',s.deductions,previousCell('deductions'),{breakdown:crmAccountingBreakdown('deductions',dre)}));
  rows.push(crmAccountingDreRow('= Receita Líquida','net_revenue',s.netRevenue,previousCell('netRevenue'),{result:true}));
  if(dre.breakdown.costs.length)rows.push(crmAccountingDreRow('(-) Custos','costs',s.costs,previousCell('costs'),{breakdown:crmAccountingBreakdown('costs',dre)}));
  rows.push(crmAccountingDreRow('= Resultado Bruto','gross_result',s.grossResult,previousCell('grossResult'),{result:true}));
  if(dre.breakdown.operating_expenses.length)rows.push(crmAccountingDreRow('(-) Despesas Operacionais','operating_expenses',s.operatingExpenses,previousCell('operatingExpenses'),{breakdown:crmAccountingBreakdown('operating_expenses',dre)}));
  rows.push(crmAccountingDreRow('= Resultado Operacional','operating_result',s.operatingResult,previousCell('operatingResult'),{result:true}));
  if(dre.breakdown.financial_result.length)rows.push(crmAccountingDreRow('(+/-) Resultado Financeiro','financial_result',s.financialResult,previousCell('financialResult'),{breakdown:crmAccountingBreakdown('financial_result',dre)}));
  if(dre.breakdown.other_results.length)rows.push(crmAccountingDreRow('(+/-) Outros Resultados','other_results',s.otherResults,previousCell('otherResults'),{breakdown:crmAccountingBreakdown('other_results',dre)}));
  if(dre.breakdown.result_taxes.length){rows.push(crmAccountingDreRow('= Resultado antes de Tributos','pretax_result',s.preTaxResult,previousCell('preTaxResult'),{result:true}));rows.push(crmAccountingDreRow('(-) Tributos sobre Resultado','result_taxes',s.resultTaxes,previousCell('resultTaxes'),{breakdown:crmAccountingBreakdown('result_taxes',dre)}));}
  rows.push(crmAccountingDreRow('= Resultado Final','final_result',s.finalResult,previousCell('finalResult'),{result:true,final:true}));
  return `<section class="crm-acct-dre-card"><header><div><h3>Demonstrativo de Resultado</h3><p>Regime de ${f.basis==='accrual'?'Competência':'Caixa'} · ${f.from||'início'} a ${f.to||'hoje'}</p></div><div><span>Margem Bruta <b>${crmAccountingMargin(s.grossMargin)}</b></span><span>Margem Operacional <b>${crmAccountingMargin(s.operatingMargin)}</b></span></div></header><div class="crm-acct-dre-wrap"><table><thead><tr><th>Estrutura</th><th class="right">Período atual</th>${withPrevious?'<th class="right">Período anterior</th>':''}</tr></thead><tbody>${rows.join('')}</tbody></table></div></section>`;
}
function crmAccountingEntryStatus(row,f){const labels=[];if(!row.classification)labels.push('Não classificada');if(f.basis==='accrual'&&!row.date)labels.push('Sem competência');if(row.issues.includes('invalid_allocation_reference'))labels.push('Rateio inválido');return labels.length?`<span class="crm-acct-status pending">${esc(labels.join(' · '))}</span>`:'<span class="crm-acct-status ready">Pronta</span>';}
function crmAccountingEntryDimension(tx){if(Array.isArray(tx.allocations)&&tx.allocations.length>1)return `${tx.allocations.length} destinos · Rateado`;return typeof crmFinanceProductLabel==='function'?crmFinanceProductLabel(tx):(tx.businessDimension==='corporate'?'Corporativo':tx.productId||'—');}
function crmAccountingEntriesView(result){
  const {service,f}=result,rows=service.listEntries(f),services=crmAccountingServices(),units=crmAccountingUnits();
  const body=rows.map((row)=>{const tx=row.transaction,meta=row.accounting,classificationId=row.classification?.id||'',source=row.classificationSource==='override'?'Override manual':row.classificationSource==='mapping'?'Mapeamento padrão':row.classificationSource==='related'?'Herdada da movimentação relacionada':'Não classificada';return `<tr><td><strong>${esc(tx.transactionDate||'—')}</strong><small>${f.basis==='cash'?`Caixa: ${esc(row.date||'—')}`:'Data financeira'}</small></td><td><input class="crm-acct-inline-date" type="date" data-action="crm-acct-recognition" data-id="${esc(tx.id)}" value="${esc(meta.recognitionDate||'')}"></td><td class="description"><strong>${esc(tx.originalDescription||'Sem descrição')}</strong>${tx.normalizedDescription?`<small>${esc(tx.normalizedDescription)}</small>`:''}</td><td>${esc(typeof crmFinanceCategoryLabel==='function'?crmFinanceCategoryLabel(tx.categoryId):tx.categoryId||'—')}</td><td><select class="crm-acct-inline-select" data-action="crm-acct-classification-override" data-id="${esc(tx.id)}">${crmAccountingClassificationOptions(classificationId,true)}</select><small>${esc(source)}</small></td><td>${esc(crmAccountingEntryDimension(tx))}</td><td>${services.length?`<select class="crm-acct-inline-select compact" data-action="crm-acct-service-meta" data-id="${esc(tx.id)}">${crmAccountingServiceOptions(meta.serviceId||'')}</select>`:'—'}</td><td>${units.length?`<select class="crm-acct-inline-select compact" data-action="crm-acct-unit-meta" data-id="${esc(tx.id)}">${crmAccountingUnitOptions(meta.businessUnitId||'')}</select>`:'—'}</td><td class="money">${crmAccountingMoney(row.amount)}</td><td>${crmAccountingEntryStatus(row,f)}</td><td><a class="crm-acct-link" href="#/crm/financeiro?q=${encodeURIComponent(tx.originalDescription||tx.id)}">Ver em Transações</a></td></tr>`;}).join('');
  return `<section class="crm-acct-entry-head"><div><h3>Lançamentos contábeis gerenciais</h3><p>Leitura das transações lançadas. Valor, descrição bancária, conta e contraparte continuam sob responsabilidade de Transações.</p></div><button type="button" class="secondary ${f.onlyPending?'active':''}" data-action="crm-acct-only-pending">${f.onlyPending?'Mostrar todos':'Somente pendências'}</button></section><section class="crm-acct-table-card"><div class="crm-acct-table-wrap"><table class="crm-acct-entry-table"><thead><tr><th>Data</th><th>Competência</th><th>Descrição</th><th>Categoria Financeira</th><th>Classificação Contábil</th><th>Produto/Sistema</th><th>Serviço</th><th>Unidade</th><th class="right">Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>${body}</tbody></table>${body?'':`<div class="crm-acct-empty"><strong>Nenhuma movimentação nesta classificação.</strong><span>Altere os filtros ou revise as movimentações lançadas em Transações.</span></div>`}</div></section>`;
}
function crmAccountingClassificationsView(result){
  const {service}=result,finance=crmFinanceService(),categories=finance.data.categories.filter((x)=>x.status==='active'),classifications=service.data.classifications.filter((x)=>x.status==='active').sort((a,b)=>a.order-b.order);
  const mapRows=categories.map((cat)=>{const mapping=service.getMapping(cat.id),selected=mapping?.classificationId||'';return `<tr><td><strong>${esc(typeof crmFinanceCategoryLabel==='function'?crmFinanceCategoryLabel(cat.id):cat.name)}</strong><small>${esc(cat.nature||'')}</small></td><td><select class="crm-acct-inline-select wide" data-action="crm-acct-mapping" data-category="${esc(cat.id)}">${crmAccountingClassificationOptions(selected,true)}</select></td><td>${selected?`<span class="crm-acct-status ready">Ativo</span>`:'<span class="crm-acct-status pending">Sem mapeamento</span>'}</td></tr>`;}).join('');
  const chart=classifications.map((x)=>`<article><span>${esc(x.code||'—')}</span><div><strong>${esc(x.name)}</strong><small>${esc(crmAccountingGroupLabel(x.section))}${x.parentId?` · Parent ${esc(x.parentId)}`:''}</small></div><em>${x.sign>0?'Credora gerencial':'Redutora gerencial'}</em></article>`).join('');
  return `<div class="crm-acct-classification-grid"><section class="crm-acct-table-card"><header><div><h3>Mapeamento Categoria → Classificação</h3><p>Categorias financeiras continuam pertencendo a Transações. Aqui existe somente o mapeamento contábil padrão.</p></div></header><div class="crm-acct-table-wrap"><table><thead><tr><th>Categoria Financeira</th><th>Classificação Contábil padrão</th><th>Status</th></tr></thead><tbody>${mapRows}</tbody></table></div></section><section class="crm-acct-chart"><header><h3>Estrutura contábil gerencial</h3><p>Estrutura extensível para DRE e análises. Não representa um plano legal completo de partidas dobradas.</p></header><div>${chart}</div></section></div>`;
}
function crmAccountingMountOverlay(html){document.getElementById('crm-acct-overlay')?.remove();const root=document.createElement('div');root.id='crm-acct-overlay';root.className='crm-acct-overlay';root.innerHTML=html;document.body.appendChild(root);document.body.classList.add('crm-rel-modal-open');}
function crmAccountingCloseOverlay(){document.getElementById('crm-acct-overlay')?.remove();document.body.classList.remove('crm-rel-modal-open');}
function crmAccountingOpenDrill(target){
  const service=crmAccountingService(),f=crmAccountingCurrentFilters(),drill=service.drillDown(target,f),classification=service.getClassification(target),label=classification?.name||({'gross_revenue':'Receita Bruta','deductions':'Deduções da Receita','net_revenue':'Receita Líquida','costs':'Custos','gross_result':'Resultado Bruto','operating_expenses':'Despesas Operacionais','operating_result':'Resultado Operacional','financial_result':'Resultado Financeiro','other_results':'Outros Resultados','pretax_result':'Resultado antes de Tributos','result_taxes':'Tributos sobre Resultado','final_result':'Resultado Final'}[target]||target);
  const rows=drill.rows.map((row)=>{const tx=row.transaction;return `<tr><td>${esc(row.date||tx.transactionDate||'—')}</td><td><strong>${esc(tx.originalDescription||'—')}</strong></td><td>${esc(typeof crmFinanceCategoryLabel==='function'?crmFinanceCategoryLabel(tx.categoryId):tx.categoryId||'—')}</td><td>${esc(row.classification.name)}</td><td>${esc(crmAccountingEntryDimension(tx))}</td><td>${esc(typeof crmFinanceAccountLabel==='function'?crmFinanceAccountLabel(tx.financialAccountId):tx.financialAccountId||'—')}</td><td>${esc(typeof crmFinanceCounterpartyLabel==='function'?crmFinanceCounterpartyLabel(tx):tx.counterpartyId||'—')}</td><td class="money">${crmAccountingMoney(row.amount)}</td><td><a class="crm-acct-link" href="#/crm/financeiro?q=${encodeURIComponent(tx.originalDescription||tx.id)}">Ver transação</a></td></tr>`;}).join('');
  crmAccountingMountOverlay(`<div class="crm-acct-backdrop" data-action="crm-acct-close"></div><aside class="crm-acct-drawer"><header><div><span>Drill-down</span><h2>${esc(label)}</h2><p>${drill.rows.length} movimento${drill.rows.length===1?'':'s'} · ${crmAccountingMoney(drill.displayTotal)}</p></div><button type="button" data-action="crm-acct-close">×</button></header><div class="crm-acct-drawer-body"><div class="crm-acct-table-wrap"><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Classificação</th><th>Produto/Sistema</th><th>Conta</th><th>Contraparte</th><th class="right">Valor</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>${rows?'':'<div class="crm-acct-empty"><strong>Nenhuma movimentação nesta classificação.</strong></div>'}</div></aside>`);
}
function crmAccountingPage(){
  const result=crmAccountingResult(),{f}=result,actions=`<a class="secondary" href="#/crm/financeiro">${crmRefIcon('database')} Transações</a>`,content=f.view==='dre'?crmAccountingDreView(result):f.view==='entries'?crmAccountingEntriesView(result):crmAccountingClassificationsView(result);
  return crmFidelityPage('accounting','accounting','Contabilidade','Classificação, competência e visão gerencial derivadas de Transações',actions,`<div class="crm-acct-workspace">${crmAccountingPendingBanner(result.pendencies)}${crmAccountingSummaryCards(result.dre,result.previous)}${crmAccountingTabs(f)}${crmAccountingFilters(f)}${content}</div>`);
}

if(!window.__valtrenAccountingBound){
  window.__valtrenAccountingBound=true;
  document.addEventListener('click',(event)=>{const t=event.target.closest('[data-action]');if(!t)return;const action=t.dataset.action;
    if(action==='crm-acct-view'){crmAccountingSetQuery({view:t.dataset.view,only:''});return;}
    if(action==='crm-acct-review-pending'){crmAccountingSetQuery({view:'entries',only:'pending'});return;}
    if(action==='crm-acct-only-pending'){crmAccountingSetQuery({only:crmAccountingCurrentFilters().onlyPending?'':'pending'});return;}
    if(action==='crm-acct-drill'){crmAccountingOpenDrill(t.dataset.target);return;}
    if(action==='crm-acct-close'){crmAccountingCloseOverlay();return;}
  });
  document.addEventListener('change',(event)=>{const t=event.target,service=crmAccountingService();
    if(t.matches('[data-action="crm-acct-recognition"]')){service.setTransactionAccounting(t.dataset.id,{recognitionDate:t.value});renderCurrentWithoutReset();return;}
    if(t.matches('[data-action="crm-acct-classification-override"]')){service.setTransactionAccounting(t.dataset.id,{classificationId:t.value});renderCurrentWithoutReset();return;}
    if(t.matches('[data-action="crm-acct-service-meta"]')){service.setTransactionAccounting(t.dataset.id,{serviceId:t.value});renderCurrentWithoutReset();return;}
    if(t.matches('[data-action="crm-acct-unit-meta"]')){service.setTransactionAccounting(t.dataset.id,{businessUnitId:t.value});renderCurrentWithoutReset();return;}
    if(t.matches('[data-action="crm-acct-mapping"]')){service.setMapping(t.dataset.category,t.value,!!t.value);renderCurrentWithoutReset();return;}
    if(t.id==='crm-acct-period'){crmAccountingSetQuery({period:t.value,page:'',from:'',to:''});return;}
    if(t.id==='crm-acct-basis'){crmAccountingSetQuery({basis:t.value});return;}
    if(t.id==='crm-acct-dimension'){crmAccountingSetQuery({dimension:t.value});return;}
    if(t.id==='crm-acct-service'){crmAccountingSetQuery({service:t.value});return;}
    if(t.id==='crm-acct-unit'){crmAccountingSetQuery({unit:t.value});return;}
    if(t.id==='crm-acct-category'){crmAccountingSetQuery({category:t.value});return;}
    if(t.id==='crm-acct-classification'){crmAccountingSetQuery({classification:t.value});return;}
    if(t.id==='crm-acct-from'){crmAccountingSetQuery({from:t.value});return;}
    if(t.id==='crm-acct-to'){crmAccountingSetQuery({to:t.value});return;}
    if(t.id==='crm-acct-compare'){crmAccountingSetQuery({compare:t.checked});return;}
  });
  document.addEventListener('keydown',(event)=>{if(event.key==='Escape'&&document.getElementById('crm-acct-overlay'))crmAccountingCloseOverlay();});
}