'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ValtrenComplianceCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const OBLIGATION_STATUSES=['draft','active','under_review','compliant','non_compliant','expired','archived'];
  const RISKS=['low','medium','high','critical'];
  const CONTROL_STATUSES=['planned','active','ineffective','suspended','archived'];
  const OCCURRENCE_TYPES=['incident','breach','non_compliance','exception','finding','complaint','other'];
  const OCCURRENCE_STATUSES=['open','analysis','in_progress','resolved','closed','archived'];
  const POLICY_STATUSES=['draft','review','approved','active','superseded','rejected','archived'];
  const clone=(v)=>v==null?v:JSON.parse(JSON.stringify(v));const text=(v)=>v==null?'':String(v).trim();const required=(v,label)=>{const x=text(v);if(!x)throw new Error(`${label} obrigatório`);return x;};const arr=(v)=>Array.isArray(v)?v:[];
  const validDate=(v,label)=>{if(v==null||v==='')return null;const x=String(v);if(Number.isNaN(Date.parse(x)))throw new Error(`${label} inválida`);return x;};const enumValue=(v,values,label,fallback)=>{const x=text(v)||fallback;if(!values.includes(x))throw new Error(`${label} inválido`);return x;};
  function createState(input={}){return {schemaVersion:1,obligations:[],controls:[],occurrences:[],policies:[],policyVersions:[],evidence:[],reviews:[],history:[],legacyBindings:[],metadata:{createdAt:input.now?input.now():new Date().toISOString(),legacyMigrated:false}};}
  function ensureState(input){const s=input&&typeof input==='object'?input:createState();for(const key of ['obligations','controls','occurrences','policies','policyVersions','evidence','reviews','history','legacyBindings'])if(!Array.isArray(s[key]))s[key]=[];if(!s.metadata||typeof s.metadata!=='object')s.metadata={};s.schemaVersion=1;return s;}
  function createService(input,options={}){
    const data=ensureState(input),now=options.now||(()=>new Date().toISOString()),actor=options.actorProvider||(()=>null),idFactory=options.idFactory||((p)=>`${p}_${Math.random().toString(36).slice(2,10)}`),businessResolver=options.businessResolver||(()=>null),matterResolver=options.matterResolver||(()=>null);const id=(p)=>idFactory(p);
    const stamp=(row,isNew=true)=>{const at=now(),by=actor();if(isNew){row.createdAt=at;row.createdBy=by;}row.updatedAt=at;row.updatedBy=by;return row;};const history=(entityType,entityId,action,details={})=>data.history.push({id:id('coh'),entityType,entityId,action,details:clone(details),at:now(),by:actor()});
    const validateBusiness=(kind,ref)=>{if(ref&&!businessResolver(kind,ref))throw new Error('Referência de Negócios não encontrada');};
    const getObligation=(x)=>data.obligations.find(r=>r.id===x)||null,getPolicy=(x)=>data.policies.find(r=>r.id===x)||null,getPolicyVersion=(x)=>data.policyVersions.find(r=>r.id===x)||null,getOccurrence=(x)=>data.occurrences.find(r=>r.id===x)||null;
    const must=(getter,id,label)=>{const r=getter(id);if(!r)throw new Error(`${label} não encontrado`);return r;};
    function nextCode(prefix,rows){const nums=rows.map(x=>new RegExp(`^${prefix}-(\\d{3})$`).exec(x.code)).filter(Boolean).map(x=>Number(x[1]));return `${prefix}-${String((nums.length?Math.max(...nums):0)+1).padStart(3,'0')}`;}
    function createObligation(input={}){for(const [key,kind] of [['productId','product'],['serviceId','service'],['businessUnitId','business_unit']])validateBusiness(kind,text(input[key]));const row=stamp({id:id('obligation'),code:text(input.code)||nextCode('CMP',data.obligations),title:required(input.title,'Título'),category:text(input.category),description:text(input.description),status:enumValue(input.status,OBLIGATION_STATUSES,'Status','draft'),riskLevel:enumValue(input.riskLevel,RISKS,'Risco','medium'),responsibleUserId:text(input.responsibleUserId)||null,source:text(input.source),authority:text(input.authority),reference:text(input.reference),effectiveFrom:validDate(input.effectiveFrom,'Vigência inicial'),effectiveUntil:validDate(input.effectiveUntil,'Vigência final'),reviewDate:validDate(input.reviewDate,'Data de revisão'),dueDate:validDate(input.dueDate,'Prazo'),productId:text(input.productId)||null,serviceId:text(input.serviceId)||null,businessUnitId:text(input.businessUnitId)||null,notes:text(input.notes),isDemo:Boolean(input.isDemo),metadata:clone(input.metadata||{})});if(data.obligations.some(x=>x.code===row.code))throw new Error('Código de obrigação duplicado');data.obligations.push(row);history('obligation',row.id,'created',{code:row.code});return row;}
    function updateObligation(obligationId,patch={}){const row=must(getObligation,obligationId,'Obrigação');for(const [key,kind] of [['productId','product'],['serviceId','service'],['businessUnitId','business_unit']])if(Object.prototype.hasOwnProperty.call(patch,key)){const ref=text(patch[key]);validateBusiness(kind,ref);row[key]=ref||null;}for(const k of ['title','category','description','responsibleUserId','source','authority','reference','notes'])if(Object.prototype.hasOwnProperty.call(patch,k))row[k]=text(patch[k])||((k==='responsibleUserId')?null:'');if(Object.prototype.hasOwnProperty.call(patch,'status'))row.status=enumValue(patch.status,OBLIGATION_STATUSES,'Status');if(Object.prototype.hasOwnProperty.call(patch,'riskLevel'))row.riskLevel=enumValue(patch.riskLevel,RISKS,'Risco');for(const k of ['effectiveFrom','effectiveUntil','reviewDate','dueDate'])if(Object.prototype.hasOwnProperty.call(patch,k))row[k]=validDate(patch[k],k);stamp(row,false);history('obligation',row.id,'updated',{fields:Object.keys(patch)});return row;}
    function createControl(obligationId,input={}){must(getObligation,obligationId,'Obrigação');const row=stamp({id:id('control'),obligationId,name:required(input.name,'Controle'),description:text(input.description),ownerUserId:text(input.ownerUserId)||null,frequency:text(input.frequency)||'as_needed',status:enumValue(input.status,CONTROL_STATUSES,'Status do controle','planned'),lastReviewAt:validDate(input.lastReviewAt,'Última revisão'),nextReviewAt:validDate(input.nextReviewAt,'Próxima revisão'),notes:text(input.notes)},true);data.controls.push(row);history('obligation',obligationId,'control_created',{controlId:row.id});return row;}
    function reviewControl(controlId,input={}){const row=data.controls.find(x=>x.id===controlId);if(!row)throw new Error('Controle não encontrado');row.lastReviewAt=validDate(input.reviewedAt,'Data da revisão')||now();row.nextReviewAt=validDate(input.nextReviewAt,'Próxima revisão');if(input.status)row.status=enumValue(input.status,CONTROL_STATUSES,'Status do controle');stamp(row,false);const review=stamp({id:id('review'),entityType:'control',entityId:row.id,outcome:text(input.outcome)||'reviewed',notes:text(input.notes)},true);data.reviews.push(review);history('obligation',row.obligationId,'control_reviewed',{controlId:row.id,reviewId:review.id});return review;}
    function createOccurrence(input={}){const matterId=text(input.matterId);if(matterId&&!matterResolver(matterId))throw new Error('Assunto Jurídico não encontrado');const obligationId=text(input.obligationId);if(obligationId)must(getObligation,obligationId,'Obrigação');const row=stamp({id:id('occurrence'),code:text(input.code)||nextCode('OCC',data.occurrences),type:enumValue(input.type,OCCURRENCE_TYPES,'Tipo de ocorrência','other'),title:required(input.title,'Título'),description:text(input.description),severity:enumValue(input.severity,RISKS,'Severidade','medium'),status:enumValue(input.status,OCCURRENCE_STATUSES,'Status','open'),responsibleUserId:text(input.responsibleUserId)||null,occurredAt:validDate(input.occurredAt,'Data da ocorrência')||now(),resolvedAt:validDate(input.resolvedAt,'Data de resolução'),obligationId:obligationId||null,matterId:matterId||null,actions:arr(input.actions).map(String),resolution:text(input.resolution),isDemo:Boolean(input.isDemo),metadata:clone(input.metadata||{})});data.occurrences.push(row);history('occurrence',row.id,'created',{type:row.type});return row;}
    function resolveOccurrence(occurrenceId,input={}){const row=must(getOccurrence,occurrenceId,'Ocorrência');row.status='resolved';row.resolvedAt=validDate(input.resolvedAt,'Data de resolução')||now();row.resolution=required(input.resolution,'Resolução');stamp(row,false);history('occurrence',row.id,'resolved',{});return row;}
    function createPolicy(input={}){const row=stamp({id:id('policy'),code:text(input.code)||nextCode('POL',data.policies),name:required(input.name,'Nome da política'),category:text(input.category),description:text(input.description),ownerUserId:text(input.ownerUserId)||null,status:'draft',isDemo:Boolean(input.isDemo),metadata:clone(input.metadata||{})});if(data.policies.some(x=>x.code===row.code))throw new Error('Código de política duplicado');data.policies.push(row);history('policy',row.id,'created',{code:row.code});if(input.content||input.createInitialVersion!==false)createPolicyVersion(row.id,{content:text(input.content),changeSummary:'Versão inicial'});return row;}
    function versionsFor(policyId){return data.policyVersions.filter(x=>x.policyId===policyId).sort((a,b)=>a.versionNumber-b.versionNumber);}
    function createPolicyVersion(policyId,input={}){const policy=must(getPolicy,policyId,'Política');const prior=versionsFor(policyId);const row=stamp({id:id('policy_version'),policyId,versionNumber:(prior.length?prior[prior.length-1].versionNumber:0)+1,status:'draft',content:text(input.content),changeSummary:text(input.changeSummary),effectiveFrom:validDate(input.effectiveFrom,'Vigência inicial'),effectiveUntil:validDate(input.effectiveUntil,'Vigência final'),reviewDate:validDate(input.reviewDate,'Data de revisão'),approvedAt:null,approvedBy:null,activatedAt:null,isDemo:Boolean(policy.isDemo),metadata:clone(input.metadata||{})});data.policyVersions.push(row);policy.status='draft';stamp(policy,false);history('policy',policyId,'version_created',{versionId:row.id,versionNumber:row.versionNumber});return row;}
    function assertMutableVersion(row){if(['approved','active','superseded'].includes(row.status))throw new Error('Versão aprovada/publicada é imutável');}
    function updatePolicyVersion(versionId,patch={}){const row=must(getPolicyVersion,versionId,'Versão de política');assertMutableVersion(row);for(const k of ['content','changeSummary'])if(Object.prototype.hasOwnProperty.call(patch,k))row[k]=text(patch[k]);for(const k of ['effectiveFrom','effectiveUntil','reviewDate'])if(Object.prototype.hasOwnProperty.call(patch,k))row[k]=validDate(patch[k],k);stamp(row,false);history('policy',row.policyId,'version_updated',{versionId});return row;}
    function sendPolicyVersionToReview(versionId){const row=must(getPolicyVersion,versionId,'Versão de política');assertMutableVersion(row);if(row.status!=='draft'&&row.status!=='rejected')throw new Error('Versão não pode entrar em revisão');row.status='review';stamp(row,false);history('policy',row.policyId,'version_review',{versionId});return row;}
    function approvePolicyVersion(versionId){const row=must(getPolicyVersion,versionId,'Versão de política');if(row.status!=='review')throw new Error('Versão precisa estar em revisão');row.status='approved';row.approvedAt=now();row.approvedBy=actor();stamp(row,false);const policy=must(getPolicy,row.policyId,'Política');policy.status='approved';stamp(policy,false);history('policy',row.policyId,'version_approved',{versionId});return row;}
    function activatePolicyVersion(versionId){const row=must(getPolicyVersion,versionId,'Versão de política');if(row.status!=='approved')throw new Error('Versão precisa estar aprovada');for(const old of versionsFor(row.policyId).filter(x=>x.id!==row.id&&x.status==='active')){old.status='superseded';stamp(old,false);}row.status='active';row.activatedAt=now();stamp(row,false);const policy=must(getPolicy,row.policyId,'Política');policy.status='active';stamp(policy,false);history('policy',row.policyId,'version_activated',{versionId});return row;}
    function addEvidence(input={}){const entityType=required(input.entityType,'Tipo da evidência'),entityId=required(input.entityId,'Entidade');const valid=(entityType==='obligation'&&getObligation(entityId))||(entityType==='control'&&data.controls.some(x=>x.id===entityId))||(entityType==='occurrence'&&getOccurrence(entityId))||(entityType==='policy_version'&&getPolicyVersion(entityId));if(!valid)throw new Error('Entidade da evidência não encontrada');const row=stamp({id:id('evidence'),entityType,entityId,name:required(input.name,'Evidência'),reference:text(input.reference)||null,url:text(input.url)||null,storage:'metadata-only',notes:text(input.notes)},true);data.evidence.push(row);history(entityType,entityId,'evidence_added',{evidenceId:row.id});return row;}
    function addReview(input={}){const row=stamp({id:id('review'),entityType:required(input.entityType,'Tipo'),entityId:required(input.entityId,'Entidade'),reviewedAt:validDate(input.reviewedAt,'Data de revisão')||now(),reviewedBy:text(input.reviewedBy)||actor(),outcome:text(input.outcome)||'reviewed',notes:text(input.notes)},true);data.reviews.push(row);history(row.entityType,row.entityId,'review_added',{reviewId:row.id});return row;}
    function filterRows(rows,filters={},searchFields=[]){let out=rows.filter(x=>filters.includeDemo?true:!x.isDemo);if(!filters.includeArchived)out=out.filter(x=>x.status!=='archived');for(const key of ['status','riskLevel','category','responsibleUserId','productId','serviceId','businessUnitId','type'])if(filters[key])out=out.filter(x=>String(x[key]||'')===String(filters[key]));if(filters.search){const q=text(filters.search).toLowerCase();out=out.filter(x=>searchFields.some(k=>text(x[k]).toLowerCase().includes(q)));}return clone(out);}
    const obligationsFeed=(filters={})=>filterRows(data.obligations,filters,['code','title','category','source','authority','reference']);
    const policiesFeed=(filters={})=>filterRows(data.policies,filters,['code','name','category','description']);
    const occurrencesFeed=(filters={})=>filterRows(data.occurrences,filters,['code','title','description','resolution']);
    function deadlinesFeed(filters={}){const rows=[];for(const o of data.obligations){if(!filters.includeDemo&&o.isDemo)continue;for(const [kind,value] of [['due',o.dueDate],['review',o.reviewDate]])if(value)rows.push({id:`${o.id}:${kind}`,domain:'compliance',entityType:'obligation',entityId:o.id,title:o.title,dueAt:value,type:kind,responsibleUserId:o.responsibleUserId,status:o.status});}for(const c of data.controls){if(c.nextReviewAt)rows.push({id:`${c.id}:review`,domain:'compliance',entityType:'control',entityId:c.id,title:c.name,dueAt:c.nextReviewAt,type:'control_review',responsibleUserId:c.ownerUserId,status:c.status});}for(const v of data.policyVersions){const p=getPolicy(v.policyId);if(v.reviewDate&&p&&(filters.includeDemo||!p.isDemo))rows.push({id:`${v.id}:review`,domain:'compliance',entityType:'policy_version',entityId:v.id,title:p.name,dueAt:v.reviewDate,type:'policy_review',responsibleUserId:p.ownerUserId,status:v.status});}return clone(rows);}
    function classifyLegacy(record={}){const explicit=['compliance_obligation','compliance_policy','compliance_occurrence'].includes(text(record.domain||record.kind||record.entityType));return {status:explicit?'legacy_review_required':'legacy_incompatible',record:clone(record)};}
    return {data,createObligation,updateObligation,getObligation,createControl,reviewControl,createOccurrence,resolveOccurrence,getOccurrence,createPolicy,getPolicy,createPolicyVersion,getPolicyVersion,updatePolicyVersion,sendPolicyVersionToReview,approvePolicyVersion,activatePolicyVersion,versionsFor,addEvidence,addReview,obligationsFeed,policiesFeed,occurrencesFeed,deadlinesFeed,classifyLegacy,historyFor:(type,entityId)=>clone(data.history.filter(x=>x.entityType===type&&x.entityId===entityId))};
  }
  return {OBLIGATION_STATUSES,RISKS,CONTROL_STATUSES,OCCURRENCE_TYPES,OCCURRENCE_STATUSES,POLICY_STATUSES,createState,ensureState,createService};
});
