// VALTREN CANONICAL PARTIES BROWSER/LEGACY ADAPTER
function crmCanonicalPartyService(){
  const core=typeof ValtrenPartyCore!=='undefined'?ValtrenPartyCore:globalThis.ValtrenPartyCore;if(!core)throw new Error('ValtrenPartyCore indisponível');
  state.crmCanonicalParties=core.ensureState(state.crmCanonicalParties);
  if(!state.__crmCanonicalPartyService||state.__crmCanonicalPartyService.data!==state.crmCanonicalParties)state.__crmCanonicalPartyService=core.createService(state.crmCanonicalParties,{actorProvider:()=>state.crmUserId||state.crmUserName||null});
  return state.__crmCanonicalPartyService;
}
function crmCanonicalRoleFromSegment(value){const core=globalThis.ValtrenPartyCore;const key=core.fold(value),map={cliente:'customer',fornecedor:'supplier',parceiro:'partner','prestador de servicos':'service_provider',contratante:'contractual_party',beneficiario:'beneficiary'};return map[key]||core.normalizeRole(value||'crm_contact');}
function crmCanonicalSplitCity(value){const parts=String(value||'').split('/').map((x)=>x.trim()).filter(Boolean);return {city:parts[0]||'',region:parts[1]||''};}
function crmCanonicalIdentityInput(item,type){const city=crmCanonicalSplitCity(item.city),address={line1:item.address||'',number:item.addressNumber||'',complement:item.addressComplement||'',district:item.neighborhood||'',city:city.city,region:city.region,postalCode:item.zipCode||'',country:'BR'};return type==='organization'?{legalName:item.name||item.company||'',tradeName:item.company||'',cnpj:item.cnpj||'',email:item.email||'',phone:item.phone||'',site:item.site||'',address,status:item.status||'active',segment:item.segment||'',metadata:{source:'crm_legacy_adapter'}}:{fullName:item.name||'',cpf:item.cpf||'',email:item.email||'',phone:item.phone||'',address,status:item.status||'active',metadata:{source:'crm_legacy_adapter'}};}
function crmCanonicalBinding(source,id){return crmCanonicalPartyService().data.legacyBindings.find((x)=>x.source===source&&String(x.legacyId)===String(id))||null;}
function crmCanonicalLegacyMetadata(item){return {segment:item.segment||'',profile:item.profile||'',source:item.source||'',stage:item.stage||'',status:item.status||'',priority:item.priority||'',responsible:item.responsible||'',responsibleRole:item.responsibleRole||'',responsibleEmail:item.responsibleEmail||'',responsiblePhone:item.responsiblePhone||'',instagram:item.instagram||'',function:item.function||'',notes:item.notes||'',interactions:Array.isArray(item.interactions)?item.interactions.map((x)=>({...x})):[],legacySnapshot:{...item,interactions:Array.isArray(item.interactions)?item.interactions.map((x)=>({...x})):[]}};}
function crmCanonicalEnsureBinding(source,item,type,entityId,organizationId,legacy){const service=crmCanonicalPartyService();let binding=crmCanonicalBinding(source,item.id);const meta=crmCanonicalLegacyMetadata(item);if(!binding){binding={id:`bind_${source.replace(/\W+/g,'_')}_${item.id}`,source,legacyId:String(item.id),entityType:type,entityId,organizationId:organizationId||'',metadata:meta,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};legacy?service.data.legacyBindings.push(binding):service.data.legacyBindings.unshift(binding);}else{Object.assign(binding,{entityType:type,entityId,organizationId:organizationId||binding.organizationId||'',metadata:{...(binding.metadata||{}),...meta},updatedAt:new Date().toISOString()});}return binding;}
function crmCanonicalUpsertResponsible(orgId,item,legacy){const name=String(item.responsible||'').trim();if(!name||/^equipe valtren$/i.test(name))return null;const service=crmCanonicalPartyService(),core=globalThis.ValtrenPartyCore;const existing=service.getOrganizationContacts(orgId).filter((x)=>core.fold(x.person.fullName)===core.fold(name));let person;if(existing.length===1)person=service.updatePerson(existing[0].person.id,{fullName:name,email:item.responsibleEmail||'',phone:item.responsiblePhone||''},{allowInvalidLegacy:legacy});else person=service.createPerson({fullName:name,email:item.responsibleEmail||'',phone:item.responsiblePhone||'',metadata:{source:'crm_organization_contact'}},{allowInvalidLegacy:legacy});service.assignRole('person',person.id,'organization_contact',{source:'crm'});return service.linkPersonOrganization(person.id,orgId,{relationshipType:'organization_contact',positionTitle:item.responsibleRole||'',primary:true,financialContact:core.fold(item.responsibleRole||'').includes('financeir'),legalContact:core.fold(item.responsibleRole||'').includes('jurid'),metadata:{source:'crm'}});}
function crmCanonicalUpsertLegacyRecord(kind,item,mode='create',options={}){
  try{
    const service=crmCanonicalPartyService(),source=kind==='contacts'?'crm.contacts':'crm.leads',binding=crmCanonicalBinding(source,item.id),legacy=!!options.legacy,type=item.tipo_pessoa==='pessoa_juridica'?'organization':'person',input=crmCanonicalIdentityInput(item,type);
    let entity;
    if(binding&&binding.entityType===type&&service.getEntity(type,binding.entityId))entity=type==='organization'?service.updateOrganization(binding.entityId,input,{allowInvalidLegacy:legacy}):service.updatePerson(binding.entityId,input,{allowInvalidLegacy:legacy});
    else entity=type==='organization'?service.createOrganization(input,{allowInvalidLegacy:legacy,allowExactNameMatch:legacy}):service.createPerson(input,{allowInvalidLegacy:legacy});
    if(kind==='contacts'){service.assignRole(type,entity.id,'crm_contact',{source:'crm'});if(item.segment)service.assignRole(type,entity.id,crmCanonicalRoleFromSegment(item.segment),{source:'crm',displayLabel:item.segment});}else service.assignRole(type,entity.id,'lead',{source:'crm',stage:item.stage||'Novo'});
    let organizationId=type==='organization'?entity.id:'';
    if(type==='organization')crmCanonicalUpsertResponsible(entity.id,item,legacy);
    else if(item.company){let org=binding?.organizationId?service.getEntity('organization',binding.organizationId):null;if(org)service.updateOrganization(org.id,{legalName:item.company,tradeName:item.company},{allowInvalidLegacy:legacy});else org=service.createOrganization({legalName:item.company,tradeName:item.company,status:'active',metadata:{source:'crm_company_reference'}},{allowExactNameMatch:legacy,allowInvalidLegacy:legacy});organizationId=org.id;service.assignRole('organization',org.id,kind==='leads'?'prospect':'crm_contact',{source:'crm'});service.linkPersonOrganization(entity.id,org.id,{relationshipType:'organization_contact',positionTitle:item.function||'',primary:true,metadata:{source:'crm'}});}
    crmCanonicalEnsureBinding(source,item,type,entity.id,organizationId,legacy);crmCanonicalSyncLegacyViews();return true;
  }catch(error){console.error('Falha na infraestrutura canônica de Pessoas e Organizações:',error);if(!options.silent&&typeof alert==='function')alert(error?.message||'Não foi possível salvar o cadastro.');return false;}
}
function crmCanonicalProjectBinding(binding){const service=crmCanonicalPartyService(),entity=service.getEntity(binding.entityType,binding.entityId);if(!entity)return null;const meta=binding.metadata||{},snap=meta.legacySnapshot||{},email=service.primaryContact(binding.entityType,binding.entityId,'email')?.value||snap.email||'',phone=service.primaryContact(binding.entityType,binding.entityId,'phone')?.value||snap.phone||'',address=service.primaryAddress(binding.entityType,binding.entityId),org=binding.organizationId?service.getEntity('organization',binding.organizationId):null,city=address?[address.city,address.region].filter(Boolean).join(' / '):snap.city||'',cpf=binding.entityType==='person'?service.documentFor('person',binding.entityId,'cpf')?.value||snap.cpf||'':'',cnpj=binding.entityType==='organization'?service.documentFor('organization',binding.entityId,'cnpj')?.value||snap.cnpj||'':'';return {id:String(binding.legacyId),tipo_pessoa:binding.entityType==='organization'?'pessoa_juridica':'pessoa_fisica',name:binding.entityType==='organization'?entity.legalName:entity.fullName,company:binding.entityType==='organization'?(entity.tradeName||''):(org?.tradeName||org?.legalName||snap.company||''),segment:meta.segment||snap.segment||'',profile:meta.profile||snap.profile||'',source:meta.source||snap.source||'',stage:meta.stage||snap.stage||'',phone,email,city,responsible:meta.responsible||snap.responsible||'',responsibleRole:meta.responsibleRole||snap.responsibleRole||'',responsibleEmail:meta.responsibleEmail||snap.responsibleEmail||'',responsiblePhone:meta.responsiblePhone||snap.responsiblePhone||'',status:meta.status||entity.status||snap.status||'',priority:meta.priority||snap.priority||'',cpf,cnpj,instagram:meta.instagram||snap.instagram||'',function:meta.function||snap.function||'',address:address?.line1||snap.address||'',addressNumber:address?.number||snap.addressNumber||'',addressComplement:address?.complement||snap.addressComplement||'',neighborhood:address?.district||snap.neighborhood||'',zipCode:address?.postalCode||snap.zipCode||'',notes:meta.notes||snap.notes||'',interactions:Array.isArray(meta.interactions)?meta.interactions.map((x)=>({...x})):[],canonicalEntityType:binding.entityType,canonicalEntityId:binding.entityId,canonicalOrganizationId:binding.organizationId||'',canonicalRoles:service.getRoles(binding.entityType,binding.entityId).map((x)=>x.role)};}
function crmCanonicalSyncLegacyViews(){const service=crmCanonicalPartyService(),contacts=service.data.legacyBindings.filter((x)=>x.source==='crm.contacts').map(crmCanonicalProjectBinding).filter(Boolean),leads=service.data.legacyBindings.filter((x)=>x.source==='crm.leads').map(crmCanonicalProjectBinding).filter(Boolean);state.crmRelContacts=contacts;state.crmRelLeads=leads;return {contacts,leads};}
function crmCanonicalEnsureFromLegacy(){const service=crmCanonicalPartyService();if(!service.data.metadata.crmLegacyMigrated){const contacts=Array.isArray(state.crmRelContacts)?state.crmRelContacts.map((x)=>({...x,interactions:Array.isArray(x.interactions)?x.interactions.map((i)=>({...i})):[]})):[],leads=Array.isArray(state.crmRelLeads)?state.crmRelLeads.map((x)=>({...x,interactions:Array.isArray(x.interactions)?x.interactions.map((i)=>({...i})):[]})):[];contacts.forEach((x)=>crmCanonicalUpsertLegacyRecord('contacts',x,'migrate',{legacy:true,silent:true}));leads.forEach((x)=>crmCanonicalUpsertLegacyRecord('leads',x,'migrate',{legacy:true,silent:true}));service.data.metadata.crmLegacyMigrated=true;service.data.metadata.migratedAt=new Date().toISOString();service.data.metadata.source='crmRelContacts/crmRelLeads';}return crmCanonicalSyncLegacyViews();}
function crmCanonicalRemoveLegacyRecord(kind,id){const service=crmCanonicalPartyService(),source=kind==='contacts'?'crm.contacts':'crm.leads',index=service.data.legacyBindings.findIndex((x)=>x.source===source&&String(x.legacyId)===String(id));if(index<0)return false;const [binding]=service.data.legacyBindings.splice(index,1),stillUsed=service.data.legacyBindings.some((x)=>x.source===source&&x.entityType===binding.entityType&&x.entityId===binding.entityId);if(!stillUsed)service.removeRole(binding.entityType,binding.entityId,kind==='contacts'?'crm_contact':'lead');service.data.history.push({id:`hist_legacy_${Date.now()}_${Math.random().toString(36).slice(2)}`,action:'legacy.binding.removed',entityType:binding.entityType,entityId:binding.entityId,at:new Date().toISOString(),actorId:state.crmUserId||state.crmUserName||null,before:binding,after:null,metadata:{source}});crmCanonicalSyncLegacyViews();return true;}
function crmCanonicalRemoveLegacyRecords(kind,ids){let changed=false;for(const id of new Set((ids||[]).map(String)))changed=crmCanonicalRemoveLegacyRecord(kind,id)||changed;return changed;}
if(typeof module==='object'&&module.exports)module.exports.legacyAdapter={crmCanonicalRoleFromSegment,crmCanonicalSplitCity,crmCanonicalIdentityInput,crmCanonicalLegacyMetadata,crmCanonicalPartyService,crmCanonicalEnsureFromLegacy,crmCanonicalSyncLegacyViews,crmCanonicalUpsertLegacyRecord,crmCanonicalRemoveLegacyRecord,crmCanonicalRemoveLegacyRecords};
