// VALTREN INTELLECTUAL PROPERTY BROWSER
function crmIPPartyResolver(type,id){try{return typeof crmCanonicalPartyService==='function'?crmCanonicalPartyService().getEntity(type,id):null;}catch(_){return null;}}
function crmIPBusinessResolver(kind,id){if(!id)return null;try{const row=typeof crmBusinessResolveDimension==='function'?crmBusinessResolveDimension(kind,id):null;return row&&row.resolved?row:null;}catch(_){return null;}}
function crmIPContractResolver(id){if(!id)return null;try{return typeof crmLegalContractService==='function'?crmLegalContractService().getContract(id):null;}catch(_){return null;}}
function crmIntellectualPropertyService(){if(typeof ValtrenIntellectualPropertyCore==='undefined')throw new Error('ValtrenIntellectualPropertyCore indisponível');state.crmIntellectualProperty=ValtrenIntellectualPropertyCore.ensureState(state.crmIntellectualProperty);if(!state.__crmIPService||state.__crmIPService.data!==state.crmIntellectualProperty)state.__crmIPService=ValtrenIntellectualPropertyCore.createService(state.crmIntellectualProperty,{partyResolver:crmIPPartyResolver,businessResolver:crmIPBusinessResolver,contractResolver:crmIPContractResolver,actorProvider:()=>state.crmUserId||state.crmUserName||null});return state.__crmIPService;}
function crmIntellectualPropertyFeed(filters={}){return crmIntellectualPropertyService().feed(filters);}
function crmIntellectualPropertyDeadlinesFeed(filters={}){return crmIntellectualPropertyService().deadlinesFeed(filters);}
function crmIPTypeLabel(v){return ({trademark:'Marca',patent:'Patente',copyright:'Direito autoral',software:'Software',industrial_design:'Desenho industrial',domain_related:'Ativo relacionado a domínio',other:'Outro'}[v]||v||'—');}
function crmIPStatusLabel(v){return ({draft:'Rascunho',filed:'Pedido protocolado',pending:'Pendente',registered:'Registrado',active:'Ativo',expired:'Expirado',rejected:'Rejeitado',cancelled:'Cancelado',archived:'Arquivado'}[v]||v||'—');}
function crmIPDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('pt-BR');}
function crmIPPartyName(type,id){const p=crmIPPartyResolver(type,id);return p?(type==='person'?(p.fullName||id):(p.legalName||p.tradeName||id)):(id?'Referência não resolvida':'—');}
function crmIPAllParties(){try{const s=crmCanonicalPartyService();return [...s.data.people.map(x=>({type:'person',id:x.id,name:x.fullName||x.id})),...s.data.organizations.map(x=>({type:'organization',id:x.id,name:x.legalName||x.tradeName||x.id}))];}catch(_){return [];}}
function crmIPPartyOptions(){return `<option value="">Sem titular</option>${crmIPAllParties().map(p=>`<option value="${esc(`${p.type}:${p.id}`)}">${esc(`${p.type==='person'?'Pessoa':'Organização'} · ${p.name}`)}</option>`).join('')}`;}
function crmIPParseParty(v=''){const [ownerPartyType,...rest]=String(v).split(':');return {ownerPartyType,ownerPartyId:rest.join(':')};}
function crmIPBusinessOptions(kind){const rows=kind==='product'?(typeof crmBusinessProductsFeed==='function'?crmBusinessProductsFeed({includeArchived:false}):[]):kind==='service'?(typeof crmBusinessServicesFeed==='function'?crmBusinessServicesFeed({includeArchived:false}):[]):(typeof crmBusinessUnitsFeed==='function'?crmBusinessUnitsFeed({includeArchived:false}):[]);return `<option value="">Sem referência</option>${rows.map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.id)}</option>`).join('')}`;}
function crmIPContractOptions(){let rows=[];try{rows=crmLegalContractService().data.contracts.filter(x=>!x.isDemo&&x.status!=='archived');}catch(_){}return `<option value="">Sem Contrato</option>${rows.map(x=>`<option value="${esc(x.id)}">${esc(`${x.number||''} · ${x.name||x.id}`)}</option>`).join('')}`;}
function crmIPBreadcrumb(){return crmArchitectureBreadcrumb([{label:'Jurídico',href:'#/crm/juridico'},{label:'Propriedade Intelectual',href:'#/crm/juridico/propriedade-intelectual'}]);}
function crmIPSetQuery(changes){const q=new URLSearchParams(routeInfo().query||new URLSearchParams());Object.entries(changes).forEach(([k,v])=>{if(v==null||v===''||v==='all')q.delete(k);else q.set(k,String(v));});location.hash=`#/crm/juridico/propriedade-intelectual${q.toString()?`?${q.toString()}`:''}`;}
function crmIPFilters(){const q=routeInfo().query;return {tab:q.get('tab')||'all',search:q.get('q')||'',type:q.get('type')||'',status:q.get('status')||'',ownerPartyId:q.get('owner')||'',responsibleUserId:q.get('responsible')||'',expiringBefore:q.get('expires')||'',page:Math.max(1,Number(q.get('page')||1))};}
function crmIPTabs(tab){return `<nav class="crm-ip-tabs" aria-label="Tipos de propriedade intelectual">${[['all','Todos'],['trademark','Marcas'],['software','Software'],['other','Outros']].map(([id,label])=>`<button type="button" class="${tab===id?'active':''}" data-action="crm-ip-tab" data-tab="${id}">${label}</button>`).join('')}</nav>`;}
function crmIPToolbar(f){return `<section class="crm-ip-toolbar"><label class="crm-ip-search">${icon('search',15)}<input id="crm-ip-search" type="search" value="${esc(f.search)}" placeholder="Buscar ativo, pedido, registro ou jurisdição"></label><select id="crm-ip-type"><option value="">Todos os tipos</option>${ValtrenIntellectualPropertyCore.ASSET_TYPES.map(x=>`<option value="${x}" ${f.type===x?'selected':''}>${crmIPTypeLabel(x)}</option>`).join('')}</select><select id="crm-ip-status"><option value="">Todos os status</option>${ValtrenIntellectualPropertyCore.ASSET_STATUSES.map(x=>`<option value="${x}" ${f.status===x?'selected':''}>${crmIPStatusLabel(x)}</option>`).join('')}</select><select id="crm-ip-owner"><option value="">Todos os titulares</option>${crmIPAllParties().map(p=>`<option value="${esc(p.id)}" ${f.ownerPartyId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><input id="crm-ip-expires" type="date" value="${esc(f.expiringBefore)}" aria-label="Vencimento até"><details class="crm-ip-more"><summary>Mais filtros</summary><div><input id="crm-ip-responsible" value="${esc(f.responsibleUserId)}" placeholder="Responsável"></div></details></section>`;}
function crmIPRows(f){let filters={search:f.search,type:f.type,status:f.status,ownerPartyId:f.ownerPartyId,responsibleUserId:f.responsibleUserId,expiringBefore:f.expiringBefore};let rows=crmIntellectualPropertyFeed(filters);if(f.tab==='trademark')rows=rows.filter(x=>x.type==='trademark');else if(f.tab==='software')rows=rows.filter(x=>x.type==='software');else if(f.tab==='other')rows=rows.filter(x=>!['trademark','software'].includes(x.type));const limit=50,pages=Math.max(1,Math.ceil(rows.length/limit));return {rows:rows.slice((f.page-1)*limit,f.page*limit),page:f.page,total:rows.length,pages};}
function crmIPPagination(r){if(r.pages<=1)return '';return `<nav class="crm-ip-pagination"><button data-action="crm-ip-page" data-page="${Math.max(1,r.page-1)}" ${r.page<=1?'disabled':''}>Anterior</button><span>Página ${r.page} de ${r.pages}</span><button data-action="crm-ip-page" data-page="${Math.min(r.pages,r.page+1)}" ${r.page>=r.pages?'disabled':''}>Próxima</button></nav>`;}
function crmIntellectualPropertyPage(){const f=crmIPFilters(),r=crmIPRows(f),actions=`<button type="button" class="primary" data-action="crm-ip-new">${icon('plus',14)} Novo Ativo</button>`,table=`<section class="crm-ip-table-card"><div class="crm-ip-table-wrap"><table><thead><tr><th>Ativo</th><th>Tipo</th><th>Titular</th><th>Registro</th><th>Jurisdição</th><th>Vigência</th><th>Status</th><th>Responsável</th><th>Ação</th></tr></thead><tbody>${r.rows.map(a=>`<tr><td><strong>${esc(a.name)}</strong><small>${esc(a.code)}</small></td><td>${crmIPTypeLabel(a.type)}</td><td>${esc(crmIPPartyName(a.ownerPartyType,a.ownerPartyId))}</td><td>${esc(a.registrationNumber||a.applicationNumber||'—')}</td><td>${esc(a.jurisdiction||'—')}</td><td>${esc(`${crmIPDate(a.registrationDate||a.filingDate)} → ${crmIPDate(a.expirationDate||a.renewalDate)}`)}</td><td><span class="crm-ip-status status-${esc(a.status)}">${crmIPStatusLabel(a.status)}</span></td><td>${esc(a.responsibleUserId||'—')}</td><td><button data-action="crm-ip-view" data-id="${esc(a.id)}">Ver</button></td></tr>`).join('')}</tbody></table></div>${r.rows.length?'':`<div class="crm-ip-empty"><strong>Nenhum ativo de Propriedade Intelectual cadastrado.</strong><span>Cadastre apenas ativos reais. Licenças operacionais continuam em Administração / Patrimônio e Licenças.</span></div>`}${crmIPPagination(r)}</section>`;return crmFidelityPage('legal','ip','Propriedade Intelectual','Marcas, software, direitos de PI, pedidos, registros, titularidade e vencimentos.',actions,`${crmIPBreadcrumb()}${crmIPTabs(f.tab)}${crmIPToolbar(f)}${table}`);}
function crmIPOverlay(html){document.querySelector('.crm-ip-overlay')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="crm-ip-overlay"><div class="crm-ip-modal">${html}</div></div>`);}
function crmIPEditor(){crmIPOverlay(`<header><div><strong>Novo Ativo de PI</strong><small>Cadastro interno. Status Registrado exige número de registro; nenhuma integração oficial é simulada.</small></div><button data-action="crm-ip-close">×</button></header><form id="crm-ip-form"><div class="crm-ip-form-grid"><label>Nome<input name="name" required></label><label>Tipo<select name="type">${ValtrenIntellectualPropertyCore.ASSET_TYPES.map(x=>`<option value="${x}">${crmIPTypeLabel(x)}</option>`).join('')}</select></label><label>Categoria<input name="category"></label><label>Status<select name="status">${ValtrenIntellectualPropertyCore.ASSET_STATUSES.map(x=>`<option value="${x}">${crmIPStatusLabel(x)}</option>`).join('')}</select></label><label>Titular<select name="owner">${crmIPPartyOptions()}</select></label><label>Jurisdição<input name="jurisdiction"></label><label>Número do pedido<input name="applicationNumber"></label><label>Número do registro<input name="registrationNumber"></label><label>Data do pedido<input type="date" name="filingDate"></label><label>Data do registro<input type="date" name="registrationDate"></label><label>Validade<input type="date" name="expirationDate"></label><label>Renovação<input type="date" name="renewalDate"></label><label>Responsável<input name="responsibleUserId"></label><label>Produto<select name="productId">${crmIPBusinessOptions('product')}</select></label><label>Serviço<select name="serviceId">${crmIPBusinessOptions('service')}</select></label><label>Unidade<select name="businessUnitId">${crmIPBusinessOptions('business_unit')}</select></label><label>Contrato relacionado<select name="contractId">${crmIPContractOptions()}</select></label><label class="wide">Descrição<textarea name="description"></textarea></label><label class="wide">Notas<textarea name="notes"></textarea></label></div><footer><button type="button" data-action="crm-ip-close">Cancelar</button><button class="primary">Salvar</button></footer></form>`);}
function crmIPDetail(id){const d=crmIntellectualPropertyService().detail(id),a=d.asset,section=(title,body)=>`<section><h4>${title}</h4>${body}</section>`,list=(rows,render,empty)=>rows.length?rows.map(render).join(''):`<p class="muted">${empty}</p>`;crmIPOverlay(`<header><div><strong>${esc(a.code)} · ${esc(a.name)}</strong><small>${crmIPTypeLabel(a.type)} · ${crmIPStatusLabel(a.status)}</small></div><button data-action="crm-ip-close">×</button></header><div class="crm-ip-detail">${section('Visão Geral',`<dl><div><dt>Titular</dt><dd>${esc(crmIPPartyName(a.ownerPartyType,a.ownerPartyId))}</dd></div><div><dt>Jurisdição</dt><dd>${esc(a.jurisdiction||'—')}</dd></div><div><dt>Pedido</dt><dd>${esc(a.applicationNumber||'—')}</dd></div><div><dt>Registro</dt><dd>${esc(a.registrationNumber||'—')}</dd></div></dl><p>${esc(a.description||'Sem descrição.')}</p>`)}${section('Registros',list(d.registrations,x=>`<article>${esc(x.registrationNumber||x.applicationNumber||'Registro interno')}<small>${esc(x.status)} · ${crmIPDate(x.registrationDate||x.filingDate)}</small></article>`,'Nenhum registro/pedido adicional.'))}${section('Titularidade',list(d.owners,x=>`<article>${esc(crmIPPartyName(x.partyType,x.partyId))}<small>${esc(x.role)}</small></article>`,'Nenhum vínculo adicional.'))}${section('Licenças jurídicas de PI',list(d.licenses,x=>`<article>Contrato ${esc(x.contractId)}<small>Condições permanecem no owner Contratos.</small></article>`,'Nenhum licenciamento jurídico.'))}${section('Prazos',list(d.deadlines,x=>`<article>${esc(x.title)}<small>${crmIPDate(x.dueAt)} · ${esc(x.status)}</small></article>`,'Nenhum prazo adicional.'))}${section('Documentos',list(d.documents,x=>`<article>${esc(x.name)}<small>Metadata/referência · sem storage persistente</small></article>`,'Nenhum documento.'))}${section('Relacionamentos',`<dl><div><dt>Produto</dt><dd>${esc(a.productId||'—')}</dd></div><div><dt>Serviço</dt><dd>${esc(a.serviceId||'—')}</dd></div><div><dt>Unidade</dt><dd>${esc(a.businessUnitId||'—')}</dd></div><div><dt>Contrato</dt><dd>${esc(a.contractId||'—')}</dd></div></dl>`)}${section('Histórico',list(d.history,x=>`<article>${esc(x.action)}<small>${crmIPDate(x.at)}</small></article>`,'Sem histórico.'))}</div><footer class="crm-ip-detail-actions"><button data-action="crm-ip-add-deadline" data-id="${esc(id)}">Adicionar prazo</button><button data-action="crm-ip-add-license" data-id="${esc(id)}">Vincular licença/Contrato</button></footer>`);}
function crmIPRefresh(){if(routeInfo().path==='/crm/juridico/propriedade-intelectual')render();}
function crmIPBind(){if(window.__crmIPBound)return;window.__crmIPBound=true;document.addEventListener('click',e=>{const t=e.target.closest('[data-action]');if(!t)return;const a=t.dataset.action;if(!a||!a.startsWith('crm-ip-'))return;e.preventDefault();const s=crmIntellectualPropertyService();if(a==='crm-ip-tab')return crmIPSetQuery({tab:t.dataset.tab,page:1});if(a==='crm-ip-page')return crmIPSetQuery({page:t.dataset.page});if(a==='crm-ip-new')return crmIPEditor();if(a==='crm-ip-close'){document.querySelector('.crm-ip-overlay')?.remove();return;}if(a==='crm-ip-view')return crmIPDetail(t.dataset.id);if(a==='crm-ip-add-deadline'){const title=prompt('Título do prazo');if(!title)return;const dueAt=prompt('Vencimento (AAAA-MM-DD)');if(!dueAt)return;try{s.addDeadline(t.dataset.id,{title,dueAt});crmIPDetail(t.dataset.id);}catch(err){alert(err.message);}return;}if(a==='crm-ip-add-license'){const contractId=prompt('ID do Contrato canônico');if(!contractId)return;try{s.addLicense(t.dataset.id,{contractId});crmIPDetail(t.dataset.id);}catch(err){alert(err.message);}return;}});document.addEventListener('submit',e=>{if(e.target.id!=='crm-ip-form')return;e.preventDefault();const fd=new FormData(e.target),input={};for(const [k,v] of fd.entries())input[k]=String(v).trim();const party=crmIPParseParty(input.owner);delete input.owner;Object.assign(input,party.ownerPartyId?party:{});try{crmIntellectualPropertyService().createAsset(input);document.querySelector('.crm-ip-overlay')?.remove();crmIPRefresh();}catch(err){alert(err.message);}});document.addEventListener('change',e=>{const map={'crm-ip-type':'type','crm-ip-status':'status','crm-ip-owner':'owner','crm-ip-expires':'expires','crm-ip-responsible':'responsible'};if(map[e.target.id])crmIPSetQuery({[map[e.target.id]]:e.target.value,page:1});});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='crm-ip-search'){e.preventDefault();crmIPSetQuery({q:e.target.value,page:1});}});}
crmIPBind();
