// VALTREN FINANCIAL TRANSACTIONS PRESENTATION
// Camada final de apresentação da tabela de Transações.
// Mantém uma única coluna monetária e não renderiza os antigos cards de status.

function crmFinanceSignedMoney(tx){
  const amount=Number(tx?.amount||0);
  return crmFinanceMoney(tx?.direction==='outflow'?-amount:amount,tx?.currency||'BRL');
}

crmFinanceRow=function(tx){
  const service=crmFinanceService(),ui=crmFinanceUi(),account=service.getAccount(tx.financialAccountId),hasAttachments=Array.isArray(tx.attachments)&&tx.attachments.length,hasNotes=!!tx.notes,allocationLabel=tx.allocations?.length>1?`${tx.allocations.length} destinos · Rateado`:crmFinanceProductLabel(tx),directionClass=tx.direction==='outflow'?'out':'in';
  return `<tr data-fin-row="${esc(tx.id)}"><td><input type="checkbox" data-fin-select value="${esc(tx.id)}" ${ui.selected.includes(tx.id)?'checked':''} aria-label="Selecionar transação"></td><td><strong>${esc(tx.transactionDate||'-')}</strong><small>${esc(account?.name||'-')}</small></td><td class="crm-fin-description"><strong>${esc(tx.originalDescription||'Sem descrição')}</strong>${tx.normalizedDescription?`<small>${esc(tx.normalizedDescription)}</small>`:''}<div class="crm-fin-description-meta"><em>${esc(crmFinanceSourceLabel(tx.source))}${tx.classificationSource==='rule'?' · Regra automática':''}</em><select data-action="crm-fin-nature" data-id="${esc(tx.id)}" aria-label="Classificação financeira">${crmFinanceNatureOptions(tx.financialNature)}</select></div></td><td class="money ${directionClass}">${crmFinanceSignedMoney(tx)}</td><td data-col="counterparty"><select class="crm-fin-inline" data-action="crm-fin-counterparty" data-id="${esc(tx.id)}">${crmFinanceCounterpartyOptions(tx.counterpartyType,tx.counterpartyId)}</select></td><td><select class="crm-fin-inline" data-action="crm-fin-category" data-id="${esc(tx.id)}">${crmFinanceCategoryOptions(tx.categoryId)}</select></td><td><select class="crm-fin-inline" data-action="crm-fin-business" data-id="${esc(tx.id)}" title="${esc(allocationLabel)}">${crmFinanceBusinessOptions(tx)}</select>${tx.allocations?.length>1?`<button class="crm-fin-rate-badge" type="button" data-action="crm-fin-allocate" data-id="${esc(tx.id)}">Rateado</button>`:''}</td><td data-col="status"><span class="crm-fin-status ${tx.status}">${crmFinanceStatusLabel(tx.status)}</span><small>${crmFinanceReconLabel(tx.reconciliationStatus)}</small></td><td class="crm-fin-icons" data-col="indicators">${hasAttachments?`<span title="${tx.attachments.length} anexo(s)">📎</span>`:''}${hasNotes?'<span title="Possui observação">●</span>':''}</td><td class="crm-fin-row-actions">${tx.status==='pending'?`<button type="button" class="primary" data-action="crm-fin-post" data-id="${esc(tx.id)}">Lançar</button>`:tx.status==='posted'&&tx.reconciliationStatus!=='reconciled'?`<button type="button" class="secondary" data-action="crm-fin-reconcile" data-id="${esc(tx.id)}">Conciliar</button>`:tx.status==='excluded'?`<button type="button" class="secondary" data-action="crm-fin-restore" data-id="${esc(tx.id)}">Restaurar</button>`:''}<details><summary aria-label="Mais ações">•••</summary><div><button type="button" data-action="crm-fin-detail" data-id="${esc(tx.id)}">Ver detalhes</button><button type="button" data-action="crm-fin-edit" data-id="${esc(tx.id)}">Editar</button>${tx.status!=='excluded'?`<button type="button" data-action="crm-fin-allocate" data-id="${esc(tx.id)}">Ratear</button><button type="button" data-action="crm-fin-match" data-id="${esc(tx.id)}">Correspondência</button><button type="button" data-action="crm-fin-exclude" data-id="${esc(tx.id)}">Excluir</button>`:''}</div></details></td></tr>`;
};

crmFinanceTable=function(){
  const result=crmFinanceQuery(),filters=result.filters,total=result.total,start=total?((filters.page-1)*filters.limit+1):0,end=Math.min(total,filters.page*filters.limit),pages=Math.max(1,Math.ceil(total/filters.limit)),hidden=crmFinanceUi().hiddenColumns||[],tableClasses=hidden.map((id)=>`hide-${id}`).join(' '),rows=result.rows.map(crmFinanceRow).join('');
  return `${crmFinanceBulkBar()}<section class="crm-fin-table-card"><div class="crm-fin-table-wrap"><table class="crm-fin-table ${tableClasses}"><thead><tr><th><input type="checkbox" data-action="crm-fin-select-page" aria-label="Selecionar página"></th><th>Data</th><th>Descrição</th><th class="right">Valor</th><th data-col="counterparty">Origem/Destino</th><th>Categoria</th><th>Produto/Sistema</th><th data-col="status">Status</th><th data-col="indicators"></th><th>Ação</th></tr></thead><tbody>${rows}</tbody></table>${rows?'':`<div class="crm-fin-empty"><strong>Nenhuma transação ${filters.status==='pending'?'pendente':filters.status==='posted'?'lançada':'excluída'}</strong><span>${filters.status==='pending'?'Todas as movimentações deste recorte já foram revisadas ou ainda não há dados.':'Nenhuma movimentação encontrada para os filtros atuais.'}</span></div>`}</div><footer class="crm-fin-pagination"><span>${start}–${end} de ${total}</span><div><button type="button" data-action="crm-fin-page" data-page="${filters.page-1}" ${filters.page<=1?'disabled':''}>‹</button><b>Página ${filters.page} de ${pages}</b><button type="button" data-action="crm-fin-page" data-page="${filters.page+1}" ${filters.page>=pages?'disabled':''}>›</button></div></footer></section>`;
};

crmTransactionsPage=function(){
  const service=crmFinanceService(),filters=crmFinanceCurrentFilters(),selected=filters.accountId==='all'?null:service.getAccount(filters.accountId),canSync=!!selected?.integrationId&&selected.integrationValidated;
  const actions=`<button class="secondary" type="button" data-action="crm-fin-import-ofx" title="Importação OFX será habilitada apenas com parser validado">${crmRefIcon('upload')} Importar OFX</button><button class="secondary" type="button" data-action="crm-fin-rules">${crmRefIcon('layers')} Regras</button><button class="secondary" type="button" data-action="crm-fin-update" ${canSync?'':'disabled'} title="${canSync?'Conta possui integração validada':'Nenhuma integração financeira validada para esta conta'}">${crmRefIcon('refresh')} Atualizar</button><button class="secondary" type="button" data-action="crm-fin-add-account">${crmRefIcon('plus')} Adicionar conta</button><button class="primary" type="button" data-action="crm-fin-new-transaction">${crmRefIcon('plus')} Nova Transação</button>`;
  return crmFidelityPage('accounting','finance','Transações','Classificação e conciliação das movimentações financeiras',actions,`<div class="crm-fin-workspace">${crmFinanceAccountCards()}${crmFinanceToolbar()}${crmFinanceTable()}</div>`);
};
