// VALTREN FINANCIAL TRANSACTIONS PRESENTATION
// Camada final de apresentação da tabela de Transações.
// Mantém uma única coluna monetária e não renderiza os antigos cards de status.

function crmFinanceSignedMoney(tx){
  const amount=Number(tx?.amount||0);
  return crmFinanceMoney(tx?.direction==='outflow'?-amount:amount,tx?.currency||'BRL');
}

function crmFinanceAccountCards(){
  const service=crmFinanceService(),filters=crmFinanceCurrentFilters(),all=service.allAccountsSummary();
  const card=(id,name,summary)=>`<button type="button" class="crm-fin-account-card ${filters.accountId===id?'active':''}" data-action="crm-fin-select-account" data-id="${esc(id)}"><span>${esc(name)}</span><strong>${summary.currentBalance==null?'Saldo não informado':crmFinanceMoney(summary.currentBalance)}</strong></button>`;
  return `<div class="crm-fin-account-strip">${card('all','Todas as contas',all)}${service.data.accounts.filter((a)=>a.status!=='inactive'&&!a.isDemo).map((a)=>card(a.id,a.name,service.accountSummary(a.id))).join('')}<button type="button" class="crm-fin-account-add" data-action="crm-fin-add-account">${icon('plus',18)}<span>Adicionar conta</span><small>Cadastro</small></button></div>`;
}

crmFinanceToolbar=function(){
  const service=crmFinanceService(),filters=crmFinanceCurrentFilters(),products=crmFinanceProducts();
  return `<div class="crm-fin-toolbar"><label class="crm-fin-search">${icon('search',15)}<input id="crm-fin-search" type="search" value="${esc(filters.search)}" placeholder="Buscar descrição, contraparte, categoria, documento, valor ou Produto/Sistema"></label><select id="crm-fin-period"><option value="all" ${filters.period==='all'?'selected':''}>Todo período</option><option value="today" ${filters.period==='today'?'selected':''}>Hoje</option><option value="week" ${filters.period==='week'?'selected':''}>Esta semana</option><option value="month" ${filters.period==='month'?'selected':''}>Este mês</option><option value="previous" ${filters.period==='previous'?'selected':''}>Mês anterior</option><option value="custom" ${filters.period==='custom'?'selected':''}>Personalizado</option></select>${filters.period==='custom'?`<input id="crm-fin-from" type="date" value="${esc(filters.from)}"><input id="crm-fin-to" type="date" value="${esc(filters.to)}">`:''}<select id="crm-fin-type"><option value="">Todos os tipos</option><option value="revenue" ${filters.type==='revenue'?'selected':''}>Receitas</option><option value="expense" ${filters.type==='expense'?'selected':''}>Despesas</option><option value="transfer" ${filters.type==='transfer'?'selected':''}>Transferências</option></select><select id="crm-fin-dimension"><option value="">Todo Produto/Sistema</option><option value="corporate" ${filters.dimension==='corporate'?'selected':''}>Corporativo</option>${products.map((p)=>`<option value="product:${esc(p.id)}" ${filters.dimension===`product:${p.id}`?'selected':''}>${esc(p.name)}</option>`).join('')}</select>${filters.accountId==='all'?`<select id="crm-fin-account-filter"><option value="all">Todas as contas</option>${service.data.accounts.filter((a)=>a.status!=='inactive'&&!a.isDemo).map((a)=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}</select>`:''}</div>`;
};

function crmFinanceRow(tx){
  const service=crmFinanceService(),ui=crmFinanceUi(),account=service.getAccount(tx.financialAccountId),hasAttachments=Array.isArray(tx.attachments)&&tx.attachments.length,hasNotes=!!tx.notes,directionClass=tx.direction==='outflow'?'out':'in';
  const automationMeta=tx.classificationSource==='rule'?'<div class="crm-fin-description-meta"><em>Regra automática</em></div>':'';
  return `<tr data-fin-row="${esc(tx.id)}"><td><input type="checkbox" data-fin-select value="${esc(tx.id)}" ${ui.selected.includes(tx.id)?'checked':''} aria-label="Selecionar transação"></td><td><strong>${esc(tx.transactionDate||'-')}</strong><small>${esc(account?.name||'-')}</small></td><td class="crm-fin-description"><strong>${esc(tx.originalDescription||'Sem descrição')}</strong>${tx.normalizedDescription?`<small>${esc(tx.normalizedDescription)}</small>`:''}${automationMeta}</td><td class="money ${directionClass}">${crmFinanceSignedMoney(tx)}</td><td data-col="status"><span class="crm-fin-status ${tx.status}">${crmFinanceStatusLabel(tx.status)}</span><small>${crmFinanceReconLabel(tx.reconciliationStatus)}</small></td><td class="crm-fin-icons" data-col="indicators">${hasAttachments?`<span title="${tx.attachments.length} anexo(s)">📎</span>`:''}${hasNotes?'<span title="Possui observação">●</span>':''}</td><td class="crm-fin-row-actions"><details><summary aria-label="Ações da transação">⋯</summary><div><button type="button" data-action="crm-fin-detail" data-id="${esc(tx.id)}">Ver</button><button type="button" data-action="crm-fin-edit" data-id="${esc(tx.id)}">Editar</button><button type="button" data-action="crm-fin-exclude" data-id="${esc(tx.id)}" ${tx.status==='excluded'?'disabled':''}>Excluir</button></div></details></td></tr>`;
}

function crmFinanceTable(){
  const result=crmFinanceQuery(),filters=result.filters,total=result.total,start=total?((filters.page-1)*filters.limit+1):0,end=Math.min(total,filters.page*filters.limit),pages=Math.max(1,Math.ceil(total/filters.limit)),hidden=crmFinanceUi().hiddenColumns||[],tableClasses=hidden.map((id)=>`hide-${id}`).join(' '),rows=result.rows.map(crmFinanceRow).join('');
  return `${crmFinanceBulkBar()}<section class="crm-fin-table-card"><div class="crm-fin-table-wrap"><table class="crm-fin-table ${tableClasses}"><thead><tr><th><input type="checkbox" data-action="crm-fin-select-page" aria-label="Selecionar página"></th><th>Data</th><th>Descrição</th><th class="right">Valor</th><th data-col="status">Status</th><th data-col="indicators"></th><th>Ações</th></tr></thead><tbody>${rows}</tbody></table>${rows?'':`<div class="crm-fin-empty"><strong>Nenhuma transação ${filters.status==='pending'?'pendente':filters.status==='posted'?'lançada':'excluída'}</strong><span>${filters.status==='pending'?'Todas as movimentações deste recorte já foram revisadas ou ainda não há dados.':'Nenhuma movimentação encontrada para os filtros atuais.'}</span></div>`}</div><footer class="crm-fin-pagination"><span>${start}–${end} de ${total}</span><div><button type="button" data-action="crm-fin-page" data-page="${filters.page-1}" ${filters.page<=1?'disabled':''}>‹</button><b>Página ${filters.page} de ${pages}</b><button type="button" data-action="crm-fin-page" data-page="${filters.page+1}" ${filters.page>=pages?'disabled':''}>›</button></div></footer></section>`;
}

function crmTransactionsPage(){
  const service=crmFinanceService(),filters=crmFinanceCurrentFilters(),selected=filters.accountId==='all'?null:service.getAccount(filters.accountId),canSync=!!selected?.integrationId&&selected.integrationValidated;
  const actions=`<button class="secondary" type="button" data-action="crm-fin-import-ofx" title="Importação OFX será habilitada apenas com parser validado">${crmRefIcon('upload')} Importar OFX</button><button class="secondary" type="button" data-action="crm-fin-rules">${crmRefIcon('layers')} Regras</button><button class="secondary" type="button" data-action="crm-fin-update" ${canSync?'':'disabled'} title="${canSync?'Conta possui integração validada':'Nenhuma integração financeira validada para esta conta'}">${crmRefIcon('refresh')} Atualizar</button><button class="secondary" type="button" data-action="crm-fin-add-account">${crmRefIcon('plus')} Adicionar conta</button><button class="primary" type="button" data-action="crm-fin-new-transaction">${crmRefIcon('plus')} Nova Transação</button>`;
  return crmFidelityPage('accounting','finance','Transações','Classificação e conciliação das movimentações financeiras',actions,`<div class="crm-fin-workspace">${crmFinanceAccountCards()}${crmFinanceToolbar()}${crmFinanceTable()}</div>`);
}
