'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ValtrenLegalMatterCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const MATTER_TYPES=['judicial','administrative','notification','dispute','claim','regulatory','consumer','labor','tax','contractual','other'];
  const MATTER_STATUSES=['open','analysis','in_progress','waiting','settled','closed','archived'];
  const PRIORITIES=['low','medium','high','critical'];
  const RISKS=['low','medium','high','critical'];
  const EVENT_TYPES=['hearing','meeting','notification','filing','decision','deadline','settlement','other'];
  const DEADLINE_STATUSES=['open','completed','cancelled'];
  const clone=(v)=>v==null?v:JSON.parse(JSON.stringify(v));
  const text=(v)=>v==null?'':String(v).trim();
  const num=(v)=>v==null||v===''?null:Number(v);
  const arr=(v)=>Array.isArray(v)?v:[];
  const required=(v,label)=>{const out=text(v);if(!out)throw new Error(`${label} obrigatório`);return out;};
  const enumValue=(v,values,label,fallback)=>{const out=text(v)||fallback;if(!values.includes(out))throw new Error(`${label} inválido`);return out;};
  const dateValue=(v,label)=>{if(v==null||v==='')return null;const out=String(v);if(Number.isNaN(Date.parse(out)))throw new Error(`${label} inválida`);return out;};
  function createState(input={}){return {schemaVersion:1,matters:[],parties:[],events:[],deadlines:[],actions:[],authorities:[],documents:[],settlements:[],history:[],legacyBindings:[],metadata:{createdAt:input.now?input.now():new Date().toISOString(),legacyMigrated:false}};}
  function ensureState(input){const s=input&&typeof input==='object'?input:createState();for(const key of ['matters','parties','events','deadlines','actions','authorities','documents','settlements','history','legacyBindings'])if(!Array.isArray(s[key]))s[key]=[];if(!s.metadata||typeof s.metadata!=='object')s.metadata={};s.schemaVersion=1;return s;}
  function createService(input,options={}){
    const data=ensureState(input),now=options.now||(()=>new Date().toISOString()),actor=options.actorProvider||(()=>null),idFactory=options.idFactory||((prefix)=>`${prefix}_${Math.random().toString(36).slice(2,10)}`),partyResolver=options.partyResolver||(()=>null),businessResolver=options.businessResolver||(()=>null),contractResolver=options.contractResolver||(()=>null);
    const id=(prefix)=>idFactory(prefix);
    const stamp=(row,isNew=true)=>{const at=now(),by=actor();if(isNew){row.createdAt=at;row.createdBy=by;}row.updatedAt=at;row.updatedBy=by;return row;};
    const history=(entityType,entityId,action,details={})=>data.history.push({id:id('lmh'),entityType,entityId,action,details:clone(details),at:now(),by:actor()});
    const getMatter=(matterId)=>data.matters.find(x=>x.id===matterId)||null;
    const mustMatter=(matterId)=>{const row=getMatter(matterId);if(!row)throw new Error('Assunto Jurídico não encontrado');return row;};
    const validateParty=(partyType,partyId)=>{if(!['person','organization'].includes(partyType))throw new Error('Tipo de parte inválido');if(!partyResolver(partyType,partyId))throw new Error('Pessoa/Organização canônica não encontrada');};
    const validateBusiness=(kind,refId)=>{if(!refId)return;if(!businessResolver(kind,refId))throw new Error('Referência de Negócios não encontrada');};
    const validateContract=(contractId)=>{if(contractId&&!contractResolver(contractId))throw new Error('Contrato não encontrado');};
    function nextNumber(){const year=new Date(now()).getUTCFullYear();const re=new RegExp(`^AJ-${year}-(\\d{4})$`);const seq=data.matters.map(x=>re.exec(x.number)).filter(Boolean).map(x=>Number(x[1]));return `AJ-${year}-${String((seq.length?Math.max(...seq):0)+1).padStart(4,'0')}`;}
    function createMatter(input={}){
      validateContract(text(input.contractId));validateBusiness('product',text(input.productId));validateBusiness('service',text(input.serviceId));validateBusiness('business_unit',text(input.businessUnitId));
      const exposure=num(input.estimatedExposure);if(exposure!=null&&(!Number.isFinite(exposure)||exposure<0))throw new Error('Exposição estimada inválida');
      const row=stamp({id:id('matter'),number:text(input.number)||nextNumber(),title:required(input.title,'Título'),type:enumValue(input.type,MATTER_TYPES,'Tipo','other'),category:text(input.category),status:enumValue(input.status,MATTER_STATUSES,'Status','open'),priority:enumValue(input.priority,PRIORITIES,'Prioridade','medium'),riskLevel:enumValue(input.riskLevel,RISKS,'Risco','medium'),description:text(input.description),jurisdiction:text(input.jurisdiction),authority:text(input.authority),responsibleUserId:text(input.responsibleUserId)||null,openedAt:dateValue(input.openedAt,'Data de abertura')||now(),occurredAt:dateValue(input.occurredAt,'Data da ocorrência'),dueDate:dateValue(input.dueDate,'Prazo'),closedAt:dateValue(input.closedAt,'Data de encerramento'),estimatedExposure:exposure,currency:text(input.currency)||'BRL',customerPartyId:text(input.customerPartyId)||null,counterpartyPartyIds:arr(input.counterpartyPartyIds).map(String),contractId:text(input.contractId)||null,productId:text(input.productId)||null,serviceId:text(input.serviceId)||null,businessUnitId:text(input.businessUnitId)||null,notes:text(input.notes),isDemo:Boolean(input.isDemo),metadata:clone(input.metadata||{})});
      if(data.matters.some(x=>x.number===row.number))throw new Error('Número de Assunto Jurídico duplicado');data.matters.push(row);history('matter',row.id,'created',{number:row.number});return row;
    }
    function updateMatter(matterId,patch={}){const row=mustMatter(matterId);for(const [key,kind] of [['productId','product'],['serviceId','service'],['businessUnitId','business_unit']])if(Object.prototype.hasOwnProperty.call(patch,key)){const ref=text(patch[key]);validateBusiness(kind,ref);row[key]=ref||null;}if(Object.prototype.hasOwnProperty.call(patch,'contractId')){const ref=text(patch.contractId);validateContract(ref);row.contractId=ref||null;}for(const key of ['title','category','description','jurisdiction','authority','responsibleUserId','notes'])if(Object.prototype.hasOwnProperty.call(patch,key))row[key]=text(patch[key])||((key==='responsibleUserId')?null:'');if(Object.prototype.hasOwnProperty.call(patch,'type'))row.type=enumValue(patch.type,MATTER_TYPES,'Tipo');if(Object.prototype.hasOwnProperty.call(patch,'status'))row.status=enumValue(patch.status,MATTER_STATUSES,'Status');if(Object.prototype.hasOwnProperty.call(patch,'priority'))row.priority=enumValue(patch.priority,PRIORITIES,'Prioridade');if(Object.prototype.hasOwnProperty.call(patch,'riskLevel'))row.riskLevel=enumValue(patch.riskLevel,RISKS,'Risco');for(const key of ['openedAt','occurredAt','dueDate','closedAt'])if(Object.prototype.hasOwnProperty.call(patch,key))row[key]=dateValue(patch[key],key);if(Object.prototype.hasOwnProperty.call(patch,'estimatedExposure')){const v=num(patch.estimatedExposure);if(v!=null&&(!Number.isFinite(v)||v<0))throw new Error('Exposição estimada inválida');row.estimatedExposure=v;}if(Object.prototype.hasOwnProperty.call(patch,'currency'))row.currency=text(patch.currency)||'BRL';stamp(row,false);history('matter',row.id,'updated',{fields:Object.keys(patch)});return row;}
    function addParty(matterId,input={}){mustMatter(matterId);const partyType=required(input.partyType,'Tipo de parte'),partyId=required(input.partyId,'Parte');validateParty(partyType,partyId);const role=text(input.role)||'related';if(data.parties.some(x=>x.matterId===matterId&&x.partyType===partyType&&x.partyId===partyId&&x.role===role))throw new Error('Parte já vinculada');const row=stamp({id:id('matter_party'),matterId,partyType,partyId,role,notes:text(input.notes)},true);data.parties.push(row);history('matter',matterId,'party_added',{partyType,partyId,role});return row;}
    function addDeadline(matterId,input={}){mustMatter(matterId);const row=stamp({id:id('matter_deadline'),matterId,title:required(input.title,'Prazo'),dueAt:dateValue(required(input.dueAt,'Vencimento'),'Vencimento'),type:text(input.type)||'other',status:enumValue(input.status,DEADLINE_STATUSES,'Status do prazo','open'),responsibleUserId:text(input.responsibleUserId)||null,completedAt:dateValue(input.completedAt,'Conclusão'),notes:text(input.notes)},true);data.deadlines.push(row);history('matter',matterId,'deadline_added',{deadlineId:row.id});return row;}
    function completeDeadline(deadlineId){const row=data.deadlines.find(x=>x.id===deadlineId);if(!row)throw new Error('Prazo não encontrado');row.status='completed';row.completedAt=now();stamp(row,false);history('matter',row.matterId,'deadline_completed',{deadlineId});return row;}
    function addEvent(matterId,input={}){mustMatter(matterId);const row=stamp({id:id('matter_event'),matterId,type:enumValue(input.type,EVENT_TYPES,'Tipo de evento','other'),title:required(input.title,'Evento'),occurredAt:dateValue(input.occurredAt,'Data do evento')||now(),description:text(input.description),authority:text(input.authority),metadata:clone(input.metadata||{})},true);data.events.push(row);history('matter',matterId,'event_added',{eventId:row.id,type:row.type});return row;}
    function addAction(matterId,input={}){mustMatter(matterId);const row=stamp({id:id('matter_action'),matterId,title:required(input.title,'Ação'),status:text(input.status)||'open',responsibleUserId:text(input.responsibleUserId)||null,dueAt:dateValue(input.dueAt,'Prazo da ação'),completedAt:dateValue(input.completedAt,'Conclusão'),notes:text(input.notes)},true);data.actions.push(row);history('matter',matterId,'action_added',{actionId:row.id});return row;}
    function addAuthority(matterId,input={}){mustMatter(matterId);const row=stamp({id:id('matter_authority'),matterId,name:required(input.name,'Autoridade'),reference:text(input.reference),jurisdiction:text(input.jurisdiction),notes:text(input.notes)},true);data.authorities.push(row);history('matter',matterId,'authority_added',{authorityId:row.id});return row;}
    function addDocument(matterId,input={}){mustMatter(matterId);const row=stamp({id:id('matter_doc'),matterId,name:required(input.name,'Documento'),documentType:text(input.documentType)||'other',reference:text(input.reference)||null,url:text(input.url)||null,storage:'metadata-only',notes:text(input.notes)},true);data.documents.push(row);history('matter',matterId,'document_added',{documentId:row.id});return row;}
    function addSettlement(matterId,input={}){const matter=mustMatter(matterId),amount=num(input.amount);if(amount!=null&&(!Number.isFinite(amount)||amount<0))throw new Error('Valor do acordo inválido');const row=stamp({id:id('settlement'),matterId,title:required(input.title,'Acordo'),status:text(input.status)||'recorded',agreedAt:dateValue(input.agreedAt,'Data do acordo')||now(),amount,currency:text(input.currency)||matter.currency||'BRL',paymentReference:text(input.paymentReference)||null,notes:text(input.notes)},true);data.settlements.push(row);if(matter.status!=='closed'&&matter.status!=='archived')matter.status='settled';stamp(matter,false);history('matter',matterId,'settlement_recorded',{settlementId:row.id,amount});return row;}
    function closeMatter(matterId,input={}){const row=mustMatter(matterId);row.status='closed';row.closedAt=dateValue(input.closedAt,'Data de encerramento')||now();if(input.notes)row.notes=[row.notes,text(input.notes)].filter(Boolean).join('\n');stamp(row,false);history('matter',matterId,'closed',{closedAt:row.closedAt});return row;}
    function feed(filters={}){let rows=data.matters.filter(x=>filters.includeDemo?true:!x.isDemo);if(!filters.includeArchived)rows=rows.filter(x=>x.status!=='archived');for(const key of ['type','status','riskLevel','priority','responsibleUserId','productId','serviceId','businessUnitId','contractId'])if(filters[key])rows=rows.filter(x=>String(x[key]||'')===String(filters[key]));if(filters.search){const q=text(filters.search).toLowerCase();rows=rows.filter(x=>[x.number,x.title,x.category,x.description,x.authority].some(v=>text(v).toLowerCase().includes(q)));}return clone(rows);}
    function query(filters={}){const rows=feed(filters),limit=Math.min(50,Math.max(1,Number(filters.limit)||50)),page=Math.max(1,Number(filters.page)||1),pages=Math.max(1,Math.ceil(rows.length/limit));return {rows:rows.slice((page-1)*limit,page*limit),page,total:rows.length,pages,limit};}
    function deadlinesFeed(filters={}){return clone(data.deadlines.filter(d=>{const m=getMatter(d.matterId);if(!m||(!filters.includeDemo&&m.isDemo))return false;if(filters.status&&d.status!==filters.status)return false;if(filters.from&&String(d.dueAt)<String(filters.from))return false;if(filters.to&&String(d.dueAt)>String(filters.to))return false;return true;}));}
    function matterDetail(matterId){const matter=mustMatter(matterId);return clone({matter,parties:data.parties.filter(x=>x.matterId===matterId),deadlines:data.deadlines.filter(x=>x.matterId===matterId),events:data.events.filter(x=>x.matterId===matterId),actions:data.actions.filter(x=>x.matterId===matterId),authorities:data.authorities.filter(x=>x.matterId===matterId),documents:data.documents.filter(x=>x.matterId===matterId),settlements:data.settlements.filter(x=>x.matterId===matterId),history:data.history.filter(x=>x.entityType==='matter'&&x.entityId===matterId)});}
    function classifyLegacy(record={}){const explicit=['legal_matter','lawsuit','litigation_matter'].includes(text(record.domain||record.kind||record.entityType));return {status:explicit?'legacy_review_required':'legacy_incompatible',record:clone(record)};}
    return {data,nextNumber,createMatter,updateMatter,getMatter,addParty,addDeadline,completeDeadline,addEvent,addAction,addAuthority,addDocument,addSettlement,closeMatter,feed,query,deadlinesFeed,matterDetail,classifyLegacy,historyFor:(entityType,entityId)=>clone(data.history.filter(x=>x.entityType===entityType&&x.entityId===entityId))};
  }
  return {MATTER_TYPES,MATTER_STATUSES,PRIORITIES,RISKS,EVENT_TYPES,DEADLINE_STATUSES,createState,ensureState,createService};
});
