function crmMockModeActive(){const mock=new URLSearchParams(location.search).get('mock');if(mock==='1')return true;if(mock==='0')return false;return location.hostname===CRM_MOCK_DEFAULT_PREVIEW_HOST&&location.pathname.startsWith(CRM_MOCK_DEFAULT_PREVIEW_PATH);}
function crmMockSafeClone(value){return value==null?value:JSON.parse(JSON.stringify(value));}
function crmMockSafeObject(raw){try{const parsed=JSON.parse(raw);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:null;}catch(_){return null;}}
function crmMockResetServiceCaches(){for(const key of ['__crmCanonicalPartyService','__crmFullService','__crmFinanceService','__crmAccountingService','__crmFiscalService','__crmCostAllocationService','__crmLegalContractService','__crmParticipationService','__crmPayoutService','__crmBusinessService','__crmLegalMatterService','__crmComplianceService','__crmIPService','__crmCorporateService'])delete state[key];}
function crmMockInstallStorageNamespace(){if(!crmMockModeActive()||window.__crmMockStorageInstalled)return;window.__crmMockStorageInstalled=true;const rawGet=Storage.prototype.getItem,rawSet=Storage.prototype.setItem,rawRemove=Storage.prototype.removeItem;const operational=new Set(['valtren.crm.canonical-parties.v1','valtren.crm.domain.v1','valtren.crm.marketing.v1']);const scoped=(key)=>operational.has(String(key))?`${CRM_MOCK_PREFIX}${String(key)}`:String(key);Storage.prototype.getItem=function(key){return rawGet.call(this,scoped(key));};Storage.prototype.setItem=function(key,value){return rawSet.call(this,scoped(key),value);};Storage.prototype.removeItem=function(key){return rawRemove.call(this,scoped(key));};window.__crmMockRawStorage={get:rawGet,set:rawSet,remove:rawRemove};}
function crmMockReadRuntime(){if(!crmMockModeActive())return null;const raw=window.__crmMockRawStorage?.get.call(localStorage,CRM_MOCK_RUNTIME_KEY)??localStorage.getItem(CRM_MOCK_RUNTIME_KEY);return raw?crmMockSafeObject(raw):null;}
function crmMockPersistRuntime(){if(!crmMockModeActive())return;const snapshot={version:MOCK_DATA_VERSION,state:{}};for(const key of CRM_MOCK_STATE_KEYS)if(key in state)snapshot.state[key]=crmMockSafeClone(state[key]);const raw=JSON.stringify(snapshot);(window.__crmMockRawStorage?.set||Storage.prototype.setItem).call(localStorage,CRM_MOCK_RUNTIME_KEY,raw);}
function crmMockRestoreRuntime(snapshot){if(!snapshot||snapshot.version!==MOCK_DATA_VERSION||!snapshot.state||typeof snapshot.state!=='object'||Array.isArray(snapshot.state))return false;for(const key of CRM_MOCK_STATE_KEYS)if(key in snapshot.state)state[key]=crmMockSafeClone(snapshot.state[key]);crmMockResetServiceCaches();return true;}
function crmMockClearNamespace(){const remove=window.__crmMockRawStorage?.remove||Storage.prototype.removeItem,keys=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key&&key.startsWith(CRM_MOCK_PREFIX))keys.push(key);}keys.forEach(key=>remove.call(localStorage,key));}
function crmMockDiscardRuntime(){crmMockClearNamespace();for(const key of CRM_MOCK_STATE_KEYS)delete state[key];crmMockResetServiceCaches();}
