(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.ValtrenBusinessCore=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';

  const SCHEMA_VERSION=1;
  const PRODUCT_STATUSES=['draft','active','paused','retired','archived'];
  const SERVICE_STATUSES=['draft','active','paused','retired','archived'];
  const BUSINESS_UNIT_STATUSES=['draft','active','paused','retired','archived'];
  const REVENUE_MODELS=['subscription','one_time','license','usage','commission','revenue_share','free','custom'];
  const BILLING_MODELS=['monthly','quarterly','annual','one_time','usage_based','custom'];
  const PRICING_MODELS=['fixed','hourly','daily','project','retainer','usage','commission','free','custom'];
  const DIMENSION_TYPES=['corporate','product','service','business_unit'];
  const clone=(value)=>value==null?value:JSON.parse(JSON.stringify(value));
  const text=(value)=>String(value??'').trim().replace(/\s+/g,' ');
  const fold=(value)=>text(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const slugify=(value)=>fold(value).replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
  const safeUrl=(value)=>text(value);
  const currency=(value)=>text(value||'BRL').toUpperCase();
  function normalizePrice(value){if(value==null||value==='')return null;const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error('Preço de referência inválido');return Math.round((n+Number.EPSILON)*100)/100;}
  function defaultId(prefix){const token=(typeof crypto!=='undefined'&&crypto.randomUUID)?crypto.randomUUID():`${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}`;return `${prefix}_${token}`;}
  function createState(options={}){const now=options.now||(()=>new Date().toISOString());return {schemaVersion:SCHEMA_VERSION,products:[],services:[],businessUnits:[],relationships:[],history:[],legacyBindings:[],metadata:{createdAt:now(),legacyReviewed:false}};}
  function ensureState(input,options={}){const data=input&&typeof input==='object'?input:createState(options);for(const key of ['products','services','businessUnits','relationships','history','legacyBindings'])if(!Array.isArray(data[key]))data[key]=[];if(!data.metadata||typeof data.metadata!=='object')data.metadata={};data.schemaVersion=SCHEMA_VERSION;return data;}

  function createService(store,options={}){
    const data=ensureState(store,options);
    const now=options.now||(()=>new Date().toISOString());
    const actor=options.actorProvider||(()=>null);
    const idFactory=options.idFactory||defaultId;
    const referenceChecker=typeof options.referenceChecker==='function'?options.referenceChecker:(()=>[]);
    const history=(entityType,entityId,action,before,after,metadata={})=>{const event={id:idFactory('bushist'),entityType,entityId,action,at:now(),actorId:actor()||null,before:clone(before),after:clone(after),metadata:clone(metadata)};data.history.push(event);return event;};
    const byId=(rows,id)=>rows.find((row)=>row.id===String(id))||null;
    const getProduct=(id)=>byId(data.products,id);
    const getService=(id)=>byId(data.services,id);
    const getBusinessUnit=(id)=>byId(data.businessUnits,id);
    const entityRows=(kind)=>kind==='product'?data.products:kind==='service'?data.services:kind==='business_unit'?data.businessUnits:null;
    const entity=(kind,id)=>{const rows=entityRows(kind);return rows?byId(rows,id):null;};
    const statusList=(kind)=>kind==='product'?PRODUCT_STATUSES:kind==='service'?SERVICE_STATUSES:BUSINESS_UNIT_STATUSES;
    const prefix=(kind)=>kind==='product'?'PRD':kind==='service'?'SRV':'BU';

    function nextCode(kind){const p=prefix(kind),rows=entityRows(kind)||[],numbers=rows.map((row)=>{const m=String(row.code||'').match(new RegExp(`^${p}-(\\d+)$`,'i'));return m?Number(m[1]):0;}).filter(Number.isFinite);const next=(numbers.length?Math.max(...numbers):0)+1;return `${p}-${String(next).padStart(3,'0')}`;}
    function assertUniqueCode(kind,code,excludeId=''){if(!code)return;const normalized=fold(code);if((entityRows(kind)||[]).some((row)=>row.id!==excludeId&&fold(row.code)===normalized))throw new Error('Código já utilizado');}
    function assertUniqueProductIdentity(input,excludeId=''){
      assertUniqueCode('product',input.code,excludeId);
      const slug=fold(input.slug);if(slug&&data.products.some((row)=>row.id!==excludeId&&fold(row.slug)===slug))throw new Error('Slug de Produto já utilizado');
      const name=fold(input.name),category=fold(input.category);if(name&&category&&data.products.some((row)=>row.id!==excludeId&&fold(row.name)===name&&fold(row.category)===category))throw new Error('Produto duplicado para nome e categoria');
    }
    function assertUniqueServiceIdentity(input,excludeId=''){assertUniqueCode('service',input.code,excludeId);const name=fold(input.name);if(name&&data.services.some((row)=>row.id!==excludeId&&fold(row.name)===name))throw new Error('Serviço duplicado');}
    function assertUniqueUnitIdentity(input,excludeId=''){assertUniqueCode('business_unit',input.code,excludeId);const name=fold(input.name);if(name&&data.businessUnits.some((row)=>row.id!==excludeId&&fold(row.name)===name))throw new Error('Unidade de Negócio duplicada');}
    function assertUnit(id,{allowArchived=true}={}){if(!id)return null;const unit=getBusinessUnit(String(id));if(!unit)throw new Error('Unidade de Negócio não encontrada');if(!allowArchived&&['retired','archived'].includes(unit.status))throw new Error('Unidade de Negócio indisponível para novo vínculo');return unit;}
    function assertParent(id,currentId=''){if(!id)return null;const parent=assertUnit(id);if(currentId&&parent.id===currentId)throw new Error('Unidade não pode ser pai de si mesma');let cursor=parent,guard=new Set();while(cursor?.parentBusinessUnitId){if(guard.has(cursor.id))throw new Error('Ciclo hierárquico detectado');guard.add(cursor.id);if(cursor.parentBusinessUnitId===currentId)throw new Error('Hierarquia de Unidades criaria ciclo');cursor=getBusinessUnit(cursor.parentBusinessUnitId);}return parent;}
    function touch(row){row.updatedAt=now();row.updatedBy=actor()||null;return row;}
    function recordChanges(kind,row,before){if(before.status!==row.status)history(kind,row.id,'status_changed',{status:before.status},{status:row.status});if(before.businessUnitId!==row.businessUnitId)history(kind,row.id,'business_unit_changed',{businessUnitId:before.businessUnitId},{businessUnitId:row.businessUnitId});if(before.referencePrice!==row.referencePrice)history(kind,row.id,'reference_price_changed',{referencePrice:before.referencePrice},{referencePrice:row.referencePrice});history(kind,row.id,'edited',before,row);}

    function createProduct(input={}){
      const name=text(input.name);if(!name)throw new Error('Nome do Produto é obrigatório');
      const code=text(input.code||nextCode('product')),slug=text(input.slug||slugify(name));
      const status=PRODUCT_STATUSES.includes(input.status)?input.status:'draft';
      const businessUnitId=text(input.businessUnitId);if(businessUnitId)assertUnit(businessUnitId,{allowArchived:false});
      const revenueModel=text(input.revenueModel);if(revenueModel&&!REVENUE_MODELS.includes(revenueModel))throw new Error('Modelo de receita inválido');
      const billingModel=text(input.billingModel);if(billingModel&&!BILLING_MODELS.includes(billingModel))throw new Error('Modelo de cobrança inválido');
      const row={id:text(input.id||idFactory('prd')),code,name,slug,category:text(input.category),type:text(input.type),description:text(input.description),status,businessUnitId,ownerUserId:text(input.ownerUserId),revenueModel,billingModel,currency:currency(input.currency),referencePrice:normalizePrice(input.referencePrice),billingFrequency:text(input.billingFrequency||billingModel),launchDate:text(input.launchDate),retirementDate:text(input.retirementDate),websiteUrl:safeUrl(input.websiteUrl),internalReference:text(input.internalReference),metadata:clone(input.metadata||{}),isDemo:!!input.isDemo,createdAt:now(),createdBy:actor()||null,updatedAt:now(),updatedBy:actor()||null};
      if(!row.id)throw new Error('ID de Produto inválido');if(getProduct(row.id))throw new Error('ID de Produto já existe');assertUniqueProductIdentity(row);data.products.push(row);history('product',row.id,'created',null,row);return row;
    }
    function updateProduct(id,patch={}){const row=getProduct(id);if(!row)throw new Error('Produto não encontrado');const before=clone(row);const candidate={...row,...patch,id:row.id,code:text(patch.code??row.code),name:text(patch.name??row.name),slug:text(patch.slug??row.slug),category:text(patch.category??row.category),type:text(patch.type??row.type),description:text(patch.description??row.description),businessUnitId:text(patch.businessUnitId??row.businessUnitId),ownerUserId:text(patch.ownerUserId??row.ownerUserId),revenueModel:text(patch.revenueModel??row.revenueModel),billingModel:text(patch.billingModel??row.billingModel),currency:currency(patch.currency??row.currency),referencePrice:patch.referencePrice===undefined?row.referencePrice:normalizePrice(patch.referencePrice),billingFrequency:text(patch.billingFrequency??row.billingFrequency),launchDate:text(patch.launchDate??row.launchDate),retirementDate:text(patch.retirementDate??row.retirementDate),websiteUrl:safeUrl(patch.websiteUrl??row.websiteUrl),internalReference:text(patch.internalReference??row.internalReference),metadata:patch.metadata===undefined?row.metadata:clone(patch.metadata||{}),isDemo:patch.isDemo===undefined?row.isDemo:!!patch.isDemo};if(!candidate.name)throw new Error('Nome do Produto é obrigatório');if(patch.status!==undefined){if(!PRODUCT_STATUSES.includes(patch.status))throw new Error('Status de Produto inválido');candidate.status=patch.status;}if(candidate.businessUnitId)assertUnit(candidate.businessUnitId,{allowArchived:patch.businessUnitId===undefined});if(candidate.revenueModel&&!REVENUE_MODELS.includes(candidate.revenueModel))throw new Error('Modelo de receita inválido');if(candidate.billingModel&&!BILLING_MODELS.includes(candidate.billingModel))throw new Error('Modelo de cobrança inválido');assertUniqueProductIdentity(candidate,row.id);Object.assign(row,candidate);touch(row);recordChanges('product',row,before);return row;}

    function createServiceEntity(input={}){
      const name=text(input.name);if(!name)throw new Error('Nome do Serviço é obrigatório');const code=text(input.code||nextCode('service')),status=SERVICE_STATUSES.includes(input.status)?input.status:'draft',businessUnitId=text(input.businessUnitId);if(businessUnitId)assertUnit(businessUnitId,{allowArchived:false});const pricingModel=text(input.pricingModel);if(pricingModel&&!PRICING_MODELS.includes(pricingModel))throw new Error('Modelo de preço inválido');const billingFrequency=text(input.billingFrequency);if(billingFrequency&&!BILLING_MODELS.includes(billingFrequency))throw new Error('Frequência de cobrança inválida');const row={id:text(input.id||idFactory('srv')),code,name,category:text(input.category),description:text(input.description),status,businessUnitId,ownerUserId:text(input.ownerUserId),pricingModel,currency:currency(input.currency),referencePrice:normalizePrice(input.referencePrice),billingFrequency,defaultDuration:text(input.defaultDuration),metadata:clone(input.metadata||{}),isDemo:!!input.isDemo,createdAt:now(),createdBy:actor()||null,updatedAt:now(),updatedBy:actor()||null};if(getService(row.id))throw new Error('ID de Serviço já existe');assertUniqueServiceIdentity(row);data.services.push(row);history('service',row.id,'created',null,row);return row;
    }
    function updateService(id,patch={}){const row=getService(id);if(!row)throw new Error('Serviço não encontrado');const before=clone(row);const candidate={...row,...patch,id:row.id,code:text(patch.code??row.code),name:text(patch.name??row.name),category:text(patch.category??row.category),description:text(patch.description??row.description),businessUnitId:text(patch.businessUnitId??row.businessUnitId),ownerUserId:text(patch.ownerUserId??row.ownerUserId),pricingModel:text(patch.pricingModel??row.pricingModel),currency:currency(patch.currency??row.currency),referencePrice:patch.referencePrice===undefined?row.referencePrice:normalizePrice(patch.referencePrice),billingFrequency:text(patch.billingFrequency??row.billingFrequency),defaultDuration:text(patch.defaultDuration??row.defaultDuration),metadata:patch.metadata===undefined?row.metadata:clone(patch.metadata||{}),isDemo:patch.isDemo===undefined?row.isDemo:!!patch.isDemo};if(!candidate.name)throw new Error('Nome do Serviço é obrigatório');if(patch.status!==undefined){if(!SERVICE_STATUSES.includes(patch.status))throw new Error('Status de Serviço inválido');candidate.status=patch.status;}if(candidate.businessUnitId)assertUnit(candidate.businessUnitId,{allowArchived:patch.businessUnitId===undefined});if(candidate.pricingModel&&!PRICING_MODELS.includes(candidate.pricingModel))throw new Error('Modelo de preço inválido');if(candidate.billingFrequency&&!BILLING_MODELS.includes(candidate.billingFrequency))throw new Error('Frequência de cobrança inválida');assertUniqueServiceIdentity(candidate,row.id);Object.assign(row,candidate);touch(row);recordChanges('service',row,before);return row;}

    function createBusinessUnit(input={}){const name=text(input.name);if(!name)throw new Error('Nome da Unidade de Negócio é obrigatório');const code=text(input.code||nextCode('business_unit')),status=BUSINESS_UNIT_STATUSES.includes(input.status)?input.status:'active',parentBusinessUnitId=text(input.parentBusinessUnitId);if(parentBusinessUnitId)assertParent(parentBusinessUnitId);const row={id:text(input.id||idFactory('bu')),code,name,description:text(input.description),status,ownerUserId:text(input.ownerUserId),parentBusinessUnitId,metadata:clone(input.metadata||{}),isDemo:!!input.isDemo,createdAt:now(),createdBy:actor()||null,updatedAt:now(),updatedBy:actor()||null};if(getBusinessUnit(row.id))throw new Error('ID de Unidade já existe');assertUniqueUnitIdentity(row);data.businessUnits.push(row);history('business_unit',row.id,'created',null,row);return row;}
    function updateBusinessUnit(id,patch={}){const row=getBusinessUnit(id);if(!row)throw new Error('Unidade de Negócio não encontrada');const before=clone(row);const candidate={...row,...patch,id:row.id,code:text(patch.code??row.code),name:text(patch.name??row.name),description:text(patch.description??row.description),ownerUserId:text(patch.ownerUserId??row.ownerUserId),parentBusinessUnitId:text(patch.parentBusinessUnitId??row.parentBusinessUnitId),metadata:patch.metadata===undefined?row.metadata:clone(patch.metadata||{}),isDemo:patch.isDemo===undefined?row.isDemo:!!patch.isDemo};if(!candidate.name)throw new Error('Nome da Unidade de Negócio é obrigatório');if(patch.status!==undefined){if(!BUSINESS_UNIT_STATUSES.includes(patch.status))throw new Error('Status de Unidade inválido');candidate.status=patch.status;}if(candidate.parentBusinessUnitId)assertParent(candidate.parentBusinessUnitId,row.id);assertUniqueUnitIdentity(candidate,row.id);Object.assign(row,candidate);touch(row);history('business_unit',row.id,'edited',before,row);if(before.status!==row.status)history('business_unit',row.id,'status_changed',{status:before.status},{status:row.status});return row;}

    function archive(kind,id){const row=entity(kind,id);if(!row)throw new Error('Entidade de Negócios não encontrada');if(row.status==='archived')return row;const before=clone(row);row.status='archived';touch(row);history(kind,row.id,'archived',before,row);return row;}
    function restore(kind,id,status='active'){const row=entity(kind,id);if(!row)throw new Error('Entidade de Negócios não encontrada');if(!statusList(kind).includes(status)||status==='archived')throw new Error('Status de restauração inválido');const before=clone(row);row.status=status;touch(row);history(kind,row.id,'restored',before,row);return row;}
    function references(kind,id){const result=referenceChecker(kind,id);return Array.isArray(result)?clone(result):[];}
    function deleteDraft(kind,id){const rows=entityRows(kind),row=entity(kind,id);if(!rows||!row)throw new Error('Entidade de Negócios não encontrada');if(row.status!=='draft')throw new Error('Exclusão física permitida somente para rascunho');const refs=references(kind,id);if(refs.length)throw new Error('Entidade possui referências históricas');rows.splice(rows.indexOf(row),1);history(kind,id,'deleted_draft',row,null,{references:refs});return true;}

    function listRows(kind,filters={}){const rows=entityRows(kind)||[],includeDemo=!!filters.includeDemo,includeArchived=!!filters.includeArchived,includeRetired=filters.includeRetired!==false,search=fold(filters.search),status=text(filters.status),category=fold(filters.category),businessUnitId=text(filters.businessUnitId),ownerUserId=text(filters.ownerUserId);let out=rows.filter((row)=>(includeDemo||!row.isDemo)&&(includeArchived||row.status!=='archived')&&(includeRetired||row.status!=='retired'));if(status)out=out.filter((row)=>row.status===status);if(category)out=out.filter((row)=>fold(row.category)===category);if(businessUnitId)out=out.filter((row)=>row.businessUnitId===businessUnitId);if(ownerUserId)out=out.filter((row)=>row.ownerUserId===ownerUserId);if(search)out=out.filter((row)=>fold([row.name,row.code,row.category,getBusinessUnit(row.businessUnitId)?.name,row.ownerUserId].join(' ')).includes(search));return out.map(clone);}
    function listProducts(filters={}){return listRows('product',filters);}
    function listServices(filters={}){return listRows('service',filters);}
    function listBusinessUnits(filters={}){return listRows('business_unit',filters);}
    function paged(kind,filters={}){const limit=Math.max(1,Math.min(50,Number(filters.limit||50))),page=Math.max(1,Number(filters.page||1)),rows=listRows(kind,filters),total=rows.length,pages=Math.max(1,Math.ceil(total/limit)),offset=(page-1)*limit;return {rows:rows.slice(offset,offset+limit),total,page,pages,limit};}
    function countsForUnit(id){return {products:data.products.filter((row)=>row.businessUnitId===id&&!row.isDemo&&row.status!=='archived').length,services:data.services.filter((row)=>row.businessUnitId===id&&!row.isDemo&&row.status!=='archived').length};}
    function resolveDimension(kind,id){if(kind==='corporate')return {type:'corporate',id:'',name:'Corporativo',status:'active',resolved:true};if(!['product','service','business_unit'].includes(kind))return {type:kind,id:text(id),name:'Referência não resolvida',status:'unresolved',resolved:false};const row=entity(kind,id);if(!row)return {type:kind,id:text(id),name:'Referência não resolvida',status:'unresolved',resolved:false};return {type:kind,id:row.id,name:row.name,code:row.code,status:row.status,resolved:true,isDemo:!!row.isDemo,businessUnitId:row.businessUnitId||''};}
    function validateReference(kind,id,{allowHistorical=true}={}){if(kind==='corporate')return true;const resolved=resolveDimension(kind,id);if(!resolved.resolved)return false;if(!allowHistorical&&!['active','paused'].includes(resolved.status))return false;return true;}
    function registerPotentialReference(input={}){const sourceModule=text(input.sourceModule),sourceEntityId=text(input.sourceEntityId),field=text(input.field),kind=text(input.kind),legacyValue=text(input.legacyValue||input.value);if(!sourceModule||!field||!kind||!legacyValue)return null;const key=[sourceModule,sourceEntityId,field,kind,fold(legacyValue)].join('|'),existing=data.legacyBindings.find((x)=>x.key===key);if(existing)return existing;const row={id:idFactory('buslegacy'),key,sourceModule,sourceEntityId,field,kind,legacyValue,status:'potential_catalog_reference',createdAt:now(),createdBy:actor()||null,metadata:clone(input.metadata||{})};data.legacyBindings.push(row);history('legacy_reference',row.id,'registered',null,row);return row;}
    function historyFor(kind,id){return data.history.filter((event)=>event.entityType===kind&&event.entityId===id).map(clone);}

    return {data,createProduct,updateProduct,getProduct,listProducts,createService:createServiceEntity,updateService,getService,listServices,createBusinessUnit,updateBusinessUnit,getBusinessUnit,listBusinessUnits,paged,archive,restore,deleteDraft,references,countsForUnit,resolveDimension,validateReference,registerPotentialReference,historyFor,nextCode};
  }

  return {SCHEMA_VERSION,PRODUCT_STATUSES,SERVICE_STATUSES,BUSINESS_UNIT_STATUSES,REVENUE_MODELS,BILLING_MODELS,PRICING_MODELS,DIMENSION_TYPES,createState,ensureState,createService,fold,slugify};
});
