// VALTREN EXECUTIVE DASHBOARD BROWSER
function crmDashboardMoney(value,currency='BRL'){return value==null||value===''?'—':Number(value).toLocaleString('pt-BR',{style:'currency',currency:currency||'BRL'});}
function crmDashboardPercent(value,{points=false}={}){if(value==null||!Number.isFinite(Number(value)))return '—';return `${Number(value).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:2})}${points?' p.p.':'%'}`;}
function crmDashboardEsc(value){return typeof esc==='function'?esc(String(value??'')):String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));}
function crmDashboardDateInRange(value,from,to){const date=String(value||'').slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return !from&&!to;if(from&&date<from)return false;if(to&&date>to)return false;return true;}
function crmDashboardQueryFilters(query){const q=query instanceof URLSearchParams?query:new URLSearchParams(),valid=(value)=>/^\d{4}-\d{2}-\d{2}$/.test(value||'');return {basis:'accrual',from:valid(q.get('from'))?q.get('from'):'',to:valid(q.get('to'))?q.get('to'):'',sort:q.get('sort')||'valtrenResult'};}
function crmDashboardPreviousRange(accounting,filters){if(!filters.from||!filters.to||typeof accounting?.previousPeriod!=='function')return null;try{return accounting.previousPeriod(filters.from,filters.to);}catch(_error){return null;}}
function crmDashboardCollect(query){
  if(typeof ValtrenDashboardCore==='undefined')throw new Error('ValtrenDashboardCore indisponível');
  const filters=crmDashboardQueryFilters(query),errors=[],result={filters};
  let accounting=null,dre={summary:{},breakdown:{},rowCount:0},accountingRows=[],previousDre=null,previousAccountingRows=[],accountingPendingCount=0;
  try{
    if(typeof crmAccountingService!=='function')throw new Error('Financeiro → Contabilidade indisponível');
    accounting=crmAccountingService();dre=accounting.buildDre(filters);accountingRows=accounting.analyze(filters);accountingPendingCount=accounting.pendencies(filters).counts.total;
    const previousRange=crmDashboardPreviousRange(accounting,filters);if(previousRange){previousDre=accounting.buildDre({...filters,...previousRange});previousAccountingRows=accounting.analyze({...filters,...previousRange});result.previousRange=previousRange;}
  }catch(error){errors.push(`Contabilidade: ${error.message}`);}
  let catalog={products:[],services:[],businessUnits:[]};
  try{const business=crmBusinessService();catalog={products:business.data.products||[],services:business.data.services||[],businessUnits:business.data.businessUnits||[]};}catch(error){errors.push(`Negócios: ${error.message}`);}
  let participations=[],previousParticipations=[];
  try{
    const service=crmParticipationService(),eligible=(row)=>row&&!row.isDemo&&row.workflowStatus==='approved'&&row.consistencyStatus==='consistent';
    participations=(service.data.calculations||[]).filter(eligible).filter((row)=>(!filters.from||row.periodEnd>=filters.from)&&(!filters.to||row.periodStart<=filters.to));
    if(result.previousRange)previousParticipations=(service.data.calculations||[]).filter(eligible).filter((row)=>row.periodEnd>=result.previousRange.from&&row.periodStart<=result.previousRange.to);
  }catch(error){errors.push(`Participações: ${error.message}`);}
  let payoutObligations=[];
  try{const payouts=crmPayoutService();payoutObligations=payouts.refreshAll().filter((row)=>(!filters.from||row.periodEnd>=filters.from)&&(!filters.to||row.periodStart<=filters.to));}catch(error){errors.push(`Repasses: ${error.message}`);}
  let fiscalDocuments=[],settlementProvider=()=>null;
  try{
    const fiscal=crmFiscalService();fiscalDocuments=(fiscal.data.documents||[]).filter((doc)=>crmDashboardDateInRange(doc.competenceDate||doc.issueDate||doc.receivedAt,filters.from,filters.to));settlementProvider=(id)=>fiscal.settlement(id);
  }catch(error){errors.push(`Notas Fiscais: ${error.message}`);}
  const snapshot=ValtrenDashboardCore.buildDashboard({dre,previousDre,accountingRows,previousAccountingRows,participations,previousParticipations,payoutObligations,fiscalDocuments,settlementProvider,catalog,accountingPendingCount,today:new Date().toISOString().slice(0,10)});
  snapshot.errors=errors;snapshot.filters=filters;snapshot.status=errors.length?(snapshot.hasFinancialData?'partial':'error'):(snapshot.hasFinancialData?'ready':'empty');return snapshot;
}

function crmDashboardPanel(title,subtitle,body,actions=''){return `<section class="crm-dashboard-panel"><header><div><h3>${crmDashboardEsc(title)}</h3>${subtitle?`<p>${crmDashboardEsc(subtitle)}</p>`:''}</div>${actions?`<div class="crm-dashboard-panel-actions">${actions}</div>`:''}</header><div class="crm-dashboard-panel-body">${body}</div></section>`;}
function crmDashboardInlineEmpty(title,copy){return `<div class="crm-dashboard-inline-empty"><strong>${crmDashboardEsc(title)}</strong><span>${crmDashboardEsc(copy)}</span></div>`;}
function crmDashboardUnitHref(row){if(!row)return '#/crm/negocios';const q=encodeURIComponent(row.name||row.id||'');if(row.kind==='product')return `#/crm/negocios?q=${q}`;if(row.kind==='service')return `#/crm/negocios/servicos?q=${q}`;if(row.kind==='business_unit')return `#/crm/negocios/unidades?q=${q}`;if(row.kind==='corporate')return '#/crm/financeiro/accounting?dimension=corporate';return '#/crm/financeiro/accounting';}
function crmDashboardKpi({label,key,value,hasData,comparison,formula,href,emphasis=false}){const meta=comparison==null?'':`<small class="crm-dashboard-kpi-delta ${comparison>0?'up':comparison<0?'down':'flat'}">${comparison>0?'+':''}${crmDashboardPercent(comparison)}</small>`;return `<a class="crm-dashboard-kpi ${emphasis?'is-emphasis':''}" href="${href}" title="${crmDashboardEsc(formula)}"><span>${crmDashboardEsc(label)}</span><strong>${hasData?crmDashboardMoney(value):'—'}</strong>${meta}<small class="crm-dashboard-kpi-formula">${crmDashboardEsc(formula)}</small></a>`;}
function crmDashboardKpis(snapshot){const c=snapshot.consolidated,cmp=snapshot.comparison||{},has=snapshot.hasFinancialData,items=[
  ['Faturamento Bruto','grossRevenue',c.grossRevenue,'Soma do faturamento reconhecido no período.','#/crm/financeiro/accounting?section=gross_revenue',false],
  ['Deduções e Impostos','deductions',c.deductions,'Tributos, retenções, cancelamentos, estornos, descontos e demais deduções sobre receita.','#/crm/financeiro/accounting?section=deductions',false],
  ['Receita Líquida','netRevenue',c.netRevenue,'Faturamento Bruto − Deduções e Impostos.','#/crm/financeiro/accounting?section=net_revenue',false],
  ['Custos Diretos','directCosts',c.directCosts,'Custos diretamente relacionados à geração de receita.','#/crm/financeiro/accounting?section=costs',false],
  ['Despesas Operacionais','operatingExpenses',c.operatingExpenses,'Despesas necessárias para manter a operação da Valtren.','#/crm/financeiro/accounting?section=operating_expenses',false],
  ['Resultado Operacional','operatingResult',c.operatingResult,'Receita Líquida − Custos Diretos − Despesas Operacionais.','#/crm/financeiro/accounting?section=operating_result',true],
  ['Participações / Repasses','thirdPartyParticipation',c.thirdPartyParticipation,'Parcela aprovada do resultado econômico pertencente a terceiros; não é despesa operacional.','#/crm/financeiro/participacoes?status=approved',false],
  ['Resultado Valtren','valtrenResult',c.valtrenResult,'Resultado Operacional − Participações Econômicas de Terceiros.','#/crm/financeiro/accounting?view=valtren_result',true]
];return `<section class="crm-dashboard-kpi-grid">${items.map(([label,key,value,formula,href,emphasis])=>crmDashboardKpi({label,key,value,hasData:has,comparison:cmp[key],formula,href,emphasis})).join('')}</section>`;}

function crmDashboardBridge(snapshot){if(!snapshot.hasFinancialData)return crmDashboardInlineEmpty('Nenhum dado financeiro disponível','A formação do resultado aparecerá quando houver lançamentos contábeis reais.');const rows=snapshot.bridge,max=Math.max(1,...rows.map((row)=>Math.abs(Number(row.value)||0)));return `<div class="crm-dashboard-bridge">${rows.map((row)=>{const width=Math.max(2,Math.abs(Number(row.value)||0)/max*100),negative=Number(row.value)<0;return `<a href="${row.id==='thirdPartyParticipation'?'#/crm/financeiro/participacoes?status=approved':`#/crm/financeiro/accounting?section=${encodeURIComponent(row.id)}`}" class="crm-dashboard-bridge-row ${row.kind} ${negative?'negative':''}"><div><span>${row.kind==='subtract'?'− ':''}${crmDashboardEsc(row.label)}</span><strong>${crmDashboardMoney(row.value)}</strong></div><i style="--bridge-width:${width}%"></i></a>`;}).join('')}</div>`;}

function crmDashboardSortUnits(rows,sort){const copy=rows.slice(),selectors={grossRevenue:(x)=>x.grossRevenue,operatingResult:(x)=>x.operatingResult,operatingMargin:(x)=>x.operatingMargin==null?-Infinity:x.operatingMargin,thirdPartyParticipation:(x)=>x.thirdPartyParticipation,valtrenResult:(x)=>x.valtrenResult};const selector=selectors[sort]||selectors.valtrenResult;return copy.sort((a,b)=>selector(b)-selector(a)||a.name.localeCompare(b.name,'pt-BR'));}
function crmDashboardUnitTable(snapshot){const rows=crmDashboardSortUnits(snapshot.units,snapshot.filters.sort);if(!rows.length)return crmDashboardInlineEmpty('Nenhuma unidade com movimento','Classifique os lançamentos por Produto, Serviço, Unidade de Negócio ou Corporativo para formar a visão gerencial.');const options=[['grossRevenue','Maior faturamento'],['operatingResult','Maior resultado'],['operatingMargin','Maior margem'],['thirdPartyParticipation','Maior participação de terceiros'],['valtrenResult','Maior Resultado Valtren']];const select=`<select id="crm-dashboard-unit-sort" aria-label="Ordenar Performance por Unidade">${options.map(([id,label])=>`<option value="${id}" ${snapshot.filters.sort===id?'selected':''}>${label}</option>`).join('')}</select>`;const table=`<div class="crm-dashboard-table-wrap"><table class="crm-dashboard-unit-table"><thead><tr><th>Unidade</th><th>Tipo</th><th>Faturamento Bruto</th><th>Deduções e Impostos</th><th>Receita Líquida</th><th>Custos Diretos</th><th>Despesas Atribuídas</th><th>Resultado Operacional</th><th>Margem Operacional</th><th>Participação de Terceiros</th><th>Resultado Valtren</th></tr></thead><tbody>${rows.map((row)=>`<tr class="${row.kind==='unassigned'?'is-unassigned':''}"><td><a href="${crmDashboardUnitHref(row)}"><strong>${crmDashboardEsc(row.name)}</strong>${row.issues.length?`<small>${row.issues.length} pendência(s) de classificação</small>`:''}</a></td><td><span class="crm-dashboard-type">${crmDashboardEsc(row.type)}</span></td><td>${crmDashboardMoney(row.grossRevenue)}</td><td>${crmDashboardMoney(row.deductions)}</td><td>${crmDashboardMoney(row.netRevenue)}</td><td>${crmDashboardMoney(row.directCosts)}</td><td>${crmDashboardMoney(row.operatingExpenses)}</td><td>${crmDashboardMoney(row.operatingResult)}</td><td>${crmDashboardPercent(row.operatingMargin)}</td><td>${crmDashboardMoney(row.thirdPartyParticipation)}</td><td><strong>${crmDashboardMoney(row.valtrenResult)}</strong></td></tr>`).join('')}</tbody></table></div>`;return {body:table,actions:select};}

function crmDashboardGroupCard(group){return `<article class="crm-dashboard-group-card"><header><div><span>${crmDashboardEsc(group.label)}</span><strong>${crmDashboardPercent(group.revenueShare)} do faturamento</strong></div><small>${crmDashboardPercent(group.valtrenResultShare)} do Resultado Valtren</small></header><dl><div><dt>Faturamento</dt><dd>${crmDashboardMoney(group.grossRevenue)}</dd></div><div><dt>Receita Líquida</dt><dd>${crmDashboardMoney(group.netRevenue)}</dd></div><div><dt>Custos</dt><dd>${crmDashboardMoney(group.directCosts)}</dd></div><div><dt>Resultado Operacional</dt><dd>${crmDashboardMoney(group.operatingResult)}</dd></div><div><dt>Participações</dt><dd>${crmDashboardMoney(group.thirdPartyParticipation)}</dd></div><div><dt>Resultado Valtren</dt><dd>${crmDashboardMoney(group.valtrenResult)}</dd></div></dl></article>`;}
function crmDashboardProductsVsServices(snapshot){const p=snapshot.productsVsServices;if(!snapshot.units.some((row)=>['product','service'].includes(row.kind)))return crmDashboardInlineEmpty('Sem classificação Produto x Serviço','Cadastre e classifique movimentações reais por Produto ou Serviço para gerar a comparação.');return `<div class="crm-dashboard-groups">${crmDashboardGroupCard(p.products)}${crmDashboardGroupCard(p.services)}</div>${Math.abs(p.unattributedRevenue)>0.005?`<p class="crm-dashboard-footnote">${crmDashboardMoney(p.unattributedRevenue)} do faturamento consolidado está em Corporativo, Unidade de Negócio direta ou ainda não classificado; esse valor não é forçado dentro de Produtos/Serviços.</p>`:''}`;}

function crmDashboardBarList(rows,valueKey,{percentValue=false,limit=8}={}){const data=rows.filter((row)=>Number.isFinite(Number(row[valueKey]))&&row.kind!=='unassigned').slice(0).sort((a,b)=>Number(b[valueKey])-Number(a[valueKey])).slice(0,limit);if(!data.length)return crmDashboardInlineEmpty('Sem dados suficientes','O gráfico será exibido quando existirem valores reais atribuídos às unidades.');const max=Math.max(1,...data.map((row)=>Math.abs(Number(row[valueKey])||0)));return `<div class="crm-dashboard-bars">${data.map((row)=>{const value=Number(row[valueKey])||0,width=Math.max(2,Math.abs(value)/max*100);return `<a href="${crmDashboardUnitHref(row)}"><div><span>${crmDashboardEsc(row.name)}</span><strong>${percentValue?crmDashboardPercent(value):crmDashboardMoney(value)}</strong></div><i style="--bar-width:${width}%" class="${value<0?'negative':''}"></i></a>`;}).join('')}</div>`;}

function crmDashboardTrendSvg(rows){if(!rows.length)return crmDashboardInlineEmpty('Sem série temporal','São necessários lançamentos contábeis datados para formar a evolução financeira.');const keys=[['grossRevenue','Faturamento Bruto'],['netRevenue','Receita Líquida'],['operatingResult','Resultado Operacional'],['valtrenResult','Resultado Valtren']],width=760,height=260,pad=34,values=rows.flatMap((row)=>keys.map(([key])=>Number(row[key])||0)),min=Math.min(0,...values),max=Math.max(1,...values),span=Math.max(1,max-min),x=(index)=>pad+(rows.length===1?0:(index/(rows.length-1))*(width-pad*2)),y=(value)=>height-pad-((value-min)/span)*(height-pad*2),poly=(key)=>rows.map((row,index)=>`${x(index)},${y(Number(row[key])||0)}`).join(' ');return `<div class="crm-dashboard-trend"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Evolução Financeira"><line x1="${pad}" y1="${y(0)}" x2="${width-pad}" y2="${y(0)}" class="axis"></line>${keys.map(([key])=>`<polyline class="series ${key}" points="${poly(key)}"></polyline>`).join('')}${rows.map((row,index)=>`<text x="${x(index)}" y="${height-8}" text-anchor="middle">${crmDashboardEsc(row.month.split('-').reverse().join('/'))}</text>`).join('')}</svg><div class="crm-dashboard-legend">${keys.map(([key,label])=>`<span class="${key}"><i></i>${label}</span>`).join('')}</div></div>`;}

function crmDashboardParticipationSummary(snapshot){const p=snapshot.participations,has=snapshot.participationTable.length||snapshot.participations.pending||snapshot.participations.repassed;if(!has)return crmDashboardInlineEmpty('Nenhuma participação econômica aprovada','Participações contratuais aprovadas aparecerão aqui sem confundir sócios de produtos com sócios da Valtren Solutions.');const cards=[['Resultado das unidades com participação',p.totalResult],['Parcela Valtren',p.valtren],['Parcela de terceiros',p.thirdParty],['Já repassado',p.repassed],['Pendente de repasse',p.pending],['Programado',p.scheduled],['Vencido',p.overdue]];const table=snapshot.participationTable.length?`<div class="crm-dashboard-table-wrap"><table><thead><tr><th>Produto / Serviço / Unidade</th><th>Resultado</th><th>% Valtren</th><th>Valor Valtren</th><th>% Terceiros</th><th>Valor Terceiros</th><th>Repassado</th><th>Pendente</th></tr></thead><tbody>${snapshot.participationTable.map((row)=>`<tr><td><a href="${crmDashboardUnitHref(row.descriptor)}">${crmDashboardEsc(row.descriptor.name)}</a></td><td>${crmDashboardMoney(row.result)}</td><td>${crmDashboardPercent(row.valtrenPercent)}</td><td>${crmDashboardMoney(row.valtrenValue)}</td><td>${crmDashboardPercent(row.thirdPartyPercent)}</td><td>${crmDashboardMoney(row.thirdPartyValue)}</td><td>${crmDashboardMoney(row.repassed)}</td><td><a href="#/crm/financeiro/repasses">${crmDashboardMoney(row.pending)}</a></td></tr>`).join('')}</tbody></table></div>`:'';return `<div class="crm-dashboard-mini-kpis">${cards.map(([label,value])=>`<article><span>${label}</span><strong>${crmDashboardMoney(value)}</strong></article>`).join('')}</div><p class="crm-dashboard-legal-note">Participação econômica em um produto, serviço ou unidade não representa participação societária na Valtren Solutions.</p>${table}`;}

function crmDashboardBilledVsReceived(snapshot){const f=snapshot.fiscal,has=f.outgoingCount>0;if(!has)return crmDashboardInlineEmpty('Nenhum faturamento fiscal disponível','Notas Fiscais de saída reais e seus vínculos financeiros alimentarão Faturado x Recebido.');const rows=[['Faturado',f.billed],['Recebido',f.received],['Em aberto',f.open],['Percentual recebido',f.receivedPercent,'percent'],['Vencido',f.overdue]];return `<div class="crm-dashboard-financial-summary">${rows.map(([label,value,type])=>`<a href="#/crm/financeiro/notas-fiscais?direction=outgoing"><span>${label}</span><strong>${type==='percent'?crmDashboardPercent(value):crmDashboardMoney(value)}</strong></a>`).join('')}</div>`;}
function crmDashboardReceivablesPayables(snapshot){const f=snapshot.fiscal,has=f.outgoingCount||f.incomingCount;if(!has)return crmDashboardInlineEmpty('Sem contas fiscais em aberto','Documentos fiscais vinculados ao Financeiro formarão este resumo sem substituir o detalhamento financeiro.');const rows=[['Total a Receber',f.totalReceivable,'#/crm/financeiro/notas-fiscais?direction=outgoing'],['Vencido a Receber',f.overdueReceivable,'#/crm/financeiro/notas-fiscais?direction=outgoing&financial=pending'],['Total a Pagar',f.totalPayable,'#/crm/financeiro/notas-fiscais?direction=incoming'],['Vencido a Pagar',f.overduePayable,'#/crm/financeiro/notas-fiscais?direction=incoming&financial=pending']];return `<div class="crm-dashboard-arap">${rows.map(([label,value,href])=>`<a href="${href}"><span>${label}</span><strong>${crmDashboardMoney(value)}</strong></a>`).join('')}</div>`;}

function crmDashboardDeductions(snapshot){if(!snapshot.deductions.length)return crmDashboardInlineEmpty('Sem deduções classificadas','Tributos, retenções, estornos, cancelamentos e descontos aparecerão conforme a classificação contábil real.');return `<div class="crm-dashboard-breakdown">${snapshot.deductions.map((row)=>`<a href="#/crm/financeiro/accounting?classification=${encodeURIComponent(row.id)}"><div><strong>${crmDashboardEsc(row.name)}</strong><span>${row.count} lançamento${row.count===1?'':'s'}</span></div><div><strong>${crmDashboardMoney(row.value)}</strong><span>${crmDashboardPercent(row.shareOfGross)} do faturamento</span></div></a>`).join('')}</div>`;}
function crmDashboardCostBucket(title,bucket){return `<article><header><span>${crmDashboardEsc(title)}</span><strong>${crmDashboardMoney(bucket.total)}</strong></header><div><span>Custos diretos</span><b>${crmDashboardMoney(bucket.costs)}</b></div><div><span>Despesas operacionais</span><b>${crmDashboardMoney(bucket.operatingExpenses)}</b></div></article>`;}
function crmDashboardCostStructure(snapshot){const c=snapshot.costStructure,has=c.attributed.total||c.corporate.total||c.unassigned.total;if(!has)return crmDashboardInlineEmpty('Sem custos ou despesas classificadas','A estrutura aparecerá quando houver movimentações contábeis reais em Custos ou Despesas Operacionais.');return `<div class="crm-dashboard-cost-grid">${crmDashboardCostBucket('Atribuídos às unidades',c.attributed)}${crmDashboardCostBucket('Corporativos',c.corporate)}${c.unassigned.total?crmDashboardCostBucket('Não classificados',c.unassigned):''}</div><div class="crm-dashboard-allocation-ready"><strong>Rateio corporativo preparado para regras reais</strong><span>Não rateado · Igualitário · Por faturamento · Percentual manual · Regra futura</span><small>Nenhum rateio é calculado automaticamente sem regra configurada.</small></div>`;}

function crmDashboardRankings(snapshot){if(!snapshot.rankings.length)return crmDashboardInlineEmpty('Sem base suficiente para ranking','Os destaques aparecem somente quando existem unidades com dados financeiros reais.');return `<div class="crm-dashboard-ranking">${snapshot.rankings.map((item)=>{const row=snapshot.units.find((unit)=>unit.key===item.unitKey),formatted=item.format==='percent'?crmDashboardPercent(item.value):item.format==='percentage_points'?crmDashboardPercent(item.value,{points:true}):crmDashboardMoney(item.value);return `<a href="${crmDashboardUnitHref(row)}"><span>${crmDashboardEsc(item.label)}</span><strong>${crmDashboardEsc(item.unitName)}</strong><b>${formatted}</b></a>`;}).join('')}</div>`;}

function crmDashboardWarnings(snapshot){const items=[...(snapshot.warnings||[]),...(snapshot.errors||[]).map((message)=>({code:'source_error',message}))];if(!items.length)return '';return `<aside class="crm-dashboard-quality" role="status"><strong>${snapshot.status==='error'?'Dados indisponíveis':'Qualidade dos dados'}</strong>${items.map((item)=>`<p>${crmDashboardEsc(item.message)}</p>`).join('')}</aside>`;}
function crmDashboardEmptyState(snapshot){if(snapshot.status!=='empty'&&snapshot.status!=='error')return '';return `<section class="crm-dashboard-empty-state"><strong>${snapshot.status==='error'?'Não foi possível consolidar o Dashboard':'Nenhum dado financeiro disponível'}</strong><p>${snapshot.status==='error'?'As fontes canônicas necessárias estão indisponíveis. Nenhum número foi inventado.':'Cadastre e classifique transações, notas fiscais, produtos/serviços e participações reais para alimentar esta visão executiva.'}</p><div><a href="#/crm/financeiro">Ir para Financeiro</a><a href="#/crm/negocios">Ir para Negócios</a></div></section>`;}
function crmDashboardLoadingState(){return `<section class="crm-dashboard-empty-state is-loading" aria-live="polite"><strong>Consolidando Dashboard</strong><p>Preparando as fontes financeiras e gerenciais da Valtren Solutions.</p></section>`;}

function crmDashboardPage(query){
  let snapshot;try{snapshot=crmDashboardCollect(query);}catch(error){snapshot={status:'error',hasFinancialData:false,errors:[error.message],warnings:[],consolidated:{},comparison:{},bridge:[],units:[],filters:{sort:'valtrenResult'},productsVsServices:{products:{},services:{}},trend:[],participations:{},participationTable:[],fiscal:{},deductions:[],costStructure:{attributed:{total:0},corporate:{total:0},unassigned:{total:0}},rankings:[]};}
  const unitTable=crmDashboardUnitTable(snapshot),unitBody=typeof unitTable==='string'?unitTable:unitTable.body,unitActions=typeof unitTable==='string'?'':unitTable.actions;
  const body=`${crmDashboardWarnings(snapshot)}${crmDashboardKpis(snapshot)}${crmDashboardEmptyState(snapshot)}${crmDashboardPanel('Formação do Resultado','Como o faturamento da Valtren se transforma no resultado econômico final.',crmDashboardBridge(snapshot))}${crmDashboardPanel('Performance por Unidade de Negócio','Produtos, SaaS, Serviços, Unidades e Corporativo sem tratar nenhuma unidade como empresa independente.',unitBody,unitActions)}<div class="crm-dashboard-two-col">${crmDashboardPanel('Produtos x Serviços','Participação no faturamento consolidado e no Resultado Valtren.',crmDashboardProductsVsServices(snapshot))}${crmDashboardPanel('Destaques das Unidades','Rankings exibidos apenas quando existe base financeira real.',crmDashboardRankings(snapshot))}</div><div class="crm-dashboard-two-col">${crmDashboardPanel('Faturamento por Unidade','Concentração de receita por dimensão gerencial.',crmDashboardBarList(snapshot.units,'grossRevenue'))}${crmDashboardPanel('Resultado por Unidade','Resultado Valtren por produto, serviço ou unidade.',crmDashboardBarList(snapshot.units,'valtrenResult'))}</div><div class="crm-dashboard-two-col">${crmDashboardPanel('Margem Operacional por Unidade','Resultado Operacional ÷ Receita Líquida.',crmDashboardBarList(snapshot.units,'operatingMargin',{percentValue:true}))}${crmDashboardPanel('Evolução Financeira','Faturamento Bruto, Receita Líquida, Resultado Operacional e Resultado Valtren.',crmDashboardTrendSvg(snapshot.trend))}</div>${crmDashboardPanel('Participações e Repasses','Distribuição econômica de resultados de produtos/unidades para participantes terceiros.',crmDashboardParticipationSummary(snapshot))}<div class="crm-dashboard-two-col">${crmDashboardPanel('Faturado x Recebido','Faturamento fiscal não é tratado como sinônimo de caixa.',crmDashboardBilledVsReceived(snapshot))}${crmDashboardPanel('Contas a Receber e a Pagar','Resumo financeiro; o detalhamento continua nos módulos específicos.',crmDashboardReceivablesPayables(snapshot))}</div><div class="crm-dashboard-two-col">${crmDashboardPanel('Tributos e Deduções','Composição das reduções do faturamento bruto.',crmDashboardDeductions(snapshot))}${crmDashboardPanel('Estrutura de Custos e Despesas','Separação entre valores atribuídos às unidades e estrutura corporativa.',crmDashboardCostStructure(snapshot))}</div>`;
  return `<div class="crm-app-shell">${crmRelSidebar('dashboard','dashboard')}<main class="crm-main"><header class="crm-topbar"><div><span>Sistema Interno</span><h1>Dashboard</h1><p>Visão financeira-gerencial consolidada da Valtren Solutions e performance das suas unidades econômicas internas.</p></div>${crmHeaderActions('dashboard')}</header><section class="crm-workspace crm-dashboard-workspace" aria-label="Dashboard Executivo"><div class="crm-page-header"><div><h2>Visão Econômica Consolidada</h2><p>Empresa: Valtren Solutions · Produtos, SaaS, Serviços e Unidades de Negócio são dimensões gerenciais internas.</p></div></div>${body}</section></main></div>`;
}

if(!window.__valtrenExecutiveDashboardBound){window.__valtrenExecutiveDashboardBound=true;document.addEventListener('change',(event)=>{if(event.target?.id!=='crm-dashboard-unit-sort')return;const q=new URLSearchParams(routeInfo().query||new URLSearchParams());q.set('sort',event.target.value||'valtrenResult');location.hash=`#/crm/dashboard?${q.toString()}`;});}
