// VALTREN CRM COMPLETE BROWSER
const CRM_FULL_TABS=[['contacts','Contatos'],['companies','Empresas'],['customers','Clientes'],['leads','Leads'],['interactions','Interações']];
const CRM_FULL_ROLE_OPTIONS=[['customer','Cliente'],['prospect','Prospect'],['partner','Parceiro'],['supplier','Fornecedor'],['service_provider','Prestador']];
const CRM_FULL_STORAGE_PARTIES='valtren.crm.canonical-parties.v1';
const CRM_FULL_STORAGE_DOMAIN='valtren.crm.domain.v1';

function crmFullStoredObject(key,label){
  const saved=localStorage.getItem(key);if(!saved)return null;
  try{const parsed=JSON.parse(saved);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new TypeError(`${label} deve possuir raiz Object`);return parsed;}
  catch(error){console.warn(`CRM: ${label} local não pôde ser restaurado.`,error);return null;}
}
function crmFullStoredObject(key,label){
  const saved=localStorage.getItem(key);if(!saved)return null;
  try{const parsed=JSON.parse(saved);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new TypeError(`${label} deve possuir raiz Object`);return parsed;}
  catch(error){console.warn(`CRM: ${label} local não pôde ser restaurado.`,error);return null;}
}
function crmFullRestorePersistence(){
  if(state.__crmFullPersistenceRestored)return;
  state.__crmFullPersistenceRestored=true;
  if(!state.__crmCanonicalPartyService){
    const parties=crmFullStoredObject(CRM_FULL_STORAGE_PARTIES,'Pessoas/Organizações');
    if(parties){try{state.crmCanonicalParties=ValtrenPartyCore.ensureState(parties);}catch(error){console.warn('CRM: Pessoas/Organizações locais são inválidas.',error);}}
  }
  const domain=crmFullStoredObject(CRM_FULL_STORAGE_DOMAIN,'Domínio CRM');
  if(domain){try{state.crmDomain=ValtrenCrmCore.ensureState(domain);}catch(error){console.warn('CRM: domínio CRM local é inválido.',error);}}
}
function crmFullPersist(){
  try{localStorage.setItem(CRM_FULL_STORAGE_PARTIES,JSON.stringify(state.crmCanonicalParties||{}));localStorage.setItem(CRM_FULL_STORAGE_DOMAIN,JSON.stringify(state.crmDomain||{}));}catch(error){console.warn('CRM: persistência local indisponível.',error);}
}
function crmFullIsLegacyDemo(item){
  const mail=String(item?.email||'').toLowerCase(),id=String(item?.id||'');
  return ['c1','c2','c3','c4','l1','l2','l3'].includes(id)||mail.includes('@exemplo.com')||mail.endsWith('.exemplo');
}
function crmFullService(){
  crmFullRestorePersistence();
  crmRelEnsureState();
  state.crmDomain=ValtrenCrmCore.ensureState(state.crmDomain);
  if(!state.__crmFullService||state.__crmFullService.data!==state.crmDomain){state.__crmFullService=ValtrenCrmCore.createService(crmCanonicalPartyService(),state.crmDomain,{actorProvider:()=>state.crmUserId||state.crmUserName||null});}
  const service=state.__crmFullService;
  if(!service.data.metadata.legacyMigrated){const legacy=crmCanonicalSyncLegacyViews();service.migrateLegacy({...legacy,isDemo:crmFullIsLegacyDemo});crmFullPersist();}
  state.crmFullUi=state.crmFullUi||{includeDemo:false};
  return service;
}
function crmFullUsers(){
  const rows=[],seen=new Set();
  const add=(id,name)=>{id=String(id||'').trim();name=String(name||id||'').trim();if(!id||seen.has(id))return;seen.add(id);rows.push({id,name});};
  const currentId=String(state.crmUserId||'').trim(),currentName=String(state.crmUserName||'').trim();
  if(currentId||currentName)add(currentId||currentName,currentName||currentId);
  (state.crmRefUsers||[]).forEach((u)=>add(u.id||u.email,u.name||u.email));
  return rows;
}
function crmFullResponsibleName(id){return crmFullUsers().find((x)=>x.id===id)?.name||id||'-';}
function crmFullRoleLabel(role){return ValtrenCrmCore.ROLE_LABELS[role]||role||'-';}
function crmFullStageLabel(stage){return ValtrenCrmCore.STAGE_LABELS[stage]||stage||'-';}
function crmFullInteractionLabel(type){return ValtrenCrmCore.INTERACTION_LABELS[type]||type||'-';}
function crmFullDate(value,withTime=true){
  if(!value)return '-';const date=new Date(value);if(Number.isNaN(date.getTime()))return String(value);
  return new Intl.DateTimeFormat('pt-BR',withTime?{dateStyle:'short',timeStyle:'short'}:{dateStyle:'short'}).format(date);
}
function crmFullNowLocal(){const d=new Date(),pad=(n)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function crmFullSplitTags(value){return String(value||'').split(',').map((x)=>x.trim()).filter(Boolean);}
function crmFullAddressFromData(data){return {line1:String(data.get('addressLine1')||''),number:String(data.get('addressNumber')||''),complement:String(data.get('addressComplement')||''),district:String(data.get('district')||''),city:String(data.get('city')||''),region:String(data.get('region')||''),postalCode:String(data.get('postalCode')||''),country:String(data.get('country')||'BR')};}
function crmFullPartyView(entityType,entityId){
  const service=crmFullService(),party=service.party,entity=party.getEntity(entityType,entityId);if(!entity)return null;
  return {entityType,entity,name:entityType==='person'?entity.fullName:(entity.tradeName||entity.legalName),legalName:entityType==='organization'?entity.legalName:'',email:service.primary(entityType,entityId,'email'),phone:service.primary(entityType,entityId,'phone'),whatsapp:service.primary(entityType,entityId,'whatsapp'),site:service.primary(entityType,entityId,'site'),document:service.document(entityType,entityId,entityType==='person'?'cpf':'cnpj'),address:service.address(entityType,entityId),roles:service.roles(entityType,entityId),context:service.getContext(entityType,entityId,false)};
}
function crmFullLastInteraction(query){return crmFullService().interactionsFor(query)[0]||null;}
function crmFullSearchBlob(parts){return ValtrenCrmCore.fold((parts||[]).filter(Boolean).join(' '));}
function crmFullDemoBadge(isDemo){return isDemo?'<span class="crm-full-demo-badge">Demonstração</span>':'';}
function crmFullRoleBadges(roles){const list=(roles||[]).filter((r)=>ValtrenCrmCore.CRM_ROLE_SET.has(r));return list.length?`<div class="crm-full-badges">${list.map((r)=>`<span>${esc(crmFullRoleLabel(r))}</span>`).join('')}</div>`:'<span class="crm-full-muted">Sem papel adicional</span>';}
function crmFullEmpty(title,description,action=''){return `<div class="crm-full-empty">${icon('users',28)}<h3>${esc(title)}</h3><p>${esc(description)}</p>${action}</div>`;}
function crmFullToast(message,type='success'){
  document.querySelector('.crm-full-toast')?.remove();const el=document.createElement('div');el.className=`crm-full-toast ${type}`;el.setAttribute('role','status');el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),3200);
}
function crmFullError(message){crmFullToast(message,'error');}
function crmFullFormError(form,message){let box=form.querySelector('.crm-full-form-error');if(!box){box=document.createElement('div');box.className='crm-full-form-error';box.setAttribute('role','alert');form.querySelector('.crm-full-modal-body')?.prepend(box);}box.textContent=message;}
function crmFullLegacyId(prefix,existing=''){return existing||`${prefix}${Date.now()}${Math.floor(Math.random()*1000)}`;}
function crmFullPrimaryRole(roles){return (roles||[]).find((r)=>['customer','prospect','partner','supplier','service_provider'].includes(r))||'crm_contact';}
function crmFullRoleToLegacy(role){return {customer:'Cliente',prospect:'Prospect',partner:'Parceiro',supplier:'Fornecedor',service_provider:'Prestador de Serviços',crm_contact:'Contato'}[role]||crmFullRoleLabel(role);}
function crmFullSyncLegacyContact(entityType,entityId,legacyId=''){
  const service=crmFullService(),view=crmFullPartyView(entityType,entityId);if(!view)return '';
  const ctx=service.getContext(entityType,entityId,true),id=crmFullLegacyId('c',legacyId||ctx.legacyId),roles=service.roles(entityType,entityId),rel=entityType==='person'?service.party.data.personOrganizationRelationships.find((x)=>x.personId===entityId&&x.status!=='inactive'):null,org=rel?service.party.getEntity('organization',rel.organizationId):null;
  const item={id,tipo_pessoa:entityType==='organization'?'pessoa_juridica':'pessoa_fisica',name:entityType==='organization'?view.entity.legalName:view.entity.fullName,company:entityType==='organization'?(view.entity.tradeName||''):(org?.tradeName||org?.legalName||''),segment:crmFullRoleToLegacy(crmFullPrimaryRole(roles)),profile:'',phone:view.phone,email:view.email,city:[view.address?.city,view.address?.region].filter(Boolean).join(' / '),responsible:crmFullResponsibleName(ctx.responsibleId),status:ctx.status||'Ativo',priority:ctx.priority||'Média',cpf:entityType==='person'?view.document:'',cnpj:entityType==='organization'?view.document:'',function:rel?.positionTitle||'',address:view.address?.line1||'',notes:ctx.notes||'',interactions:[]};
  if(!crmCanonicalUpsertLegacyRecord('contacts',item,crmCanonicalBinding('crm.contacts',id)?'edit':'create'))throw new Error('Não foi possível atualizar a projeção de compatibilidade do contato.');
  service.patchContext(entityType,entityId,{legacyId:id});return id;
}
function crmFullSyncLegacyLead(lead){
  const service=crmFullService(),person=lead.personId?crmFullPartyView('person',lead.personId):null,org=lead.organizationId?crmFullPartyView('organization',lead.organizationId):null,id=crmFullLegacyId('l',lead.legacyId),entityType=person?'person':'organization';
  const item={id,tipo_pessoa:entityType==='organization'?'pessoa_juridica':'pessoa_fisica',name:person?.name||org?.legalName||org?.name||'',company:org?.name||'',email:person?.email||org?.email||'',phone:person?.phone||org?.phone||'',source:lead.origin||'',stage:crmFullStageLabel(lead.stage),responsible:crmFullResponsibleName(lead.responsibleId),status:lead.status||'Aberto',priority:lead.priority||'Média',notes:lead.notes||''};
  if(!crmCanonicalUpsertLegacyRecord('leads',item,crmCanonicalBinding('crm.leads',id)?'edit':'create'))throw new Error('Não foi possível atualizar a projeção de compatibilidade do lead.');lead.legacyId=id;return id;
}
function crmFullSetManagedRoles(entityType,entityId,selected){
  const service=crmFullService(),managed=['customer','prospect','partner','supplier','service_provider'];selected=new Set(selected||[]);for(const role of managed){if(selected.has(role))service.party.assignRole(entityType,entityId,role,{source:'crm'});else if(service.hasRole(entityType,entityId,role))service.party.removeRole(entityType,entityId,role);}
}
function crmFullPersistAll(){crmCanonicalSyncLegacyViews();crmFullPersist();}

function crmFullSaveContact(payload){
  const service=crmFullService(),result=service.saveContact(payload);crmFullSyncLegacyContact('person',result.person.id,payload.legacyId||result.context.legacyId);crmFullPersistAll();return result;
}
function crmFullSaveCompany(payload){
  const service=crmFullService(),result=service.saveCompany(payload);crmFullSetManagedRoles('organization',result.organization.id,payload.roles||[]);crmFullSyncLegacyContact('organization',result.organization.id,payload.legacyId||result.context.legacyId);crmFullPersistAll();return result;
}
function crmFullSaveCustomer(payload){
  const service=crmFullService(),result=service.saveCustomer(payload);crmFullSyncLegacyContact(result.entityType,result.entity.id,payload.legacyId||result.context.legacyId);crmFullPersistAll();return result;
}
function crmFullSaveLead(payload){
  const service=crmFullService(),lead=service.saveLead(payload);crmFullSyncLegacyLead(lead);if(lead.stage==='converted'&&lead.customerEntityId)crmFullSyncLegacyContact(lead.customerEntityType,lead.customerEntityId);crmFullPersistAll();return lead;
}
function crmFullConvertLead(id){const service=crmFullService(),result=service.convertLead(id);crmFullSyncLegacyLead(result.lead);crmFullSyncLegacyContact(result.customerEntityType,result.customerEntityId);crmFullPersistAll();return result;}
function crmFullArchive(kind,id){
  const service=crmFullService();if(kind==='customer'){const [entityType,entityId]=id.split(':');service.party.removeRole(entityType,entityId,'customer');service.history('customer.removed',{entityType,entityId});crmFullPersistAll();return true;}
  if(kind==='lead'){const lead=service.data.leads.find((x)=>x.id===id);if(!lead)return false;lead.status='archived';lead.updatedAt=new Date().toISOString();service.history('lead.archived',{leadId:id});crmFullPersistAll();return true;}
  if(kind==='interaction'){service.removeInteraction(id);crmFullPersistAll();return true;}
  const entityType=kind==='company'?'organization':'person';const ok=service.archiveEntityContext(entityType,id);crmFullPersistAll();return ok;
}

function crmFullCurrentTab(query){
  const aliases={contatos:'contacts',empresas:'companies',clientes:'customers',interacoes:'interactions','interações':'interactions'};const raw=query?.get('tab')||'contacts',tab=aliases[raw]||raw;return CRM_FULL_TABS.some(([id])=>id===tab)?tab:'contacts';
}
function crmFullTabHref(tab){return `#/crm/relationships?tab=${tab}`;}
function crmFullBreadcrumb(tab){const label=CRM_FULL_TABS.find(([id])=>id===tab)?.[1]||'Contatos';return `<nav class="crm-full-breadcrumb" aria-label="Breadcrumb"><a href="#/crm/relationships">CRM</a><span>/</span><strong>${label}</strong></nav>`;}
function crmFullHeader(tab){
  const config={contacts:['Contatos','Pessoas relacionadas comercial ou institucionalmente à Valtren.','Novo Contato','contact'],companies:['Empresas','Organizações relacionadas à Valtren sem duplicação por papel.','Nova Empresa','company'],customers:['Clientes','Visão de Pessoas e Organizações que possuem o papel Cliente.','Novo Cliente','customer'],leads:['Leads','Oportunidades comerciais vinculadas a identidades canônicas.','Novo Lead','lead'],interactions:['Interações','Histórico real de relacionamento comercial e institucional.','Nova Interação','interaction']},[title,description,actionLabel,kind]=config[tab];
  return `<div class="crm-full-section-header"><div><h2>${title}</h2><p>${description}</p></div><button class="crm-rel-primary" type="button" data-action="crm-full-create" data-kind="${kind}">${icon('plus',16)} ${actionLabel}</button></div>`;
}
function crmFullTabs(tab){return `<nav class="crm-rel-tabs crm-full-tabs" aria-label="Áreas do CRM">${CRM_FULL_TABS.map(([id,label])=>`<a class="${tab===id?'active':''}" href="${crmFullTabHref(id)}">${label}</a>`).join('')}</nav>`;}
function crmFullKpis(items){return `<div class="crm-full-kpis">${items.map(([label,value])=>`<article><span>${esc(label)}</span><strong>${Number(value)||0}</strong></article>`).join('')}</div>`;}
function crmFullDemoToggle(){return `<label class="crm-full-demo-toggle"><input type="checkbox" data-action="crm-full-toggle-demo" ${state.crmFullUi?.includeDemo?'checked':''}> Mostrar dados de demonstração</label>`;}
function crmFullSearchFilters(filters=[]){return `<div class="crm-rel-toolbar crm-full-toolbar"><div class="crm-rel-search"><span>${icon('search',16)}</span><input id="crm-full-search" type="search" placeholder="Buscar no CRM" autocomplete="off"></div>${filters.join('')}${crmFullDemoToggle()}</div>`;}
function crmFullSelectFilter(key,label,options){return `<select data-crm-full-filter="${key}" aria-label="${esc(label)}"><option value="all">${esc(label)}</option>${options.map(([value,text])=>`<option value="${esc(value)}">${esc(text)}</option>`).join('')}</select>`;}
function crmFullTable(title,description,headers,rows,emptyTitle,emptyDescription){
  if(!rows.length)return `<section class="crm-rel-table-card"><div class="crm-rel-list-header"><div><h3>${title}</h3><p>${description}</p></div></div>${crmFullEmpty(emptyTitle,emptyDescription)}</section>`;
  return `<section class="crm-rel-table-card"><div class="crm-rel-list-header"><div><h3>${title}</h3><p>${description}</p></div><span class="crm-rel-count"><b id="crm-full-visible-count">${rows.length}</b> registros</span></div><div class="crm-rel-table-wrap"><table class="crm-rel-table crm-full-table"><thead><tr>${headers.map((h)=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div><div class="crm-rel-pagination crm-full-count-footer"><span>Exibindo <b data-crm-full-visible-footer>${rows.length}</b> registro(s) após os filtros</span></div></section>`;
}
function crmFullActions(kind,id,extra=''){return `<div class="crm-rel-actions"><button type="button" class="crm-rel-more" data-action="crm-full-row-menu" aria-label="Ações">•••</button><div class="crm-rel-actions-menu" hidden><button type="button" data-action="crm-full-view" data-kind="${kind}" data-id="${esc(id)}">Visualizar</button><button type="button" data-action="crm-full-edit" data-kind="${kind}" data-id="${esc(id)}">Editar</button>${extra}<button type="button" class="danger" data-action="crm-full-archive" data-kind="${kind}" data-id="${esc(id)}">${kind==='interaction'?'Arquivar':'Remover do CRM'}</button></div></div>`;}

function crmFullContactsView(){
  const service=crmFullService(),includeDemo=!!state.crmFullUi.includeDemo,rowsData=service.getContacts({includeDemo});
  const real=service.getContacts({includeDemo:false}),customerPF=real.filter(({person})=>service.hasRole('person',person.id,'customer')).length,withCompany=real.filter(({person})=>service.party.data.personOrganizationRelationships.some((r)=>r.personId===person.id&&r.status!=='inactive')).length;
  const rows=rowsData.map(({person,context})=>{const view=crmFullPartyView('person',person.id),rel=service.party.data.personOrganizationRelationships.find((r)=>r.personId===person.id&&r.status!=='inactive'),org=rel?service.party.getEntity('organization',rel.organizationId):null,last=crmFullLastInteraction({personId:person.id,includeDemo}),roles=service.roles('person',person.id),demo=service.isDemoContext('person',person.id),search=crmFullSearchBlob([view.name,view.email,view.phone,view.document,org?.legalName,org?.tradeName,roles.join(' '),(context.tags||[]).join(' ')]);return `<tr data-crm-full-row data-search="${esc(search)}" data-role="${esc(roles.join(' '))}" data-status="${esc(ValtrenCrmCore.fold(context.status))}" data-responsible="${esc(context.responsibleId||'')}" data-priority="${esc(context.priority||'')}"><td><strong>${esc(view.name)}</strong>${crmFullDemoBadge(demo)}</td><td>${esc(org?.tradeName||org?.legalName||'-')}<small>${esc(rel?.positionTitle||rel?.department||'')}</small></td><td><span>${esc(view.phone||'-')}</span><small>${esc(view.email||'-')}</small></td><td>${crmFullRoleBadges(roles)}</td><td>${esc(crmFullResponsibleName(context.responsibleId))}</td><td><span class="crm-rel-status">${esc(context.status||'Ativo')}</span></td><td>${last?`<span>${esc(crmFullInteractionLabel(last.type))}</span><small>${esc(crmFullDate(last.occurredAt))}</small>`:'<span class="crm-full-muted">Sem interação</span>'}</td><td class="crm-rel-actions-cell">${crmFullActions('contact',person.id)}</td></tr>`;});
  const filters=[crmFullSelectFilter('role','Todos os papéis',[['customer','Cliente'],['prospect','Prospect'],['partner','Parceiro'],['supplier','Fornecedor'],['service_provider','Prestador']]),crmFullSelectFilter('status','Todos os status',[['active','Ativo'],['inactive','Inativo'],['negociando','Negociando']]),crmFullSelectFilter('priority','Todas as prioridades',[['high','Alta'],['medium','Média'],['low','Baixa'],['strategic','Estratégico']])];
  return `${crmFullKpis([['Total de Contatos',real.length],['Com empresa',withCompany],['Clientes PF',customerPF]])}${crmFullSearchFilters(filters)}${crmFullTable('Lista de Contatos','Pessoas e seus vínculos comerciais',['Nome','Empresa','Contato','Papéis','Responsável','Status','Última interação','Ações'],rows,'Nenhum contato encontrado','Cadastre o primeiro contato para começar.')}`;
}
function crmFullCompaniesView(){
  const service=crmFullService(),includeDemo=!!state.crmFullUi.includeDemo,rowsData=service.getCompanies({includeDemo}),real=service.getCompanies({includeDemo:false});
  const customerCount=real.filter(({organization})=>service.hasRole('organization',organization.id,'customer')).length,multiRole=real.filter(({organization})=>service.roles('organization',organization.id).filter((r)=>ValtrenCrmCore.CRM_ROLE_SET.has(r)&&r!=='crm_contact').length>1).length;
  const rows=rowsData.map(({organization,context})=>{const view=crmFullPartyView('organization',organization.id),roles=service.roles('organization',organization.id),contacts=service.party.getOrganizationContacts(organization.id),primary=contacts.find((x)=>x.relationship.primary)||contacts[0],last=crmFullLastInteraction({organizationId:organization.id,includeDemo}),demo=service.isDemoContext('organization',organization.id),search=crmFullSearchBlob([view.name,view.legalName,view.document,view.email,view.phone,view.site,organization.segment,roles.join(' '),(context.tags||[]).join(' ')]);return `<tr data-crm-full-row data-search="${esc(search)}" data-role="${esc(roles.join(' '))}" data-status="${esc(ValtrenCrmCore.fold(context.status))}" data-responsible="${esc(context.responsibleId||'')}"><td><strong>${esc(view.name)}</strong><small>${esc(view.legalName&&view.legalName!==view.name?view.legalName:'')}</small>${crmFullDemoBadge(demo)}</td><td>${view.document?esc(view.document):'<span class="crm-full-muted">Não informado</span>'}</td><td>${esc(organization.segment||'-')}</td><td>${crmFullRoleBadges(roles)}</td><td>${primary?`<span>${esc(primary.person.fullName)}</span><small>${esc(primary.relationship.positionTitle||primary.relationship.department||'')}</small>`:'<span class="crm-full-muted">Sem contato principal</span>'}</td><td>${esc(crmFullResponsibleName(context.responsibleId))}</td><td><span class="crm-rel-status">${esc(context.status||'Ativo')}</span></td><td>${last?`<span>${esc(crmFullInteractionLabel(last.type))}</span><small>${esc(crmFullDate(last.occurredAt))}</small>`:'<span class="crm-full-muted">Sem interação</span>'}</td><td class="crm-rel-actions-cell">${crmFullActions('company',organization.id)}</td></tr>`;});
  const filters=[crmFullSelectFilter('role','Todos os papéis',[['customer','Cliente'],['prospect','Prospect'],['partner','Parceiro'],['supplier','Fornecedor'],['service_provider','Prestador']]),crmFullSelectFilter('status','Todos os status',[['active','Ativo'],['inactive','Inativo'],['negociando','Negociando']])];
  return `${crmFullKpis([['Empresas',real.length],['Clientes PJ',customerCount],['Múltiplos papéis',multiRole]])}${crmFullSearchFilters(filters)}${crmFullTable('Empresas','Organizações canônicas relacionadas à Valtren',['Empresa','CNPJ','Segmento','Papéis','Contato principal','Responsável','Status','Última interação','Ações'],rows,'Nenhuma empresa cadastrada','Cadastre a primeira empresa para começar.')}`;
}
function crmFullCustomersView(){
  const service=crmFullService(),includeDemo=!!state.crmFullUi.includeDemo,items=service.getCustomers({includeDemo}),real=service.getCustomers({includeDemo:false}),pf=real.filter((x)=>x.entityType==='person').length,pj=real.length-pf;
  const rows=items.map(({entityType,entity,context})=>{const view=crmFullPartyView(entityType,entity.id),last=crmFullLastInteraction(entityType==='person'?{personId:entity.id,customerEntityType:'person',customerEntityId:entity.id,includeDemo}:{organizationId:entity.id,customerEntityType:'organization',customerEntityId:entity.id,includeDemo}),demo=service.isDemoContext(entityType,entity.id),search=crmFullSearchBlob([view.name,view.legalName,view.document,view.email,view.phone,(context.tags||[]).join(' ')]);return `<tr data-crm-full-row data-search="${esc(search)}" data-type="${entityType}" data-status="${esc(ValtrenCrmCore.fold(context.status))}" data-responsible="${esc(context.responsibleId||'')}"><td><strong>${esc(view.name)}</strong>${crmFullDemoBadge(demo)}<small>${entityType==='person'?'Pessoa Física':'Pessoa Jurídica'}</small></td><td>${view.document?esc(view.document):'<span class="crm-full-muted">Não informado</span>'}</td><td><span>${esc(view.phone||'-')}</span><small>${esc(view.email||'-')}</small></td><td>${esc(crmFullResponsibleName(context.responsibleId))}</td><td><span class="crm-rel-status">${esc(context.status||'Ativo')}</span></td><td>${last?`<span>${esc(crmFullInteractionLabel(last.type))}</span><small>${esc(crmFullDate(last.occurredAt))}</small>`:'<span class="crm-full-muted">Sem interação</span>'}</td><td class="crm-rel-actions-cell">${crmFullActions('customer',`${entityType}:${entity.id}`)}</td></tr>`;});
  const filters=[crmFullSelectFilter('type','Todos os tipos',[['person','Pessoa Física'],['organization','Pessoa Jurídica']]),crmFullSelectFilter('status','Todos os status',[['active','Ativo'],['inactive','Inativo']])];
  return `${crmFullKpis([['Clientes',real.length],['Pessoa Física',pf],['Pessoa Jurídica',pj]])}${crmFullSearchFilters(filters)}${crmFullTable('Clientes','Pessoas e Organizações com papel Cliente',['Cliente','CPF/CNPJ','Contato','Responsável','Status','Última interação','Ações'],rows,'Nenhum cliente encontrado','Crie ou converta um lead para formar a carteira de clientes.')}`;
}
function crmFullLeadIdentity(lead){const p=lead.personId?crmFullPartyView('person',lead.personId):null,o=lead.organizationId?crmFullPartyView('organization',lead.organizationId):null;return {person:p,organization:o,name:p?.name||o?.name||'-',company:o?.name||'',email:p?.email||o?.email||'',phone:p?.phone||o?.phone||''};}
function crmFullLeadsView(){
  const service=crmFullService(),includeDemo=!!state.crmFullUi.includeDemo,items=service.getLeads({includeDemo}),real=service.getLeads({includeDemo:false}),qualified=real.filter((x)=>x.stage==='qualified').length,converted=real.filter((x)=>x.stage==='converted').length;
  const pipeline=`<div class="crm-full-pipeline" aria-label="Pipeline de Leads">${ValtrenCrmCore.STAGES.map((stage)=>`<article><span>${esc(crmFullStageLabel(stage))}</span><strong>${real.filter((x)=>x.stage===stage).length}</strong></article>`).join('')}</div>`;
  const rows=items.map((lead)=>{const identity=crmFullLeadIdentity(lead),last=crmFullLastInteraction({leadId:lead.id,includeDemo}),search=crmFullSearchBlob([identity.name,identity.company,identity.email,identity.phone,lead.origin,lead.stage,lead.priority,lead.responsibleId,lead.tags?.join(' ')]),convert=lead.stage!=='converted'?`<button type="button" data-action="crm-full-convert" data-id="${esc(lead.id)}">Converter em Cliente</button>`:'';return `<tr data-crm-full-row data-search="${esc(search)}" data-stage="${esc(lead.stage)}" data-source="${esc(ValtrenCrmCore.fold(lead.origin))}" data-responsible="${esc(lead.responsibleId||'')}" data-priority="${esc(lead.priority||'')}" data-status="${esc(lead.status||'')}"><td><strong>${esc(identity.name)}</strong>${crmFullDemoBadge(service.isDemoLead(lead))}<small>${esc(identity.company||'')}</small></td><td><span>${esc(identity.phone||'-')}</span><small>${esc(identity.email||'-')}</small></td><td>${esc(lead.origin||'-')}</td><td>${esc(crmFullResponsibleName(lead.responsibleId))}</td><td><span class="crm-full-stage ${lead.stage}">${esc(crmFullStageLabel(lead.stage))}</span></td><td>${esc(lead.priority||'-')}</td><td>${last?`<span>${esc(crmFullInteractionLabel(last.type))}</span><small>${esc(crmFullDate(last.occurredAt))}</small>`:'<span class="crm-full-muted">Sem interação</span>'}</td><td class="crm-rel-actions-cell">${crmFullActions('lead',lead.id,convert)}</td></tr>`;});
  const sources=Array.from(new Set(items.map((x)=>x.origin).filter(Boolean))).sort().map((x)=>[ValtrenCrmCore.fold(x),x]);const filters=[crmFullSelectFilter('stage','Todas as etapas',ValtrenCrmCore.STAGES.map((x)=>[x,crmFullStageLabel(x)])),crmFullSelectFilter('source','Todas as origens',sources),crmFullSelectFilter('priority','Todas as prioridades',[['high','Alta'],['medium','Média'],['low','Baixa'],['alta','Alta'],['média','Média'],['baixa','Baixa']])];
  return `${crmFullKpis([['Leads',real.length],['Qualificados',qualified],['Convertidos',converted]])}${pipeline}${crmFullSearchFilters(filters)}${crmFullTable('Leads','Pipeline comercial vinculado à identidade canônica',['Lead','Contato','Origem','Responsável','Etapa','Prioridade','Última interação','Ações'],rows,'Nenhum lead encontrado','Cadastre o primeiro lead para iniciar o pipeline.')}`;
}
function crmFullInteractionTargetLabel(item){if(item.leadId){const lead=crmFullService().data.leads.find((x)=>x.id===item.leadId);return lead?`Lead · ${crmFullLeadIdentity(lead).name}`:'Lead';}if(item.personId)return crmFullPartyView('person',item.personId)?.name||'Pessoa';if(item.organizationId)return crmFullPartyView('organization',item.organizationId)?.name||'Empresa';if(item.customerEntityId)return `Cliente · ${crmFullPartyView(item.customerEntityType,item.customerEntityId)?.name||'-'}`;return '-';}
function crmFullInteractionsView(){
  const service=crmFullService(),includeDemo=!!state.crmFullUi.includeDemo,items=service.getInteractions({includeDemo}).sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))),real=service.getInteractions({includeDemo:false}),followups=real.filter((x)=>x.type==='follow_up'&&x.status==='pending').length,today=new Date().toISOString().slice(0,10),todayCount=real.filter((x)=>String(x.occurredAt).slice(0,10)===today).length;
  const rows=items.map((item)=>{const search=crmFullSearchBlob([item.title,item.description,crmFullInteractionLabel(item.type),crmFullInteractionTargetLabel(item),item.responsibleId]),entity=item.leadId?'lead':item.personId?'person':item.organizationId?'organization':item.customerEntityId?'customer':'';return `<tr data-crm-full-row data-search="${esc(search)}" data-type="${esc(item.type)}" data-responsible="${esc(item.responsibleId||'')}" data-entity="${esc(entity)}"><td><strong>${esc(crmFullInteractionLabel(item.type))}</strong>${item.metadata?.demo?crmFullDemoBadge(true):''}<small>${esc(item.title||'')}</small></td><td>${esc(crmFullDate(item.occurredAt))}</td><td>${esc(crmFullInteractionTargetLabel(item))}</td><td>${esc(crmFullResponsibleName(item.responsibleId))}</td><td>${item.type==='follow_up'?`<span class="crm-rel-status">${esc(item.status||'pending')}</span><small>${esc(item.followUpAt?crmFullDate(item.followUpAt):'Sem data prevista')}</small>`:`<span>${esc(item.description||'-')}</span>`}</td><td class="crm-rel-actions-cell">${crmFullActions('interaction',item.id)}</td></tr>`;});
  const filters=[crmFullSelectFilter('type','Todos os tipos',ValtrenCrmCore.INTERACTION_TYPES.map((x)=>[x,crmFullInteractionLabel(x)])),crmFullSelectFilter('entity','Todas as entidades',[['person','Pessoa'],['organization','Empresa'],['customer','Cliente'],['lead','Lead']])];
  return `${crmFullKpis([['Interações',real.length],['Hoje',todayCount],['Follow-ups pendentes',followups]])}${crmFullSearchFilters(filters)}${crmFullTable('Interações','Histórico comercial e institucional',['Tipo','Data e hora','Relacionado a','Responsável','Resumo / Follow-up','Ações'],rows,'Nenhuma interação registrada','Registre uma interação para iniciar o histórico de relacionamento.')}`;
}

function crmRelationshipsPage(query){
  crmFullService();const tab=crmFullCurrentTab(query),content={contacts:crmFullContactsView,companies:crmFullCompaniesView,customers:crmFullCustomersView,leads:crmFullLeadsView,interactions:crmFullInteractionsView}[tab]();
  return `<div class="crm-app-shell crm-full-shell">${crmRelSidebar('relationships')}<main class="crm-main"><header class="crm-topbar"><div><h1>CRM</h1><p>Relacionamentos comerciais sobre Pessoas e Organizações canônicas</p></div>${crmHeaderActions('')}</header><section class="crm-workspace crm-rel-workspace crm-full-workspace" aria-label="CRM">${crmFullBreadcrumb(tab)}${crmFullHeader(tab)}${crmFullTabs(tab)}${content}</section></main></div>`;
}

function crmFullApplyFilters(){
  const query=ValtrenCrmCore.fold(document.getElementById('crm-full-search')?.value||''),filters={};document.querySelectorAll('[data-crm-full-filter]').forEach((el)=>filters[el.dataset.crmFullFilter]=el.value);
  let visible=0;document.querySelectorAll('[data-crm-full-row]').forEach((row)=>{let ok=!query||String(row.dataset.search||'').includes(query);for(const [key,value] of Object.entries(filters)){if(!ok||value==='all')continue;const actual=ValtrenCrmCore.fold(row.dataset[key]||'');ok=key==='role'?actual.split(/\s+/).includes(ValtrenCrmCore.fold(value)):actual===ValtrenCrmCore.fold(value);}row.hidden=!ok;if(ok)visible++;});
  const count=document.getElementById('crm-full-visible-count');if(count)count.textContent=String(visible);document.querySelectorAll('[data-crm-full-visible-footer]').forEach((x)=>x.textContent=String(visible));
}
function crmFullCloseModal(){document.getElementById('crm-full-modal-root')?.remove();}
function crmFullOpenModal(kind,mode='create',id=''){
  crmFullCloseModal();const root=document.createElement('div');root.id='crm-full-modal-root';root.className='crm-full-modal-root';root.innerHTML=mode==='view'?crmFullDetailModal(kind,id):crmFullFormModal(kind,mode,id);document.body.appendChild(root);setTimeout(()=>{crmFullCustomerToggle();root.querySelector('input,select,textarea,button')?.focus();},0);
}
function crmFullModalShell(title,subtitle,body,footer=''){return `<div class="crm-full-modal-backdrop" data-action="crm-full-close"></div><section class="crm-full-modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><div><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div><button type="button" data-action="crm-full-close" aria-label="Fechar">×</button></header>${body}${footer}</section>`;}
function crmFullField(label,name,value='',type='text',attrs=''){return `<label class="crm-full-field"><span>${esc(label)}</span><input type="${type}" name="${name}" value="${esc(value||'')}" ${attrs}></label>`;}
function crmFullSelect(label,name,value,options,attrs=''){return `<label class="crm-full-field"><span>${esc(label)}</span><select name="${name}" ${attrs}>${options.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
function crmFullTextarea(label,name,value='',placeholder=''){return `<label class="crm-full-field crm-full-field-wide"><span>${esc(label)}</span><textarea name="${name}" placeholder="${esc(placeholder)}">${esc(value||'')}</textarea></label>`;}
function crmFullUserSelect(value=''){return crmFullSelect('Responsável comercial','responsibleId',value,[['','Não definido'],...crmFullUsers().map((u)=>[u.id,u.name])]);}
function crmFullAddressFields(address={}){return `<div class="crm-full-grid three">${crmFullField('Logradouro','addressLine1',address?.line1||'')}${crmFullField('Número','addressNumber',address?.number||'')}${crmFullField('Complemento','addressComplement',address?.complement||'')}${crmFullField('Bairro','district',address?.district||'')}${crmFullField('Cidade','city',address?.city||'')}${crmFullField('Estado/Região','region',address?.region||'')}${crmFullField('CEP','postalCode',address?.postalCode||'')}${crmFullField('País','country',address?.country||'BR')}</div>`;}
function crmFullFormSection(title,content,description=''){return `<section class="crm-full-form-section"><div><h3>${esc(title)}</h3>${description?`<p>${esc(description)}</p>`:''}</div>${content}</section>`;}
function crmFullRoleCheckboxes(selected=[]){const set=new Set(selected);return `<div class="crm-full-role-checks">${CRM_FULL_ROLE_OPTIONS.map(([v,l])=>`<label><input type="checkbox" name="roles" value="${v}" ${set.has(v)?'checked':''}> ${l}</label>`).join('')}</div>`;}
function crmFullFormFooter(){return `<footer><button type="button" class="crm-rel-secondary" data-action="crm-full-close">Cancelar</button><button type="submit" class="crm-rel-primary">Salvar</button></footer>`;}
function crmFullFormModal(kind,mode,id){
  const service=crmFullService(),edit=mode==='edit';let title='',subtitle='',body='';
  if(kind==='contact'){
    const view=edit?crmFullPartyView('person',id):null,ctx=view?.context||{},rel=edit?service.party.data.personOrganizationRelationships.find((r)=>r.personId===id&&r.status!=='inactive'):null,roles=edit?service.roles('person',id):[],orgOptions=[['','Sem empresa'],...service.party.data.organizations.map((o)=>[o.id,o.tradeName||o.legalName])];title=edit?'Editar Contato':'Novo Contato';subtitle='A identidade será criada ou reutilizada na base canônica de Pessoas.';
    body=`${crmFullFormSection('Identidade',`<div class="crm-full-grid two">${crmFullField('Nome completo *','fullName',view?.name||'','text','required')}${crmFullField('CPF','cpf',view?.document||'')}${crmFullField('E-mail','email',view?.email||'','email')}${crmFullField('Telefone','phone',view?.phone||'','tel')}${crmFullField('WhatsApp','whatsapp',view?.whatsapp||'','tel')}${crmFullField('Tags','tags',(view?.entity?.tags||[]).join(', '))}</div>`)}${crmFullFormSection('Relacionamento CRM',`<div class="crm-full-grid two">${crmFullSelect('Papel/segmento','role',crmFullPrimaryRole(roles),[['crm_contact','Contato'],...CRM_FULL_ROLE_OPTIONS])}${crmFullUserSelect(ctx.responsibleId||'')}${crmFullSelect('Prioridade','priority',ctx.priority||'medium',[['low','Baixa'],['medium','Média'],['high','Alta'],['strategic','Estratégica']])}${crmFullSelect('Status','status',ctx.status||'active',[['active','Ativo'],['inactive','Inativo'],['negotiating','Negociando']])}${crmFullField('Origem','source',ctx.source||'')}${crmFullTextarea('Observações','notes',ctx.notes||'')}</div>`)}${crmFullFormSection('Empresa vinculada',`<div class="crm-full-grid two">${crmFullSelect('Empresa existente','organizationId',rel?.organizationId||'',orgOptions)}${crmFullField('Ou nova empresa','organizationName','')}${crmFullField('Cargo/função nesta empresa','positionTitle',rel?.positionTitle||'')}${crmFullField('Departamento nesta empresa','department',rel?.department||'')}</div>`,'Cargo e departamento pertencem ao vínculo com a empresa, não à identidade global da Pessoa.')}${crmFullFormSection('Endereço',crmFullAddressFields(view?.address||{}))}`;
  }else if(kind==='company'){
    const view=edit?crmFullPartyView('organization',id):null,ctx=view?.context||{},roles=edit?service.roles('organization',id):[];title=edit?'Editar Empresa':'Nova Empresa';subtitle='A Organização canônica pode possuir vários papéis simultaneamente.';
    body=`${crmFullFormSection('Dados cadastrais',`<div class="crm-full-grid two">${crmFullField('Razão social / nome *','legalName',view?.legalName||'','text','required')}${crmFullField('Nome fantasia','tradeName',view?.entity?.tradeName||'')}${crmFullField('CNPJ','cnpj',view?.document||'')}${crmFullField('Segmento','segment',view?.entity?.segment||'')}${crmFullField('Tipo organizacional','organizationType',view?.entity?.organizationType||'')}${crmFullField('E-mail','email',view?.email||'','email')}${crmFullField('Telefone','phone',view?.phone||'','tel')}${crmFullField('Site','site',view?.site||'','url')}${crmFullField('Tags','tags',(view?.entity?.tags||[]).join(', '))}</div>`)}${crmFullFormSection('Papéis',crmFullRoleCheckboxes(roles),'Cliente, Fornecedor, Parceiro, Prestador e Prospect são papéis da mesma Organização.')}${crmFullFormSection('Gestão CRM',`<div class="crm-full-grid two">${crmFullUserSelect(ctx.responsibleId||'')}${crmFullSelect('Status','status',ctx.status||'active',[['active','Ativo'],['inactive','Inativo'],['negotiating','Negociando']])}${crmFullSelect('Prioridade','priority',ctx.priority||'medium',[['low','Baixa'],['medium','Média'],['high','Alta'],['strategic','Estratégica']])}${crmFullTextarea('Observações','notes',ctx.notes||'')}</div>`)}${crmFullFormSection('Endereço',crmFullAddressFields(view?.address||{}))}`;
  }else if(kind==='customer'){
    const parts=edit?id.split(':'):['person',''],entityType=parts[0]||'person',entityId=parts[1]||'',view=edit?crmFullPartyView(entityType,entityId):null,ctx=view?.context||{},people=[['','Criar nova Pessoa'],...service.party.data.people.map((p)=>[p.id,p.fullName])],orgs=[['','Criar nova Organização'],...service.party.data.organizations.map((o)=>[o.id,o.tradeName||o.legalName])];title=edit?'Editar Cliente':'Novo Cliente';subtitle='Cliente é um papel sobre Pessoa ou Organização; nunca uma identidade paralela.';
    body=`${crmFullFormSection('Tipo de cliente',crmFullSelect('Tipo','entityType',entityType,[['person','Pessoa Física'],['organization','Pessoa Jurídica']],'data-crm-full-customer-type'))}<div data-customer-group="person">${crmFullFormSection('Pessoa',`<div class="crm-full-grid two">${crmFullSelect('Pessoa existente','existingPersonId',entityType==='person'?entityId:'',people)}${crmFullField('Nome completo *','fullName',entityType==='person'?view?.name||'':'')}${crmFullField('CPF','cpf',entityType==='person'?view?.document||'':'')}${crmFullField('E-mail','email',entityType==='person'?view?.email||'':'','email')}${crmFullField('Telefone','phone',entityType==='person'?view?.phone||'':'','tel')}</div>`)}</div><div data-customer-group="organization">${crmFullFormSection('Empresa',`<div class="crm-full-grid two">${crmFullSelect('Empresa existente','existingOrganizationId',entityType==='organization'?entityId:'',orgs)}${crmFullField('Razão social / nome *','legalName',entityType==='organization'?view?.legalName||'':'')}${crmFullField('Nome fantasia','tradeName',entityType==='organization'?view?.entity?.tradeName||'':'')}${crmFullField('CNPJ','cnpj',entityType==='organization'?view?.document||'':'')}${crmFullField('E-mail','organizationEmail',entityType==='organization'?view?.email||'':'','email')}${crmFullField('Telefone','organizationPhone',entityType==='organization'?view?.phone||'':'','tel')}</div>`)}</div>${crmFullFormSection('Gestão CRM',`<div class="crm-full-grid two">${crmFullUserSelect(ctx.responsibleId||'')}${crmFullSelect('Status','status',ctx.status||'active',[['active','Ativo'],['inactive','Inativo']])}${crmFullSelect('Prioridade','priority',ctx.priority||'medium',[['low','Baixa'],['medium','Média'],['high','Alta']])}${crmFullTextarea('Observações','notes',ctx.notes||'')}</div>`)}`;
  }else if(kind==='lead'){
    const lead=edit?service.data.leads.find((x)=>x.id===id):null,identity=lead?crmFullLeadIdentity(lead):{},person=identity.person,org=identity.organization;title=edit?'Editar Lead':'Novo Lead';subtitle='O Lead referencia Pessoa, Organização ou ambas sem duplicar a identidade.';
    body=`${crmFullFormSection('Identidade',`<div class="crm-full-grid two">${crmFullSelect('Relacionar Lead a','identityMode',lead?.identityMode||'person',[['person','Pessoa'],['organization','Empresa'],['person_organization','Pessoa + Empresa']],'data-crm-full-lead-mode')}${crmFullField('Nome da Pessoa','fullName',person?.name||'')}${crmFullField('E-mail da Pessoa','email',person?.email||'','email')}${crmFullField('Telefone da Pessoa','phone',person?.phone||'','tel')}${crmFullField('CPF','cpf',person?.document||'')}${crmFullField('Empresa','organizationName',org?.legalName||org?.name||'')}${crmFullField('Nome fantasia','tradeName',org?.entity?.tradeName||'')}${crmFullField('CNPJ','cnpj',org?.document||'')}</div>`)}${crmFullFormSection('Oportunidade comercial',`<div class="crm-full-grid two">${crmFullField('Origem','origin',lead?.origin||'')}${crmFullUserSelect(lead?.responsibleId||'')}${crmFullSelect('Etapa','stage',lead?.stage||'new',ValtrenCrmCore.STAGES.map((s)=>[s,crmFullStageLabel(s)]))}${crmFullSelect('Prioridade','priority',lead?.priority||'medium',[['low','Baixa'],['medium','Média'],['high','Alta']])}${crmFullSelect('Status','status',lead?.status||'open',[['open','Aberto'],['paused','Pausado'],['lost','Perdido'],['converted','Convertido']])}${crmFullField('Produto de interesse','productInterestRef',lead?.productInterestRef||'')}${crmFullField('Serviço de interesse','serviceInterestRef',lead?.serviceInterestRef||'')}${crmFullTextarea('Observações','notes',lead?.notes||'')}</div>`,'Produto e Serviço são referências temporárias; nenhum catálogo paralelo é criado dentro do CRM.')}`;
  }else if(kind==='interaction'){
    const item=edit?service.data.interactions.find((x)=>x.id===id):null;title=edit?'Editar Interação':'Nova Interação';subtitle='Registre um evento real de relacionamento sem duplicar Pessoa ou Organização.';
    const targets=[['','Selecione...'],...service.getContacts({includeDemo:false}).map(({person})=>[`person:${person.id}`,`Pessoa · ${person.fullName}`]),...service.getCompanies({includeDemo:false}).map(({organization})=>[`organization:${organization.id}`,`Empresa · ${organization.tradeName||organization.legalName}`]),...service.getLeads({includeDemo:false}).map((lead)=>[`lead:${lead.id}`,`Lead · ${crmFullLeadIdentity(lead).name}`]),...service.getCustomers({includeDemo:false}).map(({entityType,entity})=>[`customer:${entityType}:${entity.id}`,`Cliente · ${entityType==='person'?entity.fullName:(entity.tradeName||entity.legalName)}`])];let target='';if(item?.leadId)target=`lead:${item.leadId}`;else if(item?.personId)target=`person:${item.personId}`;else if(item?.organizationId)target=`organization:${item.organizationId}`;else if(item?.customerEntityId)target=`customer:${item.customerEntityType}:${item.customerEntityId}`;
    body=`${crmFullFormSection('Interação',`<div class="crm-full-grid two">${crmFullSelect('Tipo','type',item?.type||'note',ValtrenCrmCore.INTERACTION_TYPES.map((x)=>[x,crmFullInteractionLabel(x)]),'data-crm-full-interaction-type')}${crmFullSelect('Relacionado a *','target',target,targets,'required')}${crmFullField('Título/resumo *','title',item?.title||'','text','required')}${crmFullField('Data e hora','occurredAt',item?.occurredAt?String(item.occurredAt).slice(0,16):crmFullNowLocal(),'datetime-local')}${crmFullUserSelect(item?.responsibleId||'')}${crmFullSelect('Status','status',item?.status||'completed',[['completed','Concluído'],['pending','Pendente'],['cancelled','Cancelado']])}${crmFullField('Data prevista do follow-up','followUpAt',item?.followUpAt?String(item.followUpAt).slice(0,16):'','datetime-local')}${crmFullTextarea('Descrição','description',item?.description||'')}</div>`)}`;
  }
  const form=`<form id="crm-full-form" data-kind="${kind}" data-mode="${mode}" data-id="${esc(id||'')}" novalidate><div class="crm-full-modal-body">${body}</div>${crmFullFormFooter()}</form>`;return crmFullModalShell(title,subtitle,form);
}

function crmFullTimeline(items){if(!items.length)return crmFullEmpty('Nenhuma interação registrada','As próximas interações aparecerão aqui.');return `<div class="crm-full-timeline">${items.map((item)=>`<article><span class="crm-full-timeline-dot"></span><time>${esc(crmFullDate(item.occurredAt))}</time><div><strong>${esc(crmFullInteractionLabel(item.type))}</strong><h4>${esc(item.title||'')}</h4><p>${esc(item.description||'')}</p></div></article>`).join('')}</div>`;}
function crmFullHistory(entityType,entityId,leadId=''){const items=crmFullService().data.history.filter((x)=>(entityId&&x.entityType===entityType&&x.entityId===entityId)||(leadId&&x.leadId===leadId)).slice().sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,20);if(!items.length)return crmFullEmpty('Sem histórico comercial','Alterações relevantes do CRM aparecerão aqui.');return `<div class="crm-full-history">${items.map((x)=>`<article><time>${esc(crmFullDate(x.at))}</time><strong>${esc(String(x.action).replaceAll('.',' · '))}</strong></article>`).join('')}</div>`;}
function crmFullDetailModal(kind,id){
  const service=crmFullService();let title='Detalhes',subtitle='CRM',content='';
  if(kind==='contact'){
    const view=crmFullPartyView('person',id),ctx=view?.context,rels=service.party.data.personOrganizationRelationships.filter((x)=>x.personId===id&&x.status!=='inactive'),interactions=service.interactionsFor({personId:id,includeDemo:!!state.crmFullUi.includeDemo});title=view?.name||'Contato';subtitle='Contato · Pessoa canônica';content=`<div class="crm-full-detail-grid">${crmFullDetailCard('Dados cadastrais',`<dl>${crmFullDl('E-mail',view?.email)}${crmFullDl('Telefone',view?.phone)}${crmFullDl('WhatsApp',view?.whatsapp)}${crmFullDl('CPF',view?.document)}${crmFullDl('Status',ctx?.status)}</dl>`)}${crmFullDetailCard('Empresas',rels.length?rels.map((r)=>{const o=service.party.getEntity('organization',r.organizationId);return `<div class="crm-full-linked-row"><strong>${esc(o?.tradeName||o?.legalName||'-')}</strong><span>${esc(r.positionTitle||r.department||'-')}</span></div>`;}).join(''):crmFullEmpty('Sem empresa vinculada','Este contato ainda não possui vínculo com empresa.'))}${crmFullDetailCard('Papéis',crmFullRoleBadges(service.roles('person',id)))}${crmFullDetailCard('Histórico',crmFullHistory('person',id))}${crmFullDetailCard('Interações',crmFullTimeline(interactions),'wide')}</div>`;
  }else if(kind==='company'){
    const view=crmFullPartyView('organization',id),ctx=view?.context,contacts=service.party.getOrganizationContacts(id),interactions=service.interactionsFor({organizationId:id,includeDemo:!!state.crmFullUi.includeDemo});title=view?.name||'Empresa';subtitle='Empresa · Organização canônica';content=`<div class="crm-full-detail-grid">${crmFullDetailCard('Dados cadastrais',`<dl>${crmFullDl('Razão social',view?.legalName)}${crmFullDl('CNPJ',view?.document)}${crmFullDl('E-mail',view?.email)}${crmFullDl('Telefone',view?.phone)}${crmFullDl('Site',view?.site)}${crmFullDl('Status',ctx?.status)}</dl>`)}${crmFullDetailCard('Contatos',contacts.length?contacts.map(({relationship,person})=>`<div class="crm-full-linked-row"><strong>${esc(person.fullName)}</strong><span>${esc(relationship.positionTitle||relationship.department||'-')}</span></div>`).join(''):crmFullEmpty('Sem contatos vinculados','Vincule Pessoas canônicas à empresa.'))}${crmFullDetailCard('Papéis',crmFullRoleBadges(service.roles('organization',id)))}${crmFullDetailCard('Histórico',crmFullHistory('organization',id))}${crmFullDetailCard('Interações',crmFullTimeline(interactions),'wide')}</div>`;
  }else if(kind==='customer'){
    const [entityType,entityId]=id.split(':'),view=crmFullPartyView(entityType,entityId),contacts=entityType==='organization'?service.party.getOrganizationContacts(entityId):[],interactions=service.interactionsFor(entityType==='person'?{personId:entityId,customerEntityType:'person',customerEntityId:entityId,includeDemo:!!state.crmFullUi.includeDemo}:{organizationId:entityId,customerEntityType:'organization',customerEntityId:entityId,includeDemo:!!state.crmFullUi.includeDemo});title=view?.name||'Cliente';subtitle=`Cliente · ${entityType==='person'?'Pessoa Física':'Pessoa Jurídica'}`;content=`<div class="crm-full-detail-grid">${crmFullDetailCard('Dados cadastrais',`<dl>${crmFullDl('Documento',view?.document)}${crmFullDl('E-mail',view?.email)}${crmFullDl('Telefone',view?.phone)}${crmFullDl('Status',view?.context?.status)}</dl>`)}${crmFullDetailCard('Contatos',entityType==='organization'?(contacts.length?contacts.map(({relationship,person})=>`<div class="crm-full-linked-row"><strong>${esc(person.fullName)}</strong><span>${esc(relationship.positionTitle||relationship.department||'-')}</span></div>`).join(''):crmFullEmpty('Sem contatos vinculados','Nenhuma Pessoa está vinculada a esta empresa.')):'<p class="crm-full-muted">Cliente Pessoa Física.</p>')}${crmFullDetailCard('Histórico',crmFullHistory(entityType,entityId))}${crmFullDetailCard('Interações',crmFullTimeline(interactions),'wide')}${crmFullFutureSections()}</div>`;
  }else if(kind==='lead'){
    const lead=service.data.leads.find((x)=>x.id===id),identity=lead?crmFullLeadIdentity(lead):{},interactions=lead?service.interactionsFor({leadId:id,includeDemo:!!state.crmFullUi.includeDemo}):[];title=identity.name||'Lead';subtitle=`Lead · ${lead?crmFullStageLabel(lead.stage):''}`;content=lead?`<div class="crm-full-detail-grid">${crmFullDetailCard('Identidade',`<dl>${crmFullDl('Pessoa',identity.person?.name)}${crmFullDl('Empresa',identity.organization?.name)}${crmFullDl('E-mail',identity.email)}${crmFullDl('Telefone',identity.phone)}</dl>`)}${crmFullDetailCard('Oportunidade',`<dl>${crmFullDl('Origem',lead.origin)}${crmFullDl('Etapa',crmFullStageLabel(lead.stage))}${crmFullDl('Prioridade',lead.priority)}${crmFullDl('Responsável',crmFullResponsibleName(lead.responsibleId))}${crmFullDl('Produto de interesse',lead.productInterestRef)}${crmFullDl('Serviço de interesse',lead.serviceInterestRef)}${crmFullDl('Convertido em',lead.convertedAt?crmFullDate(lead.convertedAt):'Não')}</dl>`)}${crmFullDetailCard('Histórico',crmFullHistory('', '', lead.id))}${crmFullDetailCard('Interações',crmFullTimeline(interactions),'wide')}</div>`:crmFullEmpty('Lead não encontrado','O registro solicitado não está disponível.');
  }else if(kind==='interaction'){
    const item=service.data.interactions.find((x)=>x.id===id);title=item?.title||'Interação';subtitle=item?crmFullInteractionLabel(item.type):'Interação';content=item?`<div class="crm-full-detail-grid">${crmFullDetailCard('Dados',`<dl>${crmFullDl('Tipo',crmFullInteractionLabel(item.type))}${crmFullDl('Data',crmFullDate(item.occurredAt))}${crmFullDl('Relacionado a',crmFullInteractionTargetLabel(item))}${crmFullDl('Responsável',crmFullResponsibleName(item.responsibleId))}${crmFullDl('Status',item.status)}${crmFullDl('Follow-up',item.followUpAt?crmFullDate(item.followUpAt):'—')}</dl>`)}${crmFullDetailCard('Descrição',`<p>${esc(item.description||'Sem descrição.')}</p>`,'wide')}</div>`:crmFullEmpty('Interação não encontrada','O registro solicitado não está disponível.');
  }
  return crmFullModalShell(title,subtitle,`<div class="crm-full-modal-body crm-full-detail-body">${content}</div><footer><button type="button" class="crm-rel-secondary" data-action="crm-full-close">Fechar</button></footer>`);
}
function crmFullDl(label,value){return `<div><dt>${esc(label)}</dt><dd>${value?esc(value):'<span class="crm-full-muted">Não informado</span>'}</dd></div>`;}
function crmFullDetailCard(title,content,cls=''){return `<section class="crm-full-detail-card ${cls}"><h3>${esc(title)}</h3>${content}</section>`;}
function crmFullFutureSections(){return `<section class="crm-full-detail-card wide crm-full-future"><h3>Integrações futuras</h3><div>${[['Produtos relacionados','Negócios'],['Serviços relacionados','Negócios'],['Contratos','Jurídico'],['Transações e Notas Fiscais','Financeiro'],['Atendimentos','ValtrenChat']].map(([label,owner])=>`<article><strong>${label}</strong><span>Sem dados · Owner: ${owner}</span></article>`).join('')}</div></section>`;}

function crmFullCustomerToggle(){const control=document.querySelector('[name="entityType"]');if(!control)return;const type=control.value||'person';document.querySelectorAll('[data-customer-group]').forEach((el)=>el.hidden=el.dataset.customerGroup!==type);}
function crmFullParseTarget(value){const parts=String(value||'').split(':');if(parts[0]==='person')return {personId:parts[1]||''};if(parts[0]==='organization')return {organizationId:parts[1]||''};if(parts[0]==='lead')return {leadId:parts[1]||''};if(parts[0]==='customer')return {customerEntityType:parts[1]||'',customerEntityId:parts[2]||''};return {};}
function crmFullSerializeForm(form){
  const data=new FormData(form),kind=form.dataset.kind,id=form.dataset.id||'',address=crmFullAddressFromData(data),common={responsibleId:String(data.get('responsibleId')||''),status:String(data.get('status')||'active'),priority:String(data.get('priority')||'medium'),notes:String(data.get('notes')||''),tags:crmFullSplitTags(data.get('tags')),address};
  if(kind==='contact')return {kind,payload:{...common,personId:id||'',legacyId:id?crmFullService().getContext('person',id,false)?.legacyId||'':'',fullName:String(data.get('fullName')||''),cpf:String(data.get('cpf')||''),email:String(data.get('email')||''),phone:String(data.get('phone')||''),whatsapp:String(data.get('whatsapp')||''),role:String(data.get('role')||'crm_contact'),source:String(data.get('source')||''),organizationId:String(data.get('organizationId')||''),organizationName:String(data.get('organizationName')||''),positionTitle:String(data.get('positionTitle')||''),department:String(data.get('department')||'')}};
  if(kind==='company')return {kind,payload:{...common,organizationId:id||'',legacyId:id?crmFullService().getContext('organization',id,false)?.legacyId||'':'',legalName:String(data.get('legalName')||''),tradeName:String(data.get('tradeName')||''),cnpj:String(data.get('cnpj')||''),segment:String(data.get('segment')||''),organizationType:String(data.get('organizationType')||''),email:String(data.get('email')||''),phone:String(data.get('phone')||''),site:String(data.get('site')||''),roles:data.getAll('roles')}};
  if(kind==='customer'){const entityType=String(data.get('entityType')||'person'),parts=id.split(':'),existingId=parts[1]||'',entityId=entityType==='person'?String(data.get('existingPersonId')||existingId):String(data.get('existingOrganizationId')||existingId);return {kind,payload:{...common,entityType,entityId,fullName:String(data.get('fullName')||''),cpf:String(data.get('cpf')||''),email:entityType==='person'?String(data.get('email')||''):String(data.get('organizationEmail')||''),phone:entityType==='person'?String(data.get('phone')||''):String(data.get('organizationPhone')||''),legalName:String(data.get('legalName')||''),tradeName:String(data.get('tradeName')||''),cnpj:String(data.get('cnpj')||'')}};}
  if(kind==='lead')return {kind,payload:{leadId:id||'',identityMode:String(data.get('identityMode')||'person'),fullName:String(data.get('fullName')||''),email:String(data.get('email')||''),phone:String(data.get('phone')||''),cpf:String(data.get('cpf')||''),organizationName:String(data.get('organizationName')||''),tradeName:String(data.get('tradeName')||''),cnpj:String(data.get('cnpj')||''),origin:String(data.get('origin')||''),responsibleId:common.responsibleId,stage:String(data.get('stage')||'new'),priority:common.priority,status:String(data.get('status')||'open'),productInterestRef:String(data.get('productInterestRef')||''),serviceInterestRef:String(data.get('serviceInterestRef')||''),notes:common.notes}};
  if(kind==='interaction')return {kind,payload:{interactionId:id||'',type:String(data.get('type')||'note'),title:String(data.get('title')||''),description:String(data.get('description')||''),occurredAt:String(data.get('occurredAt')||'')||new Date().toISOString(),responsibleId:common.responsibleId,status:String(data.get('status')||'completed'),followUpAt:String(data.get('followUpAt')||''),...crmFullParseTarget(data.get('target'))}};
  return {kind,payload:{}};
}
function crmFullValidate(kind,payload){
  if(kind==='contact'&&!payload.fullName.trim())return 'Informe o nome do contato.';
  if(kind==='company'&&!payload.legalName.trim())return 'Informe a razão social ou nome da empresa.';
  if(kind==='customer'){if(payload.entityType==='person'&&!payload.entityId&&!payload.fullName.trim())return 'Selecione uma Pessoa existente ou informe o nome.';if(payload.entityType==='organization'&&!payload.entityId&&!payload.legalName.trim())return 'Selecione uma Empresa existente ou informe a razão social.';}
  if(kind==='lead'){if(payload.identityMode!=='organization'&&!payload.fullName.trim())return 'Informe a Pessoa relacionada ao lead.';if(payload.identityMode!=='person'&&!payload.organizationName.trim())return 'Informe a Empresa relacionada ao lead.';}
  if(kind==='interaction'){if(!payload.title.trim())return 'Informe o título/resumo da interação.';if(!payload.personId&&!payload.organizationId&&!payload.leadId&&!payload.customerEntityId)return 'Selecione a entidade relacionada.';}
  return '';
}
function crmFullSubmit(form){
  const {kind,payload}=crmFullSerializeForm(form),error=crmFullValidate(kind,payload);if(error){crmFullFormError(form,error);return;}
  try{
    if(kind==='contact')crmFullSaveContact(payload);else if(kind==='company')crmFullSaveCompany(payload);else if(kind==='customer')crmFullSaveCustomer(payload);else if(kind==='lead')crmFullSaveLead(payload);else if(kind==='interaction'){const service=crmFullService();if(payload.interactionId)service.updateInteraction(payload.interactionId,payload);else service.createInteraction(payload);crmFullPersistAll();}
    crmFullCloseModal();renderCurrentWithoutReset();crmFullToast('Alterações salvas com sucesso.');
  }catch(error){crmFullFormError(form,error?.message||'Não foi possível salvar.');}
}

if(!window.__valtrenCrmCompleteBound){
  window.__valtrenCrmCompleteBound=true;
  document.addEventListener('click',(event)=>{
    const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;
    if(action==='crm-full-row-menu'){event.stopPropagation();const menu=target.parentElement?.querySelector('.crm-rel-actions-menu');document.querySelectorAll('.crm-rel-actions-menu').forEach((x)=>{if(x!==menu)x.hidden=true;});if(menu)menu.hidden=!menu.hidden;return;}
    if(action==='crm-full-create'){crmFullOpenModal(target.dataset.kind||'contact','create');return;}
    if(action==='crm-full-view'){crmFullOpenModal(target.dataset.kind||'contact','view',target.dataset.id||'');return;}
    if(action==='crm-full-edit'){crmFullOpenModal(target.dataset.kind||'contact','edit',target.dataset.id||'');return;}
    if(action==='crm-full-close'){crmFullCloseModal();return;}
    if(action==='crm-full-toggle-demo'){state.crmFullUi=state.crmFullUi||{};state.crmFullUi.includeDemo=!!target.checked;renderCurrentWithoutReset();return;}
    if(action==='crm-full-convert'){if(confirm('Converter este lead em Cliente preservando identidade e histórico?')){try{crmFullConvertLead(target.dataset.id||'');renderCurrentWithoutReset();crmFullToast('Lead convertido em Cliente.');}catch(error){crmFullError(error?.message||'Não foi possível converter o lead.');}}return;}
    if(action==='crm-full-archive'){const kind=target.dataset.kind,id=target.dataset.id;if(confirm(kind==='customer'?'Remover o papel Cliente sem apagar a identidade canônica?':'Remover este contexto do CRM sem apagar a identidade canônica?')){crmFullArchive(kind,id);crmFullCloseModal();renderCurrentWithoutReset();crmFullToast('Contexto removido sem destruir a identidade canônica.');}return;}
  });
  document.addEventListener('input',(event)=>{if(event.target?.id==='crm-full-search')crmFullApplyFilters();});
  document.addEventListener('change',(event)=>{
    if(event.target?.matches?.('[data-crm-full-filter]'))crmFullApplyFilters();
    if(event.target?.matches?.('[data-crm-full-customer-type]'))crmFullCustomerToggle();
  });
  document.addEventListener('submit',(event)=>{if(event.target?.id==='crm-full-form'){event.preventDefault();crmFullSubmit(event.target);}});
  document.addEventListener('keydown',(event)=>{if(event.key==='Escape'&&document.getElementById('crm-full-modal-root'))crmFullCloseModal();});
}