'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ValtrenCorporateGovernanceCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const STRUCTURE_STATUSES=['draft','review','approved','active','superseded','archived'];
  const HOLDING_STATUSES=['active','inactive','transferred','cancelled'];
  const ACT_TYPES=['incorporation','amendment','capital_increase','capital_reduction','shareholder_entry','shareholder_exit','share_transfer','administrator_appointment','administrator_removal','resolution','other'];
  const clone=(v)=>v==null?v:JSON.parse(JSON.stringify(v));const text=(v)=>v==null?'':String(v).trim();const required=(v,label)=>{const x=text(v);if(!x)throw new Error(`${label} obrigatório`);return x;};const num=(v)=>v==null||v===''?null:Number(v);const validDate=(v,label)=>{if(v==null||v==='')return null;const x=String(v);if(Number.isNaN(Date.parse(x)))throw new Error(`${label} inválida`);return x;};const enumValue=(v,values,label,fallback)=>{const x=text(v)||fallback;if(!values.includes(x))throw new Error(`${label} inválido`);return x;};
  function createState(input={}){return {schemaVersion:1,entities:[],capitalStructures:[],holdings:[],shareholders:[],administrators:[],contributions:[],corporateActs:[],resolutions:[],versions:[],documents:[],history:[],legacyBindings:[],metadata:{createdAt:input.now?input.now():new Date().toISOString(),legacyMigrated:false,boundary:'corporate_ownership_is_not_economic_participation'}};}
  function ensureState(input){const s=input&&typeof input==='object'?input:createState();for(const key of ['entities','capitalStructures','holdings','shareholders','administrators','contributions','corporateActs','resolutions','versions','documents','history','legacyBindings'])if(!Array.isArray(s[key]))s[key]=[];if(!s.metadata||typeof s.metadata!=='object')s.metadata={};s.metadata.boundary='corporate_ownership_is_not_economic_participation';s.schemaVersion=1;return s;}
  function createService(input,options={}){
    const data=ensureState(input),now=options.now||(()=>new Date().toISOString()),actor=options.actorProvider||(()=>null),idFactory=options.idFactory||((p)=>`${p}_${Math.random().toString(36).slice(2,10)}`),partyResolver=options.partyResolver||(()=>null);const id=(p)=>idFactory(p);
    const stamp=(row,isNew=true)=>{const at=now(),by=actor();if(isNew){row.createdAt=at;row.createdBy=by;}row.updatedAt=at;row.updatedBy=by;return row;};const history=(entityType,entityId,action,details={})=>data.history.push({id:id('cgh'),entityType,entityId,action,details:clone(details),at:now(),by:actor()});
    const getEntity=(x)=>data.entities.find(r=>r.id===x)||null,getStructure=(x)=>data.capitalStructures.find(r=>r.id===x)||null,getHolding=(x)=>data.holdings.find(r=>r.id===x)||null;const must=(getter,x,label)=>{const r=getter(x);if(!r)throw new Error(`${label} não encontrado`);return r;};
    const validateParty=(type,partyId)=>{if(!['person','organization'].includes(type))throw new Error('Tipo de parte inválido');if(!partyResolver(type,partyId))throw new Error('Pessoa/Organização canônica não encontrada');};
    const money=(v,label)=>{const x=num(v);if(x==null)return null;if(!Number.isFinite(x)||x<0)throw new Error(`${label} inválido`);return Math.round(x*100)/100;};
    function createEntity(input={}){const organizationId=required(input.organizationId,'Organização societária');validateParty('organization',organizationId);if(data.entities.some(x=>x.organizationId===organizationId))throw new Error('Entidade societária já cadastrada');const row=stamp({id:id('corp_entity'),organizationId,code:text(input.code)||null,status:text(input.status)||'active',notes:text(input.notes),isDemo:Boolean(input.isDemo),metadata:clone(input.metadata||{})});data.entities.push(row);history('entity',row.id,'created',{organizationId});return row;}
    function nextVersion(entityId){const rows=data.capitalStructures.filter(x=>x.entityId===entityId);return (rows.length?Math.max(...rows.map(x=>x.versionNumber||0)):0)+1;}
    function createStructure(input={}){const entityId=required(input.entityId,'Entidade');must(getEntity,entityId,'Entidade');const representationMode=text(input.representationMode)||'quantity';if(!['quantity','percentage','mixed'].includes(representationMode))throw new Error('Modo de representação inválido');const row=stamp({id:id('capital_structure'),entityId,versionNumber:nextVersion(entityId),status:enumValue(input.status,STRUCTURE_STATUSES,'Status','draft'),representationMode,integralRepresentation:Boolean(input.integralRepresentation),effectiveFrom:validDate(input.effectiveFrom,'Vigência inicial'),effectiveUntil:validDate(input.effectiveUntil,'Vigência final'),currency:text(input.currency)||'BRL',authorizedCapital:money(input.authorizedCapital,'Capital autorizado'),subscribedCapital:money(input.subscribedCapital,'Capital subscrito'),paidInCapital:money(input.paidInCapital,'Capital integralizado'),notes:text(input.notes),isDemo:Boolean(input.isDemo),metadata:clone(input.metadata||{})});validateCapital(row);data.capitalStructures.push(row);data.versions.push({id:id('corp_version'),entityId,structureId:row.id,versionNumber:row.versionNumber,createdAt:row.createdAt,createdBy:row.createdBy});history('structure',row.id,'created',{versionNumber:row.versionNumber});return row;}
    function validateCapital(row){if(row.authorizedCapital!=null&&row.subscribedCapital!=null&&row.subscribedCapital>row.authorizedCapital)throw new Error('Capital subscrito excede autorizado');if(row.subscribedCapital!=null&&row.paidInCapital!=null&&row.paidInCapital>row.subscribedCapital)throw new Error('Capital integralizado excede subscrito');}
    function setCapital(structureId,input={}){const row=must(getStructure,structureId,'Estrutura');if(['approved','active','superseded'].includes(row.status))throw new Error('Estrutura histórica é imutável');for(const [k,label] of [['authorizedCapital','Capital autorizado'],['subscribedCapital','Capital subscrito'],['paidInCapital','Capital integralizado']])if(Object.prototype.hasOwnProperty.call(input,k))row[k]=money(input[k],label);if(Object.prototype.hasOwnProperty.call(input,'currency'))row.currency=text(input.currency)||'BRL';validateCapital(row);stamp(row,false);history('structure',row.id,'capital_updated',{});return row;}
    function addHolding(structureId,input={}){const structure=must(getStructure,structureId,'Estrutura');if(['approved','active','superseded'].includes(structure.status))throw new Error('Estrutura histórica é imutável');const holderPartyType=required(input.holderPartyType,'Tipo de sócio'),holderPartyId=required(input.holderPartyId,'Sócio');validateParty(holderPartyType,holderPartyId);const quantity=num(input.quantity),percentage=num(input.percentage),capitalContribution=money(input.capitalContribution,'Aporte societário');if(quantity!=null&&(!Number.isFinite(quantity)||quantity<0))throw new Error('Quantidade inválida');if(percentage!=null&&(!Number.isFinite(percentage)||percentage<0||percentage>100))throw new Error('Percentual inválido');if(quantity==null&&percentage==null)throw new Error('Holding exige quantidade ou percentual');const row=stamp({id:id('holding'),structureId,entityId:structure.entityId,holderPartyType,holderPartyId,instrumentType:text(input.instrumentType)||'quota',class:text(input.class)||null,quantity,percentage,effectiveFrom:validDate(input.effectiveFrom,'Vigência inicial')||structure.effectiveFrom,effectiveUntil:validDate(input.effectiveUntil,'Vigência final')||structure.effectiveUntil,status:enumValue(input.status,HOLDING_STATUSES,'Status','active'),capitalContribution,notes:text(input.notes)},true);data.holdings.push(row);if(!data.shareholders.some(x=>x.entityId===structure.entityId&&x.partyType===holderPartyType&&x.partyId===holderPartyId)){data.shareholders.push(stamp({id:id('shareholder'),entityId:structure.entityId,partyType:holderPartyType,partyId:holderPartyId,status:'active',firstEffectiveFrom:row.effectiveFrom},true));}history('structure',structureId,'holding_added',{holdingId:row.id,holderPartyType,holderPartyId});return row;}
    function holdingsFor(structureId){return clone(data.holdings.filter(x=>x.structureId===structureId));}
    function validateOwnership(structureId){const structure=must(getStructure,structureId,'Estrutura'),rows=data.holdings.filter(x=>x.structureId===structureId&&x.status==='active');if(structure.representationMode==='percentage'&&structure.integralRepresentation){if(rows.some(x=>x.percentage==null))throw new Error('Estrutura percentual integral exige percentual em todas as posições');const total=Math.round(rows.reduce((s,x)=>s+Number(x.percentage||0),0)*1000000)/1000000;if(Math.abs(total-100)>0.000001)throw new Error(`Estrutura percentual integral deve totalizar 100% (atual ${total}%)`);}return true;}
    function sendStructureToReview(structureId){const row=must(getStructure,structureId,'Estrutura');if(row.status!=='draft')throw new Error('Somente rascunho entra em revisão');validateOwnership(structureId);row.status='review';stamp(row,false);history('structure',row.id,'review',{});return row;}
    function approveStructure(structureId){const row=must(getStructure,structureId,'Estrutura');if(row.status!=='review')throw new Error('Estrutura precisa estar em revisão');validateOwnership(structureId);row.status='approved';stamp(row,false);history('structure',row.id,'approved',{});return row;}
    function activateStructure(structureId){const row=must(getStructure,structureId,'Estrutura');if(row.status!=='approved')throw new Error('Estrutura precisa estar aprovada');for(const other of data.capitalStructures.filter(x=>x.entityId===row.entityId&&x.id!==row.id&&x.status==='active')){if(overlap(row.effectiveFrom,row.effectiveUntil,other.effectiveFrom,other.effectiveUntil))throw new Error('Conflito de vigência entre estruturas societárias ativas');}row.status='active';stamp(row,false);history('structure',row.id,'activated',{});return row;}
    function overlap(aStart,aEnd,bStart,bEnd){const a0=aStart?Date.parse(aStart):-Infinity,a1=aEnd?Date.parse(aEnd):Infinity,b0=bStart?Date.parse(bStart):-Infinity,b1=bEnd?Date.parse(bEnd):Infinity;return a0<=b1&&b0<=a1;}
    function createNewVersion(entityId,input={}){must(getEntity,entityId,'Entidade');const prior=data.capitalStructures.filter(x=>x.entityId===entityId).sort((a,b)=>b.versionNumber-a.versionNumber)[0]||null;const next=createStructure({entityId,effectiveFrom:input.effectiveFrom,effectiveUntil:input.effectiveUntil,representationMode:input.representationMode||prior?.representationMode||'quantity',integralRepresentation:Object.prototype.hasOwnProperty.call(input,'integralRepresentation')?input.integralRepresentation:Boolean(prior?.integralRepresentation),currency:input.currency||prior?.currency||'BRL',authorizedCapital:Object.prototype.hasOwnProperty.call(input,'authorizedCapital')?input.authorizedCapital:prior?.authorizedCapital,subscribedCapital:Object.prototype.hasOwnProperty.call(input,'subscribedCapital')?input.subscribedCapital:prior?.subscribedCapital,paidInCapital:Object.prototype.hasOwnProperty.call(input,'paidInCapital')?input.paidInCapital:prior?.paidInCapital,notes:input.notes,isDemo:Boolean(input.isDemo??prior?.isDemo)});if(prior&&input.cloneHoldings!==false){for(const h of data.holdings.filter(x=>x.structureId===prior.id&&x.status==='active'))addHolding(next.id,{holderPartyType:h.holderPartyType,holderPartyId:h.holderPartyId,instrumentType:h.instrumentType,class:h.class,quantity:h.quantity,percentage:h.percentage,capitalContribution:h.capitalContribution,effectiveFrom:next.effectiveFrom,effectiveUntil:next.effectiveUntil});}history('entity',entityId,'new_structure_version',{structureId:next.id,fromStructureId:prior?.id||null});return next;}
    function resolveCorporateStructureAt(entityId,date){must(getEntity,entityId,'Entidade');const when=Date.parse(required(date,'Data'));if(Number.isNaN(when))throw new Error('Data inválida');const rows=data.capitalStructures.filter(x=>x.entityId===entityId&&['approved','active','superseded'].includes(x.status)&&(!x.effectiveFrom||Date.parse(x.effectiveFrom)<=when)&&(!x.effectiveUntil||Date.parse(x.effectiveUntil)>=when));if(rows.length===0)return {status:'none',structure:null,holdings:[]};if(rows.length>1)return {status:'conflict',structure:null,structures:clone(rows),holdings:[]};const structure=rows[0];return {status:'ok',structure:clone(structure),holdings:holdingsFor(structure.id)};}
    function addContribution(entityId,input={}){must(getEntity,entityId,'Entidade');const partyType=required(input.partyType,'Tipo do aportante'),partyId=required(input.partyId,'Aportante');validateParty(partyType,partyId);const row=stamp({id:id('contribution'),entityId,partyType,partyId,amount:money(required(input.amount,'Valor do aporte'),'Aporte'),currency:text(input.currency)||'BRL',kind:text(input.kind)||'subscribed',promisedAt:validDate(input.promisedAt,'Data prometida')||now(),effectiveAt:validDate(input.effectiveAt,'Data efetiva'),transactionId:text(input.transactionId)||null,status:text(input.status)||'recorded',notes:text(input.notes),financialEffect:'none_automatic'},true);data.contributions.push(row);history('entity',entityId,'contribution_recorded',{contributionId:row.id,amount:row.amount});return row;}
    function addAdministrator(entityId,input={}){must(getEntity,entityId,'Entidade');const personId=required(input.personId,'Administrador');validateParty('person',personId);const row=stamp({id:id('administrator'),entityId,personId,title:text(input.title)||'Administrador societário',effectiveFrom:validDate(input.effectiveFrom,'Início')||now(),effectiveUntil:validDate(input.effectiveUntil,'Fim'),status:text(input.status)||'active',notes:text(input.notes),systemRoleId:null,hrPositionId:null},true);data.administrators.push(row);history('entity',entityId,'administrator_added',{administratorId:row.id,personId});return row;}
    function addCorporateAct(entityId,input={}){must(getEntity,entityId,'Entidade');const row=stamp({id:id('corporate_act'),entityId,type:enumValue(input.type,ACT_TYPES,'Tipo de ato','other'),occurredAt:validDate(input.occurredAt,'Data')||now(),description:required(input.description,'Descrição'),responsibleUserId:text(input.responsibleUserId)||null,documentReference:text(input.documentReference)||null,status:text(input.status)||'recorded',notes:text(input.notes)},true);data.corporateActs.push(row);history('entity',entityId,'corporate_act_added',{actId:row.id,type:row.type});return row;}
    function addResolution(entityId,input={}){must(getEntity,entityId,'Entidade');const row=stamp({id:id('resolution'),entityId,title:required(input.title,'Resolução'),resolvedAt:validDate(input.resolvedAt,'Data')||now(),description:text(input.description),responsibleUserId:text(input.responsibleUserId)||null,status:text(input.status)||'approved',documentReference:text(input.documentReference)||null},true);data.resolutions.push(row);history('entity',entityId,'resolution_added',{resolutionId:row.id});return row;}
    function addDocument(entityId,input={}){must(getEntity,entityId,'Entidade');const row=stamp({id:id('corp_doc'),entityId,name:required(input.name,'Documento'),documentType:text(input.documentType)||'other',reference:text(input.reference)||null,url:text(input.url)||null,storage:'metadata-only',notes:text(input.notes)},true);data.documents.push(row);history('entity',entityId,'document_added',{documentId:row.id});return row;}
    function structureFeed(filters={}){let rows=data.capitalStructures.filter(x=>{const e=getEntity(x.entityId);return e&&(filters.includeDemo||!e.isDemo)&&(!x.isDemo||filters.includeDemo);});if(!filters.includeArchived)rows=rows.filter(x=>x.status!=='archived');if(filters.entityId)rows=rows.filter(x=>x.entityId===filters.entityId);if(filters.status)rows=rows.filter(x=>x.status===filters.status);return clone(rows);}
    function shareholdersFeed(filters={}){let rows=data.shareholders.filter(x=>{const e=getEntity(x.entityId);return e&&(filters.includeDemo||!e.isDemo);});if(filters.entityId)rows=rows.filter(x=>x.entityId===filters.entityId);return clone(rows);}
    function classifyLegacy(record={}){const explicit=['corporate_structure','shareholding','shareholder_register','corporate_act'].includes(text(record.domain||record.kind||record.entityType));return {status:explicit?'legacy_review_required':'legacy_incompatible',record:clone(record)};}
    return {data,createEntity,getEntity,createStructure,getStructure,setCapital,addHolding,getHolding,holdingsFor,validateOwnership,sendStructureToReview,approveStructure,activateStructure,createNewVersion,resolveCorporateStructureAt,addContribution,addAdministrator,addCorporateAct,addResolution,addDocument,structureFeed,shareholdersFeed,classifyLegacy,historyFor:(type,entityId)=>clone(data.history.filter(x=>x.entityType===type&&x.entityId===entityId)),economicParticipationFeed:undefined,payoutFeed:undefined,createFinancialTransaction:undefined};
  }
  return {STRUCTURE_STATUSES,HOLDING_STATUSES,ACT_TYPES,BOUNDARY:'corporate_ownership_is_not_economic_participation',createState,ensureState,createService};
});
