const CRM_MARKETING_KEY='valtren-marketing-v1';
function crmMarketingSafeRead(){
  try{
    const raw=localStorage.getItem(CRM_MARKETING_KEY);
    if(raw==null||raw==='')return null;
    const parsed=JSON.parse(raw);
    return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:null;
  }catch(_error){return null;}
}
function crmMarketingEnsure(){
  if(!state.crmMarketing){
    const saved=crmMarketingSafeRead();
    state.crmMarketing=saved||{campaigns:[],content:[],briefings:[],tasks:[]};
  }
  for(const key of ['campaigns','content','briefings','tasks'])if(!Array.isArray(state.crmMarketing[key]))state.crmMarketing[key]=[];
  return state.crmMarketing;
}
function crmMarketingSave(){try{localStorage.setItem(CRM_MARKETING_KEY,JSON.stringify(crmMarketingEnsure()));return true;}catch(_error){return false;}}
function crmMarketingTab(path){const tail=String(path||'').split('/')[3]||'overview';return ['campaigns','calendar','metrics','briefings','tasks'].includes(tail)?tail:'overview';}
function crmMarketingTabs(active){const tabs=[['overview','Visão Geral','#/crm/marketing'],['campaigns','Campanhas','#/crm/marketing/campaigns'],['calendar','Calendário','#/crm/marketing/calendar'],['metrics','Métricas','#/crm/marketing/metrics'],['briefings','Briefings','#/crm/marketing/briefings'],['tasks','Tarefas','#/crm/marketing/tasks']];return `<nav class="crm-marketing-tabs" aria-label="Áreas de Marketing">${tabs.map(([id,label,href])=>`<a href="${href}" class="${active===id?'active':''}">${label}</a>`).join('')}</nav>`;}
function crmMarketingEmpty(title,copy,action=''){return `<div class="crm-marketing-empty"><strong>${title}</strong><p>${copy}</p>${action}</div>`;}
function crmMarketingOverview(data){const active=data.campaigns.filter(x=>x.status==='active').length,pending=data.tasks.filter(x=>x.status!=='done').length,scheduled=data.content.filter(x=>x.status==='scheduled').length,open=data.briefings.filter(x=>x.status!=='approved').length;return `<div class="crm-marketing-kpis"><article><span>Campanhas ativas</span><strong>${active}</strong></article><article><span>Conteúdos agendados</span><strong>${scheduled}</strong></article><article><span>Briefings em aberto</span><strong>${open}</strong></article><article><span>Tarefas pendentes</span><strong>${pending}</strong></article></div><div class="crm-marketing-grid"><section><h2>Operação</h2>${data.campaigns.length||data.content.length?`<p>${data.campaigns.length} campanha(s) e ${data.content.length} conteúdo(s) cadastrados localmente.</p>`:crmMarketingEmpty('Operação ainda vazia','Cadastre a primeira campanha para organizar objetivos, período e orçamento.')}</section><section><h2>Integrações</h2>${crmMarketingEmpty('Canais não conectados','Meta, Google Ads, TikTok, YouTube e demais plataformas só exibirão métricas após configuração real.','<a href="#/crm/configuracoes?tab=integracoes">Ver integrações</a>')}</section></div>`;}
function crmMarketingTable(kind,rows){const config={campaigns:['Campanhas',['Nome','Objetivo','Período','Orçamento','Status']],content:['Calendário de Conteúdo',['Título','Canal','Data','Status','Campanha']],briefings:['Briefings',['Título','Solicitante','Prazo','Status','Campanha']],tasks:['Tarefas',['Tarefa','Responsável','Prazo','Prioridade','Status']]}[kind];if(!rows.length)return crmMarketingEmpty(`Nenhum registro em ${config[0]}`,kind==='campaigns'?'Crie a primeira campanha para iniciar o planejamento.':'Use o botão de criação para adicionar o primeiro registro.');const cells={campaigns:r=>[r.name,r.objective,r.startDate&&r.endDate?`${r.startDate} → ${r.endDate}`:'—',r.budget?Number(r.budget).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—',r.status],content:r=>[r.title,r.channel,r.date||'—',r.status,r.campaign||'—'],briefings:r=>[r.title,r.requester||'—',r.dueDate||'—',r.status,r.campaign||'—'],tasks:r=>[r.title,r.owner||'—',r.dueDate||'—',r.priority,r.status]}[kind];return `<div class="crm-marketing-table"><table><thead><tr>${config[1].map(x=>`<th>${x}</th>`).join('')}<th>Ações</th></tr></thead><tbody>${rows.map(r=>`<tr>${cells(r).map(x=>`<td>${esc(String(x||'—'))}</td>`).join('')}<td><button type="button" data-action="crm-marketing-delete" data-kind="${kind}" data-id="${esc(r.id)}">Excluir</button></td></tr>`).join('')}</tbody></table></div>`;}
function crmMarketingMetrics(){return `<div class="crm-marketing-channel-grid">${['Meta / Instagram / Facebook','Google Ads','TikTok Ads','YouTube','Spotify Ads'].map(name=>`<article><strong>${name}</strong><span>Não configurado</span><p>Nenhuma métrica é simulada.</p></article>`).join('')}</div>`;}
function crmMarketingAction(tab){if(tab==='metrics'||tab==='overview')return '';const labels={campaigns:'Nova Campanha',calendar:'Novo Conteúdo',briefings:'Novo Briefing',tasks:'Nova Tarefa'};return `<button type="button" class="primary" data-action="crm-marketing-open" data-kind="${tab==='calendar'?'content':tab}">+ ${labels[tab]}</button>`;}
function crmMarketingPage(path){const data=crmMarketingEnsure(),tab=crmMarketingTab(path),label=tab==='overview'?'Visão Geral':{campaigns:'Campanhas',calendar:'Calendário',metrics:'Métricas',briefings:'Briefings',tasks:'Tarefas'}[tab],body=tab==='overview'?crmMarketingOverview(data):tab==='metrics'?crmMarketingMetrics():crmMarketingTable(tab==='calendar'?'content':tab,data[tab==='calendar'?'content':tab]),breadcrumb=crmArchitectureBreadcrumb([{label:'Marketing',href:'#/crm/marketing'},{label}]);return crmFidelityPage('marketing',tab,'Marketing','Planejamento e operação dos canais da Valtren Solutions.',crmMarketingAction(tab),`${breadcrumb}${crmMarketingTabs(tab)}<section class="crm-marketing-body">${body}</section><div id="crm-marketing-modal-root"></div>`);}
function crmMarketingModal(kind){const titles={campaigns:'Nova Campanha',content:'Novo Conteúdo',briefings:'Novo Briefing',tasks:'Nova Tarefa'},fields={campaigns:`<label>Nome *<input name="name" required></label><label>Objetivo *<input name="objective" required></label><label>Início<input name="startDate" type="date"></label><label>Fim<input name="endDate" type="date"></label><label>Orçamento<input name="budget" type="number" min="0" step="0.01"></label><label>Status<select name="status"><option value="draft">Rascunho</option><option value="active">Ativa</option><option value="paused">Pausada</option><option value="finished">Finalizada</option></select></label>`,content:`<label>Título *<input name="title" required></label><label>Canal *<input name="channel" required></label><label>Data<input name="date" type="date"></label><label>Campanha<input name="campaign"></label><label>Status<select name="status"><option value="draft">Rascunho</option><option value="scheduled">Agendado</option><option value="published">Publicado</option></select></label>`,briefings:`<label>Título *<input name="title" required></label><label>Solicitante<input name="requester"></label><label>Prazo<input name="dueDate" type="date"></label><label>Campanha<input name="campaign"></label><label>Status<select name="status"><option value="open">Aberto</option><option value="review">Em revisão</option><option value="approved">Aprovado</option></select></label>`,tasks:`<label>Tarefa *<input name="title" required></label><label>Responsável<input name="owner"></label><label>Prazo<input name="dueDate" type="date"></label><label>Prioridade<select name="priority"><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Status<select name="status"><option value="todo">A fazer</option><option value="doing">Em andamento</option><option value="done">Concluída</option></select></label>`};return `<div class="crm-marketing-backdrop" data-action="crm-marketing-close"></div><section class="crm-marketing-modal" role="dialog" aria-modal="true" aria-labelledby="crm-marketing-modal-title"><form data-kind="${kind}"><header><h2 id="crm-marketing-modal-title">${titles[kind]}</h2><button type="button" data-action="crm-marketing-close" aria-label="Fechar">×</button></header><div class="crm-marketing-form">${fields[kind]}</div><footer><button type="button" data-action="crm-marketing-close">Cancelar</button><button type="submit" class="primary">Salvar</button></footer></form></section>`;}
document.addEventListener('click',event=>{const button=event.target.closest('[data-action^="crm-marketing-"]');if(!button)return;const action=button.dataset.action,root=document.getElementById('crm-marketing-modal-root');if(action==='crm-marketing-open'&&root)root.innerHTML=crmMarketingModal(button.dataset.kind);if(action==='crm-marketing-close'&&root)root.innerHTML='';if(action==='crm-marketing-delete'){const data=crmMarketingEnsure();data[button.dataset.kind]=data[button.dataset.kind].filter(x=>x.id!==button.dataset.id);crmMarketingSave();render();}});
document.addEventListener('submit',event=>{if(!event.target.matches('.crm-marketing-modal form'))return;event.preventDefault();const form=event.target,kind=form.dataset.kind,values=Object.fromEntries(new FormData(form).entries());values.id=`mkt-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;values.createdAt=new Date().toISOString();crmMarketingEnsure()[kind].push(values);crmMarketingSave();document.getElementById('crm-marketing-modal-root').innerHTML='';render();});