'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ValtrenIntellectualPropertyCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const ASSET_TYPES=['trademark','patent','copyright','software','industrial_design','domain_related','other'];
  const ASSET_STATUSES=['draft','filed','pending','registered','active','expired','rejected','cancelled','archived'];
  const DEADLINE_STATUSES=['open','completed','cancelled'];
  const clone=(v)=>v==null?v:JSON.parse(JSON.stringify(v));const text=(v)=>v==null?'':String(v).trim();const required=(v,label)=>{const x=text(v);if(!x)throw new Error(`${label} obrigatório`);return x;};
  const validDate=(v,label)=>{if(v==null||v==='')return null;const x=String(v);if(Number.isNaN(Date.parse(x)))throw new Error(`${label} inválida`);return x;};const enumValue=(v,values,label,fallback)=>{const x=text(v)||fallback;if(!values.includes(x))throw new Error(`${label} inválido`);return x;};
  function createState(input={}){return {schemaVersion:1,assets:[],registrations:[],owners:[],licenses:[],deadlines:[],documents:[],history:[],legacyBindings:[],metadata:{createdAt:input.now?input.now():new Date().toISOString(),legacyMigrated:false}};}
  function ensureState(input){const s=input&&typeof input==='object'?input:createState();for(const key of ['assets','registrations','owners','licenses','deadlines','documents','history','legacyBindings'])if(!Array.isArray(s[key]))s[key]=[];if(!s.metadata||typeof s.metadata!=='object')s.metadata={};s.schemaVersion=1;return s;}
  function createService(input,options={}){
    const data=ensureState(input),now=options.now||(()=>new Date().toISOString()),actor=options.actorProvider||(()=>null),idFactory=options.idFactory||((p)=>`${p}_${Math.random().toString(36).slice(2,10)}`),partyResolver=options.partyResolver||(()=>null),businessResolver=options.businessResolver||(()=>null),contractResolver=options.contractResolver||(()=>null);const id=(p)=>idFactory(p);
    const stamp=(row,isNew=true)=>{const at=now(),by=actor();if(isNew){row.createdAt=at;row.createdBy=by;}row.updatedAt=at;row.updatedBy=by;return row;};const history=(entityId,action,details={})=>data.history.push({id:id('iph'),entityType:'ip_asset',entityId,action,details:clone(details),at:now(),by:actor()});
    const getAsset=(assetId)=>data.assets.find(x=>x.id===assetId)||null;const mustAsset=(assetId)=>{const row=getAsset(assetId);if(!row)throw new Error('Ativo de PI não encontrado');return row;};
    const validateParty=(type,partyId)=>{if(!['person','organization'].includes(type))throw new Error('Tipo de titular inválido');if(!partyResolver(type,partyId))throw new Error('Titular canônico não encontrado');};
    const validateBusiness=(kind,ref)=>{if(ref&&!businessResolver(kind,ref))throw new Error('Referência de Negócios não encontrada');};const validateContract=(contractId)=>{if(contractId&&!contractResolver(contractId))throw new Error('Contrato não encontrado');};
    function nextCode(){const nums=data.assets.map(x=>/^PI-(\d{4})$/.exec(x.code)).filter(Boolean).map(x=>Number(x[1]));return `PI-${String((nums.length?Math.max(...nums):0)+1).padStart(4,'0')}`;}
    function validateRegistered(status,registrationNumber){if(status==='registered'&&!text(registrationNumber))throw new Error('Status registrado exige número de registro comprovável');}
    function createAsset(input={}){const ownerPartyType=text(input.ownerPartyType),ownerPartyId=text(input.ownerPartyId);if(ownerPartyType||ownerPartyId){validateParty(required(ownerPartyType,'Tipo de titular'),required(ownerPartyId,'Titular'));}for(const [key,kind] of [['productId','product'],['serviceId','service'],['businessUnitId','business_unit']])validateBusiness(kind,text(input[key]));validateContract(text(input.contractId));const status=enumValue(input.status,ASSET_STATUSES,'Status','draft'),registrationNumber=text(input.registrationNumber);validateRegistered(status,registrationNumber);const row=stamp({id:id('ip'),code:text(input.code)||nextCode(),name:required(input.name,'Nome do ativo'),type:enumValue(input.type,ASSET_TYPES,'Tipo','other'),category:text(input.category),description:text(input.description),status,ownerPartyType:ownerPartyType||null,ownerPartyId:ownerPartyId||null,productId:text(input.productId)||null,serviceId:text(input.serviceId)||null,businessUnitId:text(input.businessUnitId)||null,contractId:text(input.contractId)||null,jurisdiction:text(input.jurisdiction),applicationNumber:text(input.applicationNumber),registrationNumber,filingDate:validDate(input.filingDate,'Data do pedido'),registrationDate:validDate(input.registrationDate,'Data do registro'),expirationDate:validDate(input.expirationDate,'Validade'),renewalDate:validDate(input.renewalDate,'Renovação'),responsibleUserId:text(input.responsibleUserId)||null,notes:text(input.notes),isDemo:Boolean(input.isDemo),metadata:clone(input.metadata||{})});if(data.assets.some(x=>x.code===row.code))throw new Error('Código de PI duplicado');data.assets.push(row);if(row.ownerPartyId)data.owners.push(stamp({id:id('ip_owner'),assetId:row.id,partyType:row.ownerPartyType,partyId:row.ownerPartyId,role:'owner',effectiveFrom:row.filingDate||row.createdAt,effectiveUntil:null},true));data.registrations.push(stamp({id:id('ip_registration'),assetId:row.id,applicationNumber:row.applicationNumber||null,registrationNumber:row.registrationNumber||null,jurisdiction:row.jurisdiction||null,filingDate:row.filingDate,registrationDate:row.registrationDate,status:row.status==='registered'?'registered':row.applicationNumber?'filed':'internal_record',evidenceReference:text(input.registrationEvidenceReference)||null},true));history(row.id,'created',{code:row.code,type:row.type});return row;}
    function updateAsset(assetId,patch={}){const row=mustAsset(assetId);if(Object.prototype.hasOwnProperty.call(patch,'ownerPartyId')||Object.prototype.hasOwnProperty.call(patch,'ownerPartyType')){const type=text(patch.ownerPartyType??row.ownerPartyType),pid=text(patch.ownerPartyId??row.ownerPartyId);if(type||pid)validateParty(required(type,'Tipo de titular'),required(pid,'Titular'));row.ownerPartyType=type||null;row.ownerPartyId=pid||null;}for(const [key,kind] of [['productId','product'],['serviceId','service'],['businessUnitId','business_unit']])if(Object.prototype.hasOwnProperty.call(patch,key)){const ref=text(patch[key]);validateBusiness(kind,ref);row[key]=ref||null;}if(Object.prototype.hasOwnProperty.call(patch,'contractId')){const ref=text(patch.contractId);validateContract(ref);row.contractId=ref||null;}for(const k of ['name','category','description','jurisdiction','applicationNumber','registrationNumber','responsibleUserId','notes'])if(Object.prototype.hasOwnProperty.call(patch,k))row[k]=text(patch[k])||((k==='responsibleUserId')?null:'');if(Object.prototype.hasOwnProperty.call(patch,'type'))row.type=enumValue(patch.type,ASSET_TYPES,'Tipo');if(Object.prototype.hasOwnProperty.call(patch,'status'))row.status=enumValue(patch.status,ASSET_STATUSES,'Status');for(const k of ['filingDate','registrationDate','expirationDate','renewalDate'])if(Object.prototype.hasOwnProperty.call(patch,k))row[k]=validDate(patch[k],k);validateRegistered(row.status,row.registrationNumber);stamp(row,false);history(row.id,'updated',{fields:Object.keys(patch)});return row;}
    function addRegistration(assetId,input={}){const asset=mustAsset(assetId),status=text(input.status)||'filed',registrationNumber=text(input.registrationNumber);if(status==='registered'&&!registrationNumber)throw new Error('Registro comprovado exige número de registro');const row=stamp({id:id('ip_registration'),assetId,applicationNumber:text(input.applicationNumber)||asset.applicationNumber||null,registrationNumber:registrationNumber||asset.registrationNumber||null,jurisdiction:text(input.jurisdiction)||asset.jurisdiction||null,filingDate:validDate(input.filingDate,'Data do pedido')||asset.filingDate,registrationDate:validDate(input.registrationDate,'Data do registro')||asset.registrationDate,status,evidenceReference:text(input.evidenceReference)||null,notes:text(input.notes)},true);data.registrations.push(row);if(row.applicationNumber)asset.applicationNumber=row.applicationNumber;if(row.registrationNumber)asset.registrationNumber=row.registrationNumber;if(row.status==='registered'){asset.status='registered';asset.registrationDate=row.registrationDate||asset.registrationDate;}stamp(asset,false);history(assetId,'registration_added',{registrationId:row.id,status:row.status});return row;}
    function addOwner(assetId,input={}){mustAsset(assetId);const partyType=required(input.partyType,'Tipo de titular'),partyId=required(input.partyId,'Titular');validateParty(partyType,partyId);const row=stamp({id:id('ip_owner'),assetId,partyType,partyId,role:text(input.role)||'owner',effectiveFrom:validDate(input.effectiveFrom,'Início')||now(),effectiveUntil:validDate(input.effectiveUntil,'Fim'),notes:text(input.notes)},true);data.owners.push(row);history(assetId,'owner_added',{ownerId:row.id,partyType,partyId});return row;}
    function addLicense(assetId,input={}){mustAsset(assetId);const contractId=required(input.contractId,'Contrato');validateContract(contractId);const licenseePartyType=text(input.licenseePartyType),licenseePartyId=text(input.licenseePartyId);if(licenseePartyType||licenseePartyId)validateParty(required(licenseePartyType,'Tipo do licenciado'),required(licenseePartyId,'Licenciado'));const row=stamp({id:id('ip_license'),assetId,contractId,licenseePartyType:licenseePartyType||null,licenseePartyId:licenseePartyId||null,effectiveFrom:validDate(input.effectiveFrom,'Início'),effectiveUntil:validDate(input.effectiveUntil,'Fim'),status:text(input.status)||'active',notes:text(input.notes),termsOwner:'contract'},true);data.licenses.push(row);history(assetId,'license_added',{licenseId:row.id,contractId});return row;}
    function addDeadline(assetId,input={}){mustAsset(assetId);const row=stamp({id:id('ip_deadline'),assetId,title:required(input.title,'Prazo'),dueAt:validDate(required(input.dueAt,'Vencimento'),'Vencimento'),type:text(input.type)||'renewal',status:enumValue(input.status,DEADLINE_STATUSES,'Status','open'),responsibleUserId:text(input.responsibleUserId)||null,completedAt:validDate(input.completedAt,'Conclusão'),notes:text(input.notes)},true);data.deadlines.push(row);history(assetId,'deadline_added',{deadlineId:row.id});return row;}
    function addDocument(assetId,input={}){mustAsset(assetId);const row=stamp({id:id('ip_doc'),assetId,name:required(input.name,'Documento'),documentType:text(input.documentType)||'other',reference:text(input.reference)||null,url:text(input.url)||null,storage:'metadata-only',notes:text(input.notes)},true);data.documents.push(row);history(assetId,'document_added',{documentId:row.id});return row;}
    function archive(assetId){const row=mustAsset(assetId);row.status='archived';stamp(row,false);history(assetId,'archived',{});return row;}
    function feed(filters={}){let rows=data.assets.filter(x=>filters.includeDemo?true:!x.isDemo);if(!filters.includeArchived)rows=rows.filter(x=>x.status!=='archived');for(const key of ['type','status','ownerPartyId','productId','serviceId','businessUnitId','responsibleUserId','jurisdiction'])if(filters[key])rows=rows.filter(x=>String(x[key]||'')===String(filters[key]));if(filters.expiringBefore)rows=rows.filter(x=>x.expirationDate&&String(x.expirationDate)<=String(filters.expiringBefore));if(filters.search){const q=text(filters.search).toLowerCase();rows=rows.filter(x=>[x.code,x.name,x.category,x.description,x.applicationNumber,x.registrationNumber,x.jurisdiction].some(v=>text(v).toLowerCase().includes(q)));}return clone(rows);}
    function query(filters={}){const rows=feed(filters),limit=Math.min(50,Math.max(1,Number(filters.limit)||50)),page=Math.max(1,Number(filters.page)||1),pages=Math.max(1,Math.ceil(rows.length/limit));return {rows:rows.slice((page-1)*limit,page*limit),page,total:rows.length,pages,limit};}
    function deadlinesFeed(filters={}){const out=[];for(const a of data.assets){if(!filters.includeDemo&&a.isDemo)continue;for(const [type,dueAt] of [['expiration',a.expirationDate],['renewal',a.renewalDate]])if(dueAt)out.push({id:`${a.id}:${type}`,domain:'intellectual_property',assetId:a.id,title:a.name,dueAt,type,status:a.status,responsibleUserId:a.responsibleUserId});}for(const d of data.deadlines){const a=getAsset(d.assetId);if(a&&(filters.includeDemo||!a.isDemo))out.push(clone({...d,domain:'intellectual_property'}));}return clone(out);}
    function detail(assetId){const asset=mustAsset(assetId);return clone({asset,registrations:data.registrations.filter(x=>x.assetId===assetId),owners:data.owners.filter(x=>x.assetId===assetId),licenses:data.licenses.filter(x=>x.assetId===assetId),deadlines:data.deadlines.filter(x=>x.assetId===assetId),documents:data.documents.filter(x=>x.assetId===assetId),history:data.history.filter(x=>x.entityId===assetId)});}
    function classifyLegacy(record={}){const explicit=['ip_asset','intellectual_property','trademark_registration','software_registration'].includes(text(record.domain||record.kind||record.entityType));return {status:explicit?'legacy_review_required':'legacy_incompatible',record:clone(record)};}
    return {data,nextCode,createAsset,updateAsset,getAsset,addRegistration,addOwner,addLicense,addDeadline,addDocument,archive,feed,query,deadlinesFeed,detail,classifyLegacy,historyFor:(assetId)=>clone(data.history.filter(x=>x.entityId===assetId))};
  }
  return {ASSET_TYPES,ASSET_STATUSES,DEADLINE_STATUSES,createState,ensureState,createService};
});
