'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),Core=require('../web/src/modules/legal/corporate/core.js');
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(e){console.error(`FAIL ${name}`);throw e;}}
let tick=0;const now=()=>`2026-08-26T13:${String(tick++).padStart(2,'0')}:00.000Z`;let seq=0;const idFactory=p=>`${p}_t_${++seq}`;const parties=new Set(['person:p1','person:p2','person:p3','organization:o1','organization:o2']);
const store=Core.createState({now}),svc=Core.createService(store,{now,idFactory,actorProvider:()=> 'u1',partyResolver:(t,id)=>parties.has(`${t}:${id}`)?{id}:null});
test('state canônico Societário possui domínios separados',()=>assert.equal(['entities','capitalStructures','holdings','shareholders','administrators','contributions','corporateActs','resolutions','versions','documents','history'].filter(k=>Array.isArray(store[k])).length,11));
test('boundary explícita Societário ≠ Participações',()=>assert.equal(store.metadata.boundary,'corporate_ownership_is_not_economic_participation'));
const entity=svc.createEntity({organizationId:'o1'});test('criar entidade jurídica societária por Organization canônica',()=>assert.equal(entity.organizationId,'o1'));test('empresa fictícia não é criada',()=>assert.equal(store.entities.length,1));
const s1=svc.createStructure({entityId:entity.id,effectiveFrom:'2026-01-01',effectiveUntil:'2026-12-31',representationMode:'percentage',integralRepresentation:true,currency:'BRL',authorizedCapital:100000,subscribedCapital:100000,paidInCapital:70000});test('criar estrutura societária',()=>assert(s1));test('estrutura v1',()=>assert.equal(s1.versionNumber,1));test('capital autorizado',()=>assert.equal(s1.authorizedCapital,100000));test('capital subscrito',()=>assert.equal(s1.subscribedCapital,100000));test('capital integralizado',()=>assert.equal(s1.paidInCapital,70000));
const h1=svc.addHolding(s1.id,{holderPartyType:'person',holderPartyId:'p1',instrumentType:'quota',class:'A',quantity:600,percentage:60,capitalContribution:60000});const h2=svc.addHolding(s1.id,{holderPartyType:'organization',holderPartyId:'o2',instrumentType:'quota',class:'A',quantity:400,percentage:40,capitalContribution:40000});
test('sócio Person canônica',()=>assert.equal(h1.holderPartyId,'p1'));test('sócio Organization canônica',()=>assert.equal(h2.holderPartyId,'o2'));test('holding preserva quantidade',()=>assert.equal(h1.quantity,600));test('holding preserva percentual',()=>assert.equal(h1.percentage,60));test('holding preserva classe',()=>assert.equal(h1.class,'A'));test('holding preserva aporte declarado',()=>assert.equal(h1.capitalContribution,60000));test('soma societária integral valida 100%',()=>assert.equal(svc.validateOwnership(s1.id),true));
svc.sendStructureToReview(s1.id);test('estrutura vai para revisão',()=>assert.equal(s1.status,'review'));svc.approveStructure(s1.id);test('estrutura pode ser aprovada',()=>assert.equal(s1.status,'approved'));svc.activateStructure(s1.id);test('estrutura pode ficar ativa',()=>assert.equal(s1.status,'active'));
const resolved1=svc.resolveCorporateStructureAt(entity.id,'2026-06-01');test('resolução societária por data v1',()=>assert.equal(resolved1.status,'ok'));test('resolução retorna holdings históricas',()=>assert.equal(resolved1.holdings.length,2));
const s2=svc.createNewVersion(entity.id,{effectiveFrom:'2027-01-01',effectiveUntil:'2027-12-31',cloneHoldings:false,representationMode:'percentage',integralRepresentation:true,authorizedCapital:120000,subscribedCapital:120000,paidInCapital:90000});test('nova versão societária',()=>assert.equal(s2.versionNumber,2));svc.addHolding(s2.id,{holderPartyType:'person',holderPartyId:'p1',instrumentType:'quota',class:'A',quantity:500,percentage:50});svc.addHolding(s2.id,{holderPartyType:'person',holderPartyId:'p2',instrumentType:'quota',class:'A',quantity:300,percentage:30});svc.addHolding(s2.id,{holderPartyType:'person',holderPartyId:'p3',instrumentType:'quota',class:'A',quantity:200,percentage:20});svc.sendStructureToReview(s2.id);svc.approveStructure(s2.id);svc.activateStructure(s2.id);test('estrutura v1 permanece histórica',()=>assert(svc.getStructure(s1.id)));const resolved2=svc.resolveCorporateStructureAt(entity.id,'2027-06-01');test('resolução por data v2',()=>assert.equal(resolved2.structure.versionNumber,2));
const conflict=svc.createStructure({entityId:entity.id,effectiveFrom:'2027-06-01',effectiveUntil:'2027-08-01',representationMode:'quantity'});svc.addHolding(conflict.id,{holderPartyType:'person',holderPartyId:'p1',quantity:1});svc.sendStructureToReview(conflict.id);svc.approveStructure(conflict.id);test('conflito de vigência é bloqueado na ativação',()=>assert.throws(()=>svc.activateStructure(conflict.id),/Conflito de vigência/));
// approved conflitante ainda deve ser sinalizado pelo selector histórico
const conflictResolved=svc.resolveCorporateStructureAt(entity.id,'2027-07-01');test('selector sinaliza conflito de vigência',()=>assert.equal(conflictResolved.status,'conflict'));
const qStruct=svc.createStructure({entityId:entity.id,effectiveFrom:'2028-01-01',representationMode:'quantity',integralRepresentation:false});svc.addHolding(qStruct.id,{holderPartyType:'person',holderPartyId:'p1',instrumentType:'share',class:'A',quantity:100});test('estrutura por quantidade não força 100%',()=>assert.equal(svc.validateOwnership(qStruct.id),true));
const contribution=svc.addContribution(entity.id,{partyType:'person',partyId:'p1',amount:15000,currency:'BRL',kind:'subscribed'});test('aporte societário',()=>assert.equal(contribution.amount,15000));test('aporte não cria Transação',()=>assert.equal(contribution.financialEffect,'none_automatic'));test('aporte sem movimento não inventa transactionId',()=>assert.equal(contribution.transactionId,null));
const admin=svc.addAdministrator(entity.id,{personId:'p2',title:'Administrador'});test('administrador societário usa Person',()=>assert.equal(admin.personId,'p2'));test('administrador societário não é role de sistema',()=>assert.equal(admin.systemRoleId,null));test('administrador societário não é cargo de RH',()=>assert.equal(admin.hrPositionId,null));
const act=svc.addCorporateAct(entity.id,{type:'capital_increase',description:'Aumento de capital deliberado',occurredAt:'2027-02-01',responsibleUserId:'u2'});test('ato societário',()=>assert.equal(act.type,'capital_increase'));const resolution=svc.addResolution(entity.id,{title:'Resolução 01',description:'Deliberação'});test('resolução societária',()=>assert.equal(resolution.entityId,entity.id));const doc=svc.addDocument(entity.id,{name:'Ata',reference:'ATA-1'});test('documento societário é metadata',()=>assert.equal(doc.storage,'metadata-only'));test('histórico societário preservado',()=>assert(svc.historyFor('entity',entity.id).length>0));
test('Sócio ≠ Participante Econômico',()=>assert.equal('economicParticipantId' in h1,false));test('holding.percentage ≠ economicRule.percentage',()=>assert.equal('economicRuleId' in h1,false));test('capitalContribution ≠ financialTransaction',()=>assert.equal('financialTransactionId' in h1,false));test('Societário não cria Participação Econômica',()=>assert.equal(svc.economicParticipationFeed,undefined));test('Societário não cria Repasse',()=>assert.equal(svc.payoutFeed,undefined));test('Societário não cria Transação',()=>assert.equal(svc.createFinancialTransaction,undefined));test('state Societário não possui participations/payouts/transactions',()=>{for(const k of ['participations','payouts','transactions'])assert.equal(k in store,false);});
const demoEntity=svc.createEntity({organizationId:'o2',isDemo:true});svc.createStructure({entityId:demoEntity.id,isDemo:true});test('demo é excluído do structureFeed real',()=>assert(!svc.structureFeed().some(x=>x.entityId===demoEntity.id)));test('includeDemo é explícito',()=>assert(svc.structureFeed({includeDemo:true}).some(x=>x.entityId===demoEntity.id)));test('Organization inexistente é rejeitada',()=>assert.throws(()=>svc.createEntity({organizationId:'missing'}),/canônica/));test('sócio inexistente é rejeitado',()=>assert.throws(()=>svc.addHolding(qStruct.id,{holderPartyType:'person',holderPartyId:'missing',quantity:1}),/canônica/));test('legacy ambíguo permanece incompatível',()=>assert.equal(svc.classifyLegacy({partner:'x'}).status,'legacy_incompatible'));test('legacy explicitamente societário exige revisão',()=>assert.equal(svc.classifyLegacy({domain:'shareholding'}).status,'legacy_review_required'));test('structureFeed é clone read-only',()=>{const rows=svc.structureFeed({includeDemo:true});rows[0].currency='USD';assert.equal(svc.getStructure(s1.id).currency,'BRL');});
if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8');
  test('bundle contém ValtrenCorporateGovernanceCore',()=>assert(app.includes('ValtrenCorporateGovernanceCore')));
  test('bundle contém state.crmCorporateGovernance',()=>assert(app.includes('state.crmCorporateGovernance')));
  test('rota Societário é canônica',()=>assert(app.includes("if(path==='/crm/juridico/societario')return crmCorporateGovernancePage();")));
  test('placeholder Societário não sobrevive',()=>assert(!app.includes("if(path==='/crm/juridico/societario')return crmArchitecturePlaceholderPage")));
  test('resolver societário por data está no bundle',()=>assert(app.includes('resolveCorporateStructureAt')));
  test('boundary Societário ≠ Participações está no bundle',()=>assert(app.includes('corporate_ownership_is_not_economic_participation')));
  test('Participações Financeiras continuam owner próprio',()=>assert(app.includes('state.crmEconomicParticipations')));
  test('Repasses continuam owner próprio',()=>assert(app.includes('state.crmPayouts')));
  test('Transações continuam owner próprio',()=>assert(app.includes('state.crmFinancialTransactions')));
}
console.log(`Corporate Governance tests: ${passed} passed`);
