'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),Core=require('./crm_compliance_core.js');
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(e){console.error(`FAIL ${name}`);throw e;}}
let tick=0;const now=()=>`2026-08-26T11:${String(tick++).padStart(2,'0')}:00.000Z`;let seq=0;const idFactory=p=>`${p}_t_${++seq}`;const business=new Set(['product:prd1','service:srv1','business_unit:bu1']);
const store=Core.createState({now}),svc=Core.createService(store,{now,idFactory,actorProvider:()=> 'u1',businessResolver:(t,id)=>business.has(`${t}:${id}`)?{id}:null,matterResolver:id=>id==='matter1'?{id}:null});
test('state canônico de Compliance possui coleções separadas',()=>assert.equal(['obligations','controls','occurrences','policies','policyVersions','evidence','reviews','history'].filter(k=>Array.isArray(store[k])).length,8));
test('nenhuma obrigação fake nasce automaticamente',()=>assert.equal(store.obligations.length,0));test('nenhuma política fictícia nasce automaticamente',()=>assert.equal(store.policies.length,0));
const o=svc.createObligation({title:'Obrigação identificada',category:'Privacidade',riskLevel:'high',responsibleUserId:'u2',source:'Fonte declarada',authority:'Autoridade informada',reference:'REF-1',effectiveFrom:'2026-01-01',reviewDate:'2026-10-01',dueDate:'2026-11-01',productId:'prd1',serviceId:'srv1',businessUnitId:'bu1'});
test('criar obrigação',()=>assert(o));test('código da obrigação',()=>assert.equal(o.code,'CMP-001'));test('risco da obrigação',()=>assert.equal(o.riskLevel,'high'));test('responsável da obrigação',()=>assert.equal(o.responsibleUserId,'u2'));test('Produto é referência canônica',()=>assert.equal(o.productId,'prd1'));test('Serviço é referência canônica',()=>assert.equal(o.serviceId,'srv1'));test('Unidade é referência canônica',()=>assert.equal(o.businessUnitId,'bu1'));test('vigência da obrigação',()=>assert.equal(o.effectiveFrom,'2026-01-01'));test('prazo/revisão ficam estruturados',()=>assert(svc.deadlinesFeed().filter(x=>x.entityId===o.id).length>=2));
const c=svc.createControl(o.id,{name:'Revisão trimestral',description:'Controle interno',ownerUserId:'u3',frequency:'quarterly',status:'active',nextReviewAt:'2026-09-30'});test('controle ligado à obrigação',()=>assert.equal(c.obligationId,o.id));const rev=svc.reviewControl(c.id,{outcome:'effective',nextReviewAt:'2026-12-31'});test('revisão de controle',()=>assert.equal(rev.entityType,'control'));test('próxima revisão do controle',()=>assert.equal(c.nextReviewAt,'2026-12-31'));
const occ=svc.createOccurrence({title:'Achado de auditoria',type:'finding',severity:'medium',responsibleUserId:'u4',obligationId:o.id,matterId:'matter1'});test('criar ocorrência',()=>assert(occ));test('tipo da ocorrência',()=>assert.equal(occ.type,'finding'));test('ocorrência pode referenciar Assunto Jurídico',()=>assert.equal(occ.matterId,'matter1'));svc.resolveOccurrence(occ.id,{resolution:'Ação corretiva concluída'});test('ocorrência pode ser resolvida',()=>assert.equal(occ.status,'resolved'));
const p=svc.createPolicy({name:'Política Interna A',category:'Governança',ownerUserId:'u5',content:'Conteúdo v1'});test('criar política',()=>assert(p));test('Policy é distinta de PolicyVersion',()=>assert.notEqual(p.id,svc.versionsFor(p.id)[0].id));const v1=svc.versionsFor(p.id)[0];test('versão inicial é draft',()=>assert.equal(v1.status,'draft'));svc.updatePolicyVersion(v1.id,{effectiveFrom:'2026-09-01',effectiveUntil:'2027-08-31',reviewDate:'2027-06-01'});test('vigência da política',()=>assert.equal(v1.effectiveUntil,'2027-08-31'));svc.sendPolicyVersionToReview(v1.id);test('fluxo draft → review',()=>assert.equal(v1.status,'review'));svc.approvePolicyVersion(v1.id);test('fluxo review → approved',()=>assert.equal(v1.status,'approved'));test('versão aprovada é imutável',()=>assert.throws(()=>svc.updatePolicyVersion(v1.id,{content:'Mutação'}),/imutável/));svc.activatePolicyVersion(v1.id);test('versão aprovada pode virar active',()=>assert.equal(v1.status,'active'));
const v2=svc.createPolicyVersion(p.id,{content:'Conteúdo v2',effectiveFrom:'2027-09-01'});svc.sendPolicyVersionToReview(v2.id);svc.approvePolicyVersion(v2.id);svc.activatePolicyVersion(v2.id);test('nova versão ativa supersede anterior',()=>assert.equal(v1.status,'superseded'));test('versão antiga permanece histórica',()=>assert(svc.versionsFor(p.id).some(x=>x.id===v1.id)));
const ev=svc.addEvidence({entityType:'obligation',entityId:o.id,name:'Evidência',reference:'EV-1'});test('evidência é metadata/referência',()=>assert.equal(ev.storage,'metadata-only'));const review=svc.addReview({entityType:'obligation',entityId:o.id,outcome:'conforme'});test('revisão explícita pode ser registrada',()=>assert.equal(review.entityId,o.id));test('histórico da obrigação',()=>assert(svc.historyFor('obligation',o.id).length>0));
const demo=svc.createObligation({title:'Demo',isDemo:true});test('demo é excluído do feed real',()=>assert(!svc.obligationsFeed().some(x=>x.id===demo.id)));test('includeDemo é explícito',()=>assert(svc.obligationsFeed({includeDemo:true}).some(x=>x.id===demo.id)));test('business inexistente é rejeitado',()=>assert.throws(()=>svc.createObligation({title:'X',productId:'missing'}),/Negócios/));test('Assunto Jurídico inexistente é rejeitado em ocorrência',()=>assert.throws(()=>svc.createOccurrence({title:'X',matterId:'missing'}),/Assunto Jurídico/));test('legacy ambíguo é incompatível',()=>assert.equal(svc.classifyLegacy({policy:'x'}).status,'legacy_incompatible'));test('legacy explícito exige revisão',()=>assert.equal(svc.classifyLegacy({domain:'compliance_policy'}).status,'legacy_review_required'));test('feeds são read-only clones',()=>{const rows=svc.obligationsFeed();rows[0].title='x';assert.notEqual(svc.getObligation(o.id).title,'x');});
if(process.argv.includes('--materialized')){const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8');test('bundle contém ValtrenComplianceCore',()=>assert(app.includes('ValtrenComplianceCore')));test('bundle contém state.crmCompliance',()=>assert(app.includes('state.crmCompliance')));test('rota Compliance é canônica',()=>assert(app.includes("if(path==='/crm/juridico/compliance')return crmCompliancePage();")));test('placeholder Compliance não sobrevive',()=>assert(!app.includes("if(path==='/crm/juridico/compliance')return crmArchitecturePlaceholderPage")));test('feeds de obrigações/políticas/ocorrências estão no bundle',()=>{for(const x of ['crmComplianceObligationsFeed','crmCompliancePoliciesFeed','crmComplianceOccurrencesFeed'])assert(app.includes(x));});test('policyVersions está no bundle',()=>assert(app.includes('policyVersions')));test('Contrato canônico permanece',()=>assert(app.includes("if(path==='/crm/juridico/contratos')return crmLegalContractsPage();")));}
console.log(`Compliance tests: ${passed} passed`);
