'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
let passed=0;
function test(name,fn){try{fn();passed++;console.log(`PASS ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}
const browser=fs.readFileSync(path.join(__dirname,'..','web','src','modules','finance','allocations','browser.js'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'..','web','src','modules','finance','allocations','styles.css'),'utf8');
const materializer=fs.readFileSync(path.join(__dirname,'crm_cost_allocations.py'),'utf8');
const core=fs.readFileSync(path.join(__dirname,'..','web','src','modules','finance','allocations','core.js'),'utf8');

test('1 rota principal é Financeiro / Rateios',()=>{assert(materializer.includes("/crm/financeiro/rateios"));assert(browser.includes("label:'Rateios'"));});
test('2 breadcrumb é Financeiro / Rateios',()=>{assert(browser.includes("label:'Financeiro'"));assert(browser.includes("label:'Rateios'"));});
test('3 ação principal é Novo Rateio',()=>{assert(browser.includes('Novo Rateio'));});
test('4 fluxo começa pela seleção da despesa',()=>{assert(browser.includes('Despesa/Transação de origem'));assert(browser.includes('crmCostAllocationSourceOptions'));});
test('5 método Percentual está disponível',()=>{assert(browser.includes("['percentage','Percentual']"));});
test('6 método Valor fixo está disponível',()=>{assert(browser.includes("['fixed','Valor fixo']"));});
test('7 método Divisão igual está disponível',()=>{assert(browser.includes("['equal','Divisão igual']"));});
test('8 método Direcionador está disponível',()=>{assert(browser.includes("['driver','Direcionador']"));});
test('9 linha pode ser adicionada inline',()=>{assert(browser.includes('crm-alloc-line-add'));assert(browser.includes('+ Adicionar destino'));});
test('10 linha pode ser removida inline',()=>{assert(browser.includes('crm-alloc-line-remove'));});
test('11 preview mostra 100%, valor e saldo',()=>{assert(browser.includes('Percentual total'));assert(browser.includes('Valor original'));assert(browser.includes('Saldo não distribuído'));});
test('12 preview reconcilia até o centavo',()=>{assert(browser.includes('Distribuição reconciliada até o centavo.'));});
test('13 workflow Rascunho → Revisão aparece na UI',()=>{assert(browser.includes('Enviar para revisão'));assert(browser.includes('Em revisão'));});
test('14 workflow Aprovação aparece na UI',()=>{assert(browser.includes('Aprovar'));assert(browser.includes('Aprovado'));});
test('15 workflow Postagem aparece na UI',()=>{assert(browser.includes('Postar'));assert(browser.includes('Postado'));});
test('16 Estorno aparece somente como ação de Rateio postado',()=>{assert(browser.includes("if(row.status==='posted')"));assert(browser.includes('Estornar'));});
test('17 busca operacional existe',()=>{assert(browser.includes('crm-alloc-search'));assert(browser.includes('Buscar descrição, conta, categoria, responsável, destino ou referência'));});
test('18 filtro de período existe',()=>{assert(browser.includes('crm-alloc-period'));assert(browser.includes('Personalizado'));});
test('19 filtro de método existe',()=>{assert(browser.includes('crm-alloc-method'));});
test('20 Mais filtros contém conta e categoria',()=>{assert(browser.includes('crm-alloc-account'));assert(browser.includes('crm-alloc-category'));});
test('21 filtros Produto Serviço Unidade Corporativo existem',()=>{['crm-alloc-product','crm-alloc-service','crm-alloc-unit','crm-alloc-corporate'].forEach((x)=>assert(browser.includes(x)));});
test('22 TableView possui colunas operacionais obrigatórias',()=>{['Data','Origem','Descrição','Valor','Método','Destinos','Status','Período','Responsável','Ação'].forEach((x)=>assert(browser.includes(`<th>${x}</th>`)));});
test('23 drawer detalha Resumo e Transação de origem',()=>{assert(browser.includes('<h3>Resumo</h3>'));assert(browser.includes('<h3>Transação de origem</h3>'));});
test('24 drawer contém Memória de cálculo',()=>{assert(browser.includes('<h3>Memória de cálculo</h3>'));});
test('25 drawer contém Status e workflow',()=>{assert(browser.includes('<h3>Status e workflow</h3>'));});
test('26 drawer contém Contabilidade sem painel financeiro paralelo',()=>{assert(browser.includes('<h3>Contabilidade</h3>'));assert(browser.includes('DRE geral continua usando o valor original uma única vez'));});
test('27 drawer contém Histórico',()=>{assert(browser.includes('<h3>Histórico</h3>'));});
test('28 transação de origem possui Ver em Transações',()=>{assert(browser.includes('Ver em Transações'));assert(browser.includes('#/crm/financeiro?focus='));});
test('29 estado vazio é explícito',()=>{assert(browser.includes('Nenhum rateio encontrado.'));assert(browser.includes('custos e despesas compartilhadas'));});
test('30 transação já rateada é identificada',()=>{assert(browser.includes('já rateada'));assert(browser.includes('já possui Rateio postado ativo'));});
test('31 rateio parcial exige opção explícita',()=>{assert(browser.includes('Permitir rateio parcial explicitamente'));assert(browser.includes('allowPartial'));});
test('32 Corporativo não é produto',()=>{assert(browser.includes('Corporativo</option>'));assert(core.includes("destinationType==='corporate'?'':"));});
test('33 Produtos vêm de fonte existente',()=>{assert(browser.includes("crmFinanceProducts"));assert(!browser.includes("Produto A"));});
test('34 Serviços vêm de fonte existente',()=>{assert(browser.includes('state.businessServices'));assert(!browser.includes("Serviço A"));});
test('35 Unidades vêm de fonte existente',()=>{assert(browser.includes('state.businessUnits'));assert(!browser.includes("Unidade A"));});
test('36 nenhum catálogo de destinos é inventado',()=>{assert(!browser.includes('Music OS 360'));assert(!browser.includes('Vivendo da Música'));});
test('37 Rateios não oferece criação de transação',()=>{assert(!browser.includes('createTransaction('));});
test('38 Rateios não oferece Participação',()=>{assert(!browser.includes('Calcular Participação'));assert(!browser.includes('Sócio'));});
test('39 Rateios não oferece Repasse',()=>{assert(!browser.includes('Criar Repasse'));assert(!browser.includes('Pagar participante'));});
test('40 Rateios não oferece regra Societária',()=>{assert(!browser.includes('Societário'));assert(!browser.includes('shareholder'));});
test('41 versão aparece no detalhe/lista',()=>{assert(browser.includes('v${row.version}'));assert(browser.includes('<dt>Versão</dt>'));});
test('42 nova versão aparece só em estados históricos',()=>{assert(browser.includes('Criar nova versão'));assert(browser.includes("if(row.status==='reversed')"));});
test('43 inconsistência da transação é visível',()=>{assert(browser.includes('Rateio necessita revisão'));assert(browser.includes('não é recalculado silenciosamente'));});
test('44 responsividade possui quatro breakpoints',()=>{['1380px','1050px','760px','520px'].forEach((x)=>assert(css.includes(`max-width:${x}`)));});
test('45 mobile refluí linhas de distribuição',()=>{assert(css.includes('@media(max-width:760px)'));assert(css.includes('.crm-alloc-line{grid-template-columns:1fr}'));});
test('46 drawer respeita viewport',()=>{assert(css.includes('width:min(920px,100%)'));assert(css.includes('height:100vh'));});
test('47 modal respeita viewport',()=>{assert(css.includes('max-height:calc(100vh - 28px)'));});
test('48 tabela possui overflow controlado',()=>{assert(css.includes('.crm-alloc-table-wrap{overflow:auto}'));});
test('49 tabela mobile remove informações secundárias antes das essenciais',()=>{assert(css.includes('.crm-alloc-table th:nth-child(3)'));assert(css.includes('.crm-alloc-table th:nth-child(8)'));});
test('50 paginação é limitada pelo domínio a 50',()=>{assert(core.includes('Math.min(50'));assert(browser.includes('crm-alloc-pagination'));});
test('51 editor simples de Transações é convertido em compatibilidade',()=>{assert(materializer.includes('crmFinanceOpenAllocation'));assert(materializer.includes('rateios?source='));});
test('52 Contabilidade recebe somente adapter mínimo',()=>{assert(materializer.includes('dimensionAmount'));assert(materializer.includes('allocation_needs_review'));});
test('53 materializador preserva Transações',()=>{assert(materializer.includes("if(path==='/crm/financeiro')return crmTransactionsPage();"));});
test('54 materializador preserva Contabilidade',()=>{assert(materializer.includes("if(path==='/crm/financeiro/accounting')return crmAccountingPage();"));});
test('55 materializador preserva Notas Fiscais',()=>{assert(materializer.includes("if(path==='/crm/financeiro/notas-fiscais')return crmFiscalDocumentsPage();"));});
test('56 sidebar é somente validado, não reescrito',()=>{assert(materializer.includes('expected_finance'));assert(materializer.includes('Direcionadores'));assert(materializer.includes('Submódulo indevido'));});
test('57 abas principais não viram itens de sidebar',()=>{assert(!materializer.includes("['draft','Rascunhos','#/crm"));assert(!materializer.includes("['criteria'"));});
test('58 ações por status são coerentes',()=>{assert(browser.indexOf("if(row.status==='draft')")>=0);assert(browser.indexOf("if(row.status==='review')")>=0);assert(browser.indexOf("if(row.status==='approved')")>=0);assert(browser.indexOf("if(row.status==='posted')")>=0);assert(browser.indexOf("if(row.status==='reversed')")>=0);});
test('59 somente rascunho expõe exclusão física',()=>{const draft=browser.match(/if\(row\.status==='draft'\).*?;/)?.[0]||'';assert(draft.includes('crm-alloc-delete'));assert(browser.includes('Excluir rascunho'));});
test('60 aprovação e postagem não são simples badges',()=>{assert(browser.includes("service.approve(id)"));assert(browser.includes("service.post(id)"));});

if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');
  const bundleCss=fs.readFileSync(path.join(__dirname,'..','assets','valtren-brand.css'),'utf8');
  test('61 UI final de Rateios está no bundle',()=>{assert(app.includes('function crmCostAllocationsPage()'));assert(app.includes('Novo Rateio'));});
  test('62 breadcrumb publicado é Financeiro / Rateios',()=>{assert(app.includes("{label:'Financeiro',href:'#/crm/financeiro'},{label:'Rateios',href:'#/crm/financeiro/rateios'}"));});
  test('63 rota publicada não é placeholder',()=>{assert(app.includes("if(path==='/crm/financeiro/rateios'){const page=crmCostAllocationsPage()"));assert(!app.includes("if(path==='/crm/financeiro/rateios')return crmArchitecturePlaceholderPage"));});
  test('64 entrada de Transações abre Rateios, não editor paralelo',()=>{assert(app.includes('rateios?source=${encodeURIComponent(id)}&new=1'));assert(!app.includes("crmFinanceModal('Distribuir transação'"));});
  test('65 bundle contém os quatro métodos',()=>{['percentage','fixed','equal','driver'].forEach((x)=>assert(app.includes(x)));});
  test('66 bundle contém workflow completo',()=>{['allocation.sent_to_review','allocation.approved','allocation.posted','allocation.reversed'].forEach((x)=>assert(app.includes(x)));});
  test('67 bundle contém proteção de double counting',()=>{assert(app.includes('A transação já possui Rateio postado ativo'));assert(app.includes('costAllocationProjection'));});
  test('68 bundle mantém DRE geral no valor original',()=>{assert(app.includes("if(!dimension&&!productId&&!serviceId&&!businessUnitId)return roundMoney(tx.amount)"));});
  test('69 bundle possui adapter dimensional para Serviço',()=>{assert(app.includes("type==='service'&&destinationId===serviceId"));});
  test('70 bundle possui adapter dimensional para Unidade',()=>{assert(app.includes("type==='business_unit'&&destinationId===businessUnitId"));});
  test('71 bundle sinaliza Rateio inconsistente na Contabilidade',()=>{assert(app.includes('allocation_needs_review'));});
  test('72 CSS de Rateios está no bundle',()=>{assert(bundleCss.includes('/* VALTREN COST ALLOCATIONS */'));});
  test('73 CSS mobile está no bundle',()=>{assert(bundleCss.includes('@media(max-width:520px)'));});
  test('74 sidebar publicado continua oficial',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);['Transações','Contabilidade','Notas Fiscais','Rateios','Participações','Repasses'].forEach((x)=>assert(sidebar.includes(x)));});
  test('75 nenhum subitem de Rateios foi publicado no sidebar',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);['Direcionadores','Critérios de Rateio','Alocações','Memória de Cálculo'].forEach((x)=>assert(!sidebar.includes(x)));});
}
console.log(`Cost Allocations UI tests: ${passed} passed`);
