const fs=require('fs'),path=require('path'),assert=require('assert');
const core=fs.readFileSync(path.resolve(__dirname,'..','src','modules','business','core.js'),'utf8');
const browser=fs.readFileSync(path.resolve(__dirname,'..','src','modules','business','browser.js'),'utf8');
const css=fs.readFileSync(path.resolve(__dirname,'..','src','modules','business','styles.css'),'utf8');
const materializer=fs.readFileSync(path.resolve(__dirname,'crm_business.py'),'utf8');
const materialize=fs.readFileSync(path.resolve(__dirname,'materialize.py'),'utf8');
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}
const has=(source,...tokens)=>tokens.forEach((token)=>assert(source.includes(token),`missing ${token}`));

test('Produtos possui página própria',()=>has(browser,'function crmBusinessProductsPage()'));
test('Serviços possui página própria',()=>has(browser,'function crmBusinessServicesPage()'));
test('Unidades possui página própria',()=>has(browser,'function crmBusinessUnitsPage()'));
test('breadcrumb Produtos é Negócios Produtos',()=>has(browser,"crmBusinessBreadcrumb('Produtos','#/crm/negocios')"));
test('breadcrumb Serviços é Negócios Serviços',()=>has(browser,"crmBusinessBreadcrumb('Serviços','#/crm/negocios/servicos')"));
test('breadcrumb Unidades é Negócios Unidades de Negócio',()=>has(browser,"crmBusinessBreadcrumb('Unidades de Negócio','#/crm/negocios/unidades')"));
test('Produtos tem busca funcional',()=>has(browser,"data-business-filter=\"search\""));
test('Produtos tem filtro Status',()=>has(browser,'Status'));
test('Produtos tem filtro Categoria',()=>has(browser,'Categoria'));
test('Produtos tem filtro Unidade',()=>has(browser,'Unidade'));
test('Produtos tem Mais filtros',()=>has(browser,'Mais filtros'));
test('Serviços tem busca funcional',()=>has(browser,'crmBusinessServicesPage'));
test('Serviços tem filtro Status',()=>has(browser,'status'));
test('Serviços tem filtro Categoria',()=>has(browser,'category'));
test('Serviços tem filtro Unidade',()=>has(browser,'businessUnitId'));
test('Unidades tem busca funcional',()=>has(browser,'crmBusinessUnitsPage'));
test('Unidades tem filtro Status',()=>has(browser,'status'));
test('Unidades tem filtro Responsável',()=>has(browser,'owner'));
test('TableView Produtos possui colunas obrigatórias',()=>has(browser,'Código','Nome','Categoria','Status'));
test('TableView Serviços possui colunas obrigatórias',()=>has(browser,'Código','Nome','Categoria','Status'));
test('TableView Unidades possui colunas obrigatórias',()=>has(browser,'Código','Nome','Responsável','Status'));
test('Preço ausente é travessão e não zero falso',()=>has(browser,"return '—'"));
test('contagens de Unidade vêm do domínio',()=>has(browser,'relatedProducts','relatedServices'));
test('ação principal de linha é Ver',()=>has(browser,'Ver'));
test('ações secundárias ficam em menu compacto',()=>has(browser,'details'));
test('editor de Produto possui Informações Classificação Modelo Comercial Relacionamentos',()=>has(browser,'Informações','Classificação','Modelo Comercial','Relacionamentos'));
test('editor de Serviço possui Informações e Modelo Comercial',()=>has(browser,'Informações','Modelo Comercial'));
test('editor de Unidade não força hierarquia',()=>assert(!browser.includes('hierarquia obrigatória')));
test('editor explica que não cria operação financeira/jurídica',()=>has(browser,'financeir','juríd'));
test('detalhe possui Visão Geral',()=>has(browser,'Visão Geral'));
test('detalhe de Produto Serviço possui Comercial',()=>has(browser,'Comercial'));
test('detalhe possui Relacionamentos',()=>has(browser,'Relacionamentos'));
test('detalhe possui Histórico',()=>has(browser,'Histórico'));
test('detalhe de Unidade lista Produtos relacionados',()=>has(browser,'Produtos relacionados'));
test('detalhe de Unidade lista Serviços relacionados',()=>has(browser,'Serviços relacionados'));
test('UI não inventa faturamento ou margem',()=>{assert(!browser.includes('R$ 120.000'));assert(!browser.includes('43% do faturamento'));});
test('UI usa referência não resolvida explícita',()=>has(browser,'Referência não resolvida'));
test('feeds read-only existem',()=>has(browser,'crmBusinessProductsFeed','crmBusinessServicesFeed','crmBusinessUnitsFeed'));
test('lookups centralizados existem',()=>has(browser,'crmBusinessService'));
test('resolução central de dimensão existe',()=>has(browser,'crmBusinessResolveDimension'));
test('Corporativo não depende de cadastro de Produto',()=>has(browser,'Corporativo'));
test('demo não é habilitado implicitamente no feed',()=>assert(!browser.includes('includeDemo:true')));
test('referências históricas consultam somente módulos concluídos',()=>has(browser,'reference'));
test('Projetos não foi criado pela UI de Negócios',()=>assert(!browser.includes("#/crm/negocios/projetos")));
test('Sistemas não foi criado como subpágina de Negócios',()=>assert(!browser.includes("#/crm/negocios/sistemas")));
test('nenhum produto real conhecido foi hardcoded',()=>['Music OS 360','Vivendo da Música','Dica de Cria','Visa Fácil'].forEach((x)=>assert(!browser.includes(x)&&!core.includes(x))));
test('responsividade possui breakpoint 1380',()=>has(css,'1380'));
test('responsividade possui breakpoint 1050',()=>has(css,'1050'));
test('responsividade possui breakpoint 760',()=>has(css,'760'));
test('responsividade possui breakpoint 520',()=>has(css,'520'));
test('TableView possui overflow controlado',()=>has(css,'overflow'));
test('drawer respeita viewport',()=>has(css,'vh'));
test('modal respeita viewport',()=>has(css,'vh'));
test('mobile reduz colunas secundárias antes das essenciais',()=>has(css,'@media'));
test('paginação está limitada a 50 no browser',()=>has(browser,'50'));
test('materializador substitui exatamente três placeholders',()=>has(materializer,"/crm/negocios","/crm/negocios/servicos","/crm/negocios/unidades"));
test('materializador valida os três handlers canônicos',()=>has(materializer,'crmBusinessProductsPage','crmBusinessServicesPage','crmBusinessUnitsPage'));
test('materializador preserva owners financeiros e jurídicos',()=>has(materializer,'crmTransactionsPage','crmAccountingPage','crmLegalContractsPage'));
test('materializador valida sidebar sem reescrever',()=>has(materializer,'VALTREN SIDEBAR ARCHITECTURE START','VALTREN SIDEBAR ARCHITECTURE END'));
test('materializador proíbe novos submódulos indevidos',()=>has(materializer,'Submódulo indevido'));
test('materializador proíbe catálogos paralelos',()=>has(materializer,'Catálogo paralelo'));
test('materializador proíbe seeds de produtos reais',()=>has(materializer,'Produto real foi hardcoded'));
test('materializador proíbe responsabilidades financeiras no core',()=>has(materializer,'responsabilidade financeira/jurídica indevida'));
test('materializador contém adapters mínimos de Transações',()=>has(materializer,'crmFinanceProducts','crmFinanceProductLabel'));
test('materializador contém adapters mínimos de Contabilidade',()=>has(materializer,'crmAccountingProducts','crmAccountingServices','crmAccountingUnits'));
test('materializador contém adapters mínimos de Notas Fiscais',()=>has(materializer,'crmFiscalProducts','crmFiscalServices','crmFiscalUnits'));
test('materializador contém adapters mínimos de Rateios',()=>has(materializer,'crmCostAllocationResolveDestination','crmCostAllocationDestinationLabel'));
test('materializador contém adapters mínimos de Contratos',()=>has(materializer,'crmLegalResolveReference','crmLegalProducts','crmLegalServices','crmLegalUnits'));
test('materializador contém adapters mínimos de Participações',()=>has(materializer,'crmParticipationReferenceLabel'));
test('materializador contém adapters mínimos de Repasses',()=>has(materializer,'crmPayoutReferenceLabel'));
test('materializador principal chama Negócios depois de Repasses',()=>{const p=materialize.indexOf('apply_crm_payouts()'),b=materialize.indexOf('apply_crm_business()');assert(p>=0&&b>p);});
test('ordem tardia protege adapters contra overwrite',()=>{const p=materialize.indexOf('apply_crm_payouts()'),b=materialize.indexOf('apply_crm_business()');assert(p>=0&&b>p);has(materializer,'crmFinanceProducts','crmLegalResolveReference','crmPayoutReferenceLabel');});

if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8'),brand=fs.readFileSync(path.resolve(__dirname,'..','assets','valtren-brand.css'),'utf8');
  test('UI final de Produtos está no bundle',()=>has(app,'function crmBusinessProductsPage()','Novo Produto'));
  test('UI final de Serviços está no bundle',()=>has(app,'function crmBusinessServicesPage()','Novo Serviço'));
  test('UI final de Unidades está no bundle',()=>has(app,'function crmBusinessUnitsPage()','Nova Unidade'));
  test('breadcrumbs publicados usam Negócios',()=>has(app,"crmBusinessBreadcrumb('Produtos','#/crm/negocios')","crmBusinessBreadcrumb('Serviços','#/crm/negocios/servicos')","crmBusinessBreadcrumb('Unidades de Negócio','#/crm/negocios/unidades')"));
  test('rotas finais usam owners canônicos',()=>has(app,"if(path==='/crm/negocios')return crmBusinessProductsPage();","if(path==='/crm/negocios/servicos')return crmBusinessServicesPage();","if(path==='/crm/negocios/unidades')return crmBusinessUnitsPage();"));
  test('CSS final de Negócios existe uma vez',()=>assert.equal((brand.match(/\/\* VALTREN BUSINESS CATALOG \*\//g)||[]).length,1));
}
console.log(`Business UI tests: ${passed} passed`);
