'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),Core=require('../web/src/modules/legal/matters/core.js');
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(e){console.error(`FAIL ${name}`);throw e;}}
let n=0;const now=()=>`2026-08-26T10:${String(n++).padStart(2,'0')}:00.000Z`;let seq=0;const idFactory=p=>`${p}_t_${++seq}`;
const parties=new Set(['person:p1','person:p2','organization:o1','organization:o2']),business=new Set(['product:prd1','service:srv1','business_unit:bu1']),contracts=new Set(['ct1']);
const store=Core.createState({now}),svc=Core.createService(store,{now,idFactory,actorProvider:()=> 'u1',partyResolver:(t,id)=>parties.has(`${t}:${id}`)?{id}:null,businessResolver:(t,id)=>business.has(`${t}:${id}`)?{id}:null,contractResolver:id=>contracts.has(id)?{id}:null});
test('state canônico de Assuntos Jurídicos possui coleções separadas',()=>assert.deepEqual(['matters','parties','events','deadlines','actions','authorities','documents','settlements','history'].filter(k=>Array.isArray(store[k])).length,9));
const m=svc.createMatter({title:'Disputa contratual',type:'dispute',category:'Comercial',priority:'high',riskLevel:'critical',responsibleUserId:'u2',contractId:'ct1',productId:'prd1',serviceId:'srv1',businessUnitId:'bu1',estimatedExposure:12500,currency:'BRL'});
test('criar assunto',()=>assert(m));test('ID estável do assunto',()=>assert(m.id.startsWith('matter_t_')));test('número automático do assunto',()=>assert(/^AJ-2026-0001$/.test(m.number)));test('tipo de assunto',()=>assert.equal(m.type,'dispute'));test('status inicial',()=>assert.equal(m.status,'open'));test('prioridade',()=>assert.equal(m.priority,'high'));test('risco',()=>assert.equal(m.riskLevel,'critical'));test('responsável',()=>assert.equal(m.responsibleUserId,'u2'));test('Contrato é somente referência',()=>assert.equal(m.contractId,'ct1'));test('Produto é somente referência',()=>assert.equal(m.productId,'prd1'));test('Serviço é somente referência',()=>assert.equal(m.serviceId,'srv1'));test('Unidade é somente referência',()=>assert.equal(m.businessUnitId,'bu1'));test('exposição estimada é preservada',()=>assert.equal(m.estimatedExposure,12500));
const p1=svc.addParty(m.id,{partyType:'person',partyId:'p1',role:'claimant'}),p2=svc.addParty(m.id,{partyType:'organization',partyId:'o1',role:'counterparty'});
test('Person canônica como parte',()=>assert.equal(p1.partyId,'p1'));test('Organization canônica como contraparte',()=>assert.equal(p2.partyId,'o1'));test('parte inexistente é rejeitada',()=>assert.throws(()=>svc.addParty(m.id,{partyType:'person',partyId:'missing'}),/canônica/));
const d=svc.addDeadline(m.id,{title:'Apresentar resposta',dueAt:'2026-09-20',type:'filing',responsibleUserId:'u2'});test('prazo ligado ao assunto',()=>assert.equal(d.matterId,m.id));test('feed de prazos preparado para Agenda',()=>assert(svc.deadlinesFeed().some(x=>x.id===d.id)));svc.completeDeadline(d.id);test('prazo pode ser concluído',()=>assert.equal(d.status,'completed'));
const ev=svc.addEvent(m.id,{type:'hearing',title:'Audiência',occurredAt:'2026-09-15'});test('evento jurídico ligado ao assunto',()=>assert.equal(ev.type,'hearing'));const action=svc.addAction(m.id,{title:'Revisar defesa',responsibleUserId:'u2'});test('ação jurídica ligada ao assunto',()=>assert.equal(action.matterId,m.id));const authority=svc.addAuthority(m.id,{name:'Órgão competente',reference:'REF-1'});test('autoridade pode ser textual/estruturada sem Organization paralela',()=>assert.equal(authority.name,'Órgão competente'));
const doc=svc.addDocument(m.id,{name:'Notificação.pdf',reference:'doc-ref'});test('documento é metadata/referência',()=>assert.equal(doc.storage,'metadata-only'));
const settlement=svc.addSettlement(m.id,{title:'Acordo registrado',amount:4000,currency:'BRL'});test('acordo é evento jurídico',()=>assert.equal(settlement.matterId,m.id));test('acordo não cria coleção de pagamentos/transações',()=>{assert.equal('transactions' in store,false);assert.equal('payments' in store,false);});test('exposição não cria Transação',()=>assert.equal('financialTransactions' in store,false));
svc.closeMatter(m.id,{notes:'Encerrado'});test('encerramento',()=>assert.equal(m.status,'closed'));test('encerramento registra closedAt',()=>assert(m.closedAt));test('histórico operacional',()=>assert(svc.historyFor('matter',m.id).some(x=>x.action==='closed')));
const demo=svc.createMatter({title:'Demo',isDemo:true});test('demo é excluído do feed real',()=>assert(!svc.feed().some(x=>x.id===demo.id)));test('demo exige includeDemo explícito',()=>assert(svc.feed({includeDemo:true}).some(x=>x.id===demo.id)));
test('tipo inválido é rejeitado',()=>assert.throws(()=>svc.createMatter({title:'X',type:'official_court_status'}),/Tipo inválido/));test('referência de Negócios inexistente é rejeitada',()=>assert.throws(()=>svc.createMatter({title:'X',productId:'missing'}),/Negócios/));test('Contrato inexistente é rejeitado',()=>assert.throws(()=>svc.createMatter({title:'X',contractId:'missing'}),/Contrato/));test('feed é clone read-only',()=>{const rows=svc.feed();if(rows[0])rows[0].title='mutado';assert.notEqual(svc.getMatter(m.id)?.title,'mutado');});test('legacy ambíguo permanece incompatível',()=>assert.equal(svc.classifyLegacy({title:'case'}).status,'legacy_incompatible'));test('legacy explicitamente jurídico exige revisão, não auto-migração',()=>assert.equal(svc.classifyLegacy({domain:'legal_matter'}).status,'legacy_review_required'));test('detalhe agrega domínios do assunto sem duplicar identidade',()=>{const x=svc.matterDetail(m.id);assert(x.parties.length>=2&&x.events.length>=1&&x.documents.length>=1);});
if(process.argv.includes('--materialized')){const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8');test('bundle contém ValtrenLegalMatterCore',()=>assert(app.includes('ValtrenLegalMatterCore')));test('bundle contém state.crmLegalMatters',()=>assert(app.includes('state.crmLegalMatters')));test('rota Assuntos Jurídicos é canônica',()=>assert(app.includes("if(path==='/crm/juridico')return crmLegalMattersPage();")));test('placeholder Assuntos Jurídicos não sobrevive',()=>assert(!app.includes("if(path==='/crm/juridico')return crmArchitecturePlaceholderPage('legal','matters'")));test('feed read-only está materializado',()=>assert(app.includes('function crmLegalMattersFeed')));test('deadlines feed está materializado',()=>assert(app.includes('function crmLegalMatterDeadlinesFeed')));test('Contrato canônico continua presente',()=>assert(app.includes("if(path==='/crm/juridico/contratos')return crmLegalContractsPage();")));test('Negócios continua owner',()=>assert(app.includes('state.crmBusinessCatalog')));test('Pessoas/Organizações continuam owner',()=>assert(app.includes('state.crmCanonicalParties')));}
console.log(`Legal Matters tests: ${passed} passed`);
