'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const browser=fs.readFileSync(path.join(__dirname,'crm_payouts_browser.js'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'crm_payouts.css'),'utf8');
const materializer=fs.readFileSync(path.join(__dirname,'crm_payouts.py'),'utf8');
let passed=0;
function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(error){console.error(`FAIL ${name}: ${error.message}`);throw error;}}
function hasAll(text,items){for(const item of items)assert(text.includes(item),`missing ${item}`);}

test('UI inicializa state.crmPayouts via ValtrenPayoutCore',()=>{hasAll(browser,['state.crmPayouts=ValtrenPayoutCore.ensureState','ValtrenPayoutCore.createService']);});
test('UI consome crmParticipationObligationsFeed',()=>{assert(browser.includes('participationFeed:()=>crmParticipationObligationsFeed()'));});
test('UI usa Participações somente como lookup/read-only',()=>{assert(browser.includes('crmPayoutParticipationLookup'));assert(!browser.includes('createCalculation('));assert(!browser.includes('submitToReview('));});
test('UI consome crmFinanceService sem criar transação',()=>{assert(browser.includes('financeService:()=>crmFinanceService()'));assert(!browser.includes('createTransaction('));});
test('UI usa beneficiário canônico',()=>{assert(browser.includes('partyService:()=>crmCanonicalPartyService()'));assert(browser.includes('crmPayoutPartyName'));});
test('rota interna usa Financeiro Repasses',()=>{assert(browser.includes("#/crm/financeiro/repasses"));});
test('breadcrumb oficial é Financeiro Repasses',()=>{hasAll(browser,["label:'Financeiro',href:'#/crm/financeiro'","label:'Repasses',href:'#/crm/financeiro/repasses'"]);});
test('página não expõe CTA de sincronização redundante',()=>{const start=browser.indexOf('function crmPayoutsPage()'),end=browser.indexOf('function crmPayoutMountOverlay',start),block=browser.slice(start,end);assert(!block.includes('Sincronizar Obrigações'));assert(block.includes(",'',"));});
test('sincronização ocorre de forma idempotente ao carregar serviço/página',()=>{assert((browser.match(/syncObligations\(\)/g)||[]).length>=2);});
test('tabs canônicas existem',()=>{for(const label of ['Todos','Em aberto','Parciais','Quitados','Vencidos','Bloqueados'])assert(browser.includes(label));});
test('TableView possui colunas operacionais',()=>{for(const label of ['Período','Beneficiário','Contrato','Produto/Serviço','Valor devido','Pago','Saldo','Vencimento','Status','Conciliação','Ação'])assert(browser.includes(label));});
test('valores monetários têm classes específicas',()=>{hasAll(browser,['class="money"','class="money paid"','class="money balance"']);});
test('obrigação aberta usa Vincular pagamento',()=>{assert(browser.includes('Vincular pagamento'));});
test('obrigação parcial usa Completar pagamento',()=>{assert(browser.includes('Completar pagamento'));});
test('obrigação quitada usa Ver',()=>{assert(browser.includes('>Ver</button>'));});
test('ações secundárias ficam em menu de linha',()=>{hasAll(browser,['crm-payout-row-menu','<summary aria-label="Mais ações">⋯</summary>']);});
test('cancelamento não aparece como CTA principal',()=>{const start=browser.indexOf('function crmPayoutAction'),end=browser.indexOf('function crmPayoutRowMenu',start),block=browser.slice(start,end);assert(!block.includes('Cancelar'));});
test('busca é funcional e conectada à query',()=>{hasAll(browser,['crm-payout-search','crmPayoutSetQuery({q:event.target.value,page:1})']);});
test('filtros principais incluem período beneficiário status Produto',()=>{hasAll(browser,['crm-payout-period','crm-payout-participant','crm-payout-status','crm-payout-product']);});
test('filtros secundários ficam em Mais filtros',()=>{const start=browser.indexOf('function crmPayoutToolbar'),end=browser.indexOf('function crmPayoutQuery',start),block=browser.slice(start,end);hasAll(block,['<summary>Mais filtros</summary>','crm-payout-contract','crm-payout-service','crm-payout-unit','crm-payout-due','crm-payout-recon']);});
test('filtros Serviço e Unidade não criam catálogo paralelo',()=>{assert(browser.includes('crmPayoutServices()'));assert(browser.includes('crmPayoutUnits()'));});
test('resumo agrupa valores por moeda',()=>{assert(browser.includes('summaryByCurrency()'));assert(browser.includes('${esc(g.currency)}'));});
test('UI não assume BRL para múltiplas moedas no resumo',()=>{const start=browser.indexOf('function crmPayoutSummary'),end=browser.indexOf('function crmPayoutAction',start),block=browser.slice(start,end);assert(!block.includes("crmPayoutMoney(g.openBalance,'BRL')"));});
test('vincular pagamento mostra apenas transações sugeridas, sem automatch',()=>{hasAll(browser,['suggestTransactions(obligationId,12)','A correspondência é apenas sugerida','A vinculação só ocorre após sua confirmação']);});
test('modal permite valor parcial explícito',()=>{hasAll(browser,['name="amount"','step="0.01"','max="${esc(row.openBalance)}"']);});
test('modal sem sugestão aponta para Transações',()=>{hasAll(browser,['Nenhuma transação elegível encontrada.','Ver Transações','crm-payout-go-transactions']);});
test('detalhe possui Resumo',()=>{assert(browser.includes('<h3>Resumo</h3>'));});
test('detalhe possui Origem da obrigação',()=>{assert(browser.includes('Origem da obrigação'));});
test('detalhe possui Beneficiário',()=>{assert(browser.includes('<h3>Beneficiário</h3>'));});
test('detalhe possui Pagamentos e Transações',()=>{assert(browser.includes('<h3>Pagamentos e Transações</h3>'));});
test('detalhe possui Histórico',()=>{assert(browser.includes('<h3>Histórico</h3>'));});
test('detalhe mostra Participação Contrato Versão Regra Período Valor aprovado',()=>{for(const label of ['Participação</dt>','Contrato</dt>','Versão</dt>','Regra</dt>','Período</dt>','Valor aprovado</dt>'])assert(browser.includes(label));});
test('detalhe oferece Ver Participação',()=>{hasAll(browser,['Ver Participação','crm-payout-view-participation','crmParticipationOpenDetail']);});
test('detalhe oferece Ver Contrato',()=>{hasAll(browser,['Ver Contrato','crm-payout-view-contract','crmLegalContractDetail']);});
test('pagamentos oferecem Ver em Transações sem editor duplicado',()=>{hasAll(browser,['Ver em Transações','crm-payout-view-transaction','crmFinanceOpenDetail']);assert(!browser.includes('crmFinanceOpenTransactionModal'));});
test('pagamentos oferecem Conciliar e Desconciliar',()=>{hasAll(browser,['crm-payout-reconcile','crm-payout-unreconcile','Conciliar','Desconciliar']);});
test('desvincular pagamento é ação secundária destrutiva',()=>{hasAll(browser,['crm-payout-unlink','class="danger"']);});
test('UI não cadastra dados bancários paralelos',()=>{const lower=browser.toLowerCase();for(const token of ['chave pix','agência bancária','conta bancária do beneficiário','payoutbeneficiaries','payeesdatabase'])assert(!lower.includes(token));});
test('UI não possui status de pagamento dentro de Participações',()=>{assert(!browser.includes('crm-part-paid'));});
test('estado vazio não inventa dados',()=>{hasAll(browser,['Nenhum repasse pendente.','As Participações aprovadas disponíveis para liquidação aparecerão aqui.']);});
test('paginação é compacta',()=>{hasAll(browser,['crm-payout-pagination','data-action="crm-payout-page"']);});
test('CSS possui breakpoint 1380',()=>{assert(css.includes('@media(max-width:1380px)'));});
test('CSS possui breakpoint 1050',()=>{assert(css.includes('@media(max-width:1050px)'));});
test('CSS possui breakpoint 760',()=>{assert(css.includes('@media(max-width:760px)'));});
test('CSS possui breakpoint 520',()=>{assert(css.includes('@media(max-width:520px)'));});
test('TableView possui overflow controlado',()=>{assert(css.includes('.crm-payout-table-wrap{width:100%;overflow:auto}'));});
test('drawer respeita viewport',()=>{hasAll(css,['width:min(920px,100%)','height:100vh','overflow:auto']);});
test('modal respeita viewport',()=>{hasAll(css,['max-height:calc(100vh - 32px)','width:min(720px,calc(100vw - 32px))']);});
test('números monetários usam tabular-nums',()=>{assert(css.includes('font-variant-numeric:tabular-nums'));});
test('status e conciliação usam componentes separados',()=>{hasAll(css,['.crm-payout-status','.crm-payout-recon']);});
test('mobile preserva beneficiário, valores, status e ação',()=>{const media=css.slice(css.indexOf('@media(max-width:760px)'));assert(media.includes('nth-child(1)'));assert(media.includes('nth-child(3)'));assert(!media.includes('nth-child(2),.crm-payout-table td:nth-child(2)'));assert(!media.includes('nth-child(6),.crm-payout-table td:nth-child(6)'));assert(!media.includes('nth-child(7),.crm-payout-table td:nth-child(7)'));assert(!media.includes('nth-child(9),.crm-payout-table td:nth-child(9)'));assert(!media.includes('nth-child(11),.crm-payout-table td:nth-child(11)'));});
test('materializador substitui somente placeholder de Repasses',()=>{assert(materializer.includes("route_old = \"if(path==='/crm/financeiro/repasses')return crmArchitecturePlaceholderPage('accounting','repasses','Repasses');\""));assert(materializer.includes("route_new = \"if(path==='/crm/financeiro/repasses')return crmPayoutsPage();\""));});
test('materializador é idempotente por rota e bloco',()=>{hasAll(materializer,['old_count == 1 and new_count == 0','old_count == 0 and new_count == 1','VALTREN PAYOUTS START']);});
test('materializador preserva owners financeiros anteriores',()=>{for(const token of ['crmTransactionsPage();','crmAccountingPage();','crmFiscalDocumentsPage();','crmCostAllocationsPage();','crmEconomicParticipationsPage();'])assert(materializer.includes(token));});
test('materializador proíbe criação de Transação/Participação',()=>{hasAll(materializer,['createTransaction(','createCalculation(']);});
test('materializador proíbe percentuais concorrentes e Societário',()=>{hasAll(materializer,['manualParticipationRule','partnerPercentage','shareholderPercentage','equityPercentage','ownershipPercentage']);});
test('materializador valida sidebar sem reescrever',()=>{assert(materializer.includes('sidebar = app[sidebar_start:sidebar_end]'));assert(!materializer.includes('app = app.replace(sidebar'));});

if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8');
  const brand=fs.readFileSync(path.resolve(__dirname,'..','assets','valtren-brand.css'),'utf8');
  test('UI final de Repasses está no bundle',()=>{hasAll(app,['function crmPayoutsPage()','function crmPayoutPaymentModal','function crmPayoutOpenDetail']);});
  test('bloco materializado de Repasses é único',()=>{assert.equal((app.match(/VALTREN PAYOUTS START/g)||[]).length,1);assert.equal((app.match(/if\(path==='\/crm\/financeiro\/repasses'\)return crmPayoutsPage\(\);/g)||[]).length,1);});
  test('rota publicada de Repasses não é placeholder',()=>{assert(app.includes("if(path==='/crm/financeiro/repasses')return crmPayoutsPage();"));assert(!app.includes("if(path==='/crm/financeiro/repasses')return crmArchitecturePlaceholderPage"));});
  test('rota publicada de Participações continua canônica',()=>{assert(app.includes("if(path==='/crm/financeiro/participacoes')return crmEconomicParticipationsPage();"));});
  test('breadcrumb publicado usa Financeiro Repasses',()=>{hasAll(app,["label:'Financeiro',href:'#/crm/financeiro'","label:'Repasses',href:'#/crm/financeiro/repasses'"]);});
  test('bundle contém obrigação e pagamento separados',()=>{hasAll(app,['obligations:[]','payments:[]','transactionLinks:[]']);});
  test('bundle contém sync idempotente por participationCalculationId',()=>{hasAll(app,['function syncObligations','participationCalculationId','data.obligations.find']);});
  test('bundle contém pagamento parcial e saldo derivado',()=>{hasAll(app,['paidCents(','openBalance','status===\'partial\'']);});
  test('bundle contém reversões e efeito líquido',()=>{hasAll(app,['REVERSAL_NATURES','relatedTransactionId','paymentEffectiveCents']);});
  test('bundle contém conciliação separada',()=>{hasAll(app,['unreconciled','partially_reconciled','reconciled','reconcilePayment','unreconcilePayment']);});
  test('bundle contém tratamento de Participação superseded',()=>{hasAll(app,['source_superseded_with_payments','obligation.participation_superseded']);});
  test('bundle usa feed de Participações read-only',()=>{hasAll(app,['crmParticipationObligationsFeed','participationFeed:()=>crmParticipationObligationsFeed()']);});
  test('bundle não cria Transação em Repasses',()=>{const start=app.indexOf('// VALTREN PAYOUTS START'),end=app.indexOf('// VALTREN PAYOUTS END',start),block=app.slice(start,end);assert(!block.includes('createTransaction('));});
  test('bundle não recalcula Participação',()=>{const start=app.indexOf('// VALTREN PAYOUTS START'),end=app.indexOf('// VALTREN PAYOUTS END',start),block=app.slice(start,end);for(const token of ['createCalculation(','previewEligible(','submitToReview('])assert(!block.includes(token));});
  test('CSS de Repasses foi materializado',()=>{assert(brand.includes('/* VALTREN PAYOUTS */'));assert(brand.includes('@media(max-width:520px)'));});
  test('sidebar Financeiro preserva seis itens oficiais',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);hasAll(sidebar,['Transações','Contabilidade','Notas Fiscais','Rateios','Participações','Repasses']);for(const bad of ['Obrigações','Pagamentos','Conciliações','Beneficiários'])assert(!sidebar.includes(bad));});
  test('Configurações preserva seis abas atuais',()=>{const start=app.indexOf('function crmCanonicalSettingsPage()'),end=app.indexOf('function crmCanonicalProfilePage()',start),settings=app.slice(start,end);for(const item of ["['empresa','Empresa']","['notificacoes','Notificações']","['seguranca','Segurança']","['integracoes','Integrações']","['auditoria','Auditoria']","['usuarios','Usuários']"])assert(settings.includes(item));assert(!settings.includes("['billing','Billing']"));});
  test('Administração preserva dois itens atuais',()=>{const start=app.lastIndexOf('const administration=['),end=app.indexOf('];',start),admin=app.slice(start,end);hasAll(admin,["['structure','Estrutura Organizacional','#/crm/administracao']","['assets','Patrimônio e Licenças','#/crm/administracao/patrimonio-licencas']"]);});
}
console.log(`Payouts UI tests: ${passed} passed`);
