const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const materialized=process.argv.includes('--materialized');
const fail=(m)=>{throw new Error(m)};
const must=(c,m)=>{if(!c)fail(m)};
const read=(name)=>fs.readFileSync(path.join(__dirname,name),'utf8');
const owner=read('crm_sidebar_architecture.py');
const relationships=read('crm_relationships_module.py');
const fidelity=read('crm_reference_fidelity_fix.js.part01')+read('crm_reference_fidelity_fix.js.part02')+read('crm_reference_fidelity_fix.js.part03')+read('crm_reference_fidelity_fix.js.part04');
const definitive=read('crm_definitive_architecture.py');
const reference=read('crm_reference_modules.py');
const materialize=read('materialize.py');
const header=read('crm_global_header.py');
const review=read('crm_product_system_review.py');
const ownsSidebar=(source)=>/^[ \t]*function[ \t]+crmRelSidebar[ \t]*[(]/m.test(source);
const ownerPayloadMatch=owner.match(/JS_BLOCK = r'''([^]*?)'''\n\nCSS_PATCH/);
must(ownerPayloadMatch,'sidebar owner payload must be statically identifiable');
const ownerPayload=ownerPayloadMatch[1];
must(owner.includes('VALTREN SIDEBAR ARCHITECTURE START'),'sidebar owner start marker missing');
must(owner.includes('VALTREN SIDEBAR ARCHITECTURE END'),'sidebar owner end marker missing');
must(owner.includes("function crmRelSidebar(active='relationships',sub='')"),'sidebar owner declaration missing');
must(!ownsSidebar(relationships),'relationships still owns sidebar');
must(!ownsSidebar(fidelity),'fidelity still owns sidebar');
must(!ownsSidebar(definitive),'definitive architecture still owns sidebar');
must(!reference.includes('crm_reference_sidebar.txt'),'reference modules still rewrites sidebar');
must(materialize.includes('from crm_sidebar_architecture import apply_crm_sidebar_architecture'),'materialize missing sidebar owner import');
must(materialize.includes('apply_crm_sidebar_architecture()'),'materialize missing sidebar owner call');
must(ownerPayload.includes("nav('#/crm/marketing','Marketing'"),'Marketing must remain first-level');
must(ownerPayload.includes("nav('#/crm/relatorios','Relatórios'"),'Reports must remain');
['ValtrenChat','MusicChat',"nav('#/crm/rh'",'Administração'].forEach((token)=>must(!ownerPayload.includes(token),`sidebar payload still contains removed module: ${token}`));
must(header.includes('crm-sidebar-toggle'),'Header missing mobile navigation toggle');
must(header.includes('@media(max-width:980px){.crm-account-copy{display:none}'),'Header missing tablet Account Menu compaction');
must(!review.includes('.crm-sidebar{position:'),'global review still positions Sidebar');
must(!review.includes('.crm-account-menu>summary'),'global review still styles Account Menu');
if(materialized){
 const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
 const css=fs.readFileSync(path.join(root,'assets','valtren-brand.css'),'utf8');
 const decl=(app.match(/\bfunction\s+crmRelSidebar\s*\(/g)||[]).length;
 must(decl===1,`crmRelSidebar declaration count must be 1, got ${decl}`);
 must((app.match(/VALTREN SIDEBAR ARCHITECTURE START/g)||[]).length===1,'sidebar start marker count mismatch');
 must((app.match(/VALTREN SIDEBAR ARCHITECTURE END/g)||[]).length===1,'sidebar end marker count mismatch');
 const s=app.indexOf('VALTREN SIDEBAR ARCHITECTURE START');
 const e=app.indexOf('VALTREN SIDEBAR ARCHITECTURE END',s);
 const block=app.slice(s,e);
 ['ValtrenChat','MusicChat','>RH<','Administração'].forEach((token)=>must(!block.includes(token),`removed module leaked into materialized sidebar: ${token}`));
 ['Marketing','Relatórios','Configurações','Negócios','Jurídico','Financeiro'].forEach((token)=>must(block.includes(token),`required sidebar module missing: ${token}`));
 must(app.includes("if(path==='/crm/valtrenchat'||path==='/crm/musicchat')return crmLegacyRoute('#/crm/configuracoes?tab=integracoes',crmCanonicalSettingsPage);"),'ValtrenChat legacy route missing integration redirect');
 must(app.includes("if(path==='/crm/rh')return crmArchitecturePlaceholderPage('','hr','RH'"),'RH compatibility route missing honest placeholder');
 must(app.includes("if(path.startsWith('/crm/marketing'))return crmMarketingUnavailablePage();"),'Marketing route must use unavailable/non-simulated workspace');
 must(app.includes("if(path==='/crm/administracao'||path==='/crm/administracao/patrimonio-licencas')return crmArchitecturePlaceholderPage('','admin','Administração'"),'Administration compatibility route missing honest placeholder');
 must(css.includes('/* VALTREN SIDEBAR ARCHITECTURE */'),'sidebar CSS owner missing');
 must(css.includes('transform:translateX(-104%)'),'mobile drawer closed state missing');
 must(css.includes('.crm-sidebar.is-open{transform:translateX(0)}'),'mobile drawer open state missing');
 must(css.includes('html.crm-sidebar-lock,body.crm-sidebar-lock{overflow:hidden}'),'mobile body lock missing');
}
console.log(`sidebar-architecture: PASS${materialized?' (materialized)':''}`);
