'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),Core=require('./crm_intellectual_property_core.js');
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(e){console.error(`FAIL ${name}`);throw e;}}
let t=0;const now=()=>`2026-08-26T12:${String(t++).padStart(2,'0')}:00.000Z`;let seq=0;const idFactory=p=>`${p}_t_${++seq}`;const parties=new Set(['person:p1','organization:o1','organization:o2']),business=new Set(['product:prd1','service:srv1','business_unit:bu1']),contracts=new Set(['ct1']);
const store=Core.createState({now}),svc=Core.createService(store,{now,idFactory,actorProvider:()=> 'u1',partyResolver:(k,id)=>parties.has(`${k}:${id}`)?{id}:null,businessResolver:(k,id)=>business.has(`${k}:${id}`)?{id}:null,contractResolver:id=>contracts.has(id)?{id}:null});
test('state canônico de PI possui coleções separadas',()=>assert.equal(['assets','registrations','owners','licenses','deadlines','documents','history'].filter(k=>Array.isArray(store[k])).length,7));test('nenhum ativo fictício nasce automaticamente',()=>assert.equal(store.assets.length,0));
const a=svc.createAsset({name:'Marca Alfa',type:'trademark',category:'Marca',ownerPartyType:'organization',ownerPartyId:'o1',jurisdiction:'BR',applicationNumber:'APP-1',filingDate:'2026-01-15',expirationDate:'2036-01-15',renewalDate:'2035-07-15',productId:'prd1',serviceId:'srv1',businessUnitId:'bu1',responsibleUserId:'u2'});
test('criar ativo de PI',()=>assert(a));test('ID estável de PI',()=>assert(a.id.startsWith('ip_t_')));test('código automático de PI',()=>assert.equal(a.code,'PI-0001'));test('tipo trademark',()=>assert.equal(a.type,'trademark'));test('status padrão draft',()=>assert.equal(a.status,'draft'));test('titular Organization canônica',()=>assert.equal(a.ownerPartyId,'o1'));test('pedido preservado',()=>assert.equal(a.applicationNumber,'APP-1'));test('jurisdição preservada',()=>assert.equal(a.jurisdiction,'BR'));test('filingDate preservada',()=>assert.equal(a.filingDate,'2026-01-15'));test('expirationDate preservada',()=>assert.equal(a.expirationDate,'2036-01-15'));test('renewalDate preservada',()=>assert.equal(a.renewalDate,'2035-07-15'));test('Produto é referência canônica',()=>assert.equal(a.productId,'prd1'));test('Serviço é referência canônica',()=>assert.equal(a.serviceId,'srv1'));test('Unidade é referência canônica',()=>assert.equal(a.businessUnitId,'bu1'));
const software=svc.createAsset({name:'Software Beta',type:'software',ownerPartyType:'person',ownerPartyId:'p1'});test('titular Person canônica',()=>assert.equal(software.ownerPartyId,'p1'));test('tipo software',()=>assert.equal(software.type,'software'));
test('registered sem número de registro é bloqueado',()=>assert.throws(()=>svc.createAsset({name:'Registro falso',status:'registered'}),/número de registro/));const reg=svc.addRegistration(a.id,{applicationNumber:'APP-1',registrationNumber:'REG-1',status:'registered',registrationDate:'2027-04-01',evidenceReference:'evidence-1'});test('registro comprovável pode ser adicionado',()=>assert.equal(reg.registrationNumber,'REG-1'));test('status do ativo acompanha registro explícito',()=>assert.equal(a.status,'registered'));
const owner2=svc.addOwner(a.id,{partyType:'organization',partyId:'o2',role:'co_owner'});test('titularidade adicional usa Organization canônica',()=>assert.equal(owner2.partyId,'o2'));const lic=svc.addLicense(a.id,{contractId:'ct1',licenseePartyType:'organization',licenseePartyId:'o2',effectiveFrom:'2027-01-01'});test('licença jurídica referencia Contrato',()=>assert.equal(lic.contractId,'ct1'));test('Contrato continua owner das condições',()=>assert.equal(lic.termsOwner,'contract'));test('licença de PI não cria licença operacional',()=>assert.equal('softwareLicenses' in store,false));
const d=svc.addDeadline(a.id,{title:'Renovar marca',dueAt:'2035-07-15',type:'renewal'});test('prazo de PI',()=>assert.equal(d.assetId,a.id));test('feed de deadlines prepara Agenda futura',()=>assert(svc.deadlinesFeed().some(x=>x.assetId===a.id)));const doc=svc.addDocument(a.id,{name:'Comprovante',reference:'doc-1'});test('documento é metadata/referência',()=>assert.equal(doc.storage,'metadata-only'));test('histórico de PI',()=>assert(svc.historyFor(a.id).length>0));
const demo=svc.createAsset({name:'Demo PI',isDemo:true});test('demo excluído do feed real',()=>assert(!svc.feed().some(x=>x.id===demo.id)));test('includeDemo explícito',()=>assert(svc.feed({includeDemo:true}).some(x=>x.id===demo.id)));test('titular inexistente é rejeitado',()=>assert.throws(()=>svc.createAsset({name:'X',ownerPartyType:'person',ownerPartyId:'missing'}),/Titular canônico/));test('Negócios inexistente é rejeitado',()=>assert.throws(()=>svc.createAsset({name:'X',productId:'missing'}),/Negócios/));test('Contrato inexistente é rejeitado em licença',()=>assert.throws(()=>svc.addLicense(a.id,{contractId:'missing'}),/Contrato/));test('feed é clone read-only',()=>{const rows=svc.feed();rows[0].name='x';assert.notEqual(svc.getAsset(a.id).name,'x');});test('legacy ambíguo é incompatível',()=>assert.equal(svc.classifyLegacy({brand:'x'}).status,'legacy_incompatible'));test('legacy explicitamente PI exige revisão',()=>assert.equal(svc.classifyLegacy({domain:'intellectual_property'}).status,'legacy_review_required'));test('PI não contém transações financeiras',()=>assert.equal('transactions' in store,false));test('PI não contém licenças administrativas/operacionais',()=>assert.equal('operationalLicenses' in store,false));
if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8');
  test('bundle contém ValtrenIntellectualPropertyCore',()=>assert(app.includes('ValtrenIntellectualPropertyCore')));
  test('bundle contém state.crmIntellectualProperty',()=>assert(app.includes('state.crmIntellectualProperty')));
  test('rota PI é canônica',()=>assert(app.includes("if(path==='/crm/juridico/propriedade-intelectual')return crmIntellectualPropertyPage();")));
  test('placeholder PI não sobrevive',()=>assert(!app.includes("if(path==='/crm/juridico/propriedade-intelectual')return crmArchitecturePlaceholderPage")));
  test('feed PI está no bundle',()=>assert(app.includes('function crmIntellectualPropertyFeed')));
  test('deadline feed PI está no bundle',()=>assert(app.includes('function crmIntellectualPropertyDeadlinesFeed')));
  test('relação PI x Contrato permanece referencial',()=>assert(app.includes("termsOwner:'contract'")));
  test('Administração permanece com Patrimônio e Licenças',()=>assert(app.includes('Patrimônio e Licenças')));
}
console.log(`Intellectual Property tests: ${passed} passed`);
