'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const Core=require('../web/src/modules/finance/payouts/core.js');
let passed=0;
function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(error){console.error(`FAIL ${name}: ${error.message}`);throw error;}}
const eq=(a,b)=>assert.deepStrictEqual(a,b);
const close=(a,b)=>assert(Math.abs(Number(a)-Number(b))<0.005,`${a} != ${b}`);
function makeEnv(options={}){
  let seq=0;const now=()=>options.now||'2026-08-25T12:00:00.000Z',idFactory=(p)=>`${p}_${++seq}`;
  const participants=(options.participations||[{id:'part1',workflowStatus:'approved',consistencyStatus:'consistent',isDemo:false,contractId:'ctr1',contractVersionId:'cv1',economicRuleId:'rule1',participantPartyType:'person',participantPartyId:'p1',periodStart:'2026-08-01',periodEnd:'2026-08-31',currency:'BRL',participationAmount:10000,productId:'prod1',serviceId:'',businessUnitId:'',approvedAt:'2026-08-20T10:00:00Z',sourceSnapshotHash:'src1',metadata:{dueDate:'2026-09-10'}}]).map(x=>JSON.parse(JSON.stringify(x)));
  const parties={people:[{id:'p1',fullName:'João Silva'},{id:'p2',fullName:'Maria Souza'}],organizations:[{id:'o1',legalName:'Empresa ABC'}]};
  const partyService={data:parties,getEntity(type,id){return (type==='person'?parties.people:parties.organizations).find(x=>x.id===id)||null;},documentFor(type,id){return {value:type==='person'?'111.444.777-35':'11.222.333/0001-81'};}};
  const accounts=[{id:'acc1',name:'Banco Principal'},{id:'acc2',name:'Banco Secundário'}];
  const transactions=(options.transactions||[]).map(x=>({financialAccountId:'acc1',status:'posted',direction:'outflow',financialNature:'expense',amount:10000,currency:'BRL',transactionDate:'2026-08-25',originalDescription:'PAGAMENTO JOAO SILVA',counterpartyType:'person',counterpartyId:'p1',isDemo:false,reconciliationStatus:'unreconciled',...JSON.parse(JSON.stringify(x))}));
  const matches=[];
  const finance={data:{transactions,matches,accounts},getTransaction(id){return transactions.find(x=>x.id===id)||null;},getAccount(id){return accounts.find(x=>x.id===id)||null;},query(filters={}){let rows=transactions.slice();if(!filters.includeDemo)rows=rows.filter(x=>!x.isDemo);if(filters.status)rows=rows.filter(x=>x.status===filters.status);if(filters.direction)rows=rows.filter(x=>x.direction===filters.direction);if(filters.limit===0)return {rows,total:rows.length};const limit=filters.limit||50;return {rows:rows.slice(0,limit),total:rows.length};},addMatch(id,input){let m=matches.find(x=>x.transactionId===id&&x.targetType===input.targetType&&x.targetId===input.targetId&&x.status==='active');if(m)return m;m={id:`match_${matches.length+1}`,transactionId:id,targetType:input.targetType,targetId:input.targetId,amount:input.amount,status:'active'};matches.push(m);const tx=this.getTransaction(id);tx.reconciliationStatus='matched';return m;},removeMatch(id){const m=matches.find(x=>x.id===id&&x.status==='active');if(!m)return false;m.status='inactive';const tx=this.getTransaction(m.transactionId);if(tx)tx.reconciliationStatus='unreconciled';return true;},reconcile(id){const tx=this.getTransaction(id);if(!tx||tx.status!=='posted')throw new Error('invalid reconcile');tx.reconciliationStatus='reconciled';return tx;},unreconcile(id){const tx=this.getTransaction(id);if(!tx)throw new Error('invalid unreconcile');tx.reconciliationStatus=matches.some(x=>x.transactionId===id&&x.status==='active')?'matched':'unreconciled';return tx;}};
  const feed=()=>participants.filter(x=>x.workflowStatus==='approved'&&x.consistencyStatus==='consistent'&&!x.isDemo).map(x=>({participationCalculationId:x.id,contractId:x.contractId,contractVersionId:x.contractVersionId,economicRuleId:x.economicRuleId,participantPartyType:x.participantPartyType,participantPartyId:x.participantPartyId,periodStart:x.periodStart,periodEnd:x.periodEnd,currency:x.currency,amountDue:x.participationAmount,productId:x.productId,serviceId:x.serviceId,businessUnitId:x.businessUnitId,approvedAt:x.approvedAt,dueDate:x.metadata?.dueDate||null,sourceSnapshotHash:x.sourceSnapshotHash}));
  const state=Core.createState({now});const service=Core.createService(state,{now,idFactory,actorProvider:()=> 'u1',participationFeed:feed,participationLookup:(id)=>participants.find(x=>x.id===id)||null,financeService:()=>finance,partyService:()=>partyService});
  return {state,service,participants,finance,partyService,transactions,addTx(input){const tx={id:`tx${transactions.length+1}`,financialAccountId:'acc1',status:'posted',direction:'outflow',financialNature:'expense',amount:10000,currency:'BRL',transactionDate:'2026-08-25',originalDescription:'PAGAMENTO JOAO SILVA',counterpartyType:'person',counterpartyId:'p1',isDemo:false,reconciliationStatus:'unreconciled',...input};transactions.push(tx);return tx;}};
}
function syncOne(e){e.service.syncObligations();eq(e.state.obligations.length,1);return e.service.getObligation(e.state.obligations[0].id);}

// Canonical obligations.
test('state canônico possui coleções próprias de Repasses',()=>{const s=Core.createState({now:()=> 'x'});for(const k of ['obligations','payments','transactionLinks','reconciliation','history','sourceSnapshots','legacyBindings'])assert(Array.isArray(s[k]));});
test('Participação approved gera obrigação elegível',()=>{const e=makeEnv();const r=e.service.syncObligations();eq(r.created,1);eq(e.state.obligations.length,1);});
test('Participação draft não gera obrigação',()=>{const e=makeEnv({participations:[{id:'d',workflowStatus:'draft',consistencyStatus:'consistent',participantPartyType:'person',participantPartyId:'p1'}]});e.service.syncObligations();eq(e.state.obligations.length,0);});
test('Participação review não gera obrigação',()=>{const e=makeEnv({participations:[{id:'r',workflowStatus:'review',consistencyStatus:'consistent',participantPartyType:'person',participantPartyId:'p1'}]});e.service.syncObligations();eq(e.state.obligations.length,0);});
test('Participação rejected não gera obrigação',()=>{const e=makeEnv({participations:[{id:'r',workflowStatus:'rejected',consistencyStatus:'consistent',participantPartyType:'person',participantPartyId:'p1'}]});e.service.syncObligations();eq(e.state.obligations.length,0);});
test('Participação superseded não gera obrigação nova',()=>{const e=makeEnv({participations:[{id:'s',workflowStatus:'superseded',consistencyStatus:'consistent',participantPartyType:'person',participantPartyId:'p1'}]});e.service.syncObligations();eq(e.state.obligations.length,0);});
test('Participação demo não gera obrigação',()=>{const e=makeEnv();e.participants[0].isDemo=true;e.service.syncObligations();eq(e.state.obligations.length,0);});
test('Participação inconsistente não gera obrigação',()=>{const e=makeEnv();e.participants[0].consistencyStatus='source_changed';e.service.syncObligations();eq(e.state.obligations.length,0);});
test('sincronização é idempotente',()=>{const e=makeEnv();e.service.syncObligations();e.service.syncObligations();eq(e.state.obligations.length,1);eq(e.state.sourceSnapshots.length,1);});
test('mesma Participation não duplica obrigação',()=>{const e=makeEnv();for(let i=0;i<5;i++)e.service.syncObligations();eq(e.state.obligations.filter(x=>x.participationCalculationId==='part1').length,1);});
test('obrigação preserva participante canônico',()=>{const e=makeEnv(),o=syncOne(e);eq(o.participantPartyType,'person');eq(o.participantPartyId,'p1');eq(o.beneficiarySnapshot.name,'João Silva');});
test('obrigação preserva contrato versão e regra',()=>{const e=makeEnv(),o=syncOne(e);eq(o.contractId,'ctr1');eq(o.contractVersionId,'cv1');eq(o.economicRuleId,'rule1');});
test('obrigação preserva período',()=>{const e=makeEnv(),o=syncOne(e);eq(o.periodStart,'2026-08-01');eq(o.periodEnd,'2026-08-31');});
test('obrigação preserva moeda',()=>{const e=makeEnv(),o=syncOne(e);eq(o.currency,'BRL');});
test('obrigação preserva amountDue',()=>{const e=makeEnv(),o=syncOne(e);close(o.amountDue,10000);});
test('dueDate determinística é preservada',()=>{const e=makeEnv(),o=syncOne(e);eq(o.dueDate,'2026-09-10');});
test('dueDate null permanece null',()=>{const e=makeEnv();e.participants[0].metadata={};const o=syncOne(e);eq(o.dueDate,null);});
test('amountPaid e openBalance são derivados e não fonte manual',()=>{const e=makeEnv(),o=syncOne(e);assert(!Object.prototype.hasOwnProperty.call(e.state.obligations[0],'amountPaid'));assert(!Object.prototype.hasOwnProperty.call(e.state.obligations[0],'openBalance'));close(o.amountPaid,0);close(o.openBalance,10000);});
test('feed de Participações é consumido read-only',()=>{const e=makeEnv(),before=JSON.stringify(e.participants);e.service.syncObligations();eq(JSON.stringify(e.participants),before);});
test('snapshot mínimo da Participação é preservado',()=>{const e=makeEnv();const o=syncOne(e),s=e.state.sourceSnapshots.find(x=>x.obligationId===o.id);eq(s.snapshot.participationCalculationId,'part1');eq(s.snapshot.sourceSnapshotHash,'src1');assert(s.snapshotHash.startsWith('fnv1a32:'));});
test('alteração inesperada da fonte não reescreve amountDue',()=>{const e=makeEnv();const o=syncOne(e);e.participants[0].participationAmount=8000;e.participants[0].sourceSnapshotHash='src2';e.service.syncObligations();const after=e.service.getObligation(o.id);close(after.amountDue,10000);eq(after.consistencyStatus,'source_changed');});

// Payment linking.
test('vincular transação lançada de saída cria pagamento sem criar transação',()=>{const e=makeEnv({transactions:[{id:'tx1'}]});const o=syncOne(e),before=e.transactions.length,p=e.service.linkPayment(o.id,'tx1');eq(e.transactions.length,before);eq(p.financialTransactionId,'tx1');eq(e.state.payments.length,1);});
test('link cria match de Transações e não lançamento duplicado',()=>{const e=makeEnv({transactions:[{id:'tx1'}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');eq(e.finance.data.matches.length,1);eq(e.finance.data.matches[0].targetType,'payout');eq(e.finance.data.matches[0].targetId,o.id);});
test('repetir link da mesma transação na mesma obrigação é idempotente',()=>{const e=makeEnv({transactions:[{id:'tx1'}]});const o=syncOne(e);const a=e.service.linkPayment(o.id,'tx1'),b=e.service.linkPayment(o.id,'tx1');eq(a.id,b.id);eq(e.state.payments.length,1);});
test('mesma transação não liquida duas obrigações',()=>{const e=makeEnv({transactions:[{id:'tx1'}],participations:[{id:'part1',workflowStatus:'approved',consistencyStatus:'consistent',contractId:'ctr1',contractVersionId:'cv1',economicRuleId:'r1',participantPartyType:'person',participantPartyId:'p1',periodStart:'2026-08-01',periodEnd:'2026-08-31',currency:'BRL',participationAmount:10000,sourceSnapshotHash:'a',metadata:{}},{id:'part2',workflowStatus:'approved',consistencyStatus:'consistent',contractId:'ctr2',contractVersionId:'cv2',economicRuleId:'r2',participantPartyType:'person',participantPartyId:'p1',periodStart:'2026-08-01',periodEnd:'2026-08-31',currency:'BRL',participationAmount:10000,sourceSnapshotHash:'b',metadata:{}}]});e.service.syncObligations();const [a,b]=e.state.obligations;e.service.linkPayment(a.id,'tx1');assert.throws(()=>e.service.linkPayment(b.id,'tx1'),/outro Repasse/);});
test('inflow não pode liquidar Repasse',()=>{const e=makeEnv({transactions:[{id:'tx1',direction:'inflow'}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1'),/saída/);});
test('pending não conta como pagamento',()=>{const e=makeEnv({transactions:[{id:'tx1',status:'pending'}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1'),/lançada/);});
test('excluded não conta como pagamento',()=>{const e=makeEnv({transactions:[{id:'tx1',status:'excluded'}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1'),/lançada/);});
test('demo não conta como pagamento',()=>{const e=makeEnv({transactions:[{id:'tx1',isDemo:true}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1'),/demo/);});
test('transfer não liquida Repasse',()=>{const e=makeEnv({transactions:[{id:'tx1',financialNature:'transfer'}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1'),/Transferência/);});
test('reversal não é pagamento principal',()=>{const e=makeEnv({transactions:[{id:'tx1',financialNature:'reversal'}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1'),/estorno/);});
test('moeda incompatível bloqueia pagamento',()=>{const e=makeEnv({transactions:[{id:'tx1',currency:'USD'}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1'),/Moeda/);});
test('contraparte diferente bloqueia vínculo',()=>{const e=makeEnv({transactions:[{id:'tx1',counterpartyId:'p2'}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1'),/beneficiário/);});
test('transação sem contraparte pode ser confirmada manualmente',()=>{const e=makeEnv({transactions:[{id:'tx1',counterpartyId:'',counterpartyType:''}]});const o=syncOne(e);assert.doesNotThrow(()=>e.service.linkPayment(o.id,'tx1'));});
test('pagamento parcial deriva saldo',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');const v=e.service.getObligation(o.id);close(v.amountPaid,4000);close(v.openBalance,6000);eq(v.status,'partial');});
test('pagamento integral quita obrigação',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');const v=e.service.getObligation(o.id);close(v.amountPaid,10000);close(v.openBalance,0);eq(v.status,'paid');});
test('múltiplos pagamentos liquidam obrigação',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000},{id:'tx2',amount:6000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.service.linkPayment(o.id,'tx2');const v=e.service.getObligation(o.id);close(v.amountPaid,10000);eq(v.status,'paid');eq(e.service.payments(o.id).length,2);});
test('sobrepagamento é bloqueado',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:7000},{id:'tx2',amount:4000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');assert.throws(()=>e.service.linkPayment(o.id,'tx2'),/excede o saldo/);});
test('valor vinculado não pode exceder a própria transação',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:3000}]});const o=syncOne(e);assert.throws(()=>e.service.linkPayment(o.id,'tx1',{amount:4000}),/excede a transação/);});
test('vínculo parcial explícito é suportado sem criar outro movimento',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:8000}]});const o=syncOne(e),before=e.transactions.length;e.service.linkPayment(o.id,'tx1',{amount:3000});close(e.service.getObligation(o.id).amountPaid,3000);eq(e.transactions.length,before);});
test('desvincular pagamento restaura saldo',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e),p=e.service.linkPayment(o.id,'tx1');e.service.unlinkPayment(p.id,'correção');const v=e.service.getObligation(o.id);close(v.amountPaid,0);close(v.openBalance,10000);eq(e.finance.data.matches[0].status,'inactive');});
test('desvincular não apaga histórico de pagamento',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e),p=e.service.linkPayment(o.id,'tx1');e.service.unlinkPayment(p.id,'correção');eq(e.state.payments.length,1);eq(e.state.payments[0].status,'unlinked');assert(e.state.history.some(x=>x.action==='payment.unlinked'));});

// Reversals and net settlement.
test('reversal reduz valor liquidado líquido',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.addTx({id:'rev1',relatedTransactionId:'tx1',direction:'inflow',financialNature:'reversal',amount:2000,counterpartyId:'p1'});const v=e.service.refreshConsistency(o.id);close(v.amountPaid,8000);close(v.openBalance,2000);eq(v.status,'partial');});
test('refund reduz liquidação',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.addTx({id:'ref1',relatedTransactionId:'tx1',direction:'inflow',financialNature:'refund',amount:2500});close(e.service.getObligation(o.id).amountPaid,7500);});
test('chargeback reduz liquidação',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.addTx({id:'cb1',relatedTransactionId:'tx1',direction:'inflow',financialNature:'chargeback',amount:1000});close(e.service.getObligation(o.id).amountPaid,9000);});
test('reversão integral devolve obrigação para aberto',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.addTx({id:'rev1',relatedTransactionId:'tx1',direction:'inflow',financialNature:'reversal',amount:10000});const v=e.service.getObligation(o.id);close(v.amountPaid,0);close(v.openBalance,10000);eq(v.status,'open');});
test('reversal pending não reduz liquidação',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.addTx({id:'rev1',relatedTransactionId:'tx1',direction:'inflow',financialNature:'reversal',amount:2000,status:'pending'});close(e.service.getObligation(o.id).amountPaid,10000);});
test('reversal demo não reduz liquidação',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.addTx({id:'rev1',relatedTransactionId:'tx1',direction:'inflow',financialNature:'reversal',amount:2000,isDemo:true});close(e.service.getObligation(o.id).amountPaid,10000);});
test('detecção de estorno registra histórico sem apagar pagamento',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.service.refreshConsistency(o.id);e.addTx({id:'rev1',relatedTransactionId:'tx1',direction:'inflow',financialNature:'reversal',amount:2000});e.service.refreshConsistency(o.id);assert(e.state.history.some(x=>x.action==='payment.reversal_detected'));eq(e.state.payments.length,1);});

// Reconciliation.
test('pagamento pode ser conciliado',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e),p=e.service.linkPayment(o.id,'tx1');e.service.reconcilePayment(p.id);eq(e.service.getObligation(o.id).reconciliationStatus,'reconciled');eq(e.finance.getTransaction('tx1').reconciliationStatus,'reconciled');});
test('pagamento pode ser desconciliado',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e),p=e.service.linkPayment(o.id,'tx1');e.service.reconcilePayment(p.id);e.service.unreconcilePayment(p.id);eq(e.service.getObligation(o.id).reconciliationStatus,'unreconciled');});
test('múltiplos pagamentos permitem conciliação parcial',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000},{id:'tx2',amount:6000}]});const o=syncOne(e),p1=e.service.linkPayment(o.id,'tx1');e.service.linkPayment(o.id,'tx2');e.service.reconcilePayment(p1.id);const v=e.service.getObligation(o.id);eq(v.status,'paid');eq(v.reconciliationStatus,'partially_reconciled');});
test('quitação e conciliação são conceitos separados',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');const v=e.service.getObligation(o.id);eq(v.status,'paid');eq(v.reconciliationStatus,'unreconciled');});
test('conciliação não altera amountDue',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e),p=e.service.linkPayment(o.id,'tx1');e.service.reconcilePayment(p.id);close(e.service.getObligation(o.id).amountDue,10000);});
test('pagamento conciliado precisa ser desconciliado antes de desvincular',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e),p=e.service.linkPayment(o.id,'tx1');e.service.reconcilePayment(p.id);assert.throws(()=>e.service.unlinkPayment(p.id),/Desconcilie/);});
test('histórico de conciliação é preservado',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e),p=e.service.linkPayment(o.id,'tx1');e.service.reconcilePayment(p.id);e.service.unreconcilePayment(p.id);eq(e.state.reconciliation.length,2);eq(e.state.reconciliation[0].action,'reconciled');eq(e.state.reconciliation[1].action,'unreconciled');});

// Supersede and source consistency.
test('Participação superseded sem pagamento torna obrigação substituída',()=>{const e=makeEnv();const o=syncOne(e);e.participants[0].workflowStatus='superseded';e.service.syncObligations();const v=e.service.getObligation(o.id);eq(v.status,'superseded');eq(v.consistencyStatus,'source_superseded');});
test('Participação superseded após pagamento preserva pagamento e sinaliza inconsistência',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.participants[0].workflowStatus='superseded';e.service.syncObligations();const v=e.service.getObligation(o.id);close(v.amountPaid,4000);eq(v.consistencyStatus,'source_superseded_with_payments');assert(e.state.history.some(x=>x.action==='obligation.participation_superseded'));});
test('nova revisão aprovada cria nova obrigação sem mover pagamento antigo',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const old=syncOne(e);e.service.linkPayment(old.id,'tx1');e.participants[0].workflowStatus='superseded';e.participants.push({id:'part2',workflowStatus:'approved',consistencyStatus:'consistent',isDemo:false,contractId:'ctr1',contractVersionId:'cv2',economicRuleId:'rule2',participantPartyType:'person',participantPartyId:'p1',periodStart:'2026-08-01',periodEnd:'2026-08-31',currency:'BRL',participationAmount:8000,productId:'prod1',serviceId:'',businessUnitId:'',approvedAt:'2026-08-26T10:00:00Z',sourceSnapshotHash:'src2',metadata:{dueDate:null}});e.service.syncObligations();eq(e.state.obligations.length,2);const oldV=e.service.getObligation(old.id),newRaw=e.state.obligations.find(x=>x.participationCalculationId==='part2'),newV=e.service.getObligation(newRaw.id);close(oldV.amountPaid,4000);close(newV.amountPaid,0);close(newV.amountDue,8000);});
test('pagamento antigo não é transferido automaticamente para nova obrigação',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const old=syncOne(e);e.service.linkPayment(old.id,'tx1');e.participants[0].workflowStatus='superseded';e.participants.push({...e.participants[0],id:'part2',workflowStatus:'approved',consistencyStatus:'consistent',participationAmount:8000,sourceSnapshotHash:'new'});e.service.syncObligations();const newer=e.state.obligations.find(x=>x.participationCalculationId==='part2');eq(e.service.payments(newer.id).length,0);});
test('transação alterada para excluded deixa de contar e sinaliza fonte alterada',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:4000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');e.finance.getTransaction('tx1').status='excluded';const v=e.service.refreshConsistency(o.id);close(v.amountPaid,0);eq(v.consistencyStatus,'source_changed');});
test('cancelamento exige motivo',()=>{const e=makeEnv();const o=syncOne(e);assert.throws(()=>e.service.cancelObligation(o.id,''),/Motivo/);});
test('cancelamento sem pagamento preserva obrigação',()=>{const e=makeEnv();const o=syncOne(e);e.service.cancelObligation(o.id,'cancelado externamente');eq(e.service.getObligation(o.id).status,'cancelled');eq(e.state.obligations.length,1);});
test('obrigação com pagamento não pode ser cancelada diretamente',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:1000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');assert.throws(()=>e.service.cancelObligation(o.id,'x'),/pagamento vinculado/);});
test('vencido é derivado da data atual e saldo',()=>{const e=makeEnv({now:'2026-09-20T12:00:00Z'});e.participants[0].metadata.dueDate='2026-09-10';const o=syncOne(e);eq(o.status,'overdue');});
test('dueDate null nunca inventa vencimento',()=>{const e=makeEnv({now:'2027-09-20T12:00:00Z'});e.participants[0].metadata={};const o=syncOne(e);eq(o.dueDate,null);eq(o.status,'open');});

// Search, filters, summaries, suggestions.
test('busca encontra beneficiário',()=>{const e=makeEnv();syncOne(e);eq(e.service.query({search:'João'}).total,1);});
test('filtro por status funciona',()=>{const e=makeEnv();syncOne(e);eq(e.service.query({status:'open'}).total,1);eq(e.service.query({status:'paid'}).total,0);});
test('filtro por participante funciona',()=>{const e=makeEnv();syncOne(e);eq(e.service.query({participantPartyId:'p1'}).total,1);eq(e.service.query({participantPartyId:'p2'}).total,0);});
test('filtro por contrato funciona',()=>{const e=makeEnv();syncOne(e);eq(e.service.query({contractId:'ctr1'}).total,1);});
test('filtro por Produto funciona',()=>{const e=makeEnv();syncOne(e);eq(e.service.query({productId:'prod1'}).total,1);});
test('filtro por período funciona',()=>{const e=makeEnv();syncOne(e);eq(e.service.query({from:'2026-08-15',to:'2026-08-20'}).total,1);eq(e.service.query({from:'2026-09-01'}).total,0);});
test('filtro por conciliação funciona',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e),p=e.service.linkPayment(o.id,'tx1');e.service.reconcilePayment(p.id);eq(e.service.query({reconciliationStatus:'reconciled'}).total,1);});
test('sugestões não auto-vinculam transações',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000}]});const o=syncOne(e),before=e.state.payments.length,rows=e.service.suggestTransactions(o.id);assert(rows.length);eq(e.state.payments.length,before);});
test('sugestão prioriza beneficiário e valor',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:10000},{id:'tx2',amount:9000,counterpartyId:''}]});const o=syncOne(e),rows=e.service.suggestTransactions(o.id);eq(rows[0].id,'tx1');assert(rows[0].matchScore>rows[1].matchScore);});
test('summary agrupa moedas sem converter FX',()=>{const e=makeEnv({participations:[{id:'brl',workflowStatus:'approved',consistencyStatus:'consistent',contractId:'c1',contractVersionId:'v1',economicRuleId:'r1',participantPartyType:'person',participantPartyId:'p1',periodStart:'2026-08-01',periodEnd:'2026-08-31',currency:'BRL',participationAmount:1000,sourceSnapshotHash:'a',metadata:{}},{id:'usd',workflowStatus:'approved',consistencyStatus:'consistent',contractId:'c2',contractVersionId:'v2',economicRuleId:'r2',participantPartyType:'person',participantPartyId:'p1',periodStart:'2026-08-01',periodEnd:'2026-08-31',currency:'USD',participationAmount:100,sourceSnapshotHash:'b',metadata:{}}]});e.service.syncObligations();const s=e.service.summaryByCurrency();eq(s.length,2);assert(s.some(x=>x.currency==='BRL'&&x.amountDue===1000));assert(s.some(x=>x.currency==='USD'&&x.amountDue===100));});

// Legacy / boundaries / ownership.
test('legado sem participationCalculationId não migra',()=>{const e=makeEnv();const r=e.service.migrateLegacy([{id:'legacy1',partner:'Sócio',amount:10}]);eq(r.migrated,0);assert(e.state.metadata.legacySkipped.some(x=>x.reason==='insufficient_participation_traceability'));});
test('legado com participationCalculationId exige sync canônico',()=>{const e=makeEnv();const r=e.service.migrateLegacy([{id:'legacy2',participationCalculationId:'part1',amount:10}]);eq(r.migrated,0);assert(e.state.metadata.legacySkipped.some(x=>x.reason==='legacy_requires_canonical_obligation_sync'));});
test('core não cria Participação nem recalcula regra econômica',()=>{const src=fs.readFileSync(path.join(__dirname,'..','web','src','modules','finance','payouts','core.js'),'utf8');for(const token of ['createCalculation(','previewEligible(','createBatch(','submitToReview('])assert(!src.includes(token));});
test('core não cria Transação financeira',()=>{const src=fs.readFileSync(path.join(__dirname,'..','web','src','modules','finance','payouts','core.js'),'utf8');assert(!src.includes('createTransaction('));});
test('core não mantém percentuais econômicos concorrentes',()=>{const src=fs.readFileSync(path.join(__dirname,'..','web','src','modules','finance','payouts','core.js'),'utf8');for(const token of ['partnerPercentage','manualParticipationRule','productPartnerSplit','shareholderPercentage'])assert(!src.includes(token));});
test('core não usa Societário como fonte automática',()=>{const src=fs.readFileSync(path.join(__dirname,'..','web','src','modules','finance','payouts','core.js'),'utf8').toLowerCase();for(const token of ['shareholder','equitypercentage','ownershippercentage','quotasociet','societario'])assert(!src.includes(token));});
test('domínio separa status da obrigação e conciliação',()=>{assert(Core.OBLIGATION_STATUSES.includes('paid'));assert(Core.RECONCILIATION_STATUSES.includes('unreconciled'));assert(!Core.OBLIGATION_STATUSES.includes('reconciled'));});
test('memória preserva obrigação pagamentos links conciliação snapshot histórico',()=>{const e=makeEnv({transactions:[{id:'tx1',amount:1000}]});const o=syncOne(e);e.service.linkPayment(o.id,'tx1');const m=e.service.memory(o.id);assert(m.obligation&&m.payments&&m.transactionLinks&&m.reconciliation&&m.sourceSnapshot&&m.history);});

if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8');
  test('bundle contém domínio canônico de Repasses',()=>{assert(app.includes('VALTREN PAYOUTS START'));assert(app.includes('ValtrenPayoutCore'));assert(app.includes('state.crmPayouts'));});
  test('rota canônica Repasses está materializada',()=>{assert(app.includes("if(path==='/crm/financeiro/repasses')return crmPayoutsPage();"));});
  test('placeholder de Repasses não sobrevive',()=>{assert(!app.includes("if(path==='/crm/financeiro/repasses')return crmArchitecturePlaceholderPage('accounting','repasses','Repasses');"));});
  test('Participações continua canônica',()=>{assert(app.includes("if(path==='/crm/financeiro/participacoes')return crmEconomicParticipationsPage();"));});
  test('bundle mantém feed canônico de Participações',()=>{assert(app.includes('function crmParticipationObligationsFeed(filters={})'));});
  test('bundle mantém Repasses depois de Participações',()=>{assert(app.indexOf('VALTREN PAYOUTS START')>app.indexOf('VALTREN ECONOMIC PARTICIPATIONS START'));});
  test('bundle de Repasses não cria Transação nem Participação',()=>{const start=app.indexOf('// VALTREN PAYOUTS START'),end=app.indexOf('// VALTREN PAYOUTS END',start),block=app.slice(start,end);assert(!block.includes('createTransaction('));assert(!block.includes('createCalculation('));});
  test('sidebar Financeiro continua com seis itens',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);for(const item of ['Transações','Contabilidade','Notas Fiscais','Rateios','Participações','Repasses'])assert(sidebar.includes(item));});
  test('Configurações preserva seis abas atuais',()=>{const start=app.indexOf('function crmCanonicalSettingsPage()'),end=app.indexOf('function crmCanonicalProfilePage()',start),settings=app.slice(start,end);for(const item of ["['empresa','Empresa']","['notificacoes','Notificações']","['seguranca','Segurança']","['integracoes','Integrações']","['auditoria','Auditoria']","['usuarios','Usuários']"])assert(settings.includes(item));assert(!settings.includes("['billing','Billing']"));});
  test('Administração preserva dois itens atuais',()=>{const start=app.lastIndexOf('const administration=['),end=app.indexOf('];',start),admin=app.slice(start,end);for(const item of ["['structure','Estrutura Organizacional','#/crm/administracao']","['assets','Patrimônio e Licenças','#/crm/administracao/patrimonio-licencas']"])assert(admin.includes(item));});
}
console.log(`Payouts domain tests: ${passed} passed`);
