'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const browser=fs.readFileSync(path.resolve(__dirname,'..','web','src','modules','business','browser.js'),'utf8');
const css=fs.readFileSync(path.resolve(__dirname,'..','web','src','modules','business','styles.css'),'utf8');
const materializer=fs.readFileSync(path.resolve(__dirname,'crm_business.py'),'utf8');
const materialize=fs.readFileSync(path.resolve(__dirname,'materialize.py'),'utf8');
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}
const has=(src,...values)=>values.forEach((v)=>assert(src.includes(v),`missing ${v}`));

test('Produtos possui página própria',()=>has(browser,'function crmBusinessProductsPage()','Produtos','Novo Produto'));
test('Serviços possui página própria',()=>has(browser,'function crmBusinessServicesPage()','Serviços','Novo Serviço'));
test('Unidades possui página própria',()=>has(browser,'function crmBusinessUnitsPage()','Unidades de Negócio','Nova Unidade'));
test('breadcrumb Produtos é Negócios Produtos',()=>has(browser,"crmBusinessBreadcrumb('Produtos','#/crm/negocios')"));
test('breadcrumb Serviços é Negócios Serviços',()=>has(browser,"crmBusinessBreadcrumb('Serviços','#/crm/negocios/servicos')"));
test('breadcrumb Unidades é Negócios Unidades de Negócio',()=>has(browser,"crmBusinessBreadcrumb('Unidades de Negócio','#/crm/negocios/unidades')"));
test('Produtos tem busca funcional',()=>has(browser,'crm-business-product-search','Buscar nome, código, categoria ou unidade'));
test('Produtos tem filtro Status',()=>has(browser,'crm-business-product-status'));
test('Produtos tem filtro Categoria',()=>has(browser,'crm-business-product-category'));
test('Produtos tem filtro Unidade',()=>has(browser,'crm-business-product-unit'));
test('Produtos tem Mais filtros',()=>has(browser,'crmBusinessProductToolbar','Mais filtros'));
test('Serviços tem busca funcional',()=>has(browser,'crm-business-service-search'));
test('Serviços tem filtro Status',()=>has(browser,'crm-business-service-status'));
test('Serviços tem filtro Categoria',()=>has(browser,'crm-business-service-category'));
test('Serviços tem filtro Unidade',()=>has(browser,'crm-business-service-unit'));
test('Unidades tem busca funcional',()=>has(browser,'crm-business-unit-search','Buscar nome, código ou responsável'));
test('Unidades tem filtro Status',()=>has(browser,'crm-business-unit-status'));
test('Unidades tem filtro Responsável',()=>has(browser,'crm-business-unit-owner'));
test('TableView Produtos possui colunas obrigatórias',()=>has(browser,'<th>Produto</th>','<th>Código</th>','<th>Categoria</th>','<th>Unidade</th>','<th>Modelo de Receita</th>','<th>Preço/Referência</th>','<th>Status</th>','<th>Responsável</th>','<th>Ação</th>'));
test('TableView Serviços possui colunas obrigatórias',()=>has(browser,'<th>Serviço</th>','<th>Modelo de Preço</th>'));
test('TableView Unidades possui colunas obrigatórias',()=>has(browser,'<th>Unidade</th>','<th>Produtos</th>','<th>Serviços</th>'));
test('Preço ausente é travessão e não zero falso',()=>assert(browser.includes("return value==null?'—'")));
test('contagens de Unidade vêm do domínio',()=>has(browser,'service.countsForUnit(row.id)'));
test('ação principal de linha é Ver',()=>has(browser,'data-action="crm-business-view"'));
test('ações secundárias ficam em menu compacto',()=>has(browser,'crm-business-row-menu','aria-label="Mais ações">⋯'));
test('editor de Produto possui Informações Classificação Modelo Comercial Relacionamentos',()=>has(browser,"kind==='product'",'<h3>Informações</h3>','<h3>Classificação</h3>','<h3>Modelo Comercial</h3>','<h3>Relacionamentos</h3>'));
test('editor de Serviço possui Informações e Modelo Comercial',()=>has(browser,"kind==='service'",'Modelo de Preço','Duração padrão'));
test('editor de Unidade não força hierarquia',()=>has(browser,'Unidade pai (opcional)'));
test('editor explica que não cria operação financeira/jurídica',()=>has(browser,'não cria Transação, Nota Fiscal ou Contrato'));
test('detalhe possui Visão Geral',()=>has(browser,'<h3>Visão Geral</h3>'));
test('detalhe de Produto Serviço possui Comercial',()=>has(browser,'<h3>Comercial</h3>'));
test('detalhe possui Relacionamentos',()=>has(browser,'<h3>Relacionamentos</h3>'));
test('detalhe possui Histórico',()=>has(browser,'<h3>Histórico</h3>'));
test('detalhe de Unidade lista Produtos relacionados',()=>has(browser,'Produtos relacionados'));
test('detalhe de Unidade lista Serviços relacionados',()=>has(browser,'Serviços relacionados'));
test('UI não inventa faturamento ou margem',()=>{for(const x of ['Faturamento','Margem','Receita Total','Resultado Financeiro'])assert(!browser.includes(x));});
test('UI usa referência não resolvida explícita',()=>has(browser,'Referência não resolvida'));
test('feeds read-only existem',()=>has(browser,'function crmBusinessProductsFeed','function crmBusinessServicesFeed','function crmBusinessUnitsFeed'));
test('lookups centralizados existem',()=>has(browser,'function crmBusinessGetProduct','function crmBusinessGetService','function crmBusinessGetUnit'));
test('resolução central de dimensão existe',()=>has(browser,'function crmBusinessResolveDimension','function crmBusinessDimensionLabel'));
test('Corporativo não depende de cadastro de Produto',()=>assert(!browser.includes("name:'Corporativo'")));
test('demo não é habilitado implicitamente no feed',()=>has(browser,'includeDemo:!!filters.includeDemo'));
test('referências históricas consultam somente módulos concluídos',()=>has(browser,"['transactions',state.crmFinancialTransactions]","['fiscal_documents',state.crmFiscalDocuments]","['legal_contracts',state.crmLegalContracts]","['economic_participations',state.crmEconomicParticipations]","['payouts',state.crmPayouts]"));
test('Projetos não foi criado pela UI de Negócios',()=>assert(!browser.includes('Projetos')));
test('Sistemas não foi criado como subpágina de Negócios',()=>assert(!browser.includes('crmBusinessSystemsPage')));
test('nenhum produto real conhecido foi hardcoded',()=>{for(const x of ['Music OS 360','Vivendo da Música','Dica de Cria','Visa Fácil'])assert(!browser.includes(x));});
test('responsividade possui breakpoint 1380',()=>assert(css.includes('@media(max-width:1380px)')));
test('responsividade possui breakpoint 1050',()=>assert(css.includes('@media(max-width:1050px)')));
test('responsividade possui breakpoint 760',()=>assert(css.includes('@media(max-width:760px)')));
test('responsividade possui breakpoint 520',()=>assert(css.includes('@media(max-width:520px)')));
test('TableView possui overflow controlado',()=>has(css,'.crm-business-table-wrap{overflow:auto}'));
test('drawer respeita viewport',()=>has(css,'height:100%','width:min(620px,100vw)'));
test('modal respeita viewport',()=>has(css,'width:min(880px,calc(100vw - 32px))'));
test('mobile reduz colunas secundárias antes das essenciais',()=>has(css,'th:nth-child(3)','th:nth-child(5)'));
test('paginação está limitada a 50 no browser',()=>has(browser,"service.paged('product',{...f,limit:50})","service.paged('service',{...f,limit:50})","service.paged('business_unit',{...f,limit:50})"));
test('materializador substitui exatamente três placeholders',()=>assert.equal((materializer.match(/crmArchitecturePlaceholderPage\('business'/g)||[]).length,3));
test('materializador valida os três handlers canônicos',()=>has(materializer,'crmBusinessProductsPage();','crmBusinessServicesPage();','crmBusinessUnitsPage();'));
test('materializador preserva owners financeiros e jurídicos',()=>has(materializer,'crmTransactionsPage();','crmAccountingPage();','crmFiscalDocumentsPage();','crmEconomicParticipationsPage();','crmPayoutsPage();','crmLegalContractsPage();'));
test('materializador valida sidebar sem reescrever',()=>{has(materializer,'const business=[','VALTREN SIDEBAR ARCHITECTURE START','VALTREN SIDEBAR ARCHITECTURE END');assert(!materializer.includes('app.rfind("function crmRelSidebar")'));assert(!materializer.includes('app.find("function crmReferenceRoute", sidebar_start)'));});
test('materializador proíbe novos submódulos indevidos',()=>has(materializer,'Projetos','Portfolio','Sistemas','Categorias','Planos'));
test('materializador proíbe catálogos paralelos',()=>has(materializer,'state.financeProducts=','state.contractProducts=','state.payoutBusinessUnits='));
test('materializador proíbe seeds de produtos reais',()=>has(materializer,'Music OS 360','Vivendo da Música','Dica de Cria','Visa Fácil'));
test('materializador proíbe responsabilidades financeiras no core',()=>has(materializer,'createTransaction(','createFiscalDocument(','participationAmount','payoutAmount'));
test('materializador contém adapters mínimos de Transações',()=>has(materializer,'crmFinanceProducts','crmFinanceProductLabel'));
test('materializador contém adapters mínimos de Contabilidade',()=>has(materializer,'crmAccountingProducts','crmAccountingServices','crmAccountingUnits'));
test('materializador contém adapters mínimos de Notas Fiscais',()=>has(materializer,'crmFiscalProducts','crmFiscalServices','crmFiscalUnits'));
test('materializador contém adapters mínimos de Rateios',()=>has(materializer,'crmCostAllocationResolveDestination','crmCostAllocationDestinationLabel'));
test('materializador contém adapters mínimos de Contratos',()=>has(materializer,'crmLegalResolveReference','crmLegalProducts','crmLegalServices','crmLegalUnits'));
test('materializador contém adapters mínimos de Participações',()=>has(materializer,'crmParticipationReferenceLabel'));
test('materializador contém adapters mínimos de Repasses',()=>has(materializer,'crmPayoutReferenceLabel'));
test('materializador principal chama Negócios depois de Repasses',()=>{const p=materialize.indexOf('apply_crm_payouts()'),b=materialize.indexOf('apply_crm_business()');assert(p>=0&&b>p);});
test('ordem tardia está documentada como proteção contra overwrite',()=>has(materializer,'patch the final runtime helpers rather than being overwritten'));

if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8'),brand=fs.readFileSync(path.resolve(__dirname,'..','assets','valtren-brand.css'),'utf8');
  test('UI final de Produtos está no bundle',()=>has(app,'function crmBusinessProductsPage()','Novo Produto'));
  test('UI final de Serviços está no bundle',()=>has(app,'function crmBusinessServicesPage()','Novo Serviço'));
  test('UI final de Unidades está no bundle',()=>has(app,'function crmBusinessUnitsPage()','Nova Unidade'));
  test('breadcrumbs publicados usam Negócios',()=>has(app,"crmBusinessBreadcrumb('Produtos','#/crm/negocios')","crmBusinessBreadcrumb('Serviços','#/crm/negocios/servicos')","crmBusinessBreadcrumb('Unidades de Negócio','#/crm/negocios/unidades')"));
  test('rotas publicadas não são placeholders',()=>{has(app,"if(path==='/crm/negocios')return crmBusinessProductsPage();","if(path==='/crm/negocios/servicos')return crmBusinessServicesPage();","if(path==='/crm/negocios/unidades')return crmBusinessUnitsPage();");});
  test('CSS de Negócios foi materializado',()=>has(brand,'/* VALTREN BUSINESS CATALOG */','.crm-business-table-wrap{overflow:auto}'));
  test('sidebar Negócios mantém exatamente três itens oficiais',()=>{const start=app.lastIndexOf('const business=['),end=app.indexOf('];',start),block=app.slice(start,end);for(const x of ["['products','Produtos','#/crm/negocios']","['services','Serviços','#/crm/negocios/servicos']","['units','Unidades de Negócio','#/crm/negocios/unidades']"])assert(block.includes(x));for(const x of ['Projetos','Portfolio','Sistemas','Categorias','Planos'])assert(!block.includes(x));});
  test('Produto Serviço Unidade não viraram item genérico',()=>assert(!app.includes("['items','Itens','#/crm/negocios")));
  test('Transações preserva Corporativo',()=>has(app,"<option value=\"corporate\"","Corporativo"));
  test('Transações resolve Produto por Negócios',()=>has(app,'crmBusinessProductsFeed','crmBusinessDimensionLabel'));
  test('Contabilidade mantém DRE canônica',()=>has(app,'function crmAccountingDreView','Demonstrativo de Resultado'));
  test('Notas Fiscais mantém domínio fiscal canônico',()=>has(app,'function crmFiscalDocumentsPage()','state.crmFiscalDocuments'));
  test('Rateios mantém workflow canônico',()=>has(app,'function crmCostAllocationsPage','ValtrenCostAllocationCore'));
  test('Contratos mantém versionamento canônico',()=>has(app,'ValtrenContractCore','function crmLegalContractsPage()'));
  test('Variáveis contratuais têm resolver canônico disponível',()=>has(app,'crmLegalResolveReference','crmBusinessResolveDimension'));
  test('Participações mantém cálculo canônico',()=>has(app,'ValtrenParticipationCore','crmParticipationObligationsFeed'));
  test('Repasses mantém liquidação canônica',()=>has(app,'ValtrenPayoutCore','function crmPayoutsPage()'));
  test('referência não resolvida nunca vira undefined',()=>has(app,'Referência não resolvida'));
  test('Configurações continua com seis abas',()=>{const start=app.indexOf('function crmCanonicalSettingsPage()'),end=app.indexOf('function crmCanonicalProfilePage()',start),s=app.slice(start,end);for(const x of ['Empresa','Notificações','Segurança','Integrações','Auditoria','Usuários'])assert(s.includes(x));});
  test('Administração permanece fora da sidebar canônica',()=>{const start=app.indexOf('VALTREN SIDEBAR ARCHITECTURE START'),end=app.indexOf('VALTREN SIDEBAR ARCHITECTURE END',start);assert(start>=0&&end>start);const sidebar=app.slice(start,end);for(const label of ['Administração','Estrutura Organizacional','Patrimônio e Licenças'])assert(!sidebar.includes(label));});
}
console.log(`Business catalog UI tests: ${passed} passed`);
