'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const FinanceCore=require('../web/src/modules/finance/transactions/core.js');
const AccountingCore=require('../web/src/modules/finance/accounting/core.js');
const AllocationCore=require('../web/src/modules/finance/allocations/core.js');

let seq=0,clock=0,passed=0;
const now=()=>`2026-08-25T18:${String(Math.floor(clock/60)).padStart(2,'0')}:${String(clock++%60).padStart(2,'0')}.000Z`;
const ids=(prefix)=>`${prefix}_${++seq}`;
const financeState=FinanceCore.createState({now});
const finance=FinanceCore.createService(financeState,{idFactory:ids,now,actorProvider:()=> 'user_rateios'});
const account=finance.createAccount({name:'Conta Operacional',type:'checking',currency:'BRL',source:'manual'});
const allocationState=AllocationCore.createState({now});
const allocations=AllocationCore.createService(allocationState,{financeService:()=>finance,idFactory:ids,now,actorProvider:()=> 'user_rateios',resolveDestination:()=>true});
function test(name,fn){try{fn();passed++;console.log(`PASS ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}
function expense(amount=10000,status='posted',description='Despesa compartilhada',extra={}){return finance.createTransaction({financialAccountId:account.id,amount,direction:'outflow',financialNature:'expense',originalDescription:description,status,categoryId:'software',businessDimension:'unassigned',transactionDate:'2026-08-25',...extra});}
function percentLines(){return [{destinationType:'product',destinationId:'product_a',percentage:40},{destinationType:'product',destinationId:'product_b',percentage:35},{destinationType:'corporate',percentage:25}];}
function workflow(row){allocations.sendToReview(row.id);allocations.approve(row.id);allocations.post(row.id);return row;}

let source,rateio;
test('1 criação de Rateio',()=>{source=expense();rateio=allocations.createAllocation({sourceTransactionId:source.id,name:'Infraestrutura geral',method:'percentage',lines:percentLines(),accountingPeriod:'2026-08'});assert(rateio.id);assert.equal(rateio.status,'draft');});
test('2 referência à transação existente',()=>{assert.equal(rateio.sourceTransactionId,source.id);assert.equal(allocations.getAllocation(rateio.id).sourceTransactionId,source.id);});
test('3 Rateio não cria transação',()=>{const before=financeState.transactions.length;allocations.updateDraft(rateio.id,{description:'Memória formal'});assert.equal(financeState.transactions.length,before);});
test('4 despesa original permanece única',()=>{assert.equal(financeState.transactions.filter((x)=>x.id===source.id).length,1);assert.equal(source.amount,10000);});
test('5 método percentual',()=>{const preview=allocations.preview(rateio.id);assert.equal(preview.distributedAmount,10000);assert.equal(preview.lines[0].amount,4000);});
test('6 método valor fixo',()=>{const tx=expense(5000,'posted','Valor fixo');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'fixed',lines:[{destinationType:'product',destinationId:'p1',amount:3000},{destinationType:'corporate',amount:2000}]});const preview=allocations.preview(row.id);assert.equal(preview.distributedAmount,5000);assert.equal(preview.totalPercentage,100);});
test('7 divisão igual',()=>{const tx=expense(100,'posted','Igual');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'equal',lines:[{destinationType:'product',destinationId:'p1'},{destinationType:'product',destinationId:'p2'},{destinationType:'corporate'}]});const values=allocations.getLines(row.id).map((x)=>x.amount);assert.deepEqual(values,[33.34,33.33,33.33]);assert.equal(values.reduce((a,b)=>a+b,0),100);});
test('8 direcionador',()=>{const tx=expense(2000,'posted','Driver');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'driver',lines:[{destinationType:'product',destinationId:'p1',driverValue:10},{destinationType:'product',destinationId:'p2',driverValue:5},{destinationType:'corporate',driverValue:5}]});const lines=allocations.getLines(row.id);assert.deepEqual(lines.map((x)=>x.amount),[1000,500,500]);});
test('9 percentual soma 100%',()=>{assert(AllocationCore.percentEqual(allocations.preview(rateio.id).totalPercentage,100));});
test('10 rejeição abaixo de 100% quando integral',()=>{const tx=expense(1000,'posted','Percentual baixo');assert.throws(()=>allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:90}]}),/100%/);});
test('11 rejeição acima de 100%',()=>{const tx=expense(1000,'posted','Percentual alto');assert.throws(()=>allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:110}]}),/100%/);});
test('12 soma de valores fecha base',()=>{const tx=expense(1200,'posted','Valores');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'fixed',lines:[{destinationType:'product',destinationId:'p1',amount:700},{destinationType:'corporate',amount:500}]});assert.equal(allocations.preview(row.id).unallocatedAmount,0);});
test('13 arredondamento por centavos',()=>{const result=allocations.calculate('equal',100,[{destinationType:'product',destinationId:'a'},{destinationType:'product',destinationId:'b'},{destinationType:'product',destinationId:'c'}],false);assert.equal(result.lines.reduce((s,x)=>s+x.amount,0),100);assert(result.lines.some((x)=>x.amount===33.34));});
test('14 Corporativo é dimensão própria',()=>{const corp=allocations.getLines(rateio.id).find((x)=>x.destinationType==='corporate');assert(corp);assert.equal(corp.destinationId,'');});
test('15 Produto usa referência',()=>{assert(allocations.getLines(rateio.id).some((x)=>x.destinationType==='product'&&x.destinationId==='product_a'));});
test('16 Serviço usa referência',()=>{const tx=expense(300,'posted','Serviço');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'service',destinationId:'service_a',percentage:100}]});assert.equal(allocations.getLines(row.id)[0].destinationId,'service_a');});
test('17 Unidade usa referência',()=>{const tx=expense(300,'posted','Unidade');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'business_unit',destinationId:'unit_a',percentage:100}]});assert.equal(allocations.getLines(row.id)[0].destinationType,'business_unit');});
test('18 múltiplos destinos',()=>{assert.equal(allocations.getLines(rateio.id).length,3);});
test('19 destino duplicado bloqueado',()=>{const tx=expense(500,'posted','Duplicado');assert.throws(()=>allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'product',destinationId:'p1',percentage:50},{destinationType:'product',destinationId:'p1',percentage:50}]}),/duplicado/);});
test('20 Rascunho não produz projeção',()=>{assert.equal(rateio.status,'draft');assert.equal(source.allocations.length,0);});
test('21 envio para Revisão',()=>{allocations.sendToReview(rateio.id);assert.equal(rateio.status,'review');assert(rateio.submittedAt);});
test('22 Aprovação',()=>{allocations.approve(rateio.id);assert.equal(rateio.status,'approved');assert.equal(rateio.approvedBy,'user_rateios');});
test('23 Postagem',()=>{allocations.post(rateio.id);assert.equal(rateio.status,'posted');assert(rateio.postedAt);});
test('24 Estorno',()=>{const tx=expense(600,'posted','Estorno');const row=workflow(allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]}));allocations.reverse(row.id,'Mudança de critério');assert.equal(row.status,'reversed');assert.equal(row.reversalReason,'Mudança de critério');});
test('25 transição Rascunho → Postado é bloqueada',()=>{const tx=expense(600,'posted','Fluxo inválido');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]});assert.throws(()=>allocations.post(row.id),/aprovado/);});
test('26 transição Revisão → Postado é bloqueada',()=>{const tx=expense(600,'posted','Fluxo revisão');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]});allocations.sendToReview(row.id);assert.throws(()=>allocations.post(row.id),/aprovado/);});
test('27 postagem é idempotente',()=>{const before=source.allocations.length;allocations.post(rateio.id);assert.equal(source.allocations.length,before);assert.equal(source.allocations.length,3);});
test('28 postagem atualiza projeção efetiva',()=>{assert(source.allocations.every((x)=>x.allocationId===rateio.id&&x.source==='cost_allocation'&&x.status==='posted'));});
test('29 Rascunho não afeta Contabilidade',()=>{const tx=expense(700,'posted','Draft sem efeito');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]});assert.equal(tx.allocations.length,0);assert.equal(row.status,'draft');});
test('30 Revisão não afeta Contabilidade',()=>{const tx=expense(710,'posted','Review sem efeito');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]});allocations.sendToReview(row.id);assert.equal(tx.allocations.length,0);});
test('31 Aprovado não postado não afeta Contabilidade',()=>{const tx=expense(720,'posted','Approved sem efeito');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]});allocations.sendToReview(row.id);allocations.approve(row.id);assert.equal(tx.allocations.length,0);});
test('32 Postado afeta análise dimensional',()=>{assert.equal(source.allocations.find((x)=>x.destinationId==='product_a').amount,4000);});

const accountingState=AccountingCore.createState({now});
const accounting=AccountingCore.createService(accountingState,{financeService:()=>finance,idFactory:ids,now,actorProvider:()=> 'user_rateios'});
accounting.setTransactionAccounting(source.id,{recognitionDate:'2026-08-25'});
test('33 DRE geral não duplica valor',()=>{const rows=accounting.analyze({basis:'accrual',from:'2026-08-01',to:'2026-08-31'}).filter((x)=>x.transaction.id===source.id);assert.equal(rows.length,1);assert.equal(rows[0].amount,10000);});
test('34 soma dimensional reconcilia valor original',()=>{const a=accounting.analyze({basis:'accrual',from:'2026-08-01',to:'2026-08-31',productId:'product_a'}).find((x)=>x.transaction.id===source.id),b=accounting.analyze({basis:'accrual',from:'2026-08-01',to:'2026-08-31',productId:'product_b'}).find((x)=>x.transaction.id===source.id),c=accounting.analyze({basis:'accrual',from:'2026-08-01',to:'2026-08-31',dimension:'corporate'}).find((x)=>x.transaction.id===source.id);assert.equal(a.amount,4000);assert.equal(b.amount,3500);assert.equal(c.amount,2500);assert.equal(a.amount+b.amount+c.amount,10000);});
test('35 Estorno remove efeito dimensional',()=>{const tx=expense(900,'posted','Dimensional estorno');const row=workflow(allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'product',destinationId:'estorno_p',percentage:100}]}));assert.equal(tx.allocations.length,1);allocations.reverse(row.id,'Teste');assert.equal(tx.allocations.length,0);});
test('36 Estorno preserva histórico',()=>{const event=allocationState.history.find((x)=>x.action==='allocation.reversed');assert(event);assert(event.after);});
test('37 nova versão é criada',()=>{const tx=expense(950,'posted','Versionar');const first=workflow(allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]}));allocations.reverse(first.id,'Nova política');const second=allocations.createNewVersion(first.id);assert.equal(second.version,2);assert.equal(second.parentAllocationId,first.id);});
test('38 versão anterior permanece preservada',()=>{const reversed=allocationState.allocations.find((x)=>x.name==='Versionar'&&x.status==='reversed');assert(reversed);assert.equal(reversed.version,1);});
test('39 versão postada não é alterada silenciosamente',()=>{assert.throws(()=>allocations.updateDraft(rateio.id,{name:'Não pode'}),/Rascunho/);});
test('40 memória de cálculo',()=>{const memory=allocations.memory(rateio.id);assert.equal(memory.basisAmount,10000);assert.equal(memory.lines.length,3);assert.equal(memory.distributedAmount,10000);});
test('41 driver é preservado',()=>{const tx=expense(800,'posted','Driver memória');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'driver',lines:[{destinationType:'product',destinationId:'d1',driverValue:3},{destinationType:'corporate',driverValue:1}]});assert.deepEqual(allocations.getLines(row.id).map((x)=>x.driverValue),[3,1]);});
test('42 rateio parcial explícito funciona',()=>{const tx=expense(1000,'posted','Parcial');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',allowPartial:true,lines:[{destinationType:'corporate',percentage:60}]});assert.equal(row.distributedAmount,600);assert.equal(row.unallocatedAmount,400);});
test('43 saldo não distribuído é identificado',()=>{const partial=allocationState.allocations.find((x)=>x.name==='Parcial');assert.equal(partial.unallocatedAmount,400);assert.equal(partial.totalPercentage,60);});
test('44 transferência não é elegível',()=>{const tx=finance.createTransaction({financialAccountId:account.id,amount:100,direction:'outflow',financialNature:'transfer',originalDescription:'Transferência',status:'posted'});assert.throws(()=>allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]}),/Transferência/);});
test('45 demo não é elegível para resultado real',()=>{const tx=expense(100,'posted','Demo',{isDemo:true});assert.throws(()=>allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]}),/demo/);});
test('46 excluída não é elegível',()=>{const tx=expense(100,'posted','Excluída');finance.exclude(tx.id,'teste');assert.throws(()=>allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]}),/excluída/);});
test('47 transação inexistente é rejeitada',()=>{assert.throws(()=>allocations.createAllocation({sourceTransactionId:'txn_missing',method:'percentage',lines:[{destinationType:'corporate',percentage:100}]}),/não encontrada/);});
test('48 mudança de valor da transação sinaliza inconsistência',()=>{finance.updateTransaction(source.id,{amount:12000});allocations.refreshConsistency(rateio.id);assert.equal(rateio.consistencyStatus,'needs_review');assert(rateio.consistencyIssues.includes('source_amount_changed'));});
test('49 mudança da origem em Rascunho preserva histórico',()=>{const a=expense(100,'pending','Origem A'),b=expense(100,'pending','Origem B');const row=allocations.createAllocation({sourceTransactionId:a.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]});allocations.updateDraft(row.id,{sourceTransactionId:b.id,lines:[{destinationType:'corporate',percentage:100}]});assert.equal(row.sourceTransactionId,b.id);assert(allocationState.history.some((x)=>x.allocationId===row.id&&x.action==='allocation.draft.changed'));});
test('50 histórico de aprovação',()=>{assert(allocationState.history.some((x)=>x.allocationId===rateio.id&&x.action==='allocation.approved'));});
test('51 histórico de postagem',()=>{assert(allocationState.history.some((x)=>x.allocationId===rateio.id&&x.action==='allocation.posted'));});
test('52 histórico de estorno',()=>{assert(allocationState.history.some((x)=>x.action==='allocation.reversed'));});
test('53 Rateio não calcula Participação',()=>{assert.equal(typeof allocations.calculateParticipation,'undefined');assert.equal('participants' in allocationState,false);});
test('54 Rateio não cria Repasse',()=>{assert.equal(typeof allocations.createRemittance,'undefined');assert.equal('remittances' in allocationState,false);});
test('55 Rateio não consulta Societário automaticamente',()=>{assert.equal('shareholders' in allocationState,false);assert.equal('corporateStructure' in allocationState,false);});
test('56 segundo Rateio ativo concorrente é bloqueado',()=>{finance.updateTransaction(source.id,{amount:10000});rateio.sourceSnapshot.amount=10000;rateio.consistencyStatus='consistent';rateio.consistencyIssues=[];if(rateio.status==='posted'&&source.allocations.length===0)allocations.post(rateio.id);assert.throws(()=>allocations.createAllocation({sourceTransactionId:source.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]}),/já possui Rateio postado/);});
test('57 pending pode preparar mas não postar',()=>{const tx=expense(1000,'pending','Pendente');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]});allocations.sendToReview(row.id);allocations.approve(row.id);assert.throws(()=>allocations.post(row.id),/lançada/);});
test('58 reclassificação da transação sinaliza revisão',()=>{const tx=expense(1000,'posted','Reclassificada');const row=workflow(allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}]}));finance.setClassification(tx.id,{categoryId:'marketing'});allocations.refreshConsistency(row.id);assert.equal(row.consistencyStatus,'needs_review');assert(row.consistencyIssues.includes('source_classification_changed'));});
test('59 inconsistência remove projeção efetiva sem apagar Rateio',()=>{const row=allocationState.allocations.find((x)=>x.name==='Reclassificada');const tx=finance.getTransaction(row.sourceTransactionId);assert.equal(tx.allocations.length,0);assert(allocations.getAllocation(row.id));assert.equal(row.status,'posted');});
test('60 critério reutilizável pode ser criado e aplicado',()=>{const criterion=allocations.createCriterion({name:'Infraestrutura geral',method:'percentage',lines:[{destinationType:'product',destinationId:'crit_p',percentage:70},{destinationType:'corporate',percentage:30}]});const tx=expense(1000,'pending','Critério');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage'});allocations.applyCriterion(row.id,criterion.id);assert.equal(row.criterionId,criterion.id);assert.equal(allocations.getLines(row.id).length,2);});
test('61 projeção postada é identificável',()=>{const tagged=source.allocations.every((x)=>x.source==='cost_allocation'&&x.allocationVersion===rateio.version);assert(tagged);});
test('62 Serviço é somente referência na projeção',()=>{const tx=expense(400,'posted','Serviço postado');const row=workflow(allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'service',destinationId:'service_x',percentage:100}]}));assert.equal(tx.allocations[0].serviceId,'service_x');assert.equal(tx.allocations[0].destinationType,'service');});
test('63 Unidade é somente referência na projeção',()=>{const tx=expense(400,'posted','Unidade postada');const row=workflow(allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'business_unit',destinationId:'unit_x',percentage:100}]}));assert.equal(tx.allocations[0].businessUnitId,'unit_x');});
test('64 consulta filtra status, método e destino',()=>{const r=allocations.query({status:'posted',method:'percentage',destinationType:'service',destinationId:'service_x',limit:50});assert(r.rows.some((x)=>x.name==='Serviço postado'));});
test('65 paginação é limitada a 50',()=>{const r=allocations.query({limit:500});assert.equal(r.limit,50);});
test('66 Rateio demo não entra na consulta real',()=>{const tx=expense(123,'posted','Fonte para Rateio demo');const row=allocations.createAllocation({sourceTransactionId:tx.id,method:'percentage',lines:[{destinationType:'corporate',percentage:100}],isDemo:true});assert(!allocations.query({limit:50}).rows.some((x)=>x.id===row.id));assert(allocations.query({limit:50,includeDemo:true}).rows.some((x)=>x.id===row.id));});
test('67 accountingProjection só expõe Rateio postado consistente',()=>{const tx=financeState.transactions.find((x)=>x.originalDescription==='Serviço postado');const projection=allocations.accountingProjection(tx.id);assert.equal(projection.handled,true);assert.equal(projection.allocation.status,'posted');assert.equal(projection.lines.length,1);});
test('68 Rateio draft formal impede allocation legado de virar efeito',()=>{const tx=expense(321,'pending','Legacy pending');finance.setAllocations(tx.id,[{dimension:'corporate',percentage:100}]);const isolated=AllocationCore.createService(AllocationCore.createState({now}),{financeService:()=>finance,idFactory:ids,now,resolveDestination:()=>true});const result=isolated.migrateLegacyTransactionAllocations();const row=isolated.data.allocations.find((x)=>x.sourceTransactionId===tx.id);assert(result.created>=1);assert.equal(row.status,'draft');assert.equal(tx.allocations.length,0);});
test('69 allocation legado de receita não migra para Rateios',()=>{const revenue=finance.createTransaction({financialAccountId:account.id,amount:500,direction:'inflow',financialNature:'revenue',originalDescription:'Receita legada',status:'posted'});finance.setAllocations(revenue.id,[{dimension:'corporate',percentage:100}]);const isolated=AllocationCore.createService(AllocationCore.createState({now}),{financeService:()=>finance,idFactory:ids,now,resolveDestination:()=>true});isolated.migrateLegacyTransactionAllocations();assert(!isolated.data.allocations.some((x)=>x.sourceTransactionId===revenue.id));});
test('70 memória preserva source snapshot',()=>{assert.equal(rateio.sourceSnapshot.amount,10000);assert.equal(rateio.sourceSnapshot.financialNature,'expense');});

if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');
  const css=fs.readFileSync(path.join(__dirname,'..','assets','valtren-brand.css'),'utf8');
  test('71 bundle contém domínio canônico de Rateios',()=>{assert(app.includes('ValtrenCostAllocationCore'));assert(app.includes('state.crmCostAllocations'));});
  test('72 rota canônica de Rateios existe',()=>{assert(app.includes("if(path==='/crm/financeiro/rateios'){const page=crmCostAllocationsPage()"));});
  test('73 placeholder antigo de Rateios não sobrevive',()=>{assert(!app.includes("if(path==='/crm/financeiro/rateios')return crmArchitecturePlaceholderPage"));});
  test('74 Transações continua canônica',()=>{assert(app.includes("if(path==='/crm/financeiro')return crmTransactionsPage();"));});
  test('75 Contabilidade continua canônica',()=>{assert(app.includes("if(path==='/crm/financeiro/accounting')return crmAccountingPage();"));});
  test('76 Notas Fiscais continua canônica',()=>{assert(app.includes("if(path==='/crm/financeiro/notas-fiscais')return crmFiscalDocumentsPage();"));});
  test('77 allocation simples de Transações virou entrada de compatibilidade',()=>{assert(app.includes('location.hash=`#/crm/financeiro/rateios?source=${encodeURIComponent(id)}&new=1`'));assert(!app.includes("crmFinanceModal('Distribuir transação'"));});
  test('78 Contabilidade materializada reconhece Serviço e Unidade rateados',()=>{assert(app.includes("type==='service'&&destinationId===serviceId"));assert(app.includes("type==='business_unit'&&destinationId===businessUnitId"));});
  test('79 pendência de alteração de Rateio chega à Contabilidade',()=>{assert(app.includes("allocation_needs_review"));});
  test('80 CSS responsivo de Rateios está materializado',()=>{assert(css.includes('/* VALTREN COST ALLOCATIONS */'));assert(css.includes('@media(max-width:520px)'));});
  test('81 sidebar financeiro mantém seis itens oficiais',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);['Transações','Contabilidade','Notas Fiscais','Rateios','Participações','Repasses'].forEach((x)=>assert(sidebar.includes(x)));});
  test('82 nenhum submódulo de Rateios foi adicionado ao sidebar',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);['Direcionadores','Critérios de Rateio','Alocações','Memória de Cálculo'].forEach((x)=>assert(!sidebar.includes(x)));});
  test('83 Configurações continua com seis abas',()=>{['empresa','notificacoes','seguranca','integracoes','auditoria','usuarios'].forEach((x)=>assert(app.includes(`['${x}'`)));});
  test('84 Administração continua com dois itens',()=>{assert(app.includes("['structure','Estrutura Organizacional'"));assert(app.includes("['assets','Patrimônio e Licenças'"));});
  test('85 Rateios materializado não cria nova transação',()=>{const start=app.indexOf('// VALTREN COST ALLOCATIONS START'),end=app.indexOf('// VALTREN COST ALLOCATIONS END',start),block=app.slice(start,end);assert(!block.includes('createTransaction('));});
}

console.log(`Cost Allocations domain tests: ${passed} passed`);
