'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const browser=fs.readFileSync(path.resolve(__dirname,'..','web','src','modules','legal','contracts','browser.js'),'utf8');
const css=fs.readFileSync(path.resolve(__dirname,'..','web','src','modules','legal','contracts','styles.css'),'utf8');
const materializer=fs.readFileSync(path.resolve(__dirname,'crm_legal_contracts.py'),'utf8');
const materialize=fs.readFileSync(path.resolve(__dirname,'materialize.py'),'utf8');
let passed=0;
function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}
function hasAll(source,items){for(const item of items)assert(source.includes(item),`ausente: ${item}`);}

test('rota principal é Jurídico / Contratos / Contratos',()=>{hasAll(browser,["crmLegalBreadcrumb('Contratos')","crmFidelityPage('legal','contracts','Contratos'"]);});
test('rota Templates possui breadcrumb aninhado',()=>{hasAll(browser,["crmLegalBreadcrumb('Templates')","crmFidelityPage('legal','contracts-templates','Templates'"]);});
test('rota Variáveis possui breadcrumb aninhado',()=>{hasAll(browser,["crmLegalBreadcrumb('Variáveis')","crmFidelityPage('legal','contracts-variables','Variáveis'"]);});
test('ação principal é Novo Contrato',()=>{assert(browser.includes('Novo Contrato'));assert(browser.includes('crm-legal-new-contract'));});
test('Contratos possui tabs Todos Rascunhos Em revisão Ativos Encerrados',()=>{hasAll(browser,["['all','Todos']","['draft','Rascunhos']","['review','Em revisão']","['active','Ativos']","['ended','Encerrados']"]);});
test('busca de Contratos cobre referências operacionais',()=>{assert(browser.includes('Buscar número, contrato, parte, cliente, produto, serviço ou responsável'));});
test('filtro Tipo existe',()=>{assert(browser.includes('crm-legal-type'));});
test('filtro Status existe',()=>{assert(browser.includes('crm-legal-status'));});
test('filtro Parte existe',()=>{assert(browser.includes('crm-legal-party'));});
test('filtro de vigência existe',()=>{assert(browser.includes('crm-legal-from'));assert(browser.includes('crm-legal-to'));});
test('Mais filtros existe',()=>{assert(browser.includes('crm-legal-more'));});
test('Mais filtros contém Categoria Cliente Produto Serviço Unidade Responsável',()=>{hasAll(browser,['crm-legal-category','crm-legal-customer','crm-legal-product','crm-legal-service','crm-legal-unit','crm-legal-responsible']);});
test('TableView de Contratos possui colunas operacionais',()=>{hasAll(browser,['Número</th>','Contrato</th>','Tipo</th>','Partes</th>','Vigência</th>','Valor/Referência</th>','Versão</th>','Status</th>','Responsável</th>','Ação</th>']);});
test('estado vazio de Contratos não inventa dados',()=>{assert(browser.includes('Nenhum contrato encontrado.'));assert(browser.includes('Os contratos jurídicos aparecerão aqui após serem cadastrados.'));});
test('paginação existe e o domínio limita a 50',()=>{assert(browser.includes('crm-legal-pagination'));assert(browser.includes('limit:50'));});
test('Novo Contrato apresenta seis etapas coerentes',()=>{hasAll(browser,['1. Informações básicas','2. Partes','3. Template opcional','4. Conteúdo','5. Regras/Condições','6. Revisão']);});
test('formulário não cria movimentação financeira',()=>{assert(!browser.includes('createTransaction('));assert(!browser.includes('createFiscalDocument('));});
test('seleção de Cliente usa Party canônica',()=>{assert(browser.includes('crmLegalPartyOptions'));assert(browser.includes('crmCanonicalPartyService()'));});
test('partes podem ser adicionadas inline',()=>{assert(browser.includes('crm-legal-add-party-row'));assert(browser.includes('data-legal-party-row'));});
test('partes podem ser removidas inline',()=>{assert(browser.includes('crm-legal-remove-inline'));});
test('papel contratual é campo da relação',()=>{assert(browser.includes('Papel: Contratante, Contratada, Cliente…'));});
test('signatário é campo separado da parte',()=>{assert(browser.includes('signatoryPersonId'));assert(browser.includes('Signatário opcional'));});
test('Produtos vêm de referência existente',()=>{assert(browser.includes("typeof crmFinanceProducts==='function'?crmFinanceProducts():[]"));});
test('Serviços vêm de fontes estruturadas existentes',()=>{assert(browser.includes('state.businessServices'));assert(browser.includes('state.crmBusinessServices'));assert(browser.includes('state.negociosServices'));});
test('Unidades vêm de fontes estruturadas existentes',()=>{assert(browser.includes('state.businessUnits'));assert(browser.includes('state.crmBusinessUnits'));assert(browser.includes('state.negociosBusinessUnits'));});
test('nenhum catálogo jurídico hardcoded de Produto Serviço Unidade',()=>{assert(!browser.includes('Produto A'));assert(!browser.includes('Serviço A'));assert(!browser.includes('Unidade A'));});
test('Template é opcional na criação do Contrato',()=>{assert(browser.includes('Sem Template'));assert(browser.includes('Template opcional'));});
test('conteúdo contratual suporta registry de Variáveis',()=>{hasAll(browser,['{{CONTRATO.NUMERO}}','{{EMPRESA.RAZAO_SOCIAL}}','{{CLIENTE.NOME}}']);});
test('regras econômicas podem ser adicionadas inline',()=>{assert(browser.includes('crm-legal-add-rule-row'));assert(browser.includes('data-legal-rule-row'));});
test('regra econômica expõe participante canônico',()=>{assert(browser.includes('Participante econômico'));});
test('regra econômica expõe bases sem calcular valores',()=>{hasAll(browser,['Base distribuível','Receita bruta','Receita líquida','Resultado do Produto','Resultado do Serviço','Referência personalizada']);assert(!browser.includes('participationAmount'));});
test('regra econômica expõe percentual',()=>{assert(browser.includes('Percentual %'));});
test('regra econômica expõe deduções permitidas',()=>{assert(browser.includes('Deduções permitidas, separadas por vírgula'));});
test('regra econômica expõe vigência',()=>{assert(browser.includes('effectiveFrom'));assert(browser.includes('effectiveUntil'));});
test('UI explica que Participações não foi implementado',()=>{assert(browser.includes('Financeiro → Participações (não implementado nesta etapa).'));});
test('detalhe contém Visão Geral',()=>{assert(browser.includes('<h3>Visão Geral</h3>'));});
test('detalhe contém Partes',()=>{assert(browser.includes('<h3>Partes</h3>'));});
test('detalhe contém Versões',()=>{assert(browser.includes('<h3>Versões</h3>'));});
test('detalhe contém Conteúdo',()=>{assert(browser.includes('<h3>Conteúdo</h3>'));});
test('detalhe contém Condições Econômicas',()=>{assert(browser.includes('<h3>Condições Econômicas</h3>'));});
test('detalhe contém Documentos sem storage falso',()=>{assert(browser.includes('<h3>Documentos</h3>'));assert(browser.includes('não simula storage ou PDF jurídico'));});
test('detalhe contém Aprovações',()=>{assert(browser.includes('<h3>Aprovações</h3>'));});
test('detalhe contém Assinaturas',()=>{assert(browser.includes('<h3>Assinaturas</h3>'));});
test('detalhe contém Histórico',()=>{assert(browser.includes('<h3>Histórico</h3>'));});
test('ações de versão distinguem Rascunho Revisão Aprovado',()=>{hasAll(browser,['crm-legal-send-review','crm-legal-approve-version','crm-legal-reject-version','crm-legal-new-version']);});
test('registro de assinatura é explicitamente manual',()=>{hasAll(browser,['crm-legal-record-signature','Registrar manualmente a assinatura','provider:\'manual\'']);});
test('UI não declara assinatura digital sem integração',()=>{assert(!browser.includes('Assinado digitalmente'));});
test('Preview A4 é identificado como interno',()=>{assert(browser.includes('Preview interno A4'));assert(browser.includes('não representa PDF assinado'));});
test('Preview A4 possui dimensões e @page',()=>{assert(css.includes('210mm'));assert(css.includes('297mm'));assert(css.includes('@page{size:A4'));});
test('Preview considera cabeçalho conteúdo cláusulas rodapé',()=>{hasAll(browser,['preview.header','preview.content','preview.clauses','preview.footer']);});
test('preview evidencia Variáveis pendentes',()=>{assert(browser.includes('Variáveis pendentes'));});
test('dados institucionais ausentes geram orientação correta',()=>{assert(browser.includes('Dados institucionais incompletos. Configure em Configurações → Empresa.'));});
test('Templates possui ação Novo Template',()=>{assert(browser.includes('Novo Template'));assert(browser.includes('crm-legal-new-template'));});
test('Templates possui Busca Categoria Tipo Status',()=>{hasAll(browser,['crm-legal-template-search','crm-legal-template-category','crm-legal-template-type','crm-legal-template-status']);});
test('TableView Templates possui colunas exigidas',()=>{hasAll(browser,['Nome</th>','Categoria</th>','Tipo</th>','Versão</th>','Variáveis</th>','Status</th>','Atualizado em</th>']);});
test('Template detail oferece Preview A4',()=>{assert(browser.includes('crm-legal-preview-template'));});
test('Template detail oferece nova versão',()=>{assert(browser.includes('crm-legal-new-template-version'));});
test('Template detail oferece duplicação',()=>{assert(browser.includes('crm-legal-duplicate-template'));});
test('Template detail oferece arquivamento',()=>{assert(browser.includes('crm-legal-archive-template'));});
test('Variáveis UI é TableView simples',()=>{assert(browser.includes("crmFidelityPage('legal','contracts-variables','Variáveis'"));});
test('Variáveis mostra Variável Descrição Escopo Tipo Obrigatória Status Origem',()=>{hasAll(browser,['Variável</th>','Descrição</th>','Escopo</th>','Tipo</th>','Obrigatória</th>','Status</th>','Origem</th>']);});
test('Variáveis não expõe resolverPath entityType metadata JSON',()=>{const start=browser.indexOf('function crmLegalVariablesPage()'),end=browser.indexOf('function crmLegalContractEditor',start),page=browser.slice(start,end);assert(!page.includes('resolverPath'));assert(!page.includes('metadata JSON'));assert(!page.includes('partyId</th>'));});
test('feed futuro para Participações é função read-only',()=>{assert(browser.includes('function crmContractEconomicRulesFeed(filters={})'));assert(browser.includes('economicRulesFeed(filters)'));});
test('resolução futura por período está exposta',()=>{assert(browser.includes('function crmContractResolveEconomicRuleForPeriod(input={})'));});
test('layout possui breakpoint 1380',()=>{assert(css.includes('@media (max-width:1380px)'));});
test('layout possui breakpoint 1050',()=>{assert(css.includes('@media (max-width:1050px)'));});
test('layout possui breakpoint 760',()=>{assert(css.includes('@media (max-width:760px)'));});
test('layout possui breakpoint 520',()=>{assert(css.includes('@media (max-width:520px)'));});
test('drawer respeita viewport',()=>{assert(css.includes('height:100vh'));assert(css.includes('width:min(920px,100%)'));});
test('modal respeita viewport',()=>{assert(css.includes('max-height:calc(100vh - 32px)'));});
test('TableView possui overflow controlado',()=>{assert(css.includes('.crm-legal-table-wrap{overflow:auto}'));});
test('mobile remove informações secundárias antes das essenciais',()=>{assert(css.includes('nth-child(3)'));assert(css.includes('nth-child(6)'));assert(css.includes('nth-child(9)'));});
test('materializador substitui apenas três placeholders de Contratos',()=>{assert.equal((materializer.match(/crmArchitecturePlaceholderPage\('legal','contracts/g)||[]).length,3);hasAll(materializer,['crmLegalContractsPage();','crmLegalTemplatesPage();','crmLegalVariablesPage();']);});
test('materializador preserva outras quatro áreas Jurídicas como placeholders',()=>{hasAll(materializer,['Assuntos Jurídicos','Compliance e Políticas','Propriedade Intelectual','Societário']);});
test('materializador preserva Transações Contabilidade Notas Fiscais Rateios',()=>{hasAll(materializer,['crmTransactionsPage();','crmAccountingPage();','crmFiscalDocumentsPage();','crmCostAllocationsPage();']);});
test('materializador exige Participações e Repasses ainda placeholders',()=>{assert(materializer.includes("crmArchitecturePlaceholderPage('accounting','participations','Participações')"));assert(materializer.includes("crmArchitecturePlaceholderPage('accounting','payouts','Repasses')"));});
test('materializador valida sidebar sem reescrevê-lo',()=>{assert(materializer.includes('sidebar = app[sidebar_start:sidebar_end]'));assert(!materializer.includes('app = app.replace(sidebar'));});
test('materializador proíbe submódulos indevidos no sidebar',()=>{hasAll(materializer,['Cláusulas','Aprovações','Assinaturas','Regras Econômicas','Participantes']);});
test('ordem do materializador coloca Contratos depois de Rateios',()=>{const rateios=materialize.indexOf('apply_crm_cost_allocations()'),contracts=materialize.indexOf('apply_crm_legal_contracts()');assert(rateios>=0&&contracts>rateios);});

if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8'),brand=fs.readFileSync(path.resolve(__dirname,'..','assets','valtren-brand.css'),'utf8');
  test('UI final de Contratos está no bundle',()=>{hasAll(app,['function crmLegalContractsPage()','function crmLegalContractEditor()','function crmLegalContractDetail(id)']);});
  test('UI final de Templates está no bundle',()=>{hasAll(app,['function crmLegalTemplatesPage()','function crmLegalTemplateEditor()','function crmLegalTemplateDetail(id)']);});
  test('UI final de Variáveis está no bundle',()=>{assert(app.includes('function crmLegalVariablesPage()'));});
  test('breadcrumbs publicados usam hierarquia Jurídico Contratos',()=>{assert(app.includes("crmLegalBreadcrumb('Contratos')"));assert(app.includes("crmLegalBreadcrumb('Templates')"));assert(app.includes("crmLegalBreadcrumb('Variáveis')"));});
  test('rotas publicadas não são placeholders',()=>{assert(app.includes("if(path==='/crm/juridico/contratos')return crmLegalContractsPage();"));assert(app.includes("if(path==='/crm/juridico/contratos/templates')return crmLegalTemplatesPage();"));assert(app.includes("if(path==='/crm/juridico/contratos/variaveis')return crmLegalVariablesPage();"));});
  test('bundle contém registry de Variáveis canônicas',()=>{hasAll(app,['EMPRESA.RAZAO_SOCIAL','EMPRESA.CNPJ','CLIENTE.NOME','CLIENTE.DOCUMENTO','CONTRATO.NUMERO','CONTRATO.VALOR','PRODUTO.NOME','SERVICO.NOME','UNIDADE.NOME']);});
  test('bundle contém workflow de versão',()=>{hasAll(app,['sendVersionToReview','approveVersion','rejectVersion','markVersionSigned','createNewVersion']);});
  test('bundle contém regras econômicas versionadas',()=>{hasAll(app,['economicRulesFeed','resolveEconomicRuleForPeriod','participantPartyId','basisType','deductions']);});
  test('bundle contém Preview A4',()=>{assert(app.includes('crm-contract-a4-page'));assert(brand.includes('crm-contract-a4-page'));});
  test('CSS jurídico foi materializado',()=>{assert(brand.includes('/* VALTREN LEGAL CONTRACTS */'));assert(brand.includes('@media (max-width:520px)'));});
  test('sidebar Jurídico mantém a arquitetura oficial',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);hasAll(sidebar,['Assuntos Jurídicos','Contratos','Templates','Variáveis','Compliance e Políticas','Propriedade Intelectual','Societário','#/crm/juridico/contratos','#/crm/juridico/contratos/templates','#/crm/juridico/contratos/variaveis']);});
  test('nenhum novo subitem jurídico indevido foi publicado',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);for(const label of ['Cláusulas','Aprovações','Assinaturas','Regras Econômicas','Participantes'])assert(!sidebar.includes(label));});
  test('sidebar Financeiro continua com seis itens oficiais',()=>{const start=app.lastIndexOf('function crmRelSidebar'),end=app.indexOf('function crmReferenceRoute',start),sidebar=app.slice(start,end);hasAll(sidebar,['Transações','Contabilidade','Notas Fiscais','Rateios','Participações','Repasses']);});
  test('regressão: Configurações mantém as seis abas canônicas atuais',()=>{const start=app.indexOf('function crmCanonicalSettingsPage()'),end=app.indexOf('function crmCanonicalProfilePage()',start),settings=app.slice(start,end),canonical=["['empresa','Empresa']","['notificacoes','Notificações']","['seguranca','Segurança']","['integracoes','Integrações']","['auditoria','Auditoria']","['usuarios','Usuários']"];assert(start>=0&&end>start);assert.equal(canonical.filter((label)=>settings.includes(label)).length,6);for(const label of canonical)assert(settings.includes(label));assert(!settings.includes("['billing','Billing']"));});
  test('regressão: Administração mantém os dois itens canônicos atuais',()=>{const start=app.lastIndexOf('const administration=['),end=app.indexOf('];',start),admin=app.slice(start,end),canonical=["['structure','Estrutura Organizacional','#/crm/administracao']","['assets','Patrimônio e Licenças','#/crm/administracao/patrimonio-licencas']"];assert(start>=0&&end>start);assert.equal(canonical.filter((item)=>admin.includes(item)).length,2);for(const item of canonical)assert(admin.includes(item));assert(!admin.includes('Auditoria'));assert(!admin.includes('Integrações'));});
  test('Participações não foi implementado pelo bundle contratual',()=>{assert(app.includes("if(path==='/crm/financeiro/participacoes')return crmArchitecturePlaceholderPage"));});
  test('Repasses não foi implementado pelo bundle contratual',()=>{assert(app.includes("if(path==='/crm/financeiro/repasses')return crmArchitecturePlaceholderPage"));});
}
console.log(`Legal Contracts UI tests: ${passed} passed`);