'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const Business=require('../web/src/modules/business/core.js');
let passed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${passed} ${name}`);}catch(error){console.error(`FAIL ${name}`);throw error;}}
let tick=0;const now=()=>`2026-08-26T02:${String(tick++).padStart(2,'0')}:00.000Z`;let seq=0;const ids=(prefix)=>`${prefix}_test_${++seq}`;const refs=new Map();const referenceChecker=(kind,id)=>refs.get(`${kind}:${id}`)||[];const store=Business.createState({now});const service=Business.createService(store,{now,idFactory:ids,actorProvider:()=> 'user_admin',referenceChecker});

test('estado canônico contém owner único de Negócios',()=>assert.deepEqual(Object.keys(store).filter((x)=>['products','services','businessUnits','relationships','history','legacyBindings','metadata'].includes(x)).sort(),['businessUnits','history','legacyBindings','metadata','products','relationships','services'].sort()));
test('Produto Serviço e Unidade são coleções distintas',()=>{assert.notStrictEqual(store.products,store.services);assert.notStrictEqual(store.products,store.businessUnits);});
test('códigos automáticos iniciam em PRD SRV BU',()=>{assert.equal(service.nextCode('product'),'PRD-001');assert.equal(service.nextCode('service'),'SRV-001');assert.equal(service.nextCode('business_unit'),'BU-001');});
const unit=service.createBusinessUnit({name:'Produtos Digitais',code:'BU-001',ownerUserId:'u1'});
test('criar Unidade com ID estável',()=>assert(unit.id.startsWith('bu_test_')));
test('Unidade preserva código',()=>assert.equal(unit.code,'BU-001'));
test('Unidade preserva nome',()=>assert.equal(unit.name,'Produtos Digitais'));
test('Unidade nasce ativa por padrão',()=>assert.equal(unit.status,'active'));
test('Unidade preserva owner',()=>assert.equal(unit.ownerUserId,'u1'));
test('código duplicado de Unidade é bloqueado',()=>assert.throws(()=>service.createBusinessUnit({name:'Outra',code:'BU-001'}),/Código/));
test('nome normalizado duplicado de Unidade é bloqueado',()=>assert.throws(()=>service.createBusinessUnit({name:'  PRODUTOS   DIGITAIS ',code:'BU-009'}),/duplicada/));
const child=service.createBusinessUnit({name:'Cursos',parentBusinessUnitId:unit.id});
test('parent opcional de Unidade funciona',()=>assert.equal(child.parentBusinessUnitId,unit.id));
test('parent inexistente é bloqueado',()=>assert.throws(()=>service.createBusinessUnit({name:'Inválida',parentBusinessUnitId:'bu_missing'}),/não encontrada/));
test('ciclo hierárquico é bloqueado',()=>assert.throws(()=>service.updateBusinessUnit(unit.id,{parentBusinessUnitId:child.id}),/ciclo/));
test('Unidade não é Departamento no modelo',()=>assert.equal('departmentId' in unit,false));
const historicalUnit=service.createBusinessUnit({name:'Unidade Histórica',code:'BU-010'});const historicalProduct=service.createProduct({name:'Produto Histórico',code:'PRD-010',category:'Histórico',businessUnitId:historicalUnit.id});const historicalService=service.createService({name:'Serviço Histórico',code:'SRV-010',businessUnitId:historicalUnit.id});service.archive('business_unit',historicalUnit.id);
test('Produto em Unidade arquivada pode editar campo não relacional',()=>{service.updateProduct(historicalProduct.id,{description:'Preservado'});assert.equal(historicalProduct.description,'Preservado');});
test('Serviço em Unidade arquivada pode editar campo não relacional',()=>{service.updateService(historicalService.id,{description:'Preservado'});assert.equal(historicalService.description,'Preservado');});
test('novo vínculo para Unidade arquivada é bloqueado',()=>assert.throws(()=>service.createProduct({name:'Novo em arquivada',category:'Histórico',businessUnitId:historicalUnit.id}),/indisponível/));
const product=service.createProduct({name:'Plataforma X',code:'PRD-001',category:'SaaS',type:'software',businessUnitId:unit.id,ownerUserId:'u2',revenueModel:'subscription',billingModel:'monthly',currency:'BRL',referencePrice:149.9,websiteUrl:'https://example.test'});
test('criar Produto',()=>assert(product));
test('Produto possui ID estável',()=>assert(product.id.startsWith('prd_test_')));
test('Produto preserva código',()=>assert.equal(product.code,'PRD-001'));
test('Produto preserva nome',()=>assert.equal(product.name,'Plataforma X'));
test('Produto gera slug determinístico',()=>assert.equal(product.slug,'plataforma-x'));
test('Produto preserva categoria',()=>assert.equal(product.category,'SaaS'));
test('Produto possui status draft padrão',()=>assert.equal(product.status,'draft'));
test('Produto referencia Unidade por ID',()=>assert.equal(product.businessUnitId,unit.id));
test('Produto preserva owner',()=>assert.equal(product.ownerUserId,'u2'));
test('Produto preserva revenueModel',()=>assert.equal(product.revenueModel,'subscription'));
test('Produto preserva billingModel',()=>assert.equal(product.billingModel,'monthly'));
test('Produto preserva moeda',()=>assert.equal(product.currency,'BRL'));
test('Produto preserva preço informado',()=>assert.equal(product.referencePrice,149.9));
test('código duplicado de Produto é bloqueado',()=>assert.throws(()=>service.createProduct({name:'Outro',code:'PRD-001',category:'Outro'}),/Código/));
test('slug duplicado de Produto é bloqueado',()=>assert.throws(()=>service.createProduct({name:'Outro Produto',code:'PRD-002',slug:'plataforma-x',category:'Outro'}),/Slug/));
test('nome+categoria normalizados duplicados são bloqueados',()=>assert.throws(()=>service.createProduct({name:' plataforma x ',code:'PRD-003',category:'saas'}),/(duplicado|Slug)/));
test('Produto com Unidade inexistente é bloqueado',()=>assert.throws(()=>service.createProduct({name:'Sem Unidade',businessUnitId:'bu_missing'}),/não encontrada/));
test('revenueModel inválido é bloqueado',()=>assert.throws(()=>service.createProduct({name:'Modelo inválido',revenueModel:'equity'}),/receita inválido/));
test('billingModel inválido é bloqueado',()=>assert.throws(()=>service.createProduct({name:'Billing inválido',billingModel:'weekly'}),/cobrança inválido/));
const noPrice=service.createProduct({name:'Sem Preço',category:'Licença',revenueModel:'license'});
test('preço opcional permanece null',()=>assert.strictEqual(noPrice.referencePrice,null));
const zeroPrice=service.createProduct({name:'Preço Zero',category:'Freemium',referencePrice:0,revenueModel:'free'});
test('preço zero legítimo permanece zero',()=>assert.strictEqual(zeroPrice.referencePrice,0));
test('ausência de preço é diferente de zero',()=>assert.notStrictEqual(noPrice.referencePrice,zeroPrice.referencePrice));
test('preço negativo é bloqueado',()=>assert.throws(()=>service.createProduct({name:'Negativo',referencePrice:-1}),/Preço/));
service.updateProduct(product.id,{status:'active',referencePrice:199.9});
test('status de Produto pode mudar para ativo',()=>assert.equal(product.status,'active'));
test('mudança de preço é preservada',()=>assert.equal(product.referencePrice,199.9));
test('histórico de Produto registra mudanças',()=>assert(service.historyFor('product',product.id).some((x)=>x.action==='reference_price_changed')));
test('Produto não possui transactionId fiscalId ou contractId',()=>{for(const key of ['transactionId','fiscalDocumentId','contractId','revenueId'])assert.equal(key in product,false);});
const serviceRow=service.createService({name:'Desenvolvimento de Software',code:'SRV-001',category:'Tecnologia',businessUnitId:unit.id,ownerUserId:'u3',pricingModel:'project',currency:'BRL',referencePrice:null,billingFrequency:'custom',defaultDuration:'sob demanda'});
test('criar Serviço',()=>assert(serviceRow));
test('Serviço possui ID estável',()=>assert(serviceRow.id.startsWith('srv_test_')));
test('Serviço preserva código',()=>assert.equal(serviceRow.code,'SRV-001'));
test('Serviço preserva categoria',()=>assert.equal(serviceRow.category,'Tecnologia'));
test('Serviço preserva status draft padrão',()=>assert.equal(serviceRow.status,'draft'));
test('Serviço referencia Unidade por ID',()=>assert.equal(serviceRow.businessUnitId,unit.id));
test('Serviço preserva pricingModel',()=>assert.equal(serviceRow.pricingModel,'project'));
test('Serviço preserva moeda',()=>assert.equal(serviceRow.currency,'BRL'));
test('Serviço aceita preço opcional',()=>assert.strictEqual(serviceRow.referencePrice,null));
test('Serviço preserva owner',()=>assert.equal(serviceRow.ownerUserId,'u3'));
test('duplicidade de código de Serviço é bloqueada',()=>assert.throws(()=>service.createService({name:'Outro Serviço',code:'SRV-001'}),/Código/));
test('duplicidade de nome normalizado de Serviço é bloqueada',()=>assert.throws(()=>service.createService({name:' desenvolvimento de software ',code:'SRV-002'}),/duplicado/));
test('Serviço com Unidade inexistente é bloqueado',()=>assert.throws(()=>service.createService({name:'Inválido',businessUnitId:'bu_missing'}),/não encontrada/));
test('pricingModel inválido é bloqueado',()=>assert.throws(()=>service.createService({name:'Pricing inválido',pricingModel:'shares'}),/preço inválido/));
service.updateService(serviceRow.id,{status:'active'});
test('Serviço pode ser ativado',()=>assert.equal(serviceRow.status,'active'));
test('histórico do Serviço registra edição',()=>assert(service.historyFor('service',serviceRow.id).some((x)=>x.action==='edited')));
test('contagem da Unidade deriva Produtos reais',()=>assert.equal(service.countsForUnit(unit.id).products,1));
test('contagem da Unidade deriva Serviços reais',()=>assert.equal(service.countsForUnit(unit.id).services,1));
const demoProduct=service.createProduct({name:'Demo Produto',category:'Demo',isDemo:true,status:'active'}),demoService=service.createService({name:'Demo Serviço',isDemo:true,status:'active'}),demoUnit=service.createBusinessUnit({name:'Demo Unidade',isDemo:true});
test('feed de Produtos exclui demo por padrão',()=>assert(!service.listProducts().some((x)=>x.id===demoProduct.id)));
test('feed de Serviços exclui demo por padrão',()=>assert(!service.listServices().some((x)=>x.id===demoService.id)));
test('feed de Unidades exclui demo por padrão',()=>assert(!service.listBusinessUnits().some((x)=>x.id===demoUnit.id)));
test('feed com includeDemo é explícito',()=>assert(service.listProducts({includeDemo:true}).some((x)=>x.id===demoProduct.id)));
test('feed é clone read-only',()=>{const list=service.listProducts({includeArchived:true});list[0].name='MUTADO';assert.notEqual(service.getProduct(list[0].id).name,'MUTADO');});
test('lookup por ID de Produto funciona',()=>assert.strictEqual(service.getProduct(product.id),product));
test('lookup por ID de Serviço funciona',()=>assert.strictEqual(service.getService(serviceRow.id),serviceRow));
test('lookup por ID de Unidade funciona',()=>assert.strictEqual(service.getBusinessUnit(unit.id),unit));
test('referência inexistente retorna null em lookup',()=>assert.strictEqual(service.getProduct('prd_missing'),null));
test('resolveDimension resolve Produto',()=>assert.equal(service.resolveDimension('product',product.id).name,'Plataforma X'));
test('resolveDimension resolve Serviço',()=>assert.equal(service.resolveDimension('service',serviceRow.id).name,'Desenvolvimento de Software'));
test('resolveDimension resolve Unidade',()=>assert.equal(service.resolveDimension('business_unit',unit.id).name,'Produtos Digitais'));
test('corporate permanece separado do catálogo',()=>{const x=service.resolveDimension('corporate','');assert(x.resolved);assert.equal(x.name,'Corporativo');assert(!service.getProduct('corporate'));});
test('referência inexistente é marcada como não resolvida',()=>{const x=service.resolveDimension('product','legacy-x');assert.equal(x.resolved,false);assert.equal(x.name,'Referência não resolvida');});
const legacy=service.registerPotentialReference({sourceModule:'legacy',sourceEntityId:'old1',field:'productId',kind:'product',legacyValue:'Music textual'});
test('label legado vira potentialCatalogReference sem criar Produto',()=>{assert.equal(legacy.status,'potential_catalog_reference');assert(!service.listProducts({includeDemo:true}).some((x)=>x.name==='Music textual'));});
test('legacyBinding é idempotente',()=>assert.strictEqual(service.registerPotentialReference({sourceModule:'legacy',sourceEntityId:'old1',field:'productId',kind:'product',legacyValue:'Music textual'}),legacy));
refs.set(`product:${product.id}`,[{source:'transactions',field:'productId'}]);service.archive('product',product.id);
test('arquivamento preserva Produto referenciado',()=>assert(service.getProduct(product.id)));
test('Produto arquivado sai do feed padrão',()=>assert(!service.listProducts().some((x)=>x.id===product.id)));
test('Produto arquivado continua resolvível historicamente',()=>assert.equal(service.resolveDimension('product',product.id).resolved,true));
test('referências históricas são consultáveis',()=>assert.equal(service.references('product',product.id).length,1));
service.restore('product',product.id,'active');
test('restauração preserva o mesmo ID',()=>assert.equal(service.getProduct(product.id).id,product.id));
service.archive('service',serviceRow.id);
test('arquivamento de Serviço preserva histórico',()=>assert(service.historyFor('service',serviceRow.id).some((x)=>x.action==='archived')));
service.restore('service',serviceRow.id,'active');service.archive('business_unit',child.id);
test('arquivamento de Unidade preserva entidade',()=>assert(service.getBusinessUnit(child.id)));
test('rascunho não referenciado pode ser excluído fisicamente',()=>{const draft=service.createProduct({name:'Descartável',category:'Teste'});assert(service.deleteDraft('product',draft.id));assert.strictEqual(service.getProduct(draft.id),null);});
test('entidade ativa não pode ser excluída fisicamente',()=>assert.throws(()=>service.deleteDraft('product',product.id),/rascunho/));
const referencedDraft=service.createService({name:'Rascunho Referenciado'});refs.set(`service:${referencedDraft.id}`,[{source:'contracts'}]);
test('rascunho referenciado não pode ser excluído fisicamente',()=>assert.throws(()=>service.deleteDraft('service',referencedDraft.id),/referências/));
test('Produto não recalcula receita despesa imposto resultado margem',()=>{const serialized=JSON.stringify(product);for(const k of ['amountRevenue','expenseAmount','taxAmount','resultAmount','margin'])assert(!serialized.includes(k));});
test('revenue_share é apenas modelo comercial e não participação econômica',()=>{const p=service.createProduct({name:'Revenue Share Comercial',category:'Modelo',revenueModel:'revenue_share'});assert.equal(p.revenueModel,'revenue_share');assert.equal('participationCalculationId' in p,false);});

if(process.argv.includes('--materialized')){
  const app=fs.readFileSync(path.resolve(__dirname,'..','app.js'),'utf8');
  test('bundle contém ValtrenBusinessCore',()=>assert(app.includes('ValtrenBusinessCore')));
  test('bundle contém state.crmBusinessCatalog',()=>assert(app.includes('state.crmBusinessCatalog')));
  test('bundle contém feeds read-only de Negócios',()=>{for(const x of ['crmBusinessProductsFeed','crmBusinessServicesFeed','crmBusinessUnitsFeed'])assert(app.includes(`function ${x}`));});
  test('rota canônica Produtos está materializada',()=>assert(app.includes("if(path==='/crm/negocios')return crmBusinessProductsPage();")));
  test('rota canônica Serviços está materializada',()=>assert(app.includes("if(path==='/crm/negocios/servicos')return crmBusinessServicesPage();")));
  test('rota canônica Unidades está materializada',()=>assert(app.includes("if(path==='/crm/negocios/unidades')return crmBusinessUnitsPage();")));
  test('placeholders de Negócios não sobrevivem',()=>{assert(!app.includes("if(path==='/crm/negocios')return crmArchitecturePlaceholderPage"));assert(!app.includes("if(path==='/crm/negocios/servicos')return crmArchitecturePlaceholderPage"));assert(!app.includes("if(path==='/crm/negocios/unidades')return crmArchitecturePlaceholderPage"));});
  test('Transações usa feed canônico de Produtos',()=>assert(app.includes("function crmFinanceProducts(){return typeof crmBusinessProductsFeed==='function'?crmBusinessProductsFeed({includeArchived:false})")));
  test('Contabilidade usa feeds canônicos',()=>{assert(app.includes("function crmAccountingServices(){return typeof crmBusinessServicesFeed==='function'"));assert(app.includes("function crmAccountingUnits(){return typeof crmBusinessUnitsFeed==='function'"));});
  test('Notas Fiscais usa catálogo canônico',()=>{assert(app.includes("function crmFiscalProducts(){return typeof crmBusinessProductsFeed==='function'"));assert(app.includes("function crmFiscalServices(){return typeof crmBusinessServicesFeed==='function'"));assert(app.includes("function crmFiscalUnits(){return typeof crmBusinessUnitsFeed==='function'"));});
  test('Rateios valida destinos no catálogo canônico',()=>assert(app.includes("function crmCostAllocationResolveDestination(type,id){if(type==='corporate')return true;return typeof crmBusinessService==='function'&&crmBusinessService().validateReference(type,id,{allowHistorical:false});}")));
  test('Contratos resolve referências no catálogo canônico',()=>assert(app.includes("function crmLegalResolveReference(type,id){if(typeof crmBusinessResolveDimension!=='function')return null;const row=crmBusinessResolveDimension(type,id);return row.resolved&&!['archived','retired'].includes(row.status)?row:null;}")));
  test('Participações resolve labels canônicas sem mudar cálculo',()=>assert(app.includes("function crmParticipationReferenceLabel(row){if(row.productId)return crmBusinessDimensionLabel('product',row.productId)")));
  test('Repasses resolve labels canônicas sem mudar liquidação',()=>assert(app.includes("function crmPayoutReferenceLabel(row){if(row.productId)return crmBusinessDimensionLabel('product',row.productId)")));
  test('Corporativo continua separado',()=>assert(app.includes("if(type==='corporate')return true")));
  test('não há catálogo financeProducts concorrente',()=>assert(!app.includes('state.financeProducts=')));
  test('não há catálogo contractProducts concorrente',()=>assert(!app.includes('state.contractProducts=')));
  test('Configurações preserva seis abas canônicas',()=>{const start=app.indexOf('function crmCanonicalSettingsPage()'),end=app.indexOf('function crmCanonicalProfilePage()',start),settings=app.slice(start,end);for(const label of ["['empresa','Empresa']","['notificacoes','Notificações']","['seguranca','Segurança']","['integracoes','Integrações']","['auditoria','Auditoria']","['usuarios','Usuários']"])assert(settings.includes(label));});
  test('Administração preserva dois itens canônicos',()=>{const start=app.lastIndexOf('const administration=['),end=app.indexOf('];',start),admin=app.slice(start,end);assert(admin.includes('Estrutura Organizacional'));assert(admin.includes('Patrimônio e Licenças'));});
}
console.log(`Business catalog domain tests: ${passed} passed`);
